/* generated by tur (phase 2) */
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
extern void *malloc(size_t);
extern void free(void *);
extern void abort(void);
extern void *memset(void *, int, size_t);

/* tur_frame - phase 4 v1 lowering (from runtime.h) */
typedef void (*defer_fn_t)(void *env);
#define TUR_FRAME_MAX_DEFERS 32

typedef struct tur_frame {
    defer_fn_t defers[TUR_FRAME_MAX_DEFERS];
    void *envs[TUR_FRAME_MAX_DEFERS];
    int n;
    struct tur_frame *parent;
    bool may_capture;
} tur_frame;

static inline void tur_frame_init(tur_frame *f, tur_frame *parent) {
    f->n = 0; f->parent = parent; f->may_capture = false;
}
static inline int tur_frame_push_defer(tur_frame *f, defer_fn_t thunk, void *env) {
    if (f->n >= TUR_FRAME_MAX_DEFERS) return -1;
    f->defers[f->n] = thunk;
    f->envs[f->n] = env;
    f->n++;
    return 0;
}
static void tur_frame_fire_lifo(tur_frame *f) {
    for (int i = f->n - 1; i >= 0; i--) f->defers[i](f->envs[i]);
    f->n = 0;
}

/* rc<T> + weak<T> reference counting - Phase 9 */
/* Phase 10: GC color enum for Bacon-Rajan */
typedef enum { GC_WHITE, GC_GREY, GC_BLACK, GC_PURPLE } GcColor;

typedef void (*RcDropFn)(void *value);

typedef struct RcControlBlock RcControlBlock;

struct RcControlBlock {
    uint64_t strong_count;
    uint64_t weak_count;
    void *value;
    RcDropFn drop_fn;
    uint8_t value_type_kind;
    uint8_t color;           /* GC color */
    bool may_contain_cycles;  /* Hint for GC */
    uint8_t reserved[6];
};

#define GC_GLOBAL_REGISTRY_CAPACITY 4096
static RcControlBlock *gc_all_blocks[GC_GLOBAL_REGISTRY_CAPACITY];
static uint32_t gc_all_blocks_count = 0;

static void gc_register_block(RcControlBlock *cb) {
    if (!cb || gc_all_blocks_count >= GC_GLOBAL_REGISTRY_CAPACITY) return;
    gc_all_blocks[gc_all_blocks_count++] = cb;
    cb->color = GC_WHITE;
    cb->may_contain_cycles = true;
}

static void gc_unregister_block(RcControlBlock *cb) {
    if (!cb) return;
    for (uint32_t i = 0; i < gc_all_blocks_count; i++) {
        if (gc_all_blocks[i] == cb) {
            gc_all_blocks[i] = gc_all_blocks[gc_all_blocks_count - 1];
            gc_all_blocks_count--;
            break;
        }
    }
}

static void gc_on_strong_decrement(RcControlBlock *cb) {
    if (!cb) return;
    if (cb->weak_count > 0) {
        cb->color = GC_PURPLE;
    }
}

static void default_rc_drop_fn(void *value) {
    free(value);
}

RcControlBlock *rc_cb_alloc(size_t value_size, int value_type_kind, RcDropFn drop_fn) {
    size_t total_size = sizeof(RcControlBlock) + value_size;
    RcControlBlock *cb = (RcControlBlock *)malloc(total_size);
    if (!cb) { fprintf(stderr, "rc: out of memory\n"); abort(); }
    cb->strong_count = 1;
    cb->weak_count = 0;
    cb->value = (void *)(cb + 1);
    cb->drop_fn = drop_fn ? drop_fn : default_rc_drop_fn;
    cb->value_type_kind = value_type_kind;
    memset(cb->reserved, 0, sizeof(cb->reserved));
    /* Register with GC */
    gc_register_block(cb);
    return cb;
}

uint64_t rc_strong_increment(RcControlBlock *cb) {
    if (!cb) return 0;
    return ++cb->strong_count;
}

bool rc_strong_decrement(RcControlBlock *cb) {
    if (!cb) return false;
    cb->strong_count--;
    if (cb->strong_count == 0) {
        if (cb->weak_count > 0) {
            gc_on_strong_decrement(cb);
            return false;
        } else {
            gc_unregister_block(cb);
            if (cb->value) cb->drop_fn(cb->value);
            free(cb);
            return true;
        }
    }
    return false;
}

uint64_t rc_weak_increment(RcControlBlock *cb) {
    if (!cb) return 0;
    return ++cb->weak_count;
}

bool rc_weak_decrement(RcControlBlock *cb) {
    if (!cb) return false;
    cb->weak_count--;
    if (cb->weak_count == 0 && cb->strong_count == 0) {
        gc_unregister_block(cb);
        free(cb);
        return true;
    }
    return false;
}

uint64_t rc_strong_count(RcControlBlock *cb) {
    if (!cb) return 0;
    return cb->strong_count;
}

uint64_t rc_weak_count(RcControlBlock *cb) {
    if (!cb) return 0;
    return cb->weak_count;
}

bool rc_is_alive(RcControlBlock *cb) {
    if (!cb) return false;
    return cb->strong_count > 0;
}

RcControlBlock *rc_upgrade(RcControlBlock *cb) {
    if (!cb) return NULL;
    if (cb->strong_count > 0) {
        rc_strong_increment(cb);
        return cb;
    }
    return NULL;
}

void *rc_get_value(RcControlBlock *cb) {
    if (!cb) return NULL;
    return cb->value;
}

/* gc (Bacon-Rajan cycle collector) - Phase 10 */
#define GC_SUSPECT_THRESHOLD 128
#define GC_MAX_SUSPECTS 4096

typedef enum { GC_DISABLED, GC_MANUAL, GC_THRESHOLD } GcMode;

static RcControlBlock *gc_suspect_roots[GC_MAX_SUSPECTS];
static uint32_t gc_suspect_count = 0;
static RcControlBlock *gc_grey_queue[GC_MAX_SUSPECTS];
static uint32_t gc_grey_count = 0;
static GcMode gc_mode = GC_DISABLED;
static bool gc_enabled = false;

static void gc_set_color(RcControlBlock *cb, GcColor color) {
    if (cb) cb->color = color;
}

static GcColor gc_get_color(RcControlBlock *cb) {
    if (cb) return cb->color;
    return GC_WHITE;
}

static void gc_mark_phase(void) {
    for (uint32_t i = 0; i < gc_all_blocks_count; i++) {
        gc_all_blocks[i]->color = GC_WHITE;
    }
    for (uint32_t i = 0; i < gc_all_blocks_count; i++) {
        RcControlBlock *cb = gc_all_blocks[i];
        if (cb->strong_count > 0) {
            cb->color = GC_BLACK;
        }
    }
}

static void gc_collect(void) {
    if (!gc_enabled || gc_mode == GC_DISABLED) return;
    gc_grey_count = 0;
    gc_mark_phase();
}

static void gc_force(void) {
    gc_collect();
}

static void gc_enable(void) {
    gc_enabled = true;
}

static void gc_disable(void) {
    gc_enabled = false;
}

static void gc_set_mode(GcMode mode) {
    gc_mode = mode;
}

static bool gc_is_alive(RcControlBlock *cb) {
    if (!cb) return false;
    if (cb->strong_count > 0) return true;
    return (cb->color == GC_BLACK || cb->color == GC_GREY);
}

static int64_t __inst_MyAdd_add_int(int64_t, int64_t);
static int64_t __inst_MyAdd_add_int(int64_t x, int64_t y) {
        return ((x) + (y));
}

typedef struct dict_MyAdd_int {
    int64_t (*add)(int64_t, int64_t);
} dict_MyAdd_int;

static dict_MyAdd_int dict_MyAdd_int_singleton = {
    .add = __inst_MyAdd_add_int,
};

int main() {
        return (int)INT64_C(0);
}


