/* kind_check.c — Kind inference and validation pass (Phase HKT H1/H2).
 *
 * This pass runs after elaboration (PASS_KIND_CHECK slot).  In Phase H1 it
 * performs two jobs:
 *
 *   1. Kind annotation propagation: walk all EX_TYPECLASS_DEF nodes; for
 *      each typeclass with kind-annotated parameters (type_param_kinds !=
 *      NULL), ensure the kind array is consistent (sets KIND_STAR for any
 *      un-annotated slot).
 *
 *   2. Kind validation at instance sites: walk all EX_TYPECLASS_INST_DEF
 *      nodes; for each instance, confirm that the type_args satisfy the
 *      corresponding kind constraints declared on the typeclass.  This is a
 *      belt-and-suspenders check — elab_definstance already performs the
 *      same validation, so this pass reports the same error only if it finds
 *      a mismatch that slipped through (e.g. generated by a macro).
 *
 * Phase H2 adds:
 *
 *   3. Bottom-up kind inference: if a typeclass parameter's kind was
 *      recorded as KIND_STAR but a definstance supplies a KIND_ARROW type
 *      argument for that position, upgrade the parameter's kind to
 *      KIND_ARROW.  This makes the explicit `^f` annotation optional.
 */

#include "kind_check.h"
#include "diag.h"
#include "expr.h"
#include "typeclass.h"
#include "types.h"

/* ---------------------------------------------------------------------------
 * Phase HKT H2: KindEnv — symbol → Kind map
 * ------------------------------------------------------------------------- */

typedef struct KindEnvEntry {
    const Symbol       *sym;
    Kind                k;
    struct KindEnvEntry *next;
} KindEnvEntry;

struct KindEnv {
    Arena        *arena;
    KindEnvEntry *head;
};

KindEnv *kind_env_new(Arena *a) {
    KindEnv *env = (KindEnv *)arena_alloc(a, sizeof(KindEnv));
    env->arena = a;
    env->head  = NULL;
    return env;
}

Kind kind_env_lookup(const KindEnv *env, const Symbol *sym) {
    if (!env || !sym) return KIND_STAR;
    for (KindEnvEntry *e = env->head; e; e = e->next) {
        if (e->sym == sym) return e->k;
    }
    return KIND_STAR;
}

/* Forward-declare so kind_env_bind can call it. */
static Kind kind_unify_internal(Kind k1, Kind k2, Span span, bool emit_diag);

void kind_env_bind(KindEnv *env, const Symbol *sym, Kind k, Span span) {
    if (!env || !sym) return;
    for (KindEnvEntry *e = env->head; e; e = e->next) {
        if (e->sym == sym) {
            e->k = kind_unify_internal(e->k, k, span, true);
            return;
        }
    }
    /* New binding */
    KindEnvEntry *entry = (KindEnvEntry *)arena_alloc(env->arena, sizeof(KindEnvEntry));
    entry->sym  = sym;
    entry->k    = k;
    entry->next = env->head;
    env->head   = entry;
}

/* ---------------------------------------------------------------------------
 * Phase HKT H2: kind_unify
 * ------------------------------------------------------------------------- */

/* True if k is one of KIND_ARROW..KIND_ARROW5 (i.e. a non-zero arity
 * type-constructor kind, excluding KIND_STAR and KIND_ROW). */
static bool kind_is_arrow_ladder(Kind k) {
    return k == KIND_ARROW  || k == KIND_ARROW2 ||
           k == KIND_ARROW3 || k == KIND_ARROW4 || k == KIND_ARROW5;
}

static Kind kind_unify_internal(Kind k1, Kind k2, Span span, bool emit_diag) {
    if (k1 == k2) return k1;
    /* Within the arrow ladder, prefer the more refined (higher-arity) kind.
     * This preserves the legacy KIND_ARROW + KIND_ARROW2 → KIND_ARROW2
     * behaviour and extends it to the full ladder. */
    if (kind_is_arrow_ladder(k1) && kind_is_arrow_ladder(k2)) {
        return (k1 > k2) ? k1 : k2;
    }
    /* Mismatch between star and arrow (or anything involving KIND_ROW) */
    if (emit_diag) {
        diag_emit_with_code(DIAG_ERROR, span, TUR_E0012_KIND_MISMATCH,
            "kind mismatch (TUR-E0012): cannot unify kind '%s' with kind '%s'",
            kind_to_string(k1), kind_to_string(k2));
    }
    return KIND_STAR;
}

Kind kind_unify(Kind k1, Kind k2, Span span) {
    return kind_unify_internal(k1, k2, span, true);
}



/* ---------------------------------------------------------------------------
 * Internal helpers
 * ------------------------------------------------------------------------- */

/* Returns the effective kind of a Type value in H1.
 * Primitive scalar types are KIND_STAR.
 * Struct types: concrete structs (def != NULL) are KIND_STAR; opaque type
 *   constructor references (def == NULL, used in HKT instance declarations)
 *   are KIND_ARROW.
 * TY_APP: result kind is computed from fn's kind (see kind_of_type_app).
 * TY_REC: kind is KIND_ARROW (recursive type constructors have kind * -> *).
 * All other types default to KIND_STAR in H1. */
static Kind type_effective_kind(Type t) {
    switch (t.kind) {
        case TY_STRUCT:
            /* Concrete struct types (with a StructDef) have kind * — they are
             * fully-applied types like Pair, Error, etc.  Opaque type constructor
             * references (def == NULL) are used in HKT contexts (e.g. option in
             * (definstance Functor [option])) and default to KIND_ARROW. */
            return (t.as.struct_.def != NULL) ? KIND_STAR : KIND_ARROW;
        case TY_REC:    return KIND_ARROW;  /* Phase HKT-P2 */
        /* KB-027: rc<T> and weak<T> are built-in type constructors of kind
         * '* -> *', so a Functor/Foldable instance on the bare `rc` constructor
         * is well-kinded.  (The inference pass below avoids promoting a
         * STAR-declared class such as Clone [rc] off the back of this.) */
        case TY_RC:
        case TY_WEAK:   return KIND_ARROW;
        case TY_APP:
            /* Phase HKT-P1: result kind depends on fn's kind */
            if (t.as.app.fn) {
                return kind_apply_one(t.as.app.fn->hkt_kind);
            }
            return KIND_STAR;
        case TY_INT:
        case TY_BOOL:
        case TY_CSTR:
        case TY_NIL:
        case TY_FLOAT:
        case TY_PTR_VOID:
            return KIND_STAR;
        default:
            return KIND_STAR;
    }
}

/* ---------------------------------------------------------------------------
 * Phase HKT-P1: kind_of_type_app
 * ------------------------------------------------------------------------- */

/* Infer the result kind of a type application (type-app fn_type arg_type).
 *
 * fn_type.hkt_kind must be one of KIND_ARROW..KIND_ARROW5; each application
 * steps the kind one rung down the ladder (ARROW5 → ARROW4 → ... → STAR).
 *
 * Emits TUR_E0012_KIND_MISMATCH and returns KIND_STAR if fn_type.hkt_kind
 * is KIND_STAR or KIND_ROW (cannot apply a non-constructor kind). */
Kind kind_of_type_app(Type fn_type, Type arg_type, Span span) {
    (void)arg_type;  /* arg kind not validated separately in v1 */
    switch (fn_type.hkt_kind) {
        case KIND_ARROW:
        case KIND_ARROW2:
        case KIND_ARROW3:
        case KIND_ARROW4:
        case KIND_ARROW5:
            return kind_apply_one(fn_type.hkt_kind);
        case KIND_STAR:
        case KIND_ROW:
            diag_emit_with_code(DIAG_ERROR, span, TUR_E0012_KIND_MISMATCH,
                "kind mismatch (TUR-E0012): cannot apply a type of kind '*' as a "
                "type constructor; type must have kind '* -> *' through "
                "'* -> * -> * -> * -> * -> *'");
            return KIND_STAR;
    }
    return KIND_STAR;
}

/* ---------------------------------------------------------------------------
 * Phase HKT-P2: occurs-check helper for TY_REC
 * ------------------------------------------------------------------------- */

/* Returns true if 'rec_name' appears in type 't' without going through
 * a TY_APP node (unguarded self-recursion causes infinite unrolling). */
static bool rec_name_occurs_unguarded(const char *rec_name, Type *t, int depth) {
    if (!t || depth > 16) return false;
    switch (t->kind) {
        case TY_REC:
            /* Same interned name pointer → unguarded self-reference */
            return (t->as.rec.name == rec_name);
        case TY_APP:
            /* TY_APP guards the recursion */
            return false;
        default:
            return false;
    }
}

/* Walk a single Expr node (non-recursive helper used by the tree walk). */
static int kind_check_expr(Expr *expr) {
    if (!expr) return 0;
    int errors = 0;

    switch (expr->kind) {
        case EX_TYPECLASS_DEF: {
            /* Propagate: fill NULL kind slots with KIND_STAR. */
            TypeClass *tc = expr->as.typeclass_def_.typeclass;
            if (tc && tc->n_type_params > 0 && tc->type_param_kinds == NULL) {
                /* type_param_kinds was never allocated — all params are KIND_STAR
                 * by definition; nothing to validate. */
            }
            break;
        }
        case EX_INSTANCE_DEF: {
            /* Belt-and-suspenders: validate kind constraints on type_args. */
            TypeClassInstance *inst = expr->as.instance_def_.instance;
            if (inst && inst->typeclass && inst->typeclass->type_param_kinds) {
                TypeClass *tc = inst->typeclass;
                for (uint8_t i = 0; i < inst->n_type_args; i++) {
                    if (i >= tc->n_type_params) break;
                    Kind expected = tc->type_param_kinds[i];
                    if (expected == KIND_ARROW) {
                        Kind actual = type_effective_kind(inst->type_args[i]);
                        if (actual != KIND_ARROW) {
                            diag_emit_with_code(DIAG_ERROR, expr->span,
                                TUR_E0012_KIND_MISMATCH,
                                "kind mismatch (TUR-E0012): instance of '%s' provides a "
                                "kind-'*' type for parameter %d which expects kind '* -> *'",
                                tc->name->name, (int)(i + 1));
                            errors++;
                        }
                    }
                }
            }
            break;
        }
        case EX_DEF: {
            /* Phase HKT-P2: occurs-check — report an unguarded self-recursive TY_REC.
             * In v1 the body is always NULL so this is a no-op, but the check is
             * in place for when body evaluation is added in a later phase. */
            Binding *b = expr->as.def_.binding;
            if (b && b->type.kind == TY_REC && b->type.as.rec.body) {
                if (rec_name_occurs_unguarded(b->type.as.rec.name,
                                              b->type.as.rec.body, 0)) {
                    diag_emit_with_code(DIAG_ERROR, expr->span,
                        TUR_E0012_KIND_MISMATCH,
                        "kind mismatch (TUR-E0012): recursive type '%s' has an "
                        "unguarded self-reference (wrap recursive use in a type "
                        "application to make the recursion guarded)",
                        b->type.as.rec.name ? b->type.as.rec.name : "<rec>");
                    errors++;
                }
            }
            break;
        }
        case EX_DEFGADT: {
            /* Phase G1/HKT: Walk each constructor's return-type form.
             * For each constructor with an explicit return-type annotation,
             * check that any F_LIST sub-form (type application) in argument
             * position has a well-kinded head.
             *
             * The primary kind check runs in elab_defgadt at elaboration time.
             * This pass adds a belt-and-suspenders walk that fires after all
             * type information has been propagated (e.g. by kind_infer_from_instances).
             *
             * In Phase G1 all GADT type parameters have kind *, so any
             * constructor return-type argument that is itself a type
             * application (F_LIST) is suspicious: the head must be a type
             * constructor of kind * -> *.  elab_defgadt already validates
             * bare-symbol arguments; here we validate F_LIST sub-forms by
             * checking that the result_type_form is well-structured (non-NULL
             * head symbol that is the GADT name). */
            AdtDef *def = expr->as.defgadt_.def;
            if (!def || !def->is_gadt) break;
            for (uint32_t ci = 0; ci < def->n_ctors; ci++) {
                CtorDef *ctor = def->ctors[ci];
                if (!ctor || !ctor->result_type_form) continue;
                const struct Form *rtf = ctor->result_type_form;
                if (rtf->tag != F_LIST || rtf->as.list.len < 1) continue;
                /* Walk argument sub-forms (indices 1..len-1). */
                for (uint32_t ai = 1; ai < rtf->as.list.len; ai++) {
                    const struct Form *arg = rtf->as.list.items[ai];
                    if (arg->tag != F_LIST) continue; /* bare symbols validated by elab */
                    /* F_LIST sub-form: type application in argument position.
                     * HEAD must be a type constructor (its kind is resolved at
                     * elaboration time by elab_defgadt).  Here we confirm the
                     * head is a symbol (not a nested application), which is the
                     * only form that elab validates.  Nested F_LIST heads
                     * (curried applications) are future work requiring a full
                     * KindEnv pass. */
                    if (arg->as.list.len < 1) continue;
                    const struct Form *app_head = arg->as.list.items[0];
                    if (app_head->tag != F_SYM) {
                        diag_emit_with_code(DIAG_ERROR, arg->span,
                            TUR_E0012_KIND_MISMATCH,
                            "kind mismatch (TUR-E0012): constructor '%s' return-type "
                            "argument is a nested type application; only simple type "
                            "constructors are supported in Phase G1",
                            ctor->name);
                        errors++;
                    }
                }
            }
            break;
        }
        default:
            break;
    }

    /* Recurse into child expressions. */
    switch (expr->kind) {
        case EX_DO: {
            for (uint32_t i = 0; i < expr->as.do_.n; i++) {
                errors += kind_check_expr(expr->as.do_.items[i]);
            }
            break;
        }
        case EX_FN_DEF:
            if (expr->as.fn_def_.fn && expr->as.fn_def_.fn->body)
                errors += kind_check_expr(expr->as.fn_def_.fn->body);
            break;
        case EX_FN:
            if (expr->as.fn_.fn && expr->as.fn_.fn->body)
                errors += kind_check_expr(expr->as.fn_.fn->body);
            break;
        case EX_LET:
            for (uint32_t i = 0; i < expr->as.let_.n; i++) {
                errors += kind_check_expr(expr->as.let_.bindings[i].init);
            }
            errors += kind_check_expr(expr->as.let_.body);
            break;
        case EX_CALL: {
            for (uint32_t i = 0; i < expr->as.call_.n_args; i++) {
                errors += kind_check_expr(expr->as.call_.args[i]);
            }
            break;
        }
        case EX_IF:
            errors += kind_check_expr(expr->as.if_.cond);
            errors += kind_check_expr(expr->as.if_.then_);
            if (expr->as.if_.else_or_null)
                errors += kind_check_expr(expr->as.if_.else_or_null);
            break;
        default:
            break;
    }

    return errors;
}

/* ---------------------------------------------------------------------------
 * Phase HKT H2: bottom-up kind inference from definstance type arguments
 *
 * Walk all EX_INSTANCE_DEF nodes in the top-level do-block.  For each
 * instance that provides a KIND_ARROW..KIND_ARROW5 type arg at position i,
 * if the corresponding typeclass parameter's recorded kind is KIND_STAR
 * (i.e. no explicit `^f` annotation was given), upgrade it to the inferred
 * kind.
 *
 * This makes `^f` optional: writing `(defclass Functor [f])` and then
 * `(definstance Functor [option])` causes the pass to infer that param 0 of
 * Functor has kind `* -> *`.
 * ------------------------------------------------------------------------- */

static void kind_infer_from_instances(Arena *a, Expr **items, uint32_t n) {
    /* We need a stable kind array for each typeclass.  Allocate lazily when
     * first needed (mirrors elab_defclass). */
    for (uint32_t idx = 0; idx < n; idx++) {
        Expr *e = items[idx];
        if (!e || e->kind != EX_INSTANCE_DEF) continue;
        TypeClassInstance *inst = e->as.instance_def_.instance;
        if (!inst || !inst->typeclass) continue;
        TypeClass *tc = inst->typeclass;

        /* Ensure type_param_kinds is allocated. */
        if (!tc->type_param_kinds && tc->n_type_params > 0) {
            tc->type_param_kinds = (Kind *)arena_alloc(a,
                tc->n_type_params * sizeof(Kind));
            /* arena_alloc zeroes → all KIND_STAR by default. */
        }

        for (uint8_t i = 0; i < inst->n_type_args && i < tc->n_type_params; i++) {
            Kind arg_kind = type_effective_kind(inst->type_args[i]);
            Kind cur_kind = tc->type_param_kinds ? tc->type_param_kinds[i] : KIND_STAR;

            if (arg_kind == KIND_STAR && cur_kind == KIND_STAR) {
                /* No inference needed. */
                continue;
            }
            if (cur_kind == KIND_STAR && arg_kind != KIND_STAR) {
                /* Infer: upgrade parameter kind from STAR to ARROW / ARROW2.
                 * Only upgrade when the param was un-annotated (KIND_STAR by
                 * default from elab).  Explicit annotations (KIND_ARROW or
                 * KIND_ARROW2 from '^f' / '^^f') are never overridden.
                 *
                 * Exception (KB-030): an opaque struct reference (TY_STRUCT
                 * with def == NULL) is the elaborator's representation for any
                 * bare type name it could not resolve to a concrete struct --
                 * both genuine HKT constructors (option, vec) and concrete
                 * built-in types that simply have no defstruct (str).
                 * type_effective_kind optimistically reports KIND_ARROW for it,
                 * which is right for an explicitly higher-kinded class ('^f',
                 * validated separately) but must NOT silently promote a
                 * STAR-declared class (e.g. Eq [a]) just because one of its
                 * instances names such a built-in.  Skip the upgrade for
                 * opaque-struct args; real constructor args (TY_APP, TY_REC)
                 * still drive inference. */
                bool opaque_struct_arg =
                    (inst->type_args[i].kind == TY_STRUCT &&
                     inst->type_args[i].as.struct_.def == NULL);
                /* KB-027: rc<T>/weak<T> report KIND_ARROW (they are genuine
                 * constructors), but in v1 they also stand in as concrete
                 * carrier handles for STAR-declared classes (Clone [rc]).
                 * Don't let such an instance promote the class to higher kind. */
                bool builtin_carrier_arg =
                    (inst->type_args[i].kind == TY_RC ||
                     inst->type_args[i].kind == TY_WEAK);
                if (!opaque_struct_arg && !builtin_carrier_arg) {
                    tc->type_param_kinds[i] = arg_kind;
                }
            }
            /* If cur_kind is already non-STAR (explicitly annotated), we trust
             * the annotation and skip any conflict check.  type_effective_kind
             * returns KIND_ARROW for all TY_STRUCT regardless of arity, so a
             * KIND_ARROW2 annotation on a TY_STRUCT argument is intentional. */
        }
    }
}

/* ---------------------------------------------------------------------------
 * Public entry point
 * ------------------------------------------------------------------------- */

int kind_check_pass(Arena *a, Expr *program) {
    if (!program) return 0;
    int errors = 0;

    Expr   **items = NULL;
    uint32_t n     = 0;
    if (program->kind == EX_DO) {
        items = program->as.do_.items;
        n     = program->as.do_.n;
    } else if (program->kind == EX_PROGRAM) {
        items = program->as.program.items;
        n     = program->as.program.n;
    }

    /* Phase HKT H2: infer typeclass parameter kinds from definstance type args
     * (runs before validation so the belt-and-suspenders check in
     * kind_check_expr sees the inferred kinds). */
    if (items && n > 0) {
        kind_infer_from_instances(a, items, n);
    }

    /* Walk all top-level items. */
    if (items) {
        for (uint32_t i = 0; i < n; i++) {
            errors += kind_check_expr(items[i]);
        }
    } else {
        errors += kind_check_expr(program);
    }

    return errors > 0 ? 1 : 0;
}

/* ---------------------------------------------------------------------------
 * Phase HKT-P6: kind_dump_program — debug helper for --dump-kinds
 * ------------------------------------------------------------------------- */

/* Print type arguments for a TypeClassInstance in a compact form. */
static void dump_instance_type_args_(TypeClassInstance *inst, FILE *out) {
    if (!inst) return;
    fputc('[', out);
    for (uint8_t a = 0; a < inst->n_type_args; a++) {
        if (a > 0) fputs(", ", out);
        const char *n = type_name(inst->type_args[a]);
        fputs(n ? n : "?", out);
    }
    fputc(']', out);
}

void kind_dump_program(Expr *program, FILE *out) {
    if (!program || !out) return;

    Expr   **items = NULL;
    uint32_t n     = 0;
    if (program->kind == EX_DO) {
        items = program->as.do_.items;
        n     = program->as.do_.n;
    } else if (program->kind == EX_PROGRAM) {
        items = program->as.program.items;
        n     = program->as.program.n;
    } else {
        return;
    }

    for (uint32_t i = 0; i < n; i++) {
        Expr *e = items[i];
        if (!e) continue;

        if (e->kind == EX_TYPECLASS_DEF) {
            /* Print each type parameter that has a non-KIND_STAR kind. */
            TypeClass *tc = e->as.typeclass_def_.typeclass;
            if (!tc || !tc->name) continue;
            for (uint8_t p = 0; p < tc->n_type_params; p++) {
                Kind k = (tc->type_param_kinds ? tc->type_param_kinds[p]
                                               : KIND_STAR);
                if (k != KIND_STAR) {
                    fprintf(out, "defclass %s param[%u] : %s\n",
                            tc->name->name, (unsigned)p, kind_to_string(k));
                }
            }

        } else if (e->kind == EX_INSTANCE_DEF) {
            TypeClassInstance *inst = e->as.instance_def_.instance;
            if (!inst || !inst->typeclass || !inst->typeclass->name) continue;

            /* Only print instances where the typeclass has HKT parameters. */
            bool has_hkt = false;
            if (inst->typeclass->type_param_kinds) {
                for (uint8_t p = 0; p < inst->typeclass->n_type_params; p++) {
                    if (inst->typeclass->type_param_kinds[p] != KIND_STAR) {
                        has_hkt = true;
                        break;
                    }
                }
            }
            if (has_hkt) {
                fprintf(out, "definstance %s ", inst->typeclass->name->name);
                dump_instance_type_args_(inst, out);
                fputc('\n', out);
            }
        }
    }
}

/* ---------------------------------------------------------------------------
 * Phase HKT-P6: kind_verify_program — debug assertion
 * Verifies that Kind information is preserved through all compiler passes.
 * --------------------------------------------------------------------------- */

/* True if k is a known kind value on the * / arrow ladder (KIND_ROW is
 * intentionally excluded — it appears only on row variables, not as a
 * type's hkt_kind). */
static bool kind_is_valid(Kind k) {
    return k == KIND_STAR   || k == KIND_ARROW  || k == KIND_ARROW2 ||
           k == KIND_ARROW3 || k == KIND_ARROW4 || k == KIND_ARROW5;
}

/* Helper: recursively verify kind info is present on types */
static bool kind_verify_type(const Type *t) {
    if (!t) return true;
    /* All types should have a valid hkt_kind on the ladder. */
    if (!kind_is_valid(t->hkt_kind)) {
        return false;
    }
    switch (t->kind) {
        case TY_APP:
            return kind_verify_type(t->as.app.fn) && kind_verify_type(t->as.app.arg);
        case TY_REC:
            return kind_verify_type(t->as.rec.body);
        default:
            /* Most types don't have nested kind info in v1 */
            return true;
    }
}

/* Helper: recursively verify kind info on typeclass instances */
static bool kind_verify_typeclass_instance(const TypeClassInstance *inst) {
    if (!inst) return true;
    /* Verify typeclass has kind info on its parameters */
    if (inst->typeclass && inst->typeclass->type_param_kinds) {
        for (uint8_t i = 0; i < inst->typeclass->n_type_params; i++) {
            Kind k = inst->typeclass->type_param_kinds[i];
            if (!kind_is_valid(k)) {
                return false;
            }
        }
    }
    /* Verify type args have kind info */
    for (uint8_t i = 0; i < inst->n_type_args; i++) {
        if (!kind_verify_type(&inst->type_args[i])) {
            return false;
        }
    }
    return true;
}

/* Helper: recursively verify kind info on expressions */
static bool kind_verify_expr(const Expr *e) {
    if (!e) return true;
    
    switch (e->kind) {
        case EX_DEF:
            /* Check the type of the binding */
            if (e->as.def_.binding && !kind_verify_type(&e->as.def_.binding->type)) {
                return false;
            }
            return kind_verify_expr(e->as.def_.init);
        case EX_LET:
            for (uint32_t i = 0; i < e->as.let_.n; i++) {
                if (e->as.let_.bindings[i].binding && 
                    !kind_verify_type(&e->as.let_.bindings[i].binding->type)) {
                    return false;
                }
            }
            return kind_verify_expr(e->as.let_.body);
        case EX_TYPECLASS_DEF:
            if (e->as.typeclass_def_.typeclass && e->as.typeclass_def_.typeclass->type_param_kinds) {
                for (uint8_t i = 0; i < e->as.typeclass_def_.typeclass->n_type_params; i++) {
                    Kind k = e->as.typeclass_def_.typeclass->type_param_kinds[i];
                    if (k != KIND_STAR && k != KIND_ARROW && k != KIND_ARROW2) {
                        return false;
                    }
                }
            }
            return true;
        case EX_INSTANCE_DEF:
            return kind_verify_typeclass_instance(e->as.instance_def_.instance);
        case EX_PROGRAM:
        case EX_DO:
            for (uint32_t i = 0; i < e->as.do_.n; i++) {
                if (!kind_verify_expr(e->as.do_.items[i])) {
                    return false;
                }
            }
            return true;
        default:
            return true;
    }
}

/* Verify that Kind information is preserved on the program.
 * In debug builds, this can be called after each pass to ensure
 * kind info is not inadvertently cleared. Returns true if all
 * kind info appears valid, false otherwise. */
bool kind_verify_program(const Expr *program) {
    if (!program) return true;
    return kind_verify_expr(program);
}

