/* generated by tur (phase 2) */
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
extern void *malloc(size_t);
extern void free(void *);

/* tur_frame - phase 4 v1 lowering (from runtime.h) */
typedef void (*defer_fn_t)(void *env);
#define TUR_FRAME_MAX_DEFERS 32

typedef struct tur_frame {
    defer_fn_t defers[TUR_FRAME_MAX_DEFERS];
    void *envs[TUR_FRAME_MAX_DEFERS];
    int n;
    struct tur_frame *parent;
    bool may_capture;
} tur_frame;

static inline void tur_frame_init(tur_frame *f, tur_frame *parent) {
    f->n = 0; f->parent = parent; f->may_capture = false;
}
static inline int tur_frame_push_defer(tur_frame *f, defer_fn_t thunk, void *env) {
    if (f->n >= TUR_FRAME_MAX_DEFERS) return -1;
    f->defers[f->n] = thunk;
    f->envs[f->n] = env;
    f->n++;
    return 0;
}
static void tur_frame_fire_lifo(tur_frame *f) {
    for (int i = f->n - 1; i >= 0; i--) f->defers[i](f->envs[i]);
    f->n = 0;
}

static bool is_even(int64_t);
static bool is_odd(int64_t);
static bool is_even(int64_t n) {
        bool __t0;
        if (((n) == (INT64_C(0)))) {
            __t0 = true;
        } else {
            __t0 = is_odd(((n) - (INT64_C(1))));
        }
        return __t0;
}

static bool is_odd(int64_t n) {
        bool __t1;
        if (((n) == (INT64_C(0)))) {
            __t1 = false;
        } else {
            __t1 = is_even(((n) - (INT64_C(1))));
        }
        return __t1;
}

int main() {
        puts((is_even(INT64_C(4))) ? "true" : "false");
        return (int)0;
}


