/* generated by tur (phase 2) */
#ifndef TUR_adder_H
#define TUR_adder_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int64_t adder__add(int64_t, int64_t);
#endif /* TUR_adder_H */
