/* generated by tur (phase 2) */
#include "input.h"

static int64_t __inst_Functor_fmap_option(int64_t container, int64_t fn) {
        return __fmap_option(container, fn);
}

typedef struct dict_Functor_option {
    int64_t (*fmap)(int64_t, int64_t);
} dict_Functor_option;

static dict_Functor_option dict_Functor_option_singleton = {
    .fmap = __inst_Functor_fmap_option,
};

static int64_t __inst_Functor_fmap_vec(int64_t container, int64_t fn) {
        return __fmap_vec(container, fn);
}

typedef struct dict_Functor_vec {
    int64_t (*fmap)(int64_t, int64_t);
} dict_Functor_vec;

static dict_Functor_vec dict_Functor_vec_singleton = {
    .fmap = __inst_Functor_fmap_vec,
};

static int64_t __opt_some(int64_t x) {
        struct { bool is_some; int64_t value; } *r = malloc(sizeof(*r));
  r->is_some = true;
  r->value = x;
  return (int64_t)(intptr_t)r;
  
}

static bool __opt_some_(int64_t o) {
        struct { bool is_some; int64_t value; } *p =
      (struct { bool is_some; int64_t value; } *)(intptr_t)o;
  return p != 0 && p->is_some;
  
}

static int64_t __opt_unwrap(int64_t o) {
        struct { bool is_some; int64_t value; } *p =
      (struct { bool is_some; int64_t value; } *)(intptr_t)o;
  return (int64_t)(p->value);
  
}

static int64_t __fmap_option(int64_t container, int64_t fn) {
        struct { bool is_some; int64_t value; } *c =
      (struct { bool is_some; int64_t value; } *)(intptr_t)container;
  if (!c || !c->is_some) return 0;
  struct { bool is_some; int64_t value; } *r = malloc(sizeof(*r));
  r->is_some = true;
  r->value = ((int64_t(*)(int64_t))(intptr_t)fn)(c->value);
  return (int64_t)(intptr_t)r;
  
}

static int64_t __vec_of(int64_t x) {
        struct { int64_t len; int64_t item; } *r = malloc(sizeof(*r));
  r->len = 1;
  r->item = x;
  return (int64_t)(intptr_t)r;
  
}

static int64_t __vec_get0(int64_t v) {
        struct { int64_t len; int64_t item; } *p =
      (struct { int64_t len; int64_t item; } *)(intptr_t)v;
  return p->item;
  
}

static int64_t __fmap_vec(int64_t container, int64_t fn) {
        struct { int64_t len; int64_t item; } *c =
      (struct { int64_t len; int64_t item; } *)(intptr_t)container;
  struct { int64_t len; int64_t item; } *r = malloc(sizeof(*r));
  r->len = c->len;
  r->item = ((int64_t(*)(int64_t))(intptr_t)fn)(c->item);
  return (int64_t)(intptr_t)r;
  
}

static int64_t add5(int64_t x) {
        return ((x) + (INT64_C(5)));
}

static int64_t twice(int64_t x) {
        return ((x) * (INT64_C(2)));
}

int main() {
        {
            int64_t o_27 = __opt_some(INT64_C(10));
            (void)o_27;
            {
                int64_t o2_28 = __inst_Functor_fmap_vec(o_27, (int64_t)(intptr_t)(add5));
                (void)o2_28;
                puts((__opt_some_(o2_28)) ? "true" : "false");
                printf("%lld\n", (long long)(__opt_unwrap(o2_28)));
            }
        }
        {
            int64_t v_29 = __vec_of(INT64_C(7));
            (void)v_29;
            {
                int64_t v2_30 = __inst_Functor_fmap_vec(v_29, (int64_t)(intptr_t)(twice));
                (void)v2_30;
                printf("%lld\n", (long long)(__vec_get0(v2_30)));
            }
        }
        int64_t __t0;
        __t0 = INT64_C(0);
        return (int)__t0;
}


