/* generated by tur (phase 2) */
#ifndef TUR_input_H
#define TUR_input_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int64_t __inst_Functor_fmap_option(int64_t, int64_t);
int64_t __inst_Functor_fmap_vec(int64_t, int64_t);
int64_t __opt_some(int64_t);
bool __opt_some_(int64_t);
int64_t __opt_unwrap(int64_t);
int64_t __fmap_option(int64_t, int64_t);
int64_t __vec_of(int64_t);
int64_t __vec_get0(int64_t);
int64_t __fmap_vec(int64_t, int64_t);
int64_t add5(int64_t);
int64_t twice(int64_t);
#endif /* TUR_input_H */
