/* generated by tur (phase 2) */
#ifndef TUR_myapp_H
#define TUR_myapp_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "adder.h"

#endif /* TUR_myapp_H */
