/* generated by tur (phase 2) */
#include "str.h"

static void str_from_cstr(int64_t cstr) {
        const char *s = (const char*)cstr;
  size_t len = strlen(s);
  struct { const char *p; size_t len; } *str = malloc(sizeof(*str));
  str->p = s;
  str->len = len;
  return str;
  
}

static int64_t str_len(int64_t s) {
        struct { const char *p; size_t len; } *str = (void*)s;
  return (int)str->len;
  
}

static bool str_eq_(int64_t s1, int64_t s2) {
        struct { const char *p; size_t len; } *a = (void*)s1;
  struct { const char *p; size_t len; } *b = (void*)s2;
  if (a == NULL || b == NULL) return a == b;
  if (a->len != b->len) return false;
  return memcmp(a->p, b->p, a->len) == 0;
  
}

static void str_free(int64_t s) {
        free(s);
  return 0;
  
}


