/* generated by tur (phase 2) */
#ifndef TUR_time_H
#define TUR_time_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

extern void * time(int64_t);
extern int64_t clock(int64_t);
extern int64_t nanosleep(int64_t, int64_t);
extern void * malloc(int64_t, int64_t);
extern void free(int64_t, int64_t);
#endif /* TUR_time_H */
