/* generated by tur (phase 2) */
#include "time.h"

extern void * time(int64_t);
extern int64_t clock(int64_t);
extern int64_t nanosleep(int64_t, int64_t);
extern void * malloc(int64_t, int64_t);
extern void free(int64_t, int64_t);
static void Real_Time() {
        /* Define the Time struct */
  typedef struct Time Time;
  struct Time {
      int (*now)(void);
      void (*sleep)(int ms);
  };
  
  /* now implementation - returns milliseconds since epoch */
  static int time_now(void) {
      time_t now = time(NULL);
      /* Convert seconds to milliseconds (approximate) */
      return (int)(now * 1000);
  }
  
  /* sleep implementation - sleeps for ms milliseconds */
  static void time_sleep(int ms) {
      if (ms <= 0) return;
      
      /* Convert ms to seconds and nanoseconds */
      long seconds = ms / 1000;
      long nanoseconds = (ms % 1000) * 1000000;
      
      struct timespec req = {.tv_sec = seconds, .tv_nsec = nanoseconds};
      struct timespec rem;
      
      while (nanosleep(&req, &rem) == -1) {
          /* If interrupted, sleep for remaining time */
          req = rem;
      }
  }
  
  /* Create and populate the capability struct */
  Time* time = (Time*)malloc(sizeof(Time));
  time->now = time_now;
  time->sleep = time_sleep;
  return (void*)time;
  
}

static void Real_Time_free(int64_t t) {
        free(t);
  
}

static void HighRes_Time() {
        typedef struct Time Time;
  struct Time {
      int (*now)(void);
      void (*sleep)(int ms);
  };
  
  /* now implementation - returns CPU time in milliseconds */
  static int hires_now(void) {
      clock_t now = clock();
      /* CLOCKS_PER_SEC is typically 1000000 */
      return (int)(now * 1000 / CLOCKS_PER_SEC);
  }
  
  /* sleep implementation */
  static void hires_sleep(int ms) {
      if (ms <= 0) return;
      
      long seconds = ms / 1000;
      long nanoseconds = (ms % 1000) * 1000000;
      
      struct timespec req = {.tv_sec = seconds, .tv_nsec = nanoseconds};
      struct timespec rem;
      
      while (nanosleep(&req, &rem) == -1) {
          req = rem;
      }
  }
  
  /* Create and populate the capability struct */
  Time* time = (Time*)malloc(sizeof(Time));
  time->now = hires_now;
  time->sleep = hires_sleep;
  return (void*)time;
  
}

static void HighRes_Time_free(int64_t t) {
        free(t);
  
}

static void Mock_Time() {
        /* Define the Time struct */
  typedef struct MockTime MockTime;
  struct MockTime {
      int (*now)(void);
      void (*sleep)(int ms);
      int current_time;  /* Current mock time in milliseconds */
  };
  
  static MockTime* mock_time = NULL;
  
  /* now implementation - returns current mock time */
  static int mock_now(void) {
      if (!mock_time) return 0;
      return mock_time->current_time;
  }
  
  /* sleep implementation - advances mock time */
  static void mock_sleep(int ms) {
      if (!mock_time) return;
      mock_time->current_time += ms;
  }
  
  /* Create and populate the capability struct */
  mock_time = (MockTime*)malloc(sizeof(MockTime));
  mock_time->current_time = 0;
  
  Time* time = (Time*)malloc(sizeof(Time));
  time->now = mock_now;
  time->sleep = mock_sleep;
  return (void*)time;
  
}

static void Mock_Time_free(int64_t t) {
        free(t);
  
}

static void mock_time_set(int64_t t, int64_t new_time) {
        typedef struct MockTime MockTime;
  MockTime* mock_time = (MockTime*)t;
  mock_time->current_time = new_time;
  
}

static void mock_time_get(int64_t t) {
        typedef struct MockTime MockTime;
  MockTime* mock_time = (MockTime*)t;
  return mock_time->current_time;
  
}

static void get_time_ms() {
        time_t now = time(NULL);
  return (int)(now * 1000);
  
}

static void sleep_ms(int64_t ms) {
        if (ms <= 0) return;
  long seconds = ms / 1000;
  long nanoseconds = (ms % 1000) * 1000000;
  struct timespec req = {.tv_sec = seconds, .tv_nsec = nanoseconds};
  struct timespec rem;
  while (nanosleep(&req, &rem) == -1) {
      req = rem;
  }
  
}

static void get_cpu_time() {
        clock_t now = clock();
  return (int)(now * 1000 / CLOCKS_PER_SEC);
  
}


