/* GENERATED by tools/gen_ffi_dispatch.py -- DO NOT EDIT BY HAND. */
#include "ffi_dispatch.h"

double tur_ffi_call_f_(void *fn) {
    return ((double (*)(void))fn)();
}

int64_t tur_ffi_call_i_(void *fn) {
    return ((int64_t (*)(void))fn)();
}

void tur_ffi_call_v_(void *fn) {
    ((void (*)(void))fn)();
}

double tur_ffi_call_f_f(void *fn, double a0) {
    return ((double (*)(double))fn)(a0);
}

int64_t tur_ffi_call_i_f(void *fn, double a0) {
    return ((int64_t (*)(double))fn)(a0);
}

void tur_ffi_call_v_f(void *fn, double a0) {
    ((void (*)(double))fn)(a0);
}

double tur_ffi_call_f_i(void *fn, int64_t a0) {
    return ((double (*)(int64_t))fn)(a0);
}

int64_t tur_ffi_call_i_i(void *fn, int64_t a0) {
    return ((int64_t (*)(int64_t))fn)(a0);
}

void tur_ffi_call_v_i(void *fn, int64_t a0) {
    ((void (*)(int64_t))fn)(a0);
}

double tur_ffi_call_f_ff(void *fn, double a0, double a1) {
    return ((double (*)(double, double))fn)(a0, a1);
}

int64_t tur_ffi_call_i_ff(void *fn, double a0, double a1) {
    return ((int64_t (*)(double, double))fn)(a0, a1);
}

void tur_ffi_call_v_ff(void *fn, double a0, double a1) {
    ((void (*)(double, double))fn)(a0, a1);
}

double tur_ffi_call_f_fi(void *fn, double a0, int64_t a1) {
    return ((double (*)(double, int64_t))fn)(a0, a1);
}

int64_t tur_ffi_call_i_fi(void *fn, double a0, int64_t a1) {
    return ((int64_t (*)(double, int64_t))fn)(a0, a1);
}

void tur_ffi_call_v_fi(void *fn, double a0, int64_t a1) {
    ((void (*)(double, int64_t))fn)(a0, a1);
}

double tur_ffi_call_f_if(void *fn, int64_t a0, double a1) {
    return ((double (*)(int64_t, double))fn)(a0, a1);
}

int64_t tur_ffi_call_i_if(void *fn, int64_t a0, double a1) {
    return ((int64_t (*)(int64_t, double))fn)(a0, a1);
}

void tur_ffi_call_v_if(void *fn, int64_t a0, double a1) {
    ((void (*)(int64_t, double))fn)(a0, a1);
}

double tur_ffi_call_f_ii(void *fn, int64_t a0, int64_t a1) {
    return ((double (*)(int64_t, int64_t))fn)(a0, a1);
}

int64_t tur_ffi_call_i_ii(void *fn, int64_t a0, int64_t a1) {
    return ((int64_t (*)(int64_t, int64_t))fn)(a0, a1);
}

void tur_ffi_call_v_ii(void *fn, int64_t a0, int64_t a1) {
    ((void (*)(int64_t, int64_t))fn)(a0, a1);
}

double tur_ffi_call_f_fff(void *fn, double a0, double a1, double a2) {
    return ((double (*)(double, double, double))fn)(a0, a1, a2);
}

int64_t tur_ffi_call_i_fff(void *fn, double a0, double a1, double a2) {
    return ((int64_t (*)(double, double, double))fn)(a0, a1, a2);
}

void tur_ffi_call_v_fff(void *fn, double a0, double a1, double a2) {
    ((void (*)(double, double, double))fn)(a0, a1, a2);
}

double tur_ffi_call_f_ffi(void *fn, double a0, double a1, int64_t a2) {
    return ((double (*)(double, double, int64_t))fn)(a0, a1, a2);
}

int64_t tur_ffi_call_i_ffi(void *fn, double a0, double a1, int64_t a2) {
    return ((int64_t (*)(double, double, int64_t))fn)(a0, a1, a2);
}

void tur_ffi_call_v_ffi(void *fn, double a0, double a1, int64_t a2) {
    ((void (*)(double, double, int64_t))fn)(a0, a1, a2);
}

double tur_ffi_call_f_fif(void *fn, double a0, int64_t a1, double a2) {
    return ((double (*)(double, int64_t, double))fn)(a0, a1, a2);
}

int64_t tur_ffi_call_i_fif(void *fn, double a0, int64_t a1, double a2) {
    return ((int64_t (*)(double, int64_t, double))fn)(a0, a1, a2);
}

void tur_ffi_call_v_fif(void *fn, double a0, int64_t a1, double a2) {
    ((void (*)(double, int64_t, double))fn)(a0, a1, a2);
}

double tur_ffi_call_f_fii(void *fn, double a0, int64_t a1, int64_t a2) {
    return ((double (*)(double, int64_t, int64_t))fn)(a0, a1, a2);
}

int64_t tur_ffi_call_i_fii(void *fn, double a0, int64_t a1, int64_t a2) {
    return ((int64_t (*)(double, int64_t, int64_t))fn)(a0, a1, a2);
}

void tur_ffi_call_v_fii(void *fn, double a0, int64_t a1, int64_t a2) {
    ((void (*)(double, int64_t, int64_t))fn)(a0, a1, a2);
}

double tur_ffi_call_f_iff(void *fn, int64_t a0, double a1, double a2) {
    return ((double (*)(int64_t, double, double))fn)(a0, a1, a2);
}

int64_t tur_ffi_call_i_iff(void *fn, int64_t a0, double a1, double a2) {
    return ((int64_t (*)(int64_t, double, double))fn)(a0, a1, a2);
}

void tur_ffi_call_v_iff(void *fn, int64_t a0, double a1, double a2) {
    ((void (*)(int64_t, double, double))fn)(a0, a1, a2);
}

double tur_ffi_call_f_ifi(void *fn, int64_t a0, double a1, int64_t a2) {
    return ((double (*)(int64_t, double, int64_t))fn)(a0, a1, a2);
}

int64_t tur_ffi_call_i_ifi(void *fn, int64_t a0, double a1, int64_t a2) {
    return ((int64_t (*)(int64_t, double, int64_t))fn)(a0, a1, a2);
}

void tur_ffi_call_v_ifi(void *fn, int64_t a0, double a1, int64_t a2) {
    ((void (*)(int64_t, double, int64_t))fn)(a0, a1, a2);
}

double tur_ffi_call_f_iif(void *fn, int64_t a0, int64_t a1, double a2) {
    return ((double (*)(int64_t, int64_t, double))fn)(a0, a1, a2);
}

int64_t tur_ffi_call_i_iif(void *fn, int64_t a0, int64_t a1, double a2) {
    return ((int64_t (*)(int64_t, int64_t, double))fn)(a0, a1, a2);
}

void tur_ffi_call_v_iif(void *fn, int64_t a0, int64_t a1, double a2) {
    ((void (*)(int64_t, int64_t, double))fn)(a0, a1, a2);
}

double tur_ffi_call_f_iii(void *fn, int64_t a0, int64_t a1, int64_t a2) {
    return ((double (*)(int64_t, int64_t, int64_t))fn)(a0, a1, a2);
}

int64_t tur_ffi_call_i_iii(void *fn, int64_t a0, int64_t a1, int64_t a2) {
    return ((int64_t (*)(int64_t, int64_t, int64_t))fn)(a0, a1, a2);
}

void tur_ffi_call_v_iii(void *fn, int64_t a0, int64_t a1, int64_t a2) {
    ((void (*)(int64_t, int64_t, int64_t))fn)(a0, a1, a2);
}

double tur_ffi_call_f_ffff(void *fn, double a0, double a1, double a2, double a3) {
    return ((double (*)(double, double, double, double))fn)(a0, a1, a2, a3);
}

int64_t tur_ffi_call_i_ffff(void *fn, double a0, double a1, double a2, double a3) {
    return ((int64_t (*)(double, double, double, double))fn)(a0, a1, a2, a3);
}

void tur_ffi_call_v_ffff(void *fn, double a0, double a1, double a2, double a3) {
    ((void (*)(double, double, double, double))fn)(a0, a1, a2, a3);
}

double tur_ffi_call_f_fffi(void *fn, double a0, double a1, double a2, int64_t a3) {
    return ((double (*)(double, double, double, int64_t))fn)(a0, a1, a2, a3);
}

int64_t tur_ffi_call_i_fffi(void *fn, double a0, double a1, double a2, int64_t a3) {
    return ((int64_t (*)(double, double, double, int64_t))fn)(a0, a1, a2, a3);
}

void tur_ffi_call_v_fffi(void *fn, double a0, double a1, double a2, int64_t a3) {
    ((void (*)(double, double, double, int64_t))fn)(a0, a1, a2, a3);
}

double tur_ffi_call_f_ffif(void *fn, double a0, double a1, int64_t a2, double a3) {
    return ((double (*)(double, double, int64_t, double))fn)(a0, a1, a2, a3);
}

int64_t tur_ffi_call_i_ffif(void *fn, double a0, double a1, int64_t a2, double a3) {
    return ((int64_t (*)(double, double, int64_t, double))fn)(a0, a1, a2, a3);
}

void tur_ffi_call_v_ffif(void *fn, double a0, double a1, int64_t a2, double a3) {
    ((void (*)(double, double, int64_t, double))fn)(a0, a1, a2, a3);
}

double tur_ffi_call_f_ffii(void *fn, double a0, double a1, int64_t a2, int64_t a3) {
    return ((double (*)(double, double, int64_t, int64_t))fn)(a0, a1, a2, a3);
}

int64_t tur_ffi_call_i_ffii(void *fn, double a0, double a1, int64_t a2, int64_t a3) {
    return ((int64_t (*)(double, double, int64_t, int64_t))fn)(a0, a1, a2, a3);
}

void tur_ffi_call_v_ffii(void *fn, double a0, double a1, int64_t a2, int64_t a3) {
    ((void (*)(double, double, int64_t, int64_t))fn)(a0, a1, a2, a3);
}

double tur_ffi_call_f_fiff(void *fn, double a0, int64_t a1, double a2, double a3) {
    return ((double (*)(double, int64_t, double, double))fn)(a0, a1, a2, a3);
}

int64_t tur_ffi_call_i_fiff(void *fn, double a0, int64_t a1, double a2, double a3) {
    return ((int64_t (*)(double, int64_t, double, double))fn)(a0, a1, a2, a3);
}

void tur_ffi_call_v_fiff(void *fn, double a0, int64_t a1, double a2, double a3) {
    ((void (*)(double, int64_t, double, double))fn)(a0, a1, a2, a3);
}

double tur_ffi_call_f_fifi(void *fn, double a0, int64_t a1, double a2, int64_t a3) {
    return ((double (*)(double, int64_t, double, int64_t))fn)(a0, a1, a2, a3);
}

int64_t tur_ffi_call_i_fifi(void *fn, double a0, int64_t a1, double a2, int64_t a3) {
    return ((int64_t (*)(double, int64_t, double, int64_t))fn)(a0, a1, a2, a3);
}

void tur_ffi_call_v_fifi(void *fn, double a0, int64_t a1, double a2, int64_t a3) {
    ((void (*)(double, int64_t, double, int64_t))fn)(a0, a1, a2, a3);
}

double tur_ffi_call_f_fiif(void *fn, double a0, int64_t a1, int64_t a2, double a3) {
    return ((double (*)(double, int64_t, int64_t, double))fn)(a0, a1, a2, a3);
}

int64_t tur_ffi_call_i_fiif(void *fn, double a0, int64_t a1, int64_t a2, double a3) {
    return ((int64_t (*)(double, int64_t, int64_t, double))fn)(a0, a1, a2, a3);
}

void tur_ffi_call_v_fiif(void *fn, double a0, int64_t a1, int64_t a2, double a3) {
    ((void (*)(double, int64_t, int64_t, double))fn)(a0, a1, a2, a3);
}

double tur_ffi_call_f_fiii(void *fn, double a0, int64_t a1, int64_t a2, int64_t a3) {
    return ((double (*)(double, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3);
}

int64_t tur_ffi_call_i_fiii(void *fn, double a0, int64_t a1, int64_t a2, int64_t a3) {
    return ((int64_t (*)(double, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3);
}

void tur_ffi_call_v_fiii(void *fn, double a0, int64_t a1, int64_t a2, int64_t a3) {
    ((void (*)(double, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3);
}

double tur_ffi_call_f_ifff(void *fn, int64_t a0, double a1, double a2, double a3) {
    return ((double (*)(int64_t, double, double, double))fn)(a0, a1, a2, a3);
}

int64_t tur_ffi_call_i_ifff(void *fn, int64_t a0, double a1, double a2, double a3) {
    return ((int64_t (*)(int64_t, double, double, double))fn)(a0, a1, a2, a3);
}

void tur_ffi_call_v_ifff(void *fn, int64_t a0, double a1, double a2, double a3) {
    ((void (*)(int64_t, double, double, double))fn)(a0, a1, a2, a3);
}

double tur_ffi_call_f_iffi(void *fn, int64_t a0, double a1, double a2, int64_t a3) {
    return ((double (*)(int64_t, double, double, int64_t))fn)(a0, a1, a2, a3);
}

int64_t tur_ffi_call_i_iffi(void *fn, int64_t a0, double a1, double a2, int64_t a3) {
    return ((int64_t (*)(int64_t, double, double, int64_t))fn)(a0, a1, a2, a3);
}

void tur_ffi_call_v_iffi(void *fn, int64_t a0, double a1, double a2, int64_t a3) {
    ((void (*)(int64_t, double, double, int64_t))fn)(a0, a1, a2, a3);
}

double tur_ffi_call_f_ifif(void *fn, int64_t a0, double a1, int64_t a2, double a3) {
    return ((double (*)(int64_t, double, int64_t, double))fn)(a0, a1, a2, a3);
}

int64_t tur_ffi_call_i_ifif(void *fn, int64_t a0, double a1, int64_t a2, double a3) {
    return ((int64_t (*)(int64_t, double, int64_t, double))fn)(a0, a1, a2, a3);
}

void tur_ffi_call_v_ifif(void *fn, int64_t a0, double a1, int64_t a2, double a3) {
    ((void (*)(int64_t, double, int64_t, double))fn)(a0, a1, a2, a3);
}

double tur_ffi_call_f_ifii(void *fn, int64_t a0, double a1, int64_t a2, int64_t a3) {
    return ((double (*)(int64_t, double, int64_t, int64_t))fn)(a0, a1, a2, a3);
}

int64_t tur_ffi_call_i_ifii(void *fn, int64_t a0, double a1, int64_t a2, int64_t a3) {
    return ((int64_t (*)(int64_t, double, int64_t, int64_t))fn)(a0, a1, a2, a3);
}

void tur_ffi_call_v_ifii(void *fn, int64_t a0, double a1, int64_t a2, int64_t a3) {
    ((void (*)(int64_t, double, int64_t, int64_t))fn)(a0, a1, a2, a3);
}

double tur_ffi_call_f_iiff(void *fn, int64_t a0, int64_t a1, double a2, double a3) {
    return ((double (*)(int64_t, int64_t, double, double))fn)(a0, a1, a2, a3);
}

int64_t tur_ffi_call_i_iiff(void *fn, int64_t a0, int64_t a1, double a2, double a3) {
    return ((int64_t (*)(int64_t, int64_t, double, double))fn)(a0, a1, a2, a3);
}

void tur_ffi_call_v_iiff(void *fn, int64_t a0, int64_t a1, double a2, double a3) {
    ((void (*)(int64_t, int64_t, double, double))fn)(a0, a1, a2, a3);
}

double tur_ffi_call_f_iifi(void *fn, int64_t a0, int64_t a1, double a2, int64_t a3) {
    return ((double (*)(int64_t, int64_t, double, int64_t))fn)(a0, a1, a2, a3);
}

int64_t tur_ffi_call_i_iifi(void *fn, int64_t a0, int64_t a1, double a2, int64_t a3) {
    return ((int64_t (*)(int64_t, int64_t, double, int64_t))fn)(a0, a1, a2, a3);
}

void tur_ffi_call_v_iifi(void *fn, int64_t a0, int64_t a1, double a2, int64_t a3) {
    ((void (*)(int64_t, int64_t, double, int64_t))fn)(a0, a1, a2, a3);
}

double tur_ffi_call_f_iiif(void *fn, int64_t a0, int64_t a1, int64_t a2, double a3) {
    return ((double (*)(int64_t, int64_t, int64_t, double))fn)(a0, a1, a2, a3);
}

int64_t tur_ffi_call_i_iiif(void *fn, int64_t a0, int64_t a1, int64_t a2, double a3) {
    return ((int64_t (*)(int64_t, int64_t, int64_t, double))fn)(a0, a1, a2, a3);
}

void tur_ffi_call_v_iiif(void *fn, int64_t a0, int64_t a1, int64_t a2, double a3) {
    ((void (*)(int64_t, int64_t, int64_t, double))fn)(a0, a1, a2, a3);
}

double tur_ffi_call_f_iiii(void *fn, int64_t a0, int64_t a1, int64_t a2, int64_t a3) {
    return ((double (*)(int64_t, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3);
}

int64_t tur_ffi_call_i_iiii(void *fn, int64_t a0, int64_t a1, int64_t a2, int64_t a3) {
    return ((int64_t (*)(int64_t, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3);
}

void tur_ffi_call_v_iiii(void *fn, int64_t a0, int64_t a1, int64_t a2, int64_t a3) {
    ((void (*)(int64_t, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3);
}

double tur_ffi_call_f_fffff(void *fn, double a0, double a1, double a2, double a3, double a4) {
    return ((double (*)(double, double, double, double, double))fn)(a0, a1, a2, a3, a4);
}

int64_t tur_ffi_call_i_fffff(void *fn, double a0, double a1, double a2, double a3, double a4) {
    return ((int64_t (*)(double, double, double, double, double))fn)(a0, a1, a2, a3, a4);
}

void tur_ffi_call_v_fffff(void *fn, double a0, double a1, double a2, double a3, double a4) {
    ((void (*)(double, double, double, double, double))fn)(a0, a1, a2, a3, a4);
}

double tur_ffi_call_f_ffffi(void *fn, double a0, double a1, double a2, double a3, int64_t a4) {
    return ((double (*)(double, double, double, double, int64_t))fn)(a0, a1, a2, a3, a4);
}

int64_t tur_ffi_call_i_ffffi(void *fn, double a0, double a1, double a2, double a3, int64_t a4) {
    return ((int64_t (*)(double, double, double, double, int64_t))fn)(a0, a1, a2, a3, a4);
}

void tur_ffi_call_v_ffffi(void *fn, double a0, double a1, double a2, double a3, int64_t a4) {
    ((void (*)(double, double, double, double, int64_t))fn)(a0, a1, a2, a3, a4);
}

double tur_ffi_call_f_fffif(void *fn, double a0, double a1, double a2, int64_t a3, double a4) {
    return ((double (*)(double, double, double, int64_t, double))fn)(a0, a1, a2, a3, a4);
}

int64_t tur_ffi_call_i_fffif(void *fn, double a0, double a1, double a2, int64_t a3, double a4) {
    return ((int64_t (*)(double, double, double, int64_t, double))fn)(a0, a1, a2, a3, a4);
}

void tur_ffi_call_v_fffif(void *fn, double a0, double a1, double a2, int64_t a3, double a4) {
    ((void (*)(double, double, double, int64_t, double))fn)(a0, a1, a2, a3, a4);
}

double tur_ffi_call_f_fffii(void *fn, double a0, double a1, double a2, int64_t a3, int64_t a4) {
    return ((double (*)(double, double, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4);
}

int64_t tur_ffi_call_i_fffii(void *fn, double a0, double a1, double a2, int64_t a3, int64_t a4) {
    return ((int64_t (*)(double, double, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4);
}

void tur_ffi_call_v_fffii(void *fn, double a0, double a1, double a2, int64_t a3, int64_t a4) {
    ((void (*)(double, double, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4);
}

double tur_ffi_call_f_ffiff(void *fn, double a0, double a1, int64_t a2, double a3, double a4) {
    return ((double (*)(double, double, int64_t, double, double))fn)(a0, a1, a2, a3, a4);
}

int64_t tur_ffi_call_i_ffiff(void *fn, double a0, double a1, int64_t a2, double a3, double a4) {
    return ((int64_t (*)(double, double, int64_t, double, double))fn)(a0, a1, a2, a3, a4);
}

void tur_ffi_call_v_ffiff(void *fn, double a0, double a1, int64_t a2, double a3, double a4) {
    ((void (*)(double, double, int64_t, double, double))fn)(a0, a1, a2, a3, a4);
}

double tur_ffi_call_f_ffifi(void *fn, double a0, double a1, int64_t a2, double a3, int64_t a4) {
    return ((double (*)(double, double, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4);
}

int64_t tur_ffi_call_i_ffifi(void *fn, double a0, double a1, int64_t a2, double a3, int64_t a4) {
    return ((int64_t (*)(double, double, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4);
}

void tur_ffi_call_v_ffifi(void *fn, double a0, double a1, int64_t a2, double a3, int64_t a4) {
    ((void (*)(double, double, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4);
}

double tur_ffi_call_f_ffiif(void *fn, double a0, double a1, int64_t a2, int64_t a3, double a4) {
    return ((double (*)(double, double, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4);
}

int64_t tur_ffi_call_i_ffiif(void *fn, double a0, double a1, int64_t a2, int64_t a3, double a4) {
    return ((int64_t (*)(double, double, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4);
}

void tur_ffi_call_v_ffiif(void *fn, double a0, double a1, int64_t a2, int64_t a3, double a4) {
    ((void (*)(double, double, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4);
}

double tur_ffi_call_f_ffiii(void *fn, double a0, double a1, int64_t a2, int64_t a3, int64_t a4) {
    return ((double (*)(double, double, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4);
}

int64_t tur_ffi_call_i_ffiii(void *fn, double a0, double a1, int64_t a2, int64_t a3, int64_t a4) {
    return ((int64_t (*)(double, double, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4);
}

void tur_ffi_call_v_ffiii(void *fn, double a0, double a1, int64_t a2, int64_t a3, int64_t a4) {
    ((void (*)(double, double, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4);
}

double tur_ffi_call_f_fifff(void *fn, double a0, int64_t a1, double a2, double a3, double a4) {
    return ((double (*)(double, int64_t, double, double, double))fn)(a0, a1, a2, a3, a4);
}

int64_t tur_ffi_call_i_fifff(void *fn, double a0, int64_t a1, double a2, double a3, double a4) {
    return ((int64_t (*)(double, int64_t, double, double, double))fn)(a0, a1, a2, a3, a4);
}

void tur_ffi_call_v_fifff(void *fn, double a0, int64_t a1, double a2, double a3, double a4) {
    ((void (*)(double, int64_t, double, double, double))fn)(a0, a1, a2, a3, a4);
}

double tur_ffi_call_f_fiffi(void *fn, double a0, int64_t a1, double a2, double a3, int64_t a4) {
    return ((double (*)(double, int64_t, double, double, int64_t))fn)(a0, a1, a2, a3, a4);
}

int64_t tur_ffi_call_i_fiffi(void *fn, double a0, int64_t a1, double a2, double a3, int64_t a4) {
    return ((int64_t (*)(double, int64_t, double, double, int64_t))fn)(a0, a1, a2, a3, a4);
}

void tur_ffi_call_v_fiffi(void *fn, double a0, int64_t a1, double a2, double a3, int64_t a4) {
    ((void (*)(double, int64_t, double, double, int64_t))fn)(a0, a1, a2, a3, a4);
}

double tur_ffi_call_f_fifif(void *fn, double a0, int64_t a1, double a2, int64_t a3, double a4) {
    return ((double (*)(double, int64_t, double, int64_t, double))fn)(a0, a1, a2, a3, a4);
}

int64_t tur_ffi_call_i_fifif(void *fn, double a0, int64_t a1, double a2, int64_t a3, double a4) {
    return ((int64_t (*)(double, int64_t, double, int64_t, double))fn)(a0, a1, a2, a3, a4);
}

void tur_ffi_call_v_fifif(void *fn, double a0, int64_t a1, double a2, int64_t a3, double a4) {
    ((void (*)(double, int64_t, double, int64_t, double))fn)(a0, a1, a2, a3, a4);
}

double tur_ffi_call_f_fifii(void *fn, double a0, int64_t a1, double a2, int64_t a3, int64_t a4) {
    return ((double (*)(double, int64_t, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4);
}

int64_t tur_ffi_call_i_fifii(void *fn, double a0, int64_t a1, double a2, int64_t a3, int64_t a4) {
    return ((int64_t (*)(double, int64_t, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4);
}

void tur_ffi_call_v_fifii(void *fn, double a0, int64_t a1, double a2, int64_t a3, int64_t a4) {
    ((void (*)(double, int64_t, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4);
}

double tur_ffi_call_f_fiiff(void *fn, double a0, int64_t a1, int64_t a2, double a3, double a4) {
    return ((double (*)(double, int64_t, int64_t, double, double))fn)(a0, a1, a2, a3, a4);
}

int64_t tur_ffi_call_i_fiiff(void *fn, double a0, int64_t a1, int64_t a2, double a3, double a4) {
    return ((int64_t (*)(double, int64_t, int64_t, double, double))fn)(a0, a1, a2, a3, a4);
}

void tur_ffi_call_v_fiiff(void *fn, double a0, int64_t a1, int64_t a2, double a3, double a4) {
    ((void (*)(double, int64_t, int64_t, double, double))fn)(a0, a1, a2, a3, a4);
}

double tur_ffi_call_f_fiifi(void *fn, double a0, int64_t a1, int64_t a2, double a3, int64_t a4) {
    return ((double (*)(double, int64_t, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4);
}

int64_t tur_ffi_call_i_fiifi(void *fn, double a0, int64_t a1, int64_t a2, double a3, int64_t a4) {
    return ((int64_t (*)(double, int64_t, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4);
}

void tur_ffi_call_v_fiifi(void *fn, double a0, int64_t a1, int64_t a2, double a3, int64_t a4) {
    ((void (*)(double, int64_t, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4);
}

double tur_ffi_call_f_fiiif(void *fn, double a0, int64_t a1, int64_t a2, int64_t a3, double a4) {
    return ((double (*)(double, int64_t, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4);
}

int64_t tur_ffi_call_i_fiiif(void *fn, double a0, int64_t a1, int64_t a2, int64_t a3, double a4) {
    return ((int64_t (*)(double, int64_t, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4);
}

void tur_ffi_call_v_fiiif(void *fn, double a0, int64_t a1, int64_t a2, int64_t a3, double a4) {
    ((void (*)(double, int64_t, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4);
}

double tur_ffi_call_f_fiiii(void *fn, double a0, int64_t a1, int64_t a2, int64_t a3, int64_t a4) {
    return ((double (*)(double, int64_t, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4);
}

int64_t tur_ffi_call_i_fiiii(void *fn, double a0, int64_t a1, int64_t a2, int64_t a3, int64_t a4) {
    return ((int64_t (*)(double, int64_t, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4);
}

void tur_ffi_call_v_fiiii(void *fn, double a0, int64_t a1, int64_t a2, int64_t a3, int64_t a4) {
    ((void (*)(double, int64_t, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4);
}

double tur_ffi_call_f_iffff(void *fn, int64_t a0, double a1, double a2, double a3, double a4) {
    return ((double (*)(int64_t, double, double, double, double))fn)(a0, a1, a2, a3, a4);
}

int64_t tur_ffi_call_i_iffff(void *fn, int64_t a0, double a1, double a2, double a3, double a4) {
    return ((int64_t (*)(int64_t, double, double, double, double))fn)(a0, a1, a2, a3, a4);
}

void tur_ffi_call_v_iffff(void *fn, int64_t a0, double a1, double a2, double a3, double a4) {
    ((void (*)(int64_t, double, double, double, double))fn)(a0, a1, a2, a3, a4);
}

double tur_ffi_call_f_ifffi(void *fn, int64_t a0, double a1, double a2, double a3, int64_t a4) {
    return ((double (*)(int64_t, double, double, double, int64_t))fn)(a0, a1, a2, a3, a4);
}

int64_t tur_ffi_call_i_ifffi(void *fn, int64_t a0, double a1, double a2, double a3, int64_t a4) {
    return ((int64_t (*)(int64_t, double, double, double, int64_t))fn)(a0, a1, a2, a3, a4);
}

void tur_ffi_call_v_ifffi(void *fn, int64_t a0, double a1, double a2, double a3, int64_t a4) {
    ((void (*)(int64_t, double, double, double, int64_t))fn)(a0, a1, a2, a3, a4);
}

double tur_ffi_call_f_iffif(void *fn, int64_t a0, double a1, double a2, int64_t a3, double a4) {
    return ((double (*)(int64_t, double, double, int64_t, double))fn)(a0, a1, a2, a3, a4);
}

int64_t tur_ffi_call_i_iffif(void *fn, int64_t a0, double a1, double a2, int64_t a3, double a4) {
    return ((int64_t (*)(int64_t, double, double, int64_t, double))fn)(a0, a1, a2, a3, a4);
}

void tur_ffi_call_v_iffif(void *fn, int64_t a0, double a1, double a2, int64_t a3, double a4) {
    ((void (*)(int64_t, double, double, int64_t, double))fn)(a0, a1, a2, a3, a4);
}

double tur_ffi_call_f_iffii(void *fn, int64_t a0, double a1, double a2, int64_t a3, int64_t a4) {
    return ((double (*)(int64_t, double, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4);
}

int64_t tur_ffi_call_i_iffii(void *fn, int64_t a0, double a1, double a2, int64_t a3, int64_t a4) {
    return ((int64_t (*)(int64_t, double, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4);
}

void tur_ffi_call_v_iffii(void *fn, int64_t a0, double a1, double a2, int64_t a3, int64_t a4) {
    ((void (*)(int64_t, double, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4);
}

double tur_ffi_call_f_ififf(void *fn, int64_t a0, double a1, int64_t a2, double a3, double a4) {
    return ((double (*)(int64_t, double, int64_t, double, double))fn)(a0, a1, a2, a3, a4);
}

int64_t tur_ffi_call_i_ififf(void *fn, int64_t a0, double a1, int64_t a2, double a3, double a4) {
    return ((int64_t (*)(int64_t, double, int64_t, double, double))fn)(a0, a1, a2, a3, a4);
}

void tur_ffi_call_v_ififf(void *fn, int64_t a0, double a1, int64_t a2, double a3, double a4) {
    ((void (*)(int64_t, double, int64_t, double, double))fn)(a0, a1, a2, a3, a4);
}

double tur_ffi_call_f_ififi(void *fn, int64_t a0, double a1, int64_t a2, double a3, int64_t a4) {
    return ((double (*)(int64_t, double, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4);
}

int64_t tur_ffi_call_i_ififi(void *fn, int64_t a0, double a1, int64_t a2, double a3, int64_t a4) {
    return ((int64_t (*)(int64_t, double, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4);
}

void tur_ffi_call_v_ififi(void *fn, int64_t a0, double a1, int64_t a2, double a3, int64_t a4) {
    ((void (*)(int64_t, double, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4);
}

double tur_ffi_call_f_ifiif(void *fn, int64_t a0, double a1, int64_t a2, int64_t a3, double a4) {
    return ((double (*)(int64_t, double, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4);
}

int64_t tur_ffi_call_i_ifiif(void *fn, int64_t a0, double a1, int64_t a2, int64_t a3, double a4) {
    return ((int64_t (*)(int64_t, double, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4);
}

void tur_ffi_call_v_ifiif(void *fn, int64_t a0, double a1, int64_t a2, int64_t a3, double a4) {
    ((void (*)(int64_t, double, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4);
}

double tur_ffi_call_f_ifiii(void *fn, int64_t a0, double a1, int64_t a2, int64_t a3, int64_t a4) {
    return ((double (*)(int64_t, double, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4);
}

int64_t tur_ffi_call_i_ifiii(void *fn, int64_t a0, double a1, int64_t a2, int64_t a3, int64_t a4) {
    return ((int64_t (*)(int64_t, double, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4);
}

void tur_ffi_call_v_ifiii(void *fn, int64_t a0, double a1, int64_t a2, int64_t a3, int64_t a4) {
    ((void (*)(int64_t, double, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4);
}

double tur_ffi_call_f_iifff(void *fn, int64_t a0, int64_t a1, double a2, double a3, double a4) {
    return ((double (*)(int64_t, int64_t, double, double, double))fn)(a0, a1, a2, a3, a4);
}

int64_t tur_ffi_call_i_iifff(void *fn, int64_t a0, int64_t a1, double a2, double a3, double a4) {
    return ((int64_t (*)(int64_t, int64_t, double, double, double))fn)(a0, a1, a2, a3, a4);
}

void tur_ffi_call_v_iifff(void *fn, int64_t a0, int64_t a1, double a2, double a3, double a4) {
    ((void (*)(int64_t, int64_t, double, double, double))fn)(a0, a1, a2, a3, a4);
}

double tur_ffi_call_f_iiffi(void *fn, int64_t a0, int64_t a1, double a2, double a3, int64_t a4) {
    return ((double (*)(int64_t, int64_t, double, double, int64_t))fn)(a0, a1, a2, a3, a4);
}

int64_t tur_ffi_call_i_iiffi(void *fn, int64_t a0, int64_t a1, double a2, double a3, int64_t a4) {
    return ((int64_t (*)(int64_t, int64_t, double, double, int64_t))fn)(a0, a1, a2, a3, a4);
}

void tur_ffi_call_v_iiffi(void *fn, int64_t a0, int64_t a1, double a2, double a3, int64_t a4) {
    ((void (*)(int64_t, int64_t, double, double, int64_t))fn)(a0, a1, a2, a3, a4);
}

double tur_ffi_call_f_iifif(void *fn, int64_t a0, int64_t a1, double a2, int64_t a3, double a4) {
    return ((double (*)(int64_t, int64_t, double, int64_t, double))fn)(a0, a1, a2, a3, a4);
}

int64_t tur_ffi_call_i_iifif(void *fn, int64_t a0, int64_t a1, double a2, int64_t a3, double a4) {
    return ((int64_t (*)(int64_t, int64_t, double, int64_t, double))fn)(a0, a1, a2, a3, a4);
}

void tur_ffi_call_v_iifif(void *fn, int64_t a0, int64_t a1, double a2, int64_t a3, double a4) {
    ((void (*)(int64_t, int64_t, double, int64_t, double))fn)(a0, a1, a2, a3, a4);
}

double tur_ffi_call_f_iifii(void *fn, int64_t a0, int64_t a1, double a2, int64_t a3, int64_t a4) {
    return ((double (*)(int64_t, int64_t, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4);
}

int64_t tur_ffi_call_i_iifii(void *fn, int64_t a0, int64_t a1, double a2, int64_t a3, int64_t a4) {
    return ((int64_t (*)(int64_t, int64_t, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4);
}

void tur_ffi_call_v_iifii(void *fn, int64_t a0, int64_t a1, double a2, int64_t a3, int64_t a4) {
    ((void (*)(int64_t, int64_t, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4);
}

double tur_ffi_call_f_iiiff(void *fn, int64_t a0, int64_t a1, int64_t a2, double a3, double a4) {
    return ((double (*)(int64_t, int64_t, int64_t, double, double))fn)(a0, a1, a2, a3, a4);
}

int64_t tur_ffi_call_i_iiiff(void *fn, int64_t a0, int64_t a1, int64_t a2, double a3, double a4) {
    return ((int64_t (*)(int64_t, int64_t, int64_t, double, double))fn)(a0, a1, a2, a3, a4);
}

void tur_ffi_call_v_iiiff(void *fn, int64_t a0, int64_t a1, int64_t a2, double a3, double a4) {
    ((void (*)(int64_t, int64_t, int64_t, double, double))fn)(a0, a1, a2, a3, a4);
}

double tur_ffi_call_f_iiifi(void *fn, int64_t a0, int64_t a1, int64_t a2, double a3, int64_t a4) {
    return ((double (*)(int64_t, int64_t, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4);
}

int64_t tur_ffi_call_i_iiifi(void *fn, int64_t a0, int64_t a1, int64_t a2, double a3, int64_t a4) {
    return ((int64_t (*)(int64_t, int64_t, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4);
}

void tur_ffi_call_v_iiifi(void *fn, int64_t a0, int64_t a1, int64_t a2, double a3, int64_t a4) {
    ((void (*)(int64_t, int64_t, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4);
}

double tur_ffi_call_f_iiiif(void *fn, int64_t a0, int64_t a1, int64_t a2, int64_t a3, double a4) {
    return ((double (*)(int64_t, int64_t, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4);
}

int64_t tur_ffi_call_i_iiiif(void *fn, int64_t a0, int64_t a1, int64_t a2, int64_t a3, double a4) {
    return ((int64_t (*)(int64_t, int64_t, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4);
}

void tur_ffi_call_v_iiiif(void *fn, int64_t a0, int64_t a1, int64_t a2, int64_t a3, double a4) {
    ((void (*)(int64_t, int64_t, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4);
}

double tur_ffi_call_f_iiiii(void *fn, int64_t a0, int64_t a1, int64_t a2, int64_t a3, int64_t a4) {
    return ((double (*)(int64_t, int64_t, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4);
}

int64_t tur_ffi_call_i_iiiii(void *fn, int64_t a0, int64_t a1, int64_t a2, int64_t a3, int64_t a4) {
    return ((int64_t (*)(int64_t, int64_t, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4);
}

void tur_ffi_call_v_iiiii(void *fn, int64_t a0, int64_t a1, int64_t a2, int64_t a3, int64_t a4) {
    ((void (*)(int64_t, int64_t, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4);
}

double tur_ffi_call_f_ffffff(void *fn, double a0, double a1, double a2, double a3, double a4, double a5) {
    return ((double (*)(double, double, double, double, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_ffffff(void *fn, double a0, double a1, double a2, double a3, double a4, double a5) {
    return ((int64_t (*)(double, double, double, double, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_ffffff(void *fn, double a0, double a1, double a2, double a3, double a4, double a5) {
    ((void (*)(double, double, double, double, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_fffffi(void *fn, double a0, double a1, double a2, double a3, double a4, int64_t a5) {
    return ((double (*)(double, double, double, double, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_fffffi(void *fn, double a0, double a1, double a2, double a3, double a4, int64_t a5) {
    return ((int64_t (*)(double, double, double, double, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_fffffi(void *fn, double a0, double a1, double a2, double a3, double a4, int64_t a5) {
    ((void (*)(double, double, double, double, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_ffffif(void *fn, double a0, double a1, double a2, double a3, int64_t a4, double a5) {
    return ((double (*)(double, double, double, double, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_ffffif(void *fn, double a0, double a1, double a2, double a3, int64_t a4, double a5) {
    return ((int64_t (*)(double, double, double, double, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_ffffif(void *fn, double a0, double a1, double a2, double a3, int64_t a4, double a5) {
    ((void (*)(double, double, double, double, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_ffffii(void *fn, double a0, double a1, double a2, double a3, int64_t a4, int64_t a5) {
    return ((double (*)(double, double, double, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_ffffii(void *fn, double a0, double a1, double a2, double a3, int64_t a4, int64_t a5) {
    return ((int64_t (*)(double, double, double, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_ffffii(void *fn, double a0, double a1, double a2, double a3, int64_t a4, int64_t a5) {
    ((void (*)(double, double, double, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_fffiff(void *fn, double a0, double a1, double a2, int64_t a3, double a4, double a5) {
    return ((double (*)(double, double, double, int64_t, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_fffiff(void *fn, double a0, double a1, double a2, int64_t a3, double a4, double a5) {
    return ((int64_t (*)(double, double, double, int64_t, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_fffiff(void *fn, double a0, double a1, double a2, int64_t a3, double a4, double a5) {
    ((void (*)(double, double, double, int64_t, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_fffifi(void *fn, double a0, double a1, double a2, int64_t a3, double a4, int64_t a5) {
    return ((double (*)(double, double, double, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_fffifi(void *fn, double a0, double a1, double a2, int64_t a3, double a4, int64_t a5) {
    return ((int64_t (*)(double, double, double, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_fffifi(void *fn, double a0, double a1, double a2, int64_t a3, double a4, int64_t a5) {
    ((void (*)(double, double, double, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_fffiif(void *fn, double a0, double a1, double a2, int64_t a3, int64_t a4, double a5) {
    return ((double (*)(double, double, double, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_fffiif(void *fn, double a0, double a1, double a2, int64_t a3, int64_t a4, double a5) {
    return ((int64_t (*)(double, double, double, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_fffiif(void *fn, double a0, double a1, double a2, int64_t a3, int64_t a4, double a5) {
    ((void (*)(double, double, double, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_fffiii(void *fn, double a0, double a1, double a2, int64_t a3, int64_t a4, int64_t a5) {
    return ((double (*)(double, double, double, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_fffiii(void *fn, double a0, double a1, double a2, int64_t a3, int64_t a4, int64_t a5) {
    return ((int64_t (*)(double, double, double, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_fffiii(void *fn, double a0, double a1, double a2, int64_t a3, int64_t a4, int64_t a5) {
    ((void (*)(double, double, double, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_ffifff(void *fn, double a0, double a1, int64_t a2, double a3, double a4, double a5) {
    return ((double (*)(double, double, int64_t, double, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_ffifff(void *fn, double a0, double a1, int64_t a2, double a3, double a4, double a5) {
    return ((int64_t (*)(double, double, int64_t, double, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_ffifff(void *fn, double a0, double a1, int64_t a2, double a3, double a4, double a5) {
    ((void (*)(double, double, int64_t, double, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_ffiffi(void *fn, double a0, double a1, int64_t a2, double a3, double a4, int64_t a5) {
    return ((double (*)(double, double, int64_t, double, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_ffiffi(void *fn, double a0, double a1, int64_t a2, double a3, double a4, int64_t a5) {
    return ((int64_t (*)(double, double, int64_t, double, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_ffiffi(void *fn, double a0, double a1, int64_t a2, double a3, double a4, int64_t a5) {
    ((void (*)(double, double, int64_t, double, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_ffifif(void *fn, double a0, double a1, int64_t a2, double a3, int64_t a4, double a5) {
    return ((double (*)(double, double, int64_t, double, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_ffifif(void *fn, double a0, double a1, int64_t a2, double a3, int64_t a4, double a5) {
    return ((int64_t (*)(double, double, int64_t, double, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_ffifif(void *fn, double a0, double a1, int64_t a2, double a3, int64_t a4, double a5) {
    ((void (*)(double, double, int64_t, double, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_ffifii(void *fn, double a0, double a1, int64_t a2, double a3, int64_t a4, int64_t a5) {
    return ((double (*)(double, double, int64_t, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_ffifii(void *fn, double a0, double a1, int64_t a2, double a3, int64_t a4, int64_t a5) {
    return ((int64_t (*)(double, double, int64_t, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_ffifii(void *fn, double a0, double a1, int64_t a2, double a3, int64_t a4, int64_t a5) {
    ((void (*)(double, double, int64_t, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_ffiiff(void *fn, double a0, double a1, int64_t a2, int64_t a3, double a4, double a5) {
    return ((double (*)(double, double, int64_t, int64_t, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_ffiiff(void *fn, double a0, double a1, int64_t a2, int64_t a3, double a4, double a5) {
    return ((int64_t (*)(double, double, int64_t, int64_t, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_ffiiff(void *fn, double a0, double a1, int64_t a2, int64_t a3, double a4, double a5) {
    ((void (*)(double, double, int64_t, int64_t, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_ffiifi(void *fn, double a0, double a1, int64_t a2, int64_t a3, double a4, int64_t a5) {
    return ((double (*)(double, double, int64_t, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_ffiifi(void *fn, double a0, double a1, int64_t a2, int64_t a3, double a4, int64_t a5) {
    return ((int64_t (*)(double, double, int64_t, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_ffiifi(void *fn, double a0, double a1, int64_t a2, int64_t a3, double a4, int64_t a5) {
    ((void (*)(double, double, int64_t, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_ffiiif(void *fn, double a0, double a1, int64_t a2, int64_t a3, int64_t a4, double a5) {
    return ((double (*)(double, double, int64_t, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_ffiiif(void *fn, double a0, double a1, int64_t a2, int64_t a3, int64_t a4, double a5) {
    return ((int64_t (*)(double, double, int64_t, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_ffiiif(void *fn, double a0, double a1, int64_t a2, int64_t a3, int64_t a4, double a5) {
    ((void (*)(double, double, int64_t, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_ffiiii(void *fn, double a0, double a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5) {
    return ((double (*)(double, double, int64_t, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_ffiiii(void *fn, double a0, double a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5) {
    return ((int64_t (*)(double, double, int64_t, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_ffiiii(void *fn, double a0, double a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5) {
    ((void (*)(double, double, int64_t, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_fiffff(void *fn, double a0, int64_t a1, double a2, double a3, double a4, double a5) {
    return ((double (*)(double, int64_t, double, double, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_fiffff(void *fn, double a0, int64_t a1, double a2, double a3, double a4, double a5) {
    return ((int64_t (*)(double, int64_t, double, double, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_fiffff(void *fn, double a0, int64_t a1, double a2, double a3, double a4, double a5) {
    ((void (*)(double, int64_t, double, double, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_fifffi(void *fn, double a0, int64_t a1, double a2, double a3, double a4, int64_t a5) {
    return ((double (*)(double, int64_t, double, double, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_fifffi(void *fn, double a0, int64_t a1, double a2, double a3, double a4, int64_t a5) {
    return ((int64_t (*)(double, int64_t, double, double, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_fifffi(void *fn, double a0, int64_t a1, double a2, double a3, double a4, int64_t a5) {
    ((void (*)(double, int64_t, double, double, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_fiffif(void *fn, double a0, int64_t a1, double a2, double a3, int64_t a4, double a5) {
    return ((double (*)(double, int64_t, double, double, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_fiffif(void *fn, double a0, int64_t a1, double a2, double a3, int64_t a4, double a5) {
    return ((int64_t (*)(double, int64_t, double, double, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_fiffif(void *fn, double a0, int64_t a1, double a2, double a3, int64_t a4, double a5) {
    ((void (*)(double, int64_t, double, double, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_fiffii(void *fn, double a0, int64_t a1, double a2, double a3, int64_t a4, int64_t a5) {
    return ((double (*)(double, int64_t, double, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_fiffii(void *fn, double a0, int64_t a1, double a2, double a3, int64_t a4, int64_t a5) {
    return ((int64_t (*)(double, int64_t, double, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_fiffii(void *fn, double a0, int64_t a1, double a2, double a3, int64_t a4, int64_t a5) {
    ((void (*)(double, int64_t, double, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_fififf(void *fn, double a0, int64_t a1, double a2, int64_t a3, double a4, double a5) {
    return ((double (*)(double, int64_t, double, int64_t, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_fififf(void *fn, double a0, int64_t a1, double a2, int64_t a3, double a4, double a5) {
    return ((int64_t (*)(double, int64_t, double, int64_t, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_fififf(void *fn, double a0, int64_t a1, double a2, int64_t a3, double a4, double a5) {
    ((void (*)(double, int64_t, double, int64_t, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_fififi(void *fn, double a0, int64_t a1, double a2, int64_t a3, double a4, int64_t a5) {
    return ((double (*)(double, int64_t, double, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_fififi(void *fn, double a0, int64_t a1, double a2, int64_t a3, double a4, int64_t a5) {
    return ((int64_t (*)(double, int64_t, double, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_fififi(void *fn, double a0, int64_t a1, double a2, int64_t a3, double a4, int64_t a5) {
    ((void (*)(double, int64_t, double, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_fifiif(void *fn, double a0, int64_t a1, double a2, int64_t a3, int64_t a4, double a5) {
    return ((double (*)(double, int64_t, double, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_fifiif(void *fn, double a0, int64_t a1, double a2, int64_t a3, int64_t a4, double a5) {
    return ((int64_t (*)(double, int64_t, double, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_fifiif(void *fn, double a0, int64_t a1, double a2, int64_t a3, int64_t a4, double a5) {
    ((void (*)(double, int64_t, double, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_fifiii(void *fn, double a0, int64_t a1, double a2, int64_t a3, int64_t a4, int64_t a5) {
    return ((double (*)(double, int64_t, double, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_fifiii(void *fn, double a0, int64_t a1, double a2, int64_t a3, int64_t a4, int64_t a5) {
    return ((int64_t (*)(double, int64_t, double, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_fifiii(void *fn, double a0, int64_t a1, double a2, int64_t a3, int64_t a4, int64_t a5) {
    ((void (*)(double, int64_t, double, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_fiifff(void *fn, double a0, int64_t a1, int64_t a2, double a3, double a4, double a5) {
    return ((double (*)(double, int64_t, int64_t, double, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_fiifff(void *fn, double a0, int64_t a1, int64_t a2, double a3, double a4, double a5) {
    return ((int64_t (*)(double, int64_t, int64_t, double, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_fiifff(void *fn, double a0, int64_t a1, int64_t a2, double a3, double a4, double a5) {
    ((void (*)(double, int64_t, int64_t, double, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_fiiffi(void *fn, double a0, int64_t a1, int64_t a2, double a3, double a4, int64_t a5) {
    return ((double (*)(double, int64_t, int64_t, double, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_fiiffi(void *fn, double a0, int64_t a1, int64_t a2, double a3, double a4, int64_t a5) {
    return ((int64_t (*)(double, int64_t, int64_t, double, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_fiiffi(void *fn, double a0, int64_t a1, int64_t a2, double a3, double a4, int64_t a5) {
    ((void (*)(double, int64_t, int64_t, double, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_fiifif(void *fn, double a0, int64_t a1, int64_t a2, double a3, int64_t a4, double a5) {
    return ((double (*)(double, int64_t, int64_t, double, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_fiifif(void *fn, double a0, int64_t a1, int64_t a2, double a3, int64_t a4, double a5) {
    return ((int64_t (*)(double, int64_t, int64_t, double, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_fiifif(void *fn, double a0, int64_t a1, int64_t a2, double a3, int64_t a4, double a5) {
    ((void (*)(double, int64_t, int64_t, double, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_fiifii(void *fn, double a0, int64_t a1, int64_t a2, double a3, int64_t a4, int64_t a5) {
    return ((double (*)(double, int64_t, int64_t, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_fiifii(void *fn, double a0, int64_t a1, int64_t a2, double a3, int64_t a4, int64_t a5) {
    return ((int64_t (*)(double, int64_t, int64_t, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_fiifii(void *fn, double a0, int64_t a1, int64_t a2, double a3, int64_t a4, int64_t a5) {
    ((void (*)(double, int64_t, int64_t, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_fiiiff(void *fn, double a0, int64_t a1, int64_t a2, int64_t a3, double a4, double a5) {
    return ((double (*)(double, int64_t, int64_t, int64_t, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_fiiiff(void *fn, double a0, int64_t a1, int64_t a2, int64_t a3, double a4, double a5) {
    return ((int64_t (*)(double, int64_t, int64_t, int64_t, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_fiiiff(void *fn, double a0, int64_t a1, int64_t a2, int64_t a3, double a4, double a5) {
    ((void (*)(double, int64_t, int64_t, int64_t, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_fiiifi(void *fn, double a0, int64_t a1, int64_t a2, int64_t a3, double a4, int64_t a5) {
    return ((double (*)(double, int64_t, int64_t, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_fiiifi(void *fn, double a0, int64_t a1, int64_t a2, int64_t a3, double a4, int64_t a5) {
    return ((int64_t (*)(double, int64_t, int64_t, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_fiiifi(void *fn, double a0, int64_t a1, int64_t a2, int64_t a3, double a4, int64_t a5) {
    ((void (*)(double, int64_t, int64_t, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_fiiiif(void *fn, double a0, int64_t a1, int64_t a2, int64_t a3, int64_t a4, double a5) {
    return ((double (*)(double, int64_t, int64_t, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_fiiiif(void *fn, double a0, int64_t a1, int64_t a2, int64_t a3, int64_t a4, double a5) {
    return ((int64_t (*)(double, int64_t, int64_t, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_fiiiif(void *fn, double a0, int64_t a1, int64_t a2, int64_t a3, int64_t a4, double a5) {
    ((void (*)(double, int64_t, int64_t, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_fiiiii(void *fn, double a0, int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5) {
    return ((double (*)(double, int64_t, int64_t, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_fiiiii(void *fn, double a0, int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5) {
    return ((int64_t (*)(double, int64_t, int64_t, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_fiiiii(void *fn, double a0, int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5) {
    ((void (*)(double, int64_t, int64_t, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_ifffff(void *fn, int64_t a0, double a1, double a2, double a3, double a4, double a5) {
    return ((double (*)(int64_t, double, double, double, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_ifffff(void *fn, int64_t a0, double a1, double a2, double a3, double a4, double a5) {
    return ((int64_t (*)(int64_t, double, double, double, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_ifffff(void *fn, int64_t a0, double a1, double a2, double a3, double a4, double a5) {
    ((void (*)(int64_t, double, double, double, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_iffffi(void *fn, int64_t a0, double a1, double a2, double a3, double a4, int64_t a5) {
    return ((double (*)(int64_t, double, double, double, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_iffffi(void *fn, int64_t a0, double a1, double a2, double a3, double a4, int64_t a5) {
    return ((int64_t (*)(int64_t, double, double, double, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_iffffi(void *fn, int64_t a0, double a1, double a2, double a3, double a4, int64_t a5) {
    ((void (*)(int64_t, double, double, double, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_ifffif(void *fn, int64_t a0, double a1, double a2, double a3, int64_t a4, double a5) {
    return ((double (*)(int64_t, double, double, double, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_ifffif(void *fn, int64_t a0, double a1, double a2, double a3, int64_t a4, double a5) {
    return ((int64_t (*)(int64_t, double, double, double, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_ifffif(void *fn, int64_t a0, double a1, double a2, double a3, int64_t a4, double a5) {
    ((void (*)(int64_t, double, double, double, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_ifffii(void *fn, int64_t a0, double a1, double a2, double a3, int64_t a4, int64_t a5) {
    return ((double (*)(int64_t, double, double, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_ifffii(void *fn, int64_t a0, double a1, double a2, double a3, int64_t a4, int64_t a5) {
    return ((int64_t (*)(int64_t, double, double, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_ifffii(void *fn, int64_t a0, double a1, double a2, double a3, int64_t a4, int64_t a5) {
    ((void (*)(int64_t, double, double, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_iffiff(void *fn, int64_t a0, double a1, double a2, int64_t a3, double a4, double a5) {
    return ((double (*)(int64_t, double, double, int64_t, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_iffiff(void *fn, int64_t a0, double a1, double a2, int64_t a3, double a4, double a5) {
    return ((int64_t (*)(int64_t, double, double, int64_t, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_iffiff(void *fn, int64_t a0, double a1, double a2, int64_t a3, double a4, double a5) {
    ((void (*)(int64_t, double, double, int64_t, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_iffifi(void *fn, int64_t a0, double a1, double a2, int64_t a3, double a4, int64_t a5) {
    return ((double (*)(int64_t, double, double, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_iffifi(void *fn, int64_t a0, double a1, double a2, int64_t a3, double a4, int64_t a5) {
    return ((int64_t (*)(int64_t, double, double, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_iffifi(void *fn, int64_t a0, double a1, double a2, int64_t a3, double a4, int64_t a5) {
    ((void (*)(int64_t, double, double, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_iffiif(void *fn, int64_t a0, double a1, double a2, int64_t a3, int64_t a4, double a5) {
    return ((double (*)(int64_t, double, double, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_iffiif(void *fn, int64_t a0, double a1, double a2, int64_t a3, int64_t a4, double a5) {
    return ((int64_t (*)(int64_t, double, double, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_iffiif(void *fn, int64_t a0, double a1, double a2, int64_t a3, int64_t a4, double a5) {
    ((void (*)(int64_t, double, double, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_iffiii(void *fn, int64_t a0, double a1, double a2, int64_t a3, int64_t a4, int64_t a5) {
    return ((double (*)(int64_t, double, double, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_iffiii(void *fn, int64_t a0, double a1, double a2, int64_t a3, int64_t a4, int64_t a5) {
    return ((int64_t (*)(int64_t, double, double, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_iffiii(void *fn, int64_t a0, double a1, double a2, int64_t a3, int64_t a4, int64_t a5) {
    ((void (*)(int64_t, double, double, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_ififff(void *fn, int64_t a0, double a1, int64_t a2, double a3, double a4, double a5) {
    return ((double (*)(int64_t, double, int64_t, double, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_ififff(void *fn, int64_t a0, double a1, int64_t a2, double a3, double a4, double a5) {
    return ((int64_t (*)(int64_t, double, int64_t, double, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_ififff(void *fn, int64_t a0, double a1, int64_t a2, double a3, double a4, double a5) {
    ((void (*)(int64_t, double, int64_t, double, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_ififfi(void *fn, int64_t a0, double a1, int64_t a2, double a3, double a4, int64_t a5) {
    return ((double (*)(int64_t, double, int64_t, double, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_ififfi(void *fn, int64_t a0, double a1, int64_t a2, double a3, double a4, int64_t a5) {
    return ((int64_t (*)(int64_t, double, int64_t, double, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_ififfi(void *fn, int64_t a0, double a1, int64_t a2, double a3, double a4, int64_t a5) {
    ((void (*)(int64_t, double, int64_t, double, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_ififif(void *fn, int64_t a0, double a1, int64_t a2, double a3, int64_t a4, double a5) {
    return ((double (*)(int64_t, double, int64_t, double, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_ififif(void *fn, int64_t a0, double a1, int64_t a2, double a3, int64_t a4, double a5) {
    return ((int64_t (*)(int64_t, double, int64_t, double, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_ififif(void *fn, int64_t a0, double a1, int64_t a2, double a3, int64_t a4, double a5) {
    ((void (*)(int64_t, double, int64_t, double, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_ififii(void *fn, int64_t a0, double a1, int64_t a2, double a3, int64_t a4, int64_t a5) {
    return ((double (*)(int64_t, double, int64_t, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_ififii(void *fn, int64_t a0, double a1, int64_t a2, double a3, int64_t a4, int64_t a5) {
    return ((int64_t (*)(int64_t, double, int64_t, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_ififii(void *fn, int64_t a0, double a1, int64_t a2, double a3, int64_t a4, int64_t a5) {
    ((void (*)(int64_t, double, int64_t, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_ifiiff(void *fn, int64_t a0, double a1, int64_t a2, int64_t a3, double a4, double a5) {
    return ((double (*)(int64_t, double, int64_t, int64_t, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_ifiiff(void *fn, int64_t a0, double a1, int64_t a2, int64_t a3, double a4, double a5) {
    return ((int64_t (*)(int64_t, double, int64_t, int64_t, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_ifiiff(void *fn, int64_t a0, double a1, int64_t a2, int64_t a3, double a4, double a5) {
    ((void (*)(int64_t, double, int64_t, int64_t, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_ifiifi(void *fn, int64_t a0, double a1, int64_t a2, int64_t a3, double a4, int64_t a5) {
    return ((double (*)(int64_t, double, int64_t, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_ifiifi(void *fn, int64_t a0, double a1, int64_t a2, int64_t a3, double a4, int64_t a5) {
    return ((int64_t (*)(int64_t, double, int64_t, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_ifiifi(void *fn, int64_t a0, double a1, int64_t a2, int64_t a3, double a4, int64_t a5) {
    ((void (*)(int64_t, double, int64_t, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_ifiiif(void *fn, int64_t a0, double a1, int64_t a2, int64_t a3, int64_t a4, double a5) {
    return ((double (*)(int64_t, double, int64_t, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_ifiiif(void *fn, int64_t a0, double a1, int64_t a2, int64_t a3, int64_t a4, double a5) {
    return ((int64_t (*)(int64_t, double, int64_t, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_ifiiif(void *fn, int64_t a0, double a1, int64_t a2, int64_t a3, int64_t a4, double a5) {
    ((void (*)(int64_t, double, int64_t, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_ifiiii(void *fn, int64_t a0, double a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5) {
    return ((double (*)(int64_t, double, int64_t, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_ifiiii(void *fn, int64_t a0, double a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5) {
    return ((int64_t (*)(int64_t, double, int64_t, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_ifiiii(void *fn, int64_t a0, double a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5) {
    ((void (*)(int64_t, double, int64_t, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_iiffff(void *fn, int64_t a0, int64_t a1, double a2, double a3, double a4, double a5) {
    return ((double (*)(int64_t, int64_t, double, double, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_iiffff(void *fn, int64_t a0, int64_t a1, double a2, double a3, double a4, double a5) {
    return ((int64_t (*)(int64_t, int64_t, double, double, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_iiffff(void *fn, int64_t a0, int64_t a1, double a2, double a3, double a4, double a5) {
    ((void (*)(int64_t, int64_t, double, double, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_iifffi(void *fn, int64_t a0, int64_t a1, double a2, double a3, double a4, int64_t a5) {
    return ((double (*)(int64_t, int64_t, double, double, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_iifffi(void *fn, int64_t a0, int64_t a1, double a2, double a3, double a4, int64_t a5) {
    return ((int64_t (*)(int64_t, int64_t, double, double, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_iifffi(void *fn, int64_t a0, int64_t a1, double a2, double a3, double a4, int64_t a5) {
    ((void (*)(int64_t, int64_t, double, double, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_iiffif(void *fn, int64_t a0, int64_t a1, double a2, double a3, int64_t a4, double a5) {
    return ((double (*)(int64_t, int64_t, double, double, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_iiffif(void *fn, int64_t a0, int64_t a1, double a2, double a3, int64_t a4, double a5) {
    return ((int64_t (*)(int64_t, int64_t, double, double, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_iiffif(void *fn, int64_t a0, int64_t a1, double a2, double a3, int64_t a4, double a5) {
    ((void (*)(int64_t, int64_t, double, double, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_iiffii(void *fn, int64_t a0, int64_t a1, double a2, double a3, int64_t a4, int64_t a5) {
    return ((double (*)(int64_t, int64_t, double, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_iiffii(void *fn, int64_t a0, int64_t a1, double a2, double a3, int64_t a4, int64_t a5) {
    return ((int64_t (*)(int64_t, int64_t, double, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_iiffii(void *fn, int64_t a0, int64_t a1, double a2, double a3, int64_t a4, int64_t a5) {
    ((void (*)(int64_t, int64_t, double, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_iififf(void *fn, int64_t a0, int64_t a1, double a2, int64_t a3, double a4, double a5) {
    return ((double (*)(int64_t, int64_t, double, int64_t, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_iififf(void *fn, int64_t a0, int64_t a1, double a2, int64_t a3, double a4, double a5) {
    return ((int64_t (*)(int64_t, int64_t, double, int64_t, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_iififf(void *fn, int64_t a0, int64_t a1, double a2, int64_t a3, double a4, double a5) {
    ((void (*)(int64_t, int64_t, double, int64_t, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_iififi(void *fn, int64_t a0, int64_t a1, double a2, int64_t a3, double a4, int64_t a5) {
    return ((double (*)(int64_t, int64_t, double, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_iififi(void *fn, int64_t a0, int64_t a1, double a2, int64_t a3, double a4, int64_t a5) {
    return ((int64_t (*)(int64_t, int64_t, double, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_iififi(void *fn, int64_t a0, int64_t a1, double a2, int64_t a3, double a4, int64_t a5) {
    ((void (*)(int64_t, int64_t, double, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_iifiif(void *fn, int64_t a0, int64_t a1, double a2, int64_t a3, int64_t a4, double a5) {
    return ((double (*)(int64_t, int64_t, double, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_iifiif(void *fn, int64_t a0, int64_t a1, double a2, int64_t a3, int64_t a4, double a5) {
    return ((int64_t (*)(int64_t, int64_t, double, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_iifiif(void *fn, int64_t a0, int64_t a1, double a2, int64_t a3, int64_t a4, double a5) {
    ((void (*)(int64_t, int64_t, double, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_iifiii(void *fn, int64_t a0, int64_t a1, double a2, int64_t a3, int64_t a4, int64_t a5) {
    return ((double (*)(int64_t, int64_t, double, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_iifiii(void *fn, int64_t a0, int64_t a1, double a2, int64_t a3, int64_t a4, int64_t a5) {
    return ((int64_t (*)(int64_t, int64_t, double, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_iifiii(void *fn, int64_t a0, int64_t a1, double a2, int64_t a3, int64_t a4, int64_t a5) {
    ((void (*)(int64_t, int64_t, double, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_iiifff(void *fn, int64_t a0, int64_t a1, int64_t a2, double a3, double a4, double a5) {
    return ((double (*)(int64_t, int64_t, int64_t, double, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_iiifff(void *fn, int64_t a0, int64_t a1, int64_t a2, double a3, double a4, double a5) {
    return ((int64_t (*)(int64_t, int64_t, int64_t, double, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_iiifff(void *fn, int64_t a0, int64_t a1, int64_t a2, double a3, double a4, double a5) {
    ((void (*)(int64_t, int64_t, int64_t, double, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_iiiffi(void *fn, int64_t a0, int64_t a1, int64_t a2, double a3, double a4, int64_t a5) {
    return ((double (*)(int64_t, int64_t, int64_t, double, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_iiiffi(void *fn, int64_t a0, int64_t a1, int64_t a2, double a3, double a4, int64_t a5) {
    return ((int64_t (*)(int64_t, int64_t, int64_t, double, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_iiiffi(void *fn, int64_t a0, int64_t a1, int64_t a2, double a3, double a4, int64_t a5) {
    ((void (*)(int64_t, int64_t, int64_t, double, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_iiifif(void *fn, int64_t a0, int64_t a1, int64_t a2, double a3, int64_t a4, double a5) {
    return ((double (*)(int64_t, int64_t, int64_t, double, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_iiifif(void *fn, int64_t a0, int64_t a1, int64_t a2, double a3, int64_t a4, double a5) {
    return ((int64_t (*)(int64_t, int64_t, int64_t, double, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_iiifif(void *fn, int64_t a0, int64_t a1, int64_t a2, double a3, int64_t a4, double a5) {
    ((void (*)(int64_t, int64_t, int64_t, double, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_iiifii(void *fn, int64_t a0, int64_t a1, int64_t a2, double a3, int64_t a4, int64_t a5) {
    return ((double (*)(int64_t, int64_t, int64_t, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_iiifii(void *fn, int64_t a0, int64_t a1, int64_t a2, double a3, int64_t a4, int64_t a5) {
    return ((int64_t (*)(int64_t, int64_t, int64_t, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_iiifii(void *fn, int64_t a0, int64_t a1, int64_t a2, double a3, int64_t a4, int64_t a5) {
    ((void (*)(int64_t, int64_t, int64_t, double, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_iiiiff(void *fn, int64_t a0, int64_t a1, int64_t a2, int64_t a3, double a4, double a5) {
    return ((double (*)(int64_t, int64_t, int64_t, int64_t, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_iiiiff(void *fn, int64_t a0, int64_t a1, int64_t a2, int64_t a3, double a4, double a5) {
    return ((int64_t (*)(int64_t, int64_t, int64_t, int64_t, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_iiiiff(void *fn, int64_t a0, int64_t a1, int64_t a2, int64_t a3, double a4, double a5) {
    ((void (*)(int64_t, int64_t, int64_t, int64_t, double, double))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_iiiifi(void *fn, int64_t a0, int64_t a1, int64_t a2, int64_t a3, double a4, int64_t a5) {
    return ((double (*)(int64_t, int64_t, int64_t, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_iiiifi(void *fn, int64_t a0, int64_t a1, int64_t a2, int64_t a3, double a4, int64_t a5) {
    return ((int64_t (*)(int64_t, int64_t, int64_t, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_iiiifi(void *fn, int64_t a0, int64_t a1, int64_t a2, int64_t a3, double a4, int64_t a5) {
    ((void (*)(int64_t, int64_t, int64_t, int64_t, double, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_iiiiif(void *fn, int64_t a0, int64_t a1, int64_t a2, int64_t a3, int64_t a4, double a5) {
    return ((double (*)(int64_t, int64_t, int64_t, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_iiiiif(void *fn, int64_t a0, int64_t a1, int64_t a2, int64_t a3, int64_t a4, double a5) {
    return ((int64_t (*)(int64_t, int64_t, int64_t, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_iiiiif(void *fn, int64_t a0, int64_t a1, int64_t a2, int64_t a3, int64_t a4, double a5) {
    ((void (*)(int64_t, int64_t, int64_t, int64_t, int64_t, double))fn)(a0, a1, a2, a3, a4, a5);
}

double tur_ffi_call_f_iiiiii(void *fn, int64_t a0, int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5) {
    return ((double (*)(int64_t, int64_t, int64_t, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

int64_t tur_ffi_call_i_iiiiii(void *fn, int64_t a0, int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5) {
    return ((int64_t (*)(int64_t, int64_t, int64_t, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}

void tur_ffi_call_v_iiiiii(void *fn, int64_t a0, int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5) {
    ((void (*)(int64_t, int64_t, int64_t, int64_t, int64_t, int64_t))fn)(a0, a1, a2, a3, a4, a5);
}
