/* GENERATED by tools/gen_ffi_dispatch.py -- DO NOT EDIT BY HAND.
 *
 * Shape-keyed bridge between the interpreter and ffi_dispatch.h.
 * See ffi_dispatch_thunk.c for the body and src/turi/ffi_thunk.c
 * for the marshaling layer that uses it.
 */
#ifndef TUR_RUNTIME_FFI_DISPATCH_THUNK_H
#define TUR_RUNTIME_FFI_DISPATCH_THUNK_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dispatch by shape. `ret` is 'i'/'f'/'v'; `args` is a string of
 * 'i'/'f' chars of length `n_args`. Pre-marshaled scalars live in
 * `i_vals` (only entries at indices where args[k]=='i' are valid)
 * and `f_vals` (likewise for 'f'). On success returns 0 and writes
 * the result to *out_i (ret='i') or *out_f (ret='f'), or leaves both
 * unchanged for ret='v'. Returns -1 if the combination isn't in the
 * generated table. */
int tur_ffi_thunk_call(char ret,
                       const char *args, uint8_t n_args,
                       void *fn,
                       const int64_t *i_vals,
                       const double  *f_vals,
                       int64_t *out_i,
                       double  *out_f);

#ifdef __cplusplus
}
#endif

#endif /* TUR_RUNTIME_FFI_DISPATCH_THUNK_H */
