/* S2 (jit-engine-plan, findings 19.4): the committed split-runtime artifacts,
 * as linked into a TUR_JIT build via src/runtime/generated/
 * tur_rt_split_embed.c (AUTO-GENERATED by tools/gen-runtime-split.py).
 *
 * `tur_rt_split_hash` is the xxHash64 (tur_hamt_hash_xxh64) of the exact
 * `tur emit-rt-split` text the artifacts were generated from.  cmd_jit
 * re-emits that text in-process and compares: on a match the compiler is
 * the one the artifacts describe, and the emitted program's fixed preamble
 * can be swapped for `tur_rt_split_decls` (declarations only; the runtime
 * lives in the host process as src/runtime/generated/tur_rt_split.c).  On
 * a mismatch -- emitter drift, a knob like --backtrack-depth, a missing
 * runtime archive -- the full preamble is used unchanged: never wrong,
 * just slower. */
#ifndef TUR_RT_SPLIT_EMBED_H
#define TUR_RT_SPLIT_EMBED_H

#include <stdint.h>
#include <stddef.h>

extern const uint64_t tur_rt_split_hash;
extern const char tur_rt_split_decls[];
extern const size_t tur_rt_split_decls_len;

#endif /* TUR_RT_SPLIT_EMBED_H */
