/* generated by tur (phase 2) */
#pragma GCC diagnostic ignored "-Wunused-function"
#pragma GCC diagnostic ignored "-Wunused-variable"
#include <sys/select.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#define _XOPEN_SOURCE 700
#include <ucontext.h>
#undef _XOPEN_SOURCE
#include <setjmp.h>
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <pthread.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
/* Phase X3: tur_set_t — sorted int64_t array */
typedef struct { int64_t *items; uint32_t n; } tur_set_t;
static int __tur_set_cmp(const void *a, const void *b) {
    int64_t x = *(const int64_t *)a, y = *(const int64_t *)b;
    return (x > y) - (x < y);
}
static tur_set_t *tur_set_from_items(uint32_t n, int64_t *src) {
    tur_set_t *s = (tur_set_t *)malloc(sizeof(tur_set_t));
    s->items = n ? (int64_t *)malloc(n * sizeof(int64_t)) : NULL;
    if (n) memcpy(s->items, src, n * sizeof(int64_t));
    if (n > 1) qsort(s->items, n, sizeof(int64_t), __tur_set_cmp);
    uint32_t k = 0;
    for (uint32_t i = 0; i < n; i++)
        if (k == 0 || s->items[k-1] != s->items[i]) s->items[k++] = s->items[i];
    s->n = k;
    return s;
}
static bool tur_set_member(tur_set_t *s, int64_t x) {
    if (!s || !s->n) return false;
    int lo = 0, hi = (int)s->n - 1;
    while (lo <= hi) { int mid = (lo+hi)/2;
        if (s->items[mid] == x) return true;
        if (s->items[mid] < x) lo = mid+1; else hi = mid-1; }
    return false;
}
static int64_t tur_set_count(tur_set_t *s) { return s ? (int64_t)s->n : 0; }
static tur_set_t *tur_set_add(tur_set_t *s, int64_t x) {
    if (tur_set_member(s, x)) {
        tur_set_t *r = (tur_set_t *)malloc(sizeof(tur_set_t));
        r->n = s->n; r->items = s->n ? (int64_t *)malloc(s->n*sizeof(int64_t)) : NULL;
        if (s->n) memcpy(r->items, s->items, s->n*sizeof(int64_t));
        return r;
    }
    tur_set_t *r = (tur_set_t *)malloc(sizeof(tur_set_t));
    r->n = (s ? s->n : 0) + 1;
    r->items = (int64_t *)malloc(r->n * sizeof(int64_t));
    uint32_t pos = 0, base = s ? s->n : 0;
    while (pos < base && s->items[pos] < x) pos++;
    if (s && pos > 0) memcpy(r->items, s->items, pos*sizeof(int64_t));
    r->items[pos] = x;
    if (s && pos < base) memcpy(r->items+pos+1, s->items+pos, (base-pos)*sizeof(int64_t));
    return r;
}
static tur_set_t *tur_set_remove(tur_set_t *s, int64_t x) {
    if (!s || !s->n || !tur_set_member(s, x)) {
        tur_set_t *r = (tur_set_t *)malloc(sizeof(tur_set_t));
        r->n = s ? s->n : 0;
        r->items = r->n ? (int64_t *)malloc(r->n*sizeof(int64_t)) : NULL;
        if (r->n) memcpy(r->items, s->items, r->n*sizeof(int64_t));
        return r;
    }
    tur_set_t *r = (tur_set_t *)malloc(sizeof(tur_set_t));
    r->items = s->n > 1 ? (int64_t *)malloc((s->n-1)*sizeof(int64_t)) : NULL;
    uint32_t k = 0;
    for (uint32_t i = 0; i < s->n; i++) if (s->items[i] != x) r->items[k++] = s->items[i];
    r->n = k; return r;
}
static tur_set_t *tur_set_union(tur_set_t *a, tur_set_t *b) {
    uint32_t na = a?a->n:0, nb = b?b->n:0, cap = na+nb;
    int64_t *tmp = cap ? (int64_t *)malloc(cap*sizeof(int64_t)) : NULL;
    if (a) memcpy(tmp, a->items, na*sizeof(int64_t));
    if (b) memcpy(tmp+na, b->items, nb*sizeof(int64_t));
    return tur_set_from_items(cap, tmp);
}
static tur_set_t *tur_set_intersection(tur_set_t *a, tur_set_t *b) {
    if (!a || !b || !a->n || !b->n) return tur_set_from_items(0, NULL);
    int64_t *tmp = (int64_t *)malloc(a->n*sizeof(int64_t));
    uint32_t k = 0;
    for (uint32_t i = 0; i < a->n; i++) if (tur_set_member(b, a->items[i])) tmp[k++] = a->items[i];
    tur_set_t *r = tur_set_from_items(k, tmp); free(tmp); return r;
}
static tur_set_t *tur_set_difference(tur_set_t *a, tur_set_t *b) {
    if (!a || !a->n) return tur_set_from_items(0, NULL);
    int64_t *tmp = (int64_t *)malloc(a->n*sizeof(int64_t));
    uint32_t k = 0;
    for (uint32_t i = 0; i < a->n; i++) if (!tur_set_member(b, a->items[i])) tmp[k++] = a->items[i];
    tur_set_t *r = tur_set_from_items(k, tmp); free(tmp); return r;
}
static void tur_set_free(tur_set_t *s) { if (s) { free(s->items); free(s); } }
/* Phase HRT1: rank-2 polymorphic function type */
typedef struct { void *env; int64_t (*fn)(void *, int64_t); } tur_poly_fn_t;
/* ET3: algebraic effect handler runtime type */
typedef struct { void *env; int64_t (*fn)(int64_t *, int, int64_t, void *); } tur_handler_t;
/* IT4: tagged union runtime representation */
typedef struct { int64_t tag; int64_t val; } tur_tagged_t;
#define TUR_TAG(t, v)  ((tur_tagged_t){(int64_t)(t), (int64_t)(v)})
#define TUR_UNTAG(x)   ((x).val)
#define TUR_GETTAG(x)  ((x).tag)
static const char *__tur_any_type_name(int64_t tag) {
    switch (tag) {
        case  1: return "nil";
        case  2: return "bool";
        case  3: return "int";
        case  4: return "float";
        case  5: return "cstr";
        case  6: return "ptr";
        default: return "unknown";
    }
}
/* Phase HRT2: existential type (opaque void* box) */
typedef void * tur_exists_t;
/* STM types (Phase 21) */
typedef void *(*stm_fn_t)(void *env);
typedef struct TVar { void *value; uint64_t version; pthread_mutex_t lock; pthread_cond_t cond; } TVar;
typedef struct STM_Transaction STM_Transaction;
struct STM_Transaction {
    TVar *read_set[256];
    uint64_t read_versions[256];
    int read_count;
    TVar *write_set[128];
    void *new_values[128];
    int write_count;
    bool retry_requested;
    bool aborted;
    bool committed;
};
static __thread STM_Transaction *__stm_current_tx = NULL;
STM_Transaction *tur_stm_current_tx(void) { return __stm_current_tx; }
void tur_stm_set_current_tx(STM_Transaction *tx) { __stm_current_tx = tx; }
static int __stm_lock_cmp(const void *a, const void *b) {
    const TVar *tv_a = *(const TVar **)a;
    const TVar *tv_b = *(const TVar **)b;
    if (tv_a < tv_b) return -1;
    if (tv_a > tv_b) return 1;
    return 0;
}
STM_Transaction *tur_stm_new_transaction(void) {
    STM_Transaction *tx = calloc(1, sizeof(STM_Transaction));
    return tx;
}
TVar *tur_tvar_new(void *type, void *initial_value) {
    (void)type; /* unused in emitted code */
    TVar *tv = malloc(sizeof(TVar));
    tv->value = initial_value; tv->version = 1;
    pthread_mutex_init(&tv->lock, NULL);
    pthread_cond_init(&tv->cond, NULL);
    return tv;
}
void *tur_tvar_read(STM_Transaction *tx, TVar *tv) {
    for (int i = 0; i < tx->write_count; i++) {
        if (tx->write_set[i] == tv) return tx->new_values[i];
    }
    if (tx->read_count < 256) {
        for (int i = 0; i < tx->read_count; i++) {
            if (tx->read_set[i] == tv) break;
        }
        tx->read_set[tx->read_count] = tv;
        tx->read_versions[tx->read_count++] = tv->version;
    }
    return tv->value;
}
void tur_tvar_write(STM_Transaction *tx, TVar *tv, void *value) {
    for (int i = 0; i < tx->write_count; i++) {
        if (tx->write_set[i] == tv) { tx->new_values[i] = value; return; }
    }
    /* Remove from read set if present */
    for (int i = 0; i < tx->read_count; i++) {
        if (tx->read_set[i] == tv) {
            for (int j = i; j < tx->read_count - 1; j++) {
                tx->read_set[j] = tx->read_set[j+1];
                tx->read_versions[j] = tx->read_versions[j+1];
            }
            tx->read_count--;
            break;
        }
    }
    if (tx->write_count < 128) {
        tx->write_set[tx->write_count] = tv;
        tx->new_values[tx->write_count++] = value;
    }
}
static bool __tur_stm_validate(STM_Transaction *tx) {
    for (int i = 0; i < tx->read_count; i++) {
        if (tx->read_set[i]->version != tx->read_versions[i]) return false;
    }
    return true;
}
bool tur_stm_commit(STM_Transaction *tx) {
    /* Sort write set by address for lock ordering */
    qsort(tx->write_set, tx->write_count, sizeof(TVar *), __stm_lock_cmp);
    /* Acquire locks in address order */
    for (int i = 0; i < tx->write_count; i++) {
        pthread_mutex_lock(&tx->write_set[i]->lock);
    }
    /* Validate */
    if (!__tur_stm_validate(tx)) {
        for (int i = 0; i < tx->write_count; i++) {
            pthread_mutex_unlock(&tx->write_set[i]->lock);
        }
        return false;
    }
    /* Apply writes */
    for (int i = 0; i < tx->write_count; i++) {
        tx->write_set[i]->value = tx->new_values[i];
        tx->write_set[i]->version++;
    }
    /* Notify waiters */
    for (int i = 0; i < tx->write_count; i++) {
        pthread_cond_broadcast(&tx->write_set[i]->cond);
    }
    tx->committed = true;
    /* Release locks in reverse order */
    for (int i = tx->write_count - 1; i >= 0; i--) {
        pthread_mutex_unlock(&tx->write_set[i]->lock);
    }
    return true;
}
void tur_stm_retry(STM_Transaction *tx) { tx->retry_requested = true; }
void tur_stm_check(bool condition) { if (!condition) tur_stm_retry(tur_stm_current_tx()); }
/* Retry with blocking on condition variables (Phase 21) */
static bool __tur_stm_should_retry(STM_Transaction *tx) {
    if (tx->retry_requested) return true;
    if (tx->aborted) return true;
    return false;
}
void *tur_atomically(void *(*fn)(void *), void *env) {
    STM_Transaction *tx = tur_stm_new_transaction();
    STM_Transaction *prev = tur_stm_current_tx();
    while (1) {
        tx->retry_requested = false;
        tx->aborted = false;
        tx->read_count = 0;
        tx->write_count = 0;
        tur_stm_set_current_tx(tx);
        fn(env);
        if (__tur_stm_should_retry(tx)) {
            tur_stm_set_current_tx(prev);
            /* Block on first read TVar's condition variable if retry requested */
            if (tx->retry_requested && tx->read_count > 0) {
                TVar *tv = tx->read_set[0];
                pthread_mutex_lock(&tv->lock);
                while (tx->retry_requested) {
                    pthread_cond_wait(&tv->cond, &tv->lock);
                }
                pthread_mutex_unlock(&tv->lock);
            }
            continue;
        }
        if (tur_stm_commit(tx)) {
            tur_stm_set_current_tx(prev);
            void *ret = tx->write_count > 0 ? tx->new_values[tx->write_count - 1] : NULL;
            free(tx);
            return ret;
        }
        /* Commit failed - retry */
        tur_stm_set_current_tx(prev);
    }
}
#include <time.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>

#define TUR_TEST_REGISTRY_MAX 1024
#define BACKTRACK_DEPTH_DEFAULT 0
typedef int64_t (*tur_test_callback_t)(void);
static const char *tur_test_registry_names[TUR_TEST_REGISTRY_MAX];
static tur_test_callback_t tur_test_registry_fns[TUR_TEST_REGISTRY_MAX];
static int64_t tur_test_registry_count = 0;

int64_t tur_test_register(const char *name, void *test_fn) {
    if (!test_fn) return 0;
    if (tur_test_registry_count >= TUR_TEST_REGISTRY_MAX) return 0;
    tur_test_registry_names[tur_test_registry_count] = name ? name : "<unnamed>";
    tur_test_registry_fns[tur_test_registry_count] = (tur_test_callback_t)test_fn;
    tur_test_registry_count++;
    return 1;
}

int64_t tur_test_run_all(void) {
    int64_t passed = 0;
    int64_t failed = 0;
    for (int64_t i = 0; i < tur_test_registry_count; i++) {
        tur_test_callback_t fn = tur_test_registry_fns[i];
        int64_t rc = fn ? fn() : 0;
        if (rc == 1) {
            putchar('.');
            putchar('\n');
            passed++;
        } else {
            putchar('F');
            putchar('\n');
            printf("%s\n", tur_test_registry_names[i]);
            failed++;
        }
    }
    printf("summary: %lld passed, %lld failed\n",
           (long long)passed, (long long)failed);
    return failed == 0 ? 0 : 1;
}

/* tur_frame - phase 4 v1 lowering (from runtime.h) */
typedef void (*defer_fn_t)(void *env);
#define TUR_FRAME_MAX_DEFERS 32

typedef struct tur_frame {
    defer_fn_t defers[TUR_FRAME_MAX_DEFERS];
    void *envs[TUR_FRAME_MAX_DEFERS];
    int n;
    struct tur_frame *parent;
    bool may_capture;
} tur_frame;

static inline void tur_frame_init(tur_frame *f, tur_frame *parent) {
    f->n = 0; f->parent = parent; f->may_capture = false;
}
static inline int tur_frame_push_defer(tur_frame *f, defer_fn_t thunk, void *env) {
    if (f->n >= TUR_FRAME_MAX_DEFERS) return -1;
    f->defers[f->n] = thunk;
    f->envs[f->n] = env;
    f->n++;
    return 0;
}
static void tur_frame_fire_lifo(tur_frame *f) {
    for (int i = f->n - 1; i >= 0; i--) f->defers[i](f->envs[i]);
    f->n = 0;
}
static void tur_frame_fire_chain(tur_frame *f) {
    tur_frame *frames[64];
    int n_frames = 0;
    for (tur_frame *cur = f; cur != NULL && n_frames < 64; cur = cur->parent) {
        frames[n_frames++] = cur;
    }
    for (int i = n_frames - 1; i >= 0; i--) {
        tur_frame_fire_lifo(frames[i]);
    }
}

/* Phase R2/R6: tur_panic */
static int tur_panic_in_progress = 0;
static tur_frame *global_panic_frame = NULL;
static int g_panic_trace = 0;  /* Set by compiler when --panic-trace is used */
static void tur_panic_set_frame(tur_frame *f) {
    global_panic_frame = f;
}
static void tur_panic_print_scope_chain(void) {
    if (!g_panic_trace || !global_panic_frame) return;
    fprintf(stderr, "  scope chain:\n");
    tur_frame *frames[64];
    int n_frames = 0;
    for (tur_frame *cur = global_panic_frame; cur != NULL && n_frames < 64; cur = cur->parent) {
        frames[n_frames++] = cur;
    }
    for (int i = 0; i < n_frames; i++) {
        fprintf(stderr, "    at frame %p (parent: %p, n_defers: %d)\n",
                (void*)frames[i], (void*)frames[i]->parent, frames[i]->n);
    }
}

static void tur_panic(const char *msg) {
    if (tur_panic_in_progress) {
        fprintf(stderr, "double panic: aborting\n");
        abort();
    }
    tur_panic_in_progress = 1;
    fprintf(stderr, "panic at %s:%d: %s\n", __FILE__, __LINE__, msg ? msg : "(no message)");
    tur_panic_print_scope_chain();
    if (global_panic_frame) {
        tur_frame_fire_chain(global_panic_frame);
    }
    abort();
}

/* Phase R5: tur_panic_abort - no unwinding, immediate abort */
static void tur_panic_abort(const char *msg) {
    fprintf(stderr, "panic (no unwind): %s\n", msg ? msg : "(no message)");
    abort();
}

static void tur_panic_with(int type_tag, void *payload, const char *file, int line);

/* Phase R2: tur_panic_with types */
typedef struct tur_panic_payload tur_panic_payload;
struct tur_panic_payload {
    int type_tag;
    void *value;
    const char *file;
    int line;
};

static tur_panic_payload *global_panic_payload = NULL;
static jmp_buf global_panic_jmpbuf;
static int global_panic_jmpbuf_valid = 0;

static tur_panic_payload *panic_payload_new(int type_tag, void *payload, const char *file, int line) {
    tur_panic_payload *p = (tur_panic_payload *)malloc(sizeof(tur_panic_payload));
    if (!p) { fprintf(stderr, "panic: oom\n"); abort(); }
    p->type_tag = type_tag; p->value = payload; p->file = file; p->line = line;
    return p;
}

static void panic_payload_free(tur_panic_payload *p) {
    if (p) { free(p->value); free(p); }
}

static int tur_panic_payload_type(tur_panic_payload *p) {
    return p ? p->type_tag : 0;
}

static void *tur_panic_payload_value(tur_panic_payload *p) {
    return p ? p->value : NULL;
}

static const char *tur_panic_payload_file(tur_panic_payload *p) {
    return p ? p->file : NULL;
}

static int tur_panic_payload_line(tur_panic_payload *p) {
    return p ? p->line : 0;
}

static void *tur_panic_payload_downcast(tur_panic_payload *p, int target_type) {
    if (!p || p->type_tag != target_type) return NULL;
    return p->value;
}

/* Phase R2: catch-unwind/catch-panic-of */
typedef enum { TUR_RESULT_OK, TUR_RESULT_ERR } tur_result_tag;
typedef struct tur_result tur_result;
struct tur_result {
    tur_result_tag tag;
    union { int64_t ok_val; void *ok_ptr; tur_panic_payload *err; } u;
};

typedef void (*tur_thunk_fn)(void *env, tur_result *out);

static bool tur_catch_unwind(tur_thunk_fn thunk, void *env, tur_result *out) {
    if (global_panic_jmpbuf_valid) {
        thunk(env, out);
        return false;
    }
    global_panic_jmpbuf_valid = 1;
    if (setjmp(global_panic_jmpbuf) == 0) {
        thunk(env, out);
        global_panic_jmpbuf_valid = 0;
        if (global_panic_payload) {
            panic_payload_free(global_panic_payload);
            global_panic_payload = NULL;
        }
        return false;
    } else {
        global_panic_jmpbuf_valid = 0;
        out->tag = TUR_RESULT_ERR;
        out->u.err = global_panic_payload;
        global_panic_payload = NULL;
        return true;
    }
}

static bool tur_catch_panic_of(int expected_type, tur_thunk_fn thunk, void *env, tur_result *out) {
    if (global_panic_jmpbuf_valid) {
        thunk(env, out);
        return false;
    }
    global_panic_jmpbuf_valid = 1;
    if (setjmp(global_panic_jmpbuf) == 0) {
        thunk(env, out);
        global_panic_jmpbuf_valid = 0;
        if (global_panic_payload) {
            panic_payload_free(global_panic_payload);
            global_panic_payload = NULL;
        }
        return false;
    } else {
        global_panic_jmpbuf_valid = 0;
        if (global_panic_payload && global_panic_payload->type_tag == expected_type) {
            out->tag = TUR_RESULT_ERR;
            out->u.err = global_panic_payload;
            global_panic_payload = NULL;
            return true;
        } else {
        if (global_panic_payload) {
            /* Type mismatch - re-panic */
            tur_panic_with(global_panic_payload->type_tag, global_panic_payload->value,
                           global_panic_payload->file, global_panic_payload->line);
        }
        return false;
        }
    }
}

/* Phase 19: Algebraic effect handler chain */
typedef struct { bool consumed; void *origin_fiber; } TurContK;

/* Phase 19D: Effect-capture continuation context */
typedef struct TurEffectCaptureCtx TurEffectCaptureCtx;
struct TurEffectCaptureCtx {
    bool has_pending_effect;
    const char *eff_name;
    int64_t eff_args[8];  /* v1: max 8 args */
    int eff_n_args;
    int64_t (*dispatch)(void *ctx, int64_t k, int64_t v);
    void *body_env;  /* heap-allocated env for body captures */
};

typedef struct EffectHandlerCase EffectHandlerCase;
struct EffectHandlerCase {
    const char *effect_name;
    int64_t (*handler_fn)(int64_t *args, int n_args, int64_t k, void *env);
    void *env;
};

typedef struct EffectHandlerFrame EffectHandlerFrame;
struct EffectHandlerFrame {
    struct EffectHandlerFrame *parent;
    int n_cases;
    EffectHandlerCase cases[8];
};

/* Phase T21: FiberBlock */
#ifdef __clang__
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
#endif
typedef struct FiberBlock FiberBlock;
struct FiberBlock {
    ucontext_t ctx;
    ucontext_t caller_ctx;
    char *stack;
    size_t stack_size;
    int done;
    int parked; /* Phase T21: scheduler park/unpark */
    int64_t result;
    int64_t arg;
    void *effect_handler_chain; /* Phase P19-8: per-fiber effect handler chain */
    bool migration_safe; /* SCH-004: true if effect handlers are safe for cross-thread migration */
    void (*entry_fn)(void);
    void *fiber_local; /* Phase T21: fiber-local storage */
    void *task_group; /* Parent TaskGroup for cancellation */
    bool cancelled; /* Set when parent TaskGroup is cancelled */
    jmp_buf panic_jmpbuf; /* Per-fiber panic recovery buffer */
    bool panic_jmpbuf_valid; /* Whether this fiber's panic handler is active */
    void *eff_ctx;  /* Phase 19D: NULL for regular fibers, TurEffectCaptureCtx* for effect-capture fibers */
};

static __thread FiberBlock *tur_current_fiber = NULL;
static void tur_panic_with(int type_tag, void *payload, const char *file, int line) {
    if (tur_panic_in_progress) {
        fprintf(stderr, "double panic: aborting\n");
        free(payload);
        abort();
    }
    tur_panic_in_progress = 1;
    if (global_panic_jmpbuf_valid) {
        global_panic_payload = panic_payload_new(type_tag, payload, file, line);
        longjmp(global_panic_jmpbuf, 1);
    } else if (tur_current_fiber && tur_current_fiber->panic_jmpbuf_valid) {
        /* Use per-fiber panic buffer - set up global payload for cleanup */
        global_panic_payload = panic_payload_new(type_tag, payload, file, line);
        longjmp(tur_current_fiber->panic_jmpbuf, 1);
    }
    fprintf(stderr, "panic at %s:%d\n", file ? file : "(unknown)", line);
    free(payload);
    abort();
}

static __thread bool tur_fiber_cancelled_flag = false;

static void tur_task_group_notify_done(void *task_group);
static void tur_fiber_set_cancelled(bool c);

static void tur_fiber_shim(uint32_t hi, uint32_t lo) {
    FiberBlock *f = (FiberBlock *)(((uintptr_t)hi << 32) | (uintptr_t)(uint32_t)lo);
    void *task_group = f->task_group;
    if (task_group) {
        /* Save previous global panic handler state */
        int prev_global_valid = global_panic_jmpbuf_valid;
        jmp_buf prev_global_buf;
        if (prev_global_valid) memcpy(&prev_global_buf, &global_panic_jmpbuf, sizeof(jmp_buf));
        /* Clear global to prevent interference */
        global_panic_jmpbuf_valid = 0;
        /* Set up per-fiber panic handler */
        if (setjmp(f->panic_jmpbuf) == 0) {
            f->panic_jmpbuf_valid = 1;
            tur_current_fiber = f;
            f->entry_fn();
            tur_current_fiber = NULL;
            f->panic_jmpbuf_valid = 0;
            if (global_panic_payload) {
                panic_payload_free(global_panic_payload);
                global_panic_payload = NULL;
            }
            /* Restore previous global panic handler */
            global_panic_jmpbuf_valid = prev_global_valid;
            if (prev_global_valid) memcpy(&global_panic_jmpbuf, &prev_global_buf, sizeof(jmp_buf));
        } else {
            /* Panic caught - auto-cancel task group (TG-004-3) */
            f->panic_jmpbuf_valid = 0;
            tur_current_fiber = NULL;
            if (global_panic_payload) {
                typedef struct TaskGroupBlock { bool cancelled; bool done; int64_t cancel_reason; pthread_mutex_t lock; pthread_cond_t done_cond; } TaskGroupBlock;
                TaskGroupBlock *g = (TaskGroupBlock *)task_group;
                pthread_mutex_lock(&g->lock);
                g->cancelled = true;
                g->done = true;
                g->cancel_reason = 1; /* panic reason (TG-004-2) */
                pthread_cond_broadcast(&g->done_cond);
                pthread_mutex_unlock(&g->lock);
                tur_fiber_set_cancelled(true);
                panic_payload_free(global_panic_payload);
                global_panic_payload = NULL;
            }
            /* Restore previous global panic handler */
            global_panic_jmpbuf_valid = prev_global_valid;
            if (prev_global_valid) memcpy(&global_panic_jmpbuf, &prev_global_buf, sizeof(jmp_buf));
        }
    } else {
        /* No task group, just run the function normally */
        f->entry_fn();
    }
    f->done = 1;
    if (task_group) tur_task_group_notify_done(task_group);
    swapcontext(&f->ctx, &f->caller_ctx);
    abort();
}

static __thread EffectHandlerFrame *global_effect_handler_chain = NULL;

static FiberBlock *tur_fiber_block_new(void (*fn)(void), size_t stack_size) {
    if (!stack_size) stack_size = 1024 * 1024;
    FiberBlock *f = (FiberBlock *)calloc(1, sizeof(FiberBlock));
    if (!f) { fprintf(stderr, "fiber: oom\n"); abort(); }
    f->stack = (char *)malloc(stack_size);
    if (!f->stack) { free(f); abort(); }
    f->stack_size = stack_size; f->entry_fn = fn; f->done = 0;
    f->migration_safe = true;
    f->effect_handler_chain = (void *)global_effect_handler_chain;
    getcontext(&f->ctx);
    f->ctx.uc_stack.ss_sp = f->stack;
    f->ctx.uc_stack.ss_size = stack_size;
    f->ctx.uc_link = NULL;
    uintptr_t _fp = (uintptr_t)f;
    uint32_t _hi = (uint32_t)(_fp >> 32);
    uint32_t _lo = (uint32_t)(_fp & 0xFFFFFFFFU);
    makecontext(&f->ctx, (void(*)(void))tur_fiber_shim, 2, _hi, _lo);
    return f;
}

static int64_t tur_fiber_block_resume(FiberBlock *f, int64_t arg) {
    if (!f || f->done) return f ? f->result : 0;
    if (f->cancelled) { f->done = 1; return 0; }
    if (f->task_group) {
        typedef struct TaskGroupBlock { bool cancelled; } TaskGroupBlock;
        if (((TaskGroupBlock *)f->task_group)->cancelled) { f->cancelled = 1; f->done = 1; return 0; }
    }
    FiberBlock *_prev = tur_current_fiber;
    tur_current_fiber = f;
    f->arg = arg;
    swapcontext(&f->caller_ctx, &f->ctx);
    tur_current_fiber = _prev;
    return f->result;
}

static void tur_fiber_block_yield(int64_t value) {
    FiberBlock *f = tur_current_fiber;
    if (!f) { fprintf(stderr, "fiber-yield: not in fiber\n"); abort(); }
    f->result = value;
    swapcontext(&f->ctx, &f->caller_ctx);
}

/* Phase 19D: Effect-capture continuation helpers */
static int64_t tur_effect_cont_resume(int64_t k_as_int64, int64_t v) {
    FiberBlock *fiber = (FiberBlock *)(intptr_t)k_as_int64;
    TurEffectCaptureCtx *ctx = (TurEffectCaptureCtx *)fiber->eff_ctx;
    if (!ctx) { fprintf(stderr, "continuation error: not a capturable continuation\n"); abort(); }
    return ctx->dispatch(ctx, k_as_int64, v);
}

static bool tur_effect_cont_valid(int64_t k_as_int64) {
    FiberBlock *fiber = (FiberBlock *)(intptr_t)k_as_int64;
    return !fiber->done;
}

typedef struct FiberLocalEntry FiberLocalEntry;
struct FiberLocalEntry {
    int64_t key;
    int64_t value;
    FiberLocalEntry *next;
};

static void tur_fiber_local_free(FiberBlock *f) {
    FiberLocalEntry *e = (FiberLocalEntry *)f->fiber_local;
    while (e) { FiberLocalEntry *n = e->next; free(e); e = n; }
}

static int64_t tur_fiber_local_get(FiberBlock *f, int64_t key) {
    FiberLocalEntry *e = (FiberLocalEntry *)f->fiber_local;
    while (e) { if (e->key == key) return e->value; e = e->next; }
    return 0;
}

static void tur_fiber_local_set(FiberBlock *f, int64_t key, int64_t value) {
    FiberLocalEntry *e = (FiberLocalEntry *)f->fiber_local;
    while (e) { if (e->key == key) { e->value = value; return; } e = e->next; }
    FiberLocalEntry *n = (FiberLocalEntry *)malloc(sizeof(FiberLocalEntry));
    if (!n) { fprintf(stderr, "fiber-local: oom\n"); abort(); }
    n->key = key; n->value = value;
    n->next = (FiberLocalEntry *)f->fiber_local;
    f->fiber_local = (void *)n;
}

static void tur_fiber_block_free(FiberBlock *f) {
    if (!f) return;
    tur_fiber_local_free(f);
    free(f->stack); free(f);
}

static bool tur_fiber_cancelled(void) {
    return tur_fiber_cancelled_flag;
}

static void tur_fiber_set_cancelled(bool c) {
    tur_fiber_cancelled_flag = c;
}

static void tur_task_group_notify_done(void *task_group) {
    if (!task_group) return;
    typedef struct TaskGroupBlock {
        pthread_mutex_t lock;
        pthread_cond_t done_cond;
        int64_t task_count;
        int64_t completed_count;
        bool cancelled;
        bool done;
        pthread_t owner_thread;
    } TaskGroupBlock;
    TaskGroupBlock *g = (TaskGroupBlock *)task_group;
    pthread_mutex_lock(&g->lock);
    g->completed_count++;
    if (g->completed_count >= g->task_count) {
        g->done = true;
        pthread_cond_broadcast(&g->done_cond);
    }
    pthread_mutex_unlock(&g->lock);
}

static int64_t tur_monotonic_ns(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (int64_t)ts.tv_sec * 1000000000LL + (int64_t)ts.tv_nsec;
}

typedef struct TurTimerEntry {
    int64_t deadline_ns;
    void (*callback)(void *);
    void *arg;
    int64_t id;
    bool cancelled;
} TurTimerEntry;

typedef struct TurTimerWheel {
    TurTimerEntry **heap;
    int64_t len;
    int64_t cap;
    int64_t next_id;
} TurTimerWheel;

static TurTimerWheel *tur_global_timers = NULL;

#define TUR_IO_READ  1
#define TUR_IO_WRITE 2

typedef struct TurIOWaiter {
    int fd;
    int events;
    FiberBlock *fiber;
    struct TurIOWaiter *next;
} TurIOWaiter;

static TurIOWaiter *tur_io_waiters = NULL;

static void tur_timer_wheel_tick(TurTimerWheel *w);
static int64_t tur_timer_wheel_next_deadline_ns(TurTimerWheel *w);
static int64_t tur_timer_wheel_insert(TurTimerWheel *w, int64_t deadline_ns, void (*cb)(void *), void *arg);
static void tur_timer_wheel_cancel(TurTimerWheel *w, int64_t id);
static TurTimerWheel *tur_timer_wheel_new(void);
static void tur_io_register(int fd, int events, FiberBlock *fiber);
static void tur_io_unregister(int fd);
static void tur_io_poll(int64_t timeout_us);
static void tur_scheduler_timeout(int64_t ms, void (*callback)(void *arg), void *arg);
static void tur_tick_timers(void);
static void tur_poll_io(int64_t timeout_us);
static bool tur_has_pending_timers(void);
static bool tur_has_pending_io(void);
static int64_t tur_next_timer_wait_us(void);

typedef struct TurScheduler TurScheduler;
struct TurScheduler {
    FiberBlock **run_queue;
    int64_t run_queue_cap;
    int64_t run_queue_len;
    int64_t run_queue_head;
    int64_t run_queue_tail;
    FiberBlock *current_fiber;
    bool running;
};

static TurScheduler *tur_scheduler = NULL;

static TurScheduler *tur_scheduler_new(void) {
    TurScheduler *s = (TurScheduler *)calloc(1, sizeof(TurScheduler));
    if (!s) { fprintf(stderr, "scheduler: oom\n"); abort(); }
    s->run_queue_cap = 64;
    s->run_queue = (FiberBlock **)malloc(sizeof(FiberBlock *) * (size_t)s->run_queue_cap);
    if (!s->run_queue) { free(s); fprintf(stderr, "scheduler: queue oom\n"); abort(); }
    s->run_queue_len = 0;
    s->run_queue_head = 0;
    s->run_queue_tail = 0;
    s->current_fiber = NULL;
    s->running = false;
    return s;
}

static TurScheduler *tur_scheduler_current(void) {
    return tur_scheduler;
}

static void tur_scheduler_enqueue(TurScheduler *s, FiberBlock *f) {
    if (s->run_queue_len >= s->run_queue_cap) {
        int64_t new_cap = s->run_queue_cap * 2;
        FiberBlock **new_q = (FiberBlock **)malloc(sizeof(FiberBlock *) * (size_t)new_cap);
        if (!new_q) { fprintf(stderr, "scheduler: grow oom\n"); abort(); }
        for (int64_t i = 0; i < s->run_queue_len; i++)
            new_q[i] = s->run_queue[(s->run_queue_head + i) % s->run_queue_cap];
        free(s->run_queue);
        s->run_queue = new_q;
        s->run_queue_cap = new_cap;
        s->run_queue_head = 0;
        s->run_queue_tail = s->run_queue_len;
    }
    s->run_queue[s->run_queue_tail] = f;
    s->run_queue_tail = (s->run_queue_tail + 1) % s->run_queue_cap;
    s->run_queue_len++;
}

static FiberBlock *tur_scheduler_dequeue(TurScheduler *s) {
    if (s->run_queue_len == 0) return NULL;
    FiberBlock *f = s->run_queue[s->run_queue_head];
    s->run_queue_head = (s->run_queue_head + 1) % s->run_queue_cap;
    s->run_queue_len--;
    return f;
}

static void tur_scheduler_spawn(TurScheduler *s, FiberBlock *f) {
    tur_scheduler_enqueue(s, f);
}

static void tur_scheduler_run(TurScheduler *s) {
    s->running = true;
    while (s->running) {
        /* Phase T24: tick timers and poll IO before dequeuing */
        tur_tick_timers();
        tur_poll_io(0);
        FiberBlock *f = tur_scheduler_dequeue(s);
        if (!f) {
            if (!tur_has_pending_timers() && !tur_has_pending_io()) break;
            int64_t sleep_us = tur_next_timer_wait_us();
            if (sleep_us < 0) sleep_us = 1000;
            if (tur_has_pending_io()) tur_poll_io(sleep_us);
            else { struct timespec ts = {0, sleep_us * 1000}; nanosleep(&ts, NULL); }
            continue;
        }
        s->current_fiber = f;
        tur_fiber_block_resume(f, 0);
        s->current_fiber = NULL;
        if (!f->done && !f->parked) tur_scheduler_enqueue(s, f);
    }
    s->running = false;
}

static void tur_scheduler_run_to_completion(TurScheduler *s) {
    s->running = true;
    while (s->running) {
        tur_tick_timers();
        tur_poll_io(0);
        FiberBlock *f = tur_scheduler_dequeue(s);
        if (f) {
            s->current_fiber = f;
            tur_fiber_block_resume(f, 0);
            s->current_fiber = NULL;
            if (!f->done && !f->parked) tur_scheduler_enqueue(s, f);
        } else {
            if (!tur_has_pending_timers() && !tur_has_pending_io()) break;
            int64_t sleep_us = tur_next_timer_wait_us();
            if (sleep_us < 0) sleep_us = 1000;
            if (tur_has_pending_io()) tur_poll_io(sleep_us);
            else { struct timespec ts = {0, sleep_us * 1000}; nanosleep(&ts, NULL); }
        }
    }
    s->running = false;
}

static void tur_scheduler_yield(void) {
    tur_fiber_block_yield(0);
}

static void tur_scheduler_park(void) {
    if (tur_current_fiber) tur_current_fiber->parked = 1;
    tur_fiber_block_yield(0);
}

static void tur_scheduler_unpark(FiberBlock *f) {
    if (!f) return;
    f->parked = 0;
    if (tur_scheduler) tur_scheduler_enqueue(tur_scheduler, f);
}

static TurTimerWheel *tur_timer_wheel_new(void) {
    TurTimerWheel *w = (TurTimerWheel *)calloc(1, sizeof(TurTimerWheel));
    if (!w) { fprintf(stderr, "timer wheel: oom\n"); abort(); }
    w->cap = 64;
    w->heap = (TurTimerEntry **)malloc(sizeof(TurTimerEntry *) * (size_t)w->cap);
    if (!w->heap) { free(w); fprintf(stderr, "timer wheel: heap oom\n"); abort(); }
    w->len = 0;
    w->next_id = 1;
    return w;
}

static void tur_timer_heap_sift_up(TurTimerWheel *w, int64_t idx) {
    while (idx > 0) {
        int64_t parent = (idx - 1) / 2;
        if (w->heap[parent]->deadline_ns <= w->heap[idx]->deadline_ns) break;
        TurTimerEntry *tmp = w->heap[parent];
        w->heap[parent] = w->heap[idx];
        w->heap[idx] = tmp;
        idx = parent;
    }
}

static void tur_timer_heap_sift_down(TurTimerWheel *w, int64_t idx) {
    while (1) {
        int64_t smallest = idx;
        int64_t left = 2 * idx + 1;
        int64_t right = 2 * idx + 2;
        if (left < w->len && w->heap[left]->deadline_ns < w->heap[smallest]->deadline_ns)
            smallest = left;
        if (right < w->len && w->heap[right]->deadline_ns < w->heap[smallest]->deadline_ns)
            smallest = right;
        if (smallest == idx) break;
        TurTimerEntry *tmp = w->heap[smallest];
        w->heap[smallest] = w->heap[idx];
        w->heap[idx] = tmp;
        idx = smallest;
    }
}

static int64_t tur_timer_wheel_insert(TurTimerWheel *w, int64_t deadline_ns,
                                       void (*cb)(void *), void *arg) {
    if (w->len >= w->cap) {
        int64_t new_cap = w->cap * 2;
        TurTimerEntry **nh = (TurTimerEntry **)malloc(sizeof(TurTimerEntry *) * (size_t)new_cap);
        if (!nh) { fprintf(stderr, "timer wheel: grow oom\n"); abort(); }
        for (int64_t i = 0; i < w->len; i++) nh[i] = w->heap[i];
        free(w->heap);
        w->heap = nh;
        w->cap = new_cap;
    }
    TurTimerEntry *e = (TurTimerEntry *)malloc(sizeof(TurTimerEntry));
    if (!e) { fprintf(stderr, "timer entry: oom\n"); abort(); }
    e->deadline_ns = deadline_ns;
    e->callback = cb;
    e->arg = arg;
    e->id = w->next_id++;
    e->cancelled = false;
    w->heap[w->len] = e;
    tur_timer_heap_sift_up(w, w->len);
    w->len++;
    return e->id;
}

static void tur_timer_wheel_cancel(TurTimerWheel *w, int64_t id) {
    for (int64_t i = 0; i < w->len; i++) {
        if (w->heap[i]->id == id) { w->heap[i]->cancelled = true; return; }
    }
}

static void tur_timer_wheel_tick(TurTimerWheel *w) {
    int64_t now = tur_monotonic_ns();
    while (w->len > 0 && w->heap[0]->deadline_ns <= now) {
        TurTimerEntry *e = w->heap[0];
        w->len--;
        if (w->len > 0) {
            w->heap[0] = w->heap[w->len];
            tur_timer_heap_sift_down(w, 0);
        }
        if (!e->cancelled) e->callback(e->arg);
        free(e);
    }
}

static int64_t tur_timer_wheel_next_deadline_ns(TurTimerWheel *w) {
    while (w->len > 0 && w->heap[0]->cancelled) {
        TurTimerEntry *e = w->heap[0];
        w->len--;
        if (w->len > 0) {
            w->heap[0] = w->heap[w->len];
            tur_timer_heap_sift_down(w, 0);
        }
        free(e);
    }
    if (w->len == 0) return -1;
    return w->heap[0]->deadline_ns;
}

static void tur_scheduler_timeout(int64_t ms, void (*callback)(void *arg), void *arg) {
    if (!tur_global_timers) tur_global_timers = tur_timer_wheel_new();
    int64_t deadline = tur_monotonic_ns() + ms * 1000000LL;
    tur_timer_wheel_insert(tur_global_timers, deadline, callback, arg);
}

static void tur_io_register(int fd, int events, FiberBlock *fiber) {
    TurIOWaiter *w = (TurIOWaiter *)malloc(sizeof(TurIOWaiter));
    if (!w) { fprintf(stderr, "io waiter: oom\n"); abort(); }
    w->fd = fd;
    w->events = events;
    w->fiber = fiber;
    w->next = tur_io_waiters;
    tur_io_waiters = w;
}

static void tur_io_unregister(int fd) {
    TurIOWaiter **pp = &tur_io_waiters;
    while (*pp) {
        if ((*pp)->fd == fd) {
            TurIOWaiter *tmp = *pp;
            *pp = tmp->next;
            free(tmp);
            return;
        }
        pp = &(*pp)->next;
    }
}

static void tur_io_poll(int64_t timeout_us) {
    if (!tur_io_waiters) return;
    fd_set rfds, wfds;
    FD_ZERO(&rfds);
    FD_ZERO(&wfds);
    int maxfd = -1;
    for (TurIOWaiter *w = tur_io_waiters; w; w = w->next) {
        if (w->events & TUR_IO_READ)  FD_SET(w->fd, &rfds);
        if (w->events & TUR_IO_WRITE) FD_SET(w->fd, &wfds);
        if (w->fd > maxfd) maxfd = w->fd;
    }
    struct timeval tv;
    tv.tv_sec = (long)(timeout_us / 1000000);
    tv.tv_usec = (long)(timeout_us % 1000000);
    int ret = select(maxfd + 1, &rfds, &wfds, NULL, &tv);
    if (ret <= 0) return;
    TurIOWaiter **pp = &tur_io_waiters;
    while (*pp) {
        TurIOWaiter *w = *pp;
        bool ready = false;
        if ((w->events & TUR_IO_READ)  && FD_ISSET(w->fd, &rfds))  ready = true;
        if ((w->events & TUR_IO_WRITE) && FD_ISSET(w->fd, &wfds)) ready = true;
        if (ready) {
            FiberBlock *f = w->fiber;
            *pp = w->next;
            free(w);
            tur_scheduler_unpark(f);
        } else {
            pp = &w->next;
        }
    }
}

static void tur_tick_timers(void) {
    if (tur_global_timers) tur_timer_wheel_tick(tur_global_timers);
}

static void tur_poll_io(int64_t timeout_us) {
    if (tur_io_waiters) tur_io_poll(timeout_us);
}

static bool tur_has_pending_timers(void) {
    return tur_global_timers && tur_global_timers->len > 0;
}

static bool tur_has_pending_io(void) {
    return tur_io_waiters != NULL;
}

static int64_t tur_next_timer_wait_us(void) {
    if (!tur_global_timers || tur_global_timers->len == 0) return -1;
    int64_t next = tur_timer_wheel_next_deadline_ns(tur_global_timers);
    if (next < 0) return -1;
    int64_t diff = (next - tur_monotonic_ns()) / 1000;
    return diff > 0 ? diff : 0;
}

#ifdef __clang__
#pragma clang diagnostic pop
#endif

static void tur_scheduler_run_one(TurScheduler *s) {
    FiberBlock *f = tur_scheduler_dequeue(s);
    if (!f) { return; }
    s->current_fiber = f;
    tur_fiber_block_resume(f, 0);
    s->current_fiber = NULL;
    if (!f->done && !f->parked) tur_scheduler_enqueue(s, f);
}

/* Phase T23: Multi-threaded scheduler */
typedef struct TurSchedulerMT {
    pthread_t       *threads;
    size_t           n_threads;
    pthread_mutex_t  lock;
    pthread_cond_t   cond;
    FiberBlock     **queue;
    size_t           qhead;
    size_t           qtail;
    size_t           qcap;
    bool             running;
    int              active;
} TurSchedulerMT;

static __thread TurSchedulerMT *tur_current_scheduler_mt = NULL;

static void tur_scheduler_mt_enqueue_locked(TurSchedulerMT *s, FiberBlock *f) {
    if (((s->qtail + 1) % s->qcap) == s->qhead) {
        size_t ncap = s->qcap * 2;
        FiberBlock **nq = (FiberBlock **)calloc(ncap, sizeof(FiberBlock *));
        size_t k = 0;
        for (size_t i = s->qhead; i != s->qtail; i = (i + 1) % s->qcap) nq[k++] = s->queue[i];
        free(s->queue);
        s->queue = nq; s->qcap = ncap; s->qhead = 0; s->qtail = k;
    }
    s->queue[s->qtail] = f;
    s->qtail = (s->qtail + 1) % s->qcap;
}

static void *tur_scheduler_mt_worker(void *arg) {
    TurSchedulerMT *s = (TurSchedulerMT *)arg;
    tur_current_scheduler_mt = s;
    for (;;) {
        pthread_mutex_lock(&s->lock);
        while (s->running && s->qhead == s->qtail) {
            pthread_cond_wait(&s->cond, &s->lock);
        }
        if (!s->running && s->qhead == s->qtail) {
            pthread_mutex_unlock(&s->lock);
            break;
        }
        FiberBlock *f = s->queue[s->qhead];
        s->qhead = (s->qhead + 1) % s->qcap;
        s->active++;
        pthread_mutex_unlock(&s->lock);
        tur_fiber_block_resume(f, 0);
        pthread_mutex_lock(&s->lock);
        s->active--;
        if (!f->done && !f->parked) tur_scheduler_mt_enqueue_locked(s, f);
        pthread_cond_broadcast(&s->cond);
        pthread_mutex_unlock(&s->lock);
    }
    return NULL;
}

static TurSchedulerMT *tur_scheduler_mt_new(size_t n_threads) {
    if (n_threads == 0) n_threads = 1;
    TurSchedulerMT *s = (TurSchedulerMT *)calloc(1, sizeof(TurSchedulerMT));
    if (!s) return NULL;
    pthread_mutex_init(&s->lock, NULL);
    pthread_cond_init(&s->cond, NULL);
    s->qcap = 32;
    s->queue = (FiberBlock **)calloc(s->qcap, sizeof(FiberBlock *));
    s->n_threads = n_threads;
    s->threads = (pthread_t *)calloc(n_threads, sizeof(pthread_t));
    s->running = true;
    for (size_t i = 0; i < n_threads; i++) {
        pthread_create(&s->threads[i], NULL, tur_scheduler_mt_worker, s);
    }
    return s;
}

static void tur_scheduler_mt_free(TurSchedulerMT *s) {
    if (!s) return;
    pthread_mutex_lock(&s->lock);
    /* Drain: wait until queue is empty and no fiber is active */
    while (s->qhead != s->qtail || s->active > 0) {
        pthread_cond_wait(&s->cond, &s->lock);
    }
    s->running = false;
    pthread_cond_broadcast(&s->cond);
    pthread_mutex_unlock(&s->lock);
    for (size_t i = 0; i < s->n_threads; i++) pthread_join(s->threads[i], NULL);
    pthread_mutex_destroy(&s->lock);
    pthread_cond_destroy(&s->cond);
    free(s->queue); free(s->threads); free(s);
}

static void tur_scheduler_mt_spawn(TurSchedulerMT *s, FiberBlock *f) {
    if (!s || !f) return;
    pthread_mutex_lock(&s->lock);
    tur_scheduler_mt_enqueue_locked(s, f);
    pthread_cond_signal(&s->cond);
    pthread_mutex_unlock(&s->lock);
}

static void tur_scheduler_mt_run(TurSchedulerMT *s) {
    /* Worker threads run automatically; this is a no-op for the
     * shared-queue impl.  Kept for API compatibility. */
    (void)s;
}

static int64_t tur_scheduler_mt_thread_id(void) {
    return (int64_t)(uintptr_t)pthread_self();
}

static void tur_scheduler_mt_set_current(TurSchedulerMT *s) {
    tur_current_scheduler_mt = s;
}

static TurSchedulerMT *tur_scheduler_mt_current(void) {
    return tur_current_scheduler_mt;
}

static void tur_scheduler_mt_yield(void) {
    /* Cooperative yield: re-enqueues current fiber via the worker loop. */
    tur_fiber_block_yield(0);
}

static void tur_scheduler_mt_park(void) {
    FiberBlock *f = tur_current_fiber;
    if (f) f->parked = 1;
    tur_fiber_block_yield(0);
}

static void tur_scheduler_mt_unpark(FiberBlock *f) {
    TurSchedulerMT *s = tur_current_scheduler_mt;
    if (!f || !s) return;
    f->parked = 0;
    pthread_mutex_lock(&s->lock);
    tur_scheduler_mt_enqueue_locked(s, f);
    pthread_cond_signal(&s->cond);
    pthread_mutex_unlock(&s->lock);
}

/* Phase T21-F: async/await runtime - fiber-based Futures */
typedef enum { FUTURE_PENDING, FUTURE_FULFILLED, FUTURE_REJECTED } TurFutureStatus;

typedef struct TurFuture TurFuture;
struct TurFuture {
    TurFutureStatus status;
    int64_t value;
    const char *error;  /* NULL if no error */
    FiberBlock *fiber;  /* The fiber running the async task */
    struct { void (*fn)(TurFuture *, int64_t); void *env; } on_complete;
};

/* Create a new pending future */
static TurFuture *tur_future_new(void) {
    TurFuture *f = (TurFuture *)calloc(1, sizeof(TurFuture));
    if (!f) { fprintf(stderr, "future: oom\n"); abort(); }
    f->status = FUTURE_PENDING;
    f->fiber = NULL;
    f->on_complete.fn = NULL;
    return f;
}

/* Fulfill a future with a value */
static void tur_future_fulfill(TurFuture *f, int64_t value) {
    if (!f || f->status != FUTURE_PENDING) return;
    f->status = FUTURE_FULFILLED;
    f->value = value;
    if (f->on_complete.fn) f->on_complete.fn(f, value);
}

/* Reject a future with an error message */
static void tur_future_reject(TurFuture *f, const char *error) {
    if (!f || f->status != FUTURE_PENDING) return;
    f->status = FUTURE_REJECTED;
    f->error = error;
}

/* Check if future is done (fulfilled or rejected) */
static int tur_future_done(TurFuture *f) {
    return f && (f->status == FUTURE_FULFILLED || f->status == FUTURE_REJECTED);
}

/* Get future value (only valid if fulfilled) */
static int64_t tur_future_get(TurFuture *f) {
    if (!f || f->status != FUTURE_FULFILLED) return 0;
    return f->value;
}

static TurFuture *tur_async_fiber(int64_t (*fn)(void)) {
    TurFuture *future = tur_future_new();
    if (!tur_scheduler) {
        /* AW-005: Initialize scheduler on first use */
        tur_scheduler = tur_scheduler_new();
    }
    /* AW-005: Simplified v1 - call function directly and fulfill */
    int64_t result = fn();
    tur_future_fulfill(future, result);
    return future;
}

/* AW-004: await lowering with shift + scheduler callback */
static int64_t tur_await_future(TurFuture *f) {
    if (!f) { fprintf(stderr, "await: null future\n"); abort(); }
    if (tur_future_done(f)) {
        if (f->status == FUTURE_REJECTED) {
            fprintf(stderr, "await: future rejected: %s\n", f->error ? f->error : "unknown");
            abort();
        }
        return f->value;
    }
    /* Future not ready */
    if (!tur_current_fiber) {
        /* Not in a fiber - run the scheduler until future is done */
        if (!tur_scheduler) {
            fprintf(stderr, "await: no scheduler and not in fiber\n");
            abort();
        }
        while (!tur_future_done(f)) {
            tur_scheduler_run_one(tur_scheduler);
        }
    } else {
        /* In a fiber - yield and let scheduler resume us */
        /* Register a callback to re-enqueue this fiber when future completes */
        f->on_complete.fn = (void (*)(TurFuture *, int64_t))tur_fiber_block_resume;
        f->on_complete.env = (void *)tur_current_fiber;
        tur_fiber_block_yield(0);
        /* When we resume, the future should be done */
        if (tur_future_done(f) && f->status == FUTURE_REJECTED) {
            fprintf(stderr, "await: future rejected: %s\n", f->error ? f->error : "unknown");
            abort();
        }
        return f->value;
    }
    if (f->status == FUTURE_REJECTED) {
        fprintf(stderr, "await: future rejected: %s\n", f->error ? f->error : "unknown");
        abort();
    }
    return f->value;
}

static void tur_future_free(TurFuture *f) {
    if (!f) return;
    free(f);
}

/* Backward compatibility: TurAsyncTask = TurFuture */
typedef TurFuture TurAsyncTask;

/* Phase SEL0: TurSelectWaiter -- select waiter for fair multi-channel blocking */
typedef struct TurSelectWaiter TurSelectWaiter;
struct TurSelectWaiter {
    pthread_mutex_t *wakeup_mutex;
    pthread_cond_t  *wakeup_cond;
    volatile int    *selected_idx;
    int              clause_idx;
    TurSelectWaiter *next;
};

/* Phase SEL0: signal the first unselected waiter in the list */
static void tur_waiter_signal_one(void *waiter_list) {
    TurSelectWaiter *w = (TurSelectWaiter *)waiter_list;
    while (w) {
        int exp = -1;
        if (__atomic_compare_exchange_n(w->selected_idx, &exp, w->clause_idx, 0,
                                        __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST)) {
            pthread_mutex_lock(w->wakeup_mutex);
            pthread_cond_signal(w->wakeup_cond);
            pthread_mutex_unlock(w->wakeup_mutex);
            return;
        }
        w = w->next;
    }
}

/* Phase SEL1: TurSelectClause -- clause descriptor for tur_select_blocking */
typedef struct { void *chan; int op; int64_t val; } TurSelectClause;

/* Phase SEL1: persistent xorshift32 PRNG for fair select */
static volatile uint32_t __tur_xr_state = 1u;

/* Phase SEL1: tur_select_blocking -- block on all clauses; wake on first ready.
 * clauses: array of TurSelectClause (op 0=recv, 1=send)
 * n: number of clauses
 * has_default: 1 if a :default arm is present
 * Returns: index of the clause that fired, or -1 for default */
static int tur_select_blocking(TurSelectClause *clauses, int n, int has_default) {
    typedef struct {
        pthread_mutex_t lock; pthread_cond_t not_full; pthread_cond_t not_empty;
        int64_t *buf; int64_t head; int64_t tail; int64_t count; int64_t cap;
        void *recv_waiters; void *send_waiters;
    } ChanBlock_;
    if (n <= 0) return -2;
    /* Phase 1: non-blocking scan -- try all clauses without blocking */
    /* Collect unique channels for lock ordering */
    ChanBlock_ *lock_order[64];
    int n_unique = 0;
    for (int i = 0; i < n && n_unique < 64; i++) {
        ChanBlock_ *ch = (ChanBlock_ *)clauses[i].chan;
        int found = 0;
        for (int j = 0; j < n_unique; j++) if (lock_order[j] == ch) { found = 1; break; }
        if (!found) lock_order[n_unique++] = ch;
    }
    /* Sort channels by address for deadlock-free locking order */
    for (int i = 0; i < n_unique - 1; i++)
        for (int j = i + 1; j < n_unique; j++)
            if ((uintptr_t)lock_order[i] > (uintptr_t)lock_order[j]) {
                ChanBlock_ *tmp = lock_order[i]; lock_order[i] = lock_order[j]; lock_order[j] = tmp;
            }
    /* Acquire all locks */
    for (int i = 0; i < n_unique; i++) pthread_mutex_lock(&lock_order[i]->lock);
    /* Final non-blocking scan under all locks */
    int ready[64]; int n_ready = 0;
    for (int i = 0; i < n; i++) {
        ChanBlock_ *ch = (ChanBlock_ *)clauses[i].chan;
        if (clauses[i].op == 0) { if (ch->count > 0) ready[n_ready++] = i; }
        else                   { if (ch->count < ch->cap) ready[n_ready++] = i; }
    }
    if (n_ready > 0) {
        /* Fair: pick uniformly at random among ready clauses.
         * Use a persistent xorshift32 state so repeated calls from the
         * same site (e.g. a TCO loop) don't always produce the same winner. */
        uint32_t xr = __tur_xr_state;
        xr ^= (uint32_t)(uintptr_t)clauses;
        if (!xr) xr = 0x9e3779b9u;
        xr ^= xr << 13; xr ^= xr >> 17; xr ^= xr << 5;
        __tur_xr_state = xr;
        int winner = ready[xr % (uint32_t)n_ready];
        ChanBlock_ *wch = (ChanBlock_ *)clauses[winner].chan;
        if (clauses[winner].op == 0) { /* recv */
            clauses[winner].val = wch->buf[wch->head];
            wch->head = (wch->head + 1) % wch->cap; wch->count--;
            pthread_cond_signal(&wch->not_full);
            tur_waiter_signal_one(wch->send_waiters);
        } else { /* send */
            wch->buf[wch->tail] = clauses[winner].val;
            wch->tail = (wch->tail + 1) % wch->cap; wch->count++;
            pthread_cond_signal(&wch->not_empty);
            tur_waiter_signal_one(wch->recv_waiters);
        }
        for (int i = 0; i < n_unique; i++) pthread_mutex_unlock(&lock_order[i]->lock);
        return winner;
    }
    /* Phase 2: default arm */
    if (has_default) {
        for (int i = 0; i < n_unique; i++) pthread_mutex_unlock(&lock_order[i]->lock);
        return -1;
    }
    /* Phase 3: register waiters and sleep until one fires */
    pthread_mutex_t wakeup_mutex;
    pthread_cond_t  wakeup_cond;
    pthread_mutex_init(&wakeup_mutex, NULL);
    pthread_cond_init(&wakeup_cond, NULL);
    volatile int selected_idx = -1;
    TurSelectWaiter waiters[64];
    int wn = n < 64 ? n : 64;
    for (int i = 0; i < wn; i++) {
        waiters[i].wakeup_mutex = &wakeup_mutex;
        waiters[i].wakeup_cond  = &wakeup_cond;
        waiters[i].selected_idx = &selected_idx;
        waiters[i].clause_idx   = i;
        ChanBlock_ *ch = (ChanBlock_ *)clauses[i].chan;
        if (clauses[i].op == 0) { /* recv waiter */
            waiters[i].next = (TurSelectWaiter *)ch->recv_waiters;
            ch->recv_waiters = &waiters[i];
        } else { /* send waiter */
            waiters[i].next = (TurSelectWaiter *)ch->send_waiters;
            ch->send_waiters = &waiters[i];
        }
    }
    /* Release all channel locks */
    for (int i = 0; i < n_unique; i++) pthread_mutex_unlock(&lock_order[i]->lock);
    /* Sleep until woken by a channel operation */
    pthread_mutex_lock(&wakeup_mutex);
    while (selected_idx == -1)
        pthread_cond_wait(&wakeup_cond, &wakeup_mutex);
    int winner = selected_idx;
    pthread_mutex_unlock(&wakeup_mutex);
    /* Deregister all waiters */
    for (int i = 0; i < wn; i++) {
        ChanBlock_ *ch = (ChanBlock_ *)clauses[i].chan;
        pthread_mutex_lock(&ch->lock);
        if (clauses[i].op == 0) {
            TurSelectWaiter **pp = (TurSelectWaiter **)&ch->recv_waiters;
            while (*pp && *pp != &waiters[i]) pp = &(*pp)->next;
            if (*pp) *pp = (*pp)->next;
        } else {
            TurSelectWaiter **pp = (TurSelectWaiter **)&ch->send_waiters;
            while (*pp && *pp != &waiters[i]) pp = &(*pp)->next;
            if (*pp) *pp = (*pp)->next;
        }
        pthread_mutex_unlock(&ch->lock);
    }
    /* Execute the winning clause */
    ChanBlock_ *wch = (ChanBlock_ *)clauses[winner].chan;
    pthread_mutex_lock(&wch->lock);
    if (clauses[winner].op == 0) { /* recv */
        while (wch->count == 0) pthread_cond_wait(&wch->not_empty, &wch->lock);
        clauses[winner].val = wch->buf[wch->head];
        wch->head = (wch->head + 1) % wch->cap; wch->count--;
        pthread_cond_signal(&wch->not_full);
        tur_waiter_signal_one(wch->send_waiters);
    } else { /* send */
        while (wch->count == wch->cap) pthread_cond_wait(&wch->not_full, &wch->lock);
        wch->buf[wch->tail] = clauses[winner].val;
        wch->tail = (wch->tail + 1) % wch->cap; wch->count++;
        pthread_cond_signal(&wch->not_empty);
        tur_waiter_signal_one(wch->recv_waiters);
    }
    pthread_mutex_unlock(&wch->lock);
    pthread_mutex_destroy(&wakeup_mutex);
    pthread_cond_destroy(&wakeup_cond);
    return winner;
}

static int64_t tur_effect_perform(const char *name, int64_t *args, int n_args) {
    EffectHandlerFrame *frame =
        (tur_current_fiber && tur_current_fiber->effect_handler_chain)
        ? (EffectHandlerFrame *)tur_current_fiber->effect_handler_chain
        : global_effect_handler_chain;
    while (frame) {
        for (int __i = 0; __i < frame->n_cases; __i++) {
            if (strcmp(frame->cases[__i].effect_name, name) == 0) {
                if (frame->cases[__i].handler_fn == NULL) {
                    /* Phase 19D: intercept case - yield fiber to parent dispatch loop */
                    FiberBlock *__cur = tur_current_fiber;
                    if (!__cur || !__cur->eff_ctx) { fprintf(stderr, "Unhandled effect: %s\n", name); abort(); }
                    TurEffectCaptureCtx *__cap = (TurEffectCaptureCtx *)__cur->eff_ctx;
                    __cap->eff_name = name;
                    int __cn = n_args < 8 ? n_args : 8;
                    for (int __ai = 0; __ai < __cn; __ai++) __cap->eff_args[__ai] = args[__ai];
                    __cap->eff_n_args = n_args;
                    __cap->has_pending_effect = true;
                    tur_fiber_block_yield(0);
                    __cap->has_pending_effect = false;
                    return __cur->arg;
                }
                TurContK __fresh_k = {false, tur_current_fiber};
                return frame->cases[__i].handler_fn(args, n_args, (int64_t)(intptr_t)&__fresh_k, frame->cases[__i].env);
            }
        }
        frame = frame->parent;
    }
    fprintf(stderr, "Unhandled effect: %s\n", name);
    abort();
    return 0;
}

/* rc<T> + weak<T> reference counting - Phase 9 */
/* Phase 10: GC color enum for Bacon-Rajan */
typedef enum { GC_WHITE, GC_GREY, GC_BLACK, GC_PURPLE } GcColor;

typedef void (*RcDropFn)(void *value);

typedef struct RcControlBlock RcControlBlock;

struct RcControlBlock {
    uint64_t strong_count;
    uint64_t weak_count;
    void *value;
    RcDropFn drop_fn;
    uint8_t value_type_kind;
    uint8_t color;           /* GC color */
    bool may_contain_cycles;  /* Hint for GC */
    uint8_t reserved[6];
};

#define RC_FREE_QUEUE_CAPACITY 65536
static RcControlBlock *rc_free_queue[RC_FREE_QUEUE_CAPACITY];
static uint32_t rc_free_queue_count = 0;
static uint32_t rc_free_queue_drain(void);  /* Forward decl */
static void rc_free_queue_push(RcControlBlock *cb);  /* Forward decl */
bool rc_strong_decrement(RcControlBlock *cb);  /* Forward decl */
bool rc_weak_decrement(RcControlBlock *cb);    /* Forward decl */
static void rc_free_queue_push(RcControlBlock *cb) {
    if (!cb) return;
    if (rc_free_queue_count >= RC_FREE_QUEUE_CAPACITY) {
        fprintf(stderr, "rc_free_queue: full, aborting\n");
        abort();
    }
    rc_free_queue[rc_free_queue_count++] = cb;
}

#define GC_GLOBAL_REGISTRY_CAPACITY 4096
static RcControlBlock *gc_all_blocks[GC_GLOBAL_REGISTRY_CAPACITY];
static uint32_t gc_all_blocks_count = 0;

#define GC_SUSPECT_THRESHOLD 128
#define GC_MAX_SUSPECTS 4096

typedef enum { GC_DISABLED, GC_MANUAL, GC_THRESHOLD } GcMode;

static RcControlBlock *gc_suspect_roots[GC_MAX_SUSPECTS];
static uint32_t gc_suspect_count = 0;
static RcControlBlock *gc_grey_queue[GC_MAX_SUSPECTS];
static uint32_t gc_grey_count = 0;
static GcMode gc_mode = GC_DISABLED;
static bool gc_enabled = false;

static void gc_collect(void);  /* Forward decl */

static void gc_set_color(RcControlBlock *cb, GcColor color) {
    if (cb) cb->color = color;
}

static GcColor gc_get_color(RcControlBlock *cb) {
    if (cb) return cb->color;
    return GC_WHITE;
}

static void gc_register_block(RcControlBlock *cb) {
    if (!cb || gc_all_blocks_count >= GC_GLOBAL_REGISTRY_CAPACITY) return;
    gc_all_blocks[gc_all_blocks_count++] = cb;
    cb->color = GC_WHITE;
    cb->may_contain_cycles = true;
}

static void gc_unregister_block(RcControlBlock *cb) {
    if (!cb) return;
    for (uint32_t i = 0; i < gc_all_blocks_count; i++) {
        if (gc_all_blocks[i] == cb) {
            gc_all_blocks[i] = gc_all_blocks[gc_all_blocks_count - 1];
            gc_all_blocks_count--;
            break;
        }
    }
}

static void gc_add_suspect(RcControlBlock *cb) {
    if (!cb || !gc_enabled || gc_mode == GC_DISABLED) return;
    for (uint32_t i = 0; i < gc_suspect_count; i++) {
        if (gc_suspect_roots[i] == cb) return;
    }
    if (gc_suspect_count >= GC_MAX_SUSPECTS) return;
    gc_suspect_roots[gc_suspect_count++] = cb;
    cb->color = GC_PURPLE;
    /* Threshold mode: auto-collect when buffer is full */
    if (gc_mode == GC_THRESHOLD && gc_suspect_count >= GC_SUSPECT_THRESHOLD) {
        gc_collect();
    }
}

static void gc_remove_suspect(RcControlBlock *cb) {
    if (!cb) return;
    for (uint32_t i = 0; i < gc_suspect_count; i++) {
        if (gc_suspect_roots[i] == cb) {
            gc_suspect_roots[i] = gc_suspect_roots[gc_suspect_count - 1];
            gc_suspect_count--;
            return;
        }
    }
}

static void gc_on_strong_decrement(RcControlBlock *cb) {
    if (!cb) return;
    /* Zombie: strong reached 0 but weak refs still exist */
    if (cb->weak_count > 0) {
        gc_add_suspect(cb);
    }
}


/* Phase 9: Deferred free queue drain */
static uint32_t rc_free_queue_drain(void) {
    if (rc_free_queue_count == 0) return 0;
    uint32_t freed = 0;
    while (rc_free_queue_count > 0) {
        RcControlBlock *cb = rc_free_queue[0];
        memmove(rc_free_queue, rc_free_queue + 1,
                (rc_free_queue_count - 1) * sizeof(RcControlBlock *));
        rc_free_queue_count--;
        gc_unregister_block(cb);
        if (cb->value) cb->drop_fn(cb->value);
        free(cb);
        freed++;
    }
    return freed;
}

static void default_rc_drop_fn(void *value) {
    free(value);
}

static void drop_ref_payload(void *value) {
    if (!value) return;
    void *inner = *((void **)value);
    if (inner) free(inner);
    free(value);
}

static void drop_rc_payload(void *value) {
    if (!value) return;
    RcControlBlock *inner = *((RcControlBlock **)value);
    if (inner) { rc_strong_decrement(inner); rc_free_queue_drain(); }
    free(value);
}

static void drop_weak_payload(void *value) {
    if (!value) return;
    RcControlBlock *inner = *((RcControlBlock **)value);
    if (inner) rc_weak_decrement(inner);
    free(value);
}

static RcDropFn default_drop_fn_for_type(int value_type_kind) {
    switch (value_type_kind) {
        case 8: return drop_ref_payload;   /* TY_REF */
        case 9: return drop_rc_payload;    /* TY_RC */
        case 10: return drop_weak_payload; /* TY_WEAK */
        default: return default_rc_drop_fn;
    }
}

RcControlBlock *rc_cb_alloc(size_t value_size, int value_type_kind, RcDropFn drop_fn) {
    size_t total_size = sizeof(RcControlBlock) + value_size;
    RcControlBlock *cb = (RcControlBlock *)malloc(total_size);
    if (!cb) { fprintf(stderr, "rc: out of memory\n"); abort(); }
    cb->strong_count = 1;
    cb->weak_count = 0;
    cb->value = (void *)(cb + 1);
    cb->drop_fn = drop_fn ? drop_fn : default_drop_fn_for_type(value_type_kind);
    cb->value_type_kind = value_type_kind;
    memset(cb->reserved, 0, sizeof(cb->reserved));
    /* Register with GC; primitives (type_kind<=7) cannot form cycles */
    gc_register_block(cb);
    if (value_type_kind <= 7) cb->may_contain_cycles = false;
    return cb;
}

uint64_t rc_strong_increment(RcControlBlock *cb) {
    if (!cb) return 0;
    return ++cb->strong_count;
}

bool rc_strong_decrement(RcControlBlock *cb) {
    if (!cb) return false;
    cb->strong_count--;
    if (cb->strong_count == 0) {
        if (cb->weak_count > 0) {
            gc_on_strong_decrement(cb);
            return false;
        } else {
            rc_free_queue_push(cb);
            return true;
        }
    }
    return false;
}

uint64_t rc_weak_increment(RcControlBlock *cb) {
    if (!cb) return 0;
    return ++cb->weak_count;
}

bool rc_weak_decrement(RcControlBlock *cb) {
    if (!cb) return false;
    cb->weak_count--;
    if (cb->weak_count == 0 && cb->strong_count == 0) {
        gc_unregister_block(cb);
        /* Free zombie value if GC did not already collect it */
        if (cb->value && cb->drop_fn) {
            cb->drop_fn(cb->value);
        }
        free(cb);
        return true;
    }
    return false;
}

uint64_t rc_strong_count(RcControlBlock *cb) {
    if (!cb) return 0;
    return cb->strong_count;
}

uint64_t rc_weak_count(RcControlBlock *cb) {
    if (!cb) return 0;
    return cb->weak_count;
}

bool rc_is_alive(RcControlBlock *cb) {
    if (!cb) return false;
    return cb->strong_count > 0;
}

RcControlBlock *rc_upgrade(RcControlBlock *cb) {
    if (!cb) return NULL;
    if (cb->strong_count > 0) {
        rc_strong_increment(cb);
        return cb;
    }
    return NULL;
}

void *rc_get_value(RcControlBlock *cb) {
    if (!cb) return NULL;
    return cb->value;
}

RcControlBlock *tur_rc_from_ref(void *ref_value, int value_type_kind) {
    if (!ref_value) return NULL;
    RcControlBlock *cb = (RcControlBlock *)malloc(sizeof(RcControlBlock));
    if (!cb) { fprintf(stderr, "rc/from-ref: out of memory\n"); abort(); }
    cb->strong_count = 1;
    cb->weak_count = 0;
    cb->value = ref_value;
    cb->drop_fn = default_drop_fn_for_type(value_type_kind);
    cb->value_type_kind = (uint8_t)value_type_kind;
    cb->color = GC_WHITE;
    cb->may_contain_cycles = true;
    memset(cb->reserved, 0, sizeof(cb->reserved));
    gc_register_block(cb);
    return cb;
}

void *tur_ref_from_rc(RcControlBlock *cb) {
    if (!cb) return NULL;
    if (cb->strong_count != 1 || cb->weak_count != 0) {
        fprintf(stderr, "ref/from-rc requires unique rc (strong_count==1 and weak_count==0), got strong=%llu weak=%llu\n",
                (unsigned long long)cb->strong_count, (unsigned long long)cb->weak_count);
        abort();
    }
    void *value = cb->value;
    cb->value = NULL;
    gc_unregister_block(cb);
    free(cb);
    return value;
}

/* gc (Bacon-Rajan cycle collector - trial deletion) - Phase 10 */
static void gc_mark_phase(void) {
    for (uint32_t i = 0; i < gc_all_blocks_count; i++) {
        gc_all_blocks[i]->color = GC_WHITE;
    }
    for (uint32_t i = 0; i < gc_all_blocks_count; i++) {
        RcControlBlock *cb = gc_all_blocks[i];
        if (cb->strong_count > 0) {
            cb->color = GC_BLACK;
        }
    }
}

static void gc_trial_deletion_phase(void) {
    uint32_t i = 0;
    while (i < gc_suspect_count) {
        RcControlBlock *cb = gc_suspect_roots[i];
        /* If revived or reachable from strong roots, keep */
        if (cb->strong_count > 0 || cb->color == GC_BLACK) {
            cb->color = GC_WHITE;
            i++;
            continue;
        }
        /* WHITE and strong_count == 0: zombie — free value, keep cb for weak refs */
        if (cb->value && cb->drop_fn) {
            cb->drop_fn(cb->value);
            cb->value = NULL;
        }
        /* Unregister from global registry (cb stays alive for weak refs) */
        gc_unregister_block(cb);
        /* Remove from suspect buffer without advancing i */
        gc_suspect_roots[i] = gc_suspect_roots[gc_suspect_count - 1];
        gc_suspect_count--;
    }
}

static void gc_collect(void) {
    if (!gc_enabled || gc_mode == GC_DISABLED) return;
    gc_grey_count = 0;
    gc_mark_phase();
    gc_trial_deletion_phase();
}

static void gc_force(void) {
    gc_collect();
}

static void gc_enable(void) {
    gc_enabled = true;
    /* Default to manual mode when enabled */
    if (gc_mode == GC_DISABLED) gc_mode = GC_MANUAL;
}

static void gc_disable(void) {
    gc_enabled = false;
    gc_mode = GC_DISABLED;
}

static void gc_set_mode(GcMode mode) {
    gc_mode = mode;
}

static bool gc_is_alive(RcControlBlock *cb) {
    if (!cb) return false;
    if (cb->strong_count > 0) return true;
    return (cb->color == GC_BLACK || cb->color == GC_GREY);
}

extern void * tur_hamt_new();
extern void tur_hamt_free(void *);
extern void * tur_hamt_retain(void *);
extern int64_t tur_hamt_count(void *);
extern void * tur_hamt_set(void *, int64_t, void *, void *);
extern void * tur_hamt_del(void *, int64_t, void *);
extern bool tur_hamt_has(void *, int64_t, void *);
extern void * tur_hamt_get(void *, int64_t, void *);
extern void * tur_hamt_merge(void *, void *);
extern int64_t tur_hamt_hash_str(const char *);
extern int64_t tur_hamt_hash_ptr(void *);
extern void tur_hamt_iter_init(void *, void *);
extern void tur_hamt_iter_free(void *);
extern bool tur_hamt_iter_next(void *, void *, void *, void *);
extern void * tur_hamt_map(void *, void *, void *);
extern void * tur_hamt_filter(void *, void *, void *);
extern void * tur_hamt_reduce(void *, void *, void *, void *);
extern void * tur_hamt_merge_with(void *, void *, void *, void *);
extern const char * tur_hamt_show(void *);
extern void tur_hamt_dump_dot(void *, void *);
extern void tur_hamt_dump_dot_stderr(void *);
extern void * tur_hamt_transient(void *);
extern void tur_hamt_transient_set(void *, int64_t, void *, void *);
extern void tur_hamt_transient_del(void *, int64_t, void *);
extern void * tur_hamt_persistent(void *);

static void * array_get(void *, int64_t);
static int64_t array_set(void *, int64_t, int64_t);
static void * array_slice(void *, int64_t, int64_t);
static void * with_c_string(const char *, void *);
static const char * from_c_string(const char *);
static void * box(int64_t);
static int64_t unbox(void *);
static bool contract_enabled_();
static void tur_contract_check(bool, const char *);
static void tur_contract_check_inv(int64_t, int64_t, const char *);
static void * hamt_new();
static void hamt_free(void *);
static void * hamt_retain(void *);
static void * hamt_set(void *, int64_t, void *, void *);
static void * hamt_del(void *, int64_t, void *);
static void * hamt_get(void *, int64_t, void *);
static bool hamt_has_(void *, int64_t, void *);
static int64_t hamt_count(void *);
static void * hamt_merge(void *, void *);
static int64_t hamt_hash_str(const char *);
static int64_t hamt_hash_ptr(void *);
static void hamt_iter_init(void *, void *);
static void hamt_iter_free(void *);
static bool hamt_iter_next(void *, void *, void *, void *);
static void * hamt_map(void *, void *, void *);
static void * hamt_filter(void *, void *, void *);
static void * hamt_reduce(void *, void *, void *, void *);
static void * hamt_merge_with(void *, void *, void *, void *);
static const char * hamt_show(void *);
static void hamt_dump(void *);
static void * hamt_transient(void *);
static void hamt_transient_set_(void *, int64_t, void *, void *);
static void hamt_transient_del_(void *, int64_t, void *);
static void * hamt_persistent_(void *);
static int64_t hamt_autolink_hint();
static void * map_new();
static void * assoc(void *, void *, void *);
static void * dissoc(void *, void *);
static void * get(void *, void *);
static bool has_(void *, void *);
static int64_t count(void *);
static void * merge(void *, void *);
static bool map_eq_(int64_t, int64_t, int64_t);
static void log_hello();
static int64_t ask_and_log();
static int64_t add(int64_t, int64_t);

static void * array_get(void * arr, int64_t idx) {
        struct __array_get_result { bool is_some; int64_t value; } *opt = malloc(sizeof(*opt));
  int64_t *array = (int64_t *)arr;
  if (idx >= 0 && (size_t)idx < 1024) {  /* v1: use a reasonable upper bound */
    opt->is_some = true;
    opt->value = array[idx];
  } else {
    opt->is_some = false;
    opt->value = 0;
  }
  return opt;
  
}

static int64_t array_set(void * arr, int64_t idx, int64_t value) {
        int64_t *array = (int64_t *)arr;
  if (idx >= 0 && (size_t)idx < 1024) {  /* v1: use a reasonable upper bound */
    array[idx] = value;
    return 1;
  }
  return 0;
  
}

static void * array_slice(void * arr, int64_t start, int64_t len) {
        /* For v1, we return a new struct containing ptr and len */
  struct { void *ptr; size_t len; } *slice = malloc(sizeof(*slice));
  slice->ptr = (char *)arr + start * sizeof(int64_t);
  slice->len = len;
  return slice;
  
}

static void * with_c_string(const char * s, void * f) {
        /* For v1, we just call f with s directly since cstr is already a C string */
  int64_t (*fn)(const char *) = (int64_t (*)(const char *))f;
  return (void *)(intptr_t)fn(s);
  
}

static const char * from_c_string(const char * s) {
        return s;
}

static void * box(int64_t v) {
        int64_t *boxed = malloc(sizeof(int64_t));
  *boxed = v;
  return boxed;
  
}

static int64_t unbox(void * p) {
        int64_t *boxed = (int64_t *)p;
  return *boxed;
  
}

static bool contract_enabled_() {
        return true;
}

static void tur_contract_check(bool condition, const char * msg) {
        if (!condition) { tur_panic((const char*)msg); }
  
}

static void tur_contract_check_inv(int64_t obj, int64_t pred, const char * msg) {
        typedef int64_t (*pred_fn)(int64_t);
  pred_fn f = (pred_fn)(intptr_t)pred;
  if (!f(obj)) { tur_panic((const char*)msg); }
  
}

static void * hamt_new() {
        return tur_hamt_new();
}

static void hamt_free(void * m) {
        tur_hamt_free((void *)(intptr_t)(m));
}

static void * hamt_retain(void * m) {
        return tur_hamt_retain((void *)(intptr_t)(m));
}

static void * hamt_set(void * m, int64_t hash, void * key, void * val) {
        return tur_hamt_set((void *)(intptr_t)(m), hash, (void *)(intptr_t)(key), (void *)(intptr_t)(val));
}

static void * hamt_del(void * m, int64_t hash, void * key) {
        return tur_hamt_del((void *)(intptr_t)(m), hash, (void *)(intptr_t)(key));
}

static void * hamt_get(void * m, int64_t hash, void * key) {
        return tur_hamt_get((void *)(intptr_t)(m), hash, (void *)(intptr_t)(key));
}

static bool hamt_has_(void * m, int64_t hash, void * key) {
        return tur_hamt_has((void *)(intptr_t)(m), hash, (void *)(intptr_t)(key));
}

static int64_t hamt_count(void * m) {
        return tur_hamt_count((void *)(intptr_t)(m));
}

static void * hamt_merge(void * a, void * b) {
        return tur_hamt_merge((void *)(intptr_t)(a), (void *)(intptr_t)(b));
}

static int64_t hamt_hash_str(const char * str) {
        return tur_hamt_hash_str(str);
}

static int64_t hamt_hash_ptr(void * ptr) {
        return tur_hamt_hash_ptr((void *)(intptr_t)(ptr));
}

static void hamt_iter_init(void * iter, void * m) {
        tur_hamt_iter_init((void *)(intptr_t)(iter), (void *)(intptr_t)(m));
}

static void hamt_iter_free(void * iter) {
        tur_hamt_iter_free((void *)(intptr_t)(iter));
}

static bool hamt_iter_next(void * iter, void * hash_out, void * key_out, void * val_out) {
        return tur_hamt_iter_next((void *)(intptr_t)(iter), (void *)(intptr_t)(hash_out), (void *)(intptr_t)(key_out), (void *)(intptr_t)(val_out));
}

static void * hamt_map(void * m, void * fn, void * ctx) {
        return tur_hamt_map((void *)(intptr_t)(m), (void *)(intptr_t)(fn), (void *)(intptr_t)(ctx));
}

static void * hamt_filter(void * m, void * fn, void * ctx) {
        return tur_hamt_filter((void *)(intptr_t)(m), (void *)(intptr_t)(fn), (void *)(intptr_t)(ctx));
}

static void * hamt_reduce(void * m, void * fn, void * init, void * ctx) {
        return tur_hamt_reduce((void *)(intptr_t)(m), (void *)(intptr_t)(fn), (void *)(intptr_t)(init), (void *)(intptr_t)(ctx));
}

static void * hamt_merge_with(void * a, void * b, void * fn, void * ctx) {
        return tur_hamt_merge_with((void *)(intptr_t)(a), (void *)(intptr_t)(b), (void *)(intptr_t)(fn), (void *)(intptr_t)(ctx));
}

static const char * hamt_show(void * m) {
        return tur_hamt_show((void *)(intptr_t)(m));
}

static void hamt_dump(void * m) {
        tur_hamt_dump_dot_stderr((void *)(intptr_t)(m));
}

static void * hamt_transient(void * m) {
        return tur_hamt_transient((void *)(intptr_t)(m));
}

static void hamt_transient_set_(void * t, int64_t hash, void * key, void * val) {
        tur_hamt_transient_set((void *)(intptr_t)(t), hash, (void *)(intptr_t)(key), (void *)(intptr_t)(val));
}

static void hamt_transient_del_(void * t, int64_t hash, void * key) {
        tur_hamt_transient_del((void *)(intptr_t)(t), hash, (void *)(intptr_t)(key));
}

static void * hamt_persistent_(void * t) {
        return tur_hamt_persistent((void *)(intptr_t)(t));
}

static int64_t hamt_autolink_hint() {
        /* __tur_autolink__: src/hamt.c -Isrc */
  return 0;
  
}

static void * map_new() {
        return hamt_new();
}

static void * assoc(void * m, void * key, void * val) {
        return hamt_set((void *)(intptr_t)(m), hamt_hash_ptr((void *)(intptr_t)(key)), (void *)(intptr_t)(key), (void *)(intptr_t)(val));
}

static void * dissoc(void * m, void * key) {
        return hamt_del((void *)(intptr_t)(m), hamt_hash_ptr((void *)(intptr_t)(key)), (void *)(intptr_t)(key));
}

static void * get(void * m, void * key) {
        return hamt_get((void *)(intptr_t)(m), hamt_hash_ptr((void *)(intptr_t)(key)), (void *)(intptr_t)(key));
}

static bool has_(void * m, void * key) {
        return hamt_has_((void *)(intptr_t)(m), hamt_hash_ptr((void *)(intptr_t)(key)), (void *)(intptr_t)(key));
}

static int64_t count(void * m) {
        return hamt_count((void *)(intptr_t)(m));
}

static void * merge(void * a, void * b) {
        return hamt_merge((void *)(intptr_t)(a), (void *)(intptr_t)(b));
}

static bool map_eq_(int64_t m1, int64_t m2, int64_t val_cmp) {
        if (tur_hamt_count((void*)(intptr_t)m1) !=
      tur_hamt_count((void*)(intptr_t)m2)) return false;
  uint64_t iter_buf[32];
  for (int __i = 0; __i < 32; __i++) iter_buf[__i] = 0;
  tur_hamt_iter_init(iter_buf, (void*)(intptr_t)m1);
  uint64_t hash_out;
  void *key_out = NULL, *val_out = NULL;
  while (tur_hamt_iter_next(iter_buf, &hash_out, &key_out, &val_out)) {
      void *val_in_b = tur_hamt_get(
          (void*)(intptr_t)m2, (int64_t)hash_out, key_out);
      if (!val_in_b) { tur_hamt_iter_free(iter_buf); return false; }
      bool vals_eq = ((bool(*)(int64_t, int64_t))(intptr_t)val_cmp)(
          (int64_t)(intptr_t)val_out, (int64_t)(intptr_t)val_in_b);
      if (!vals_eq) { tur_hamt_iter_free(iter_buf); return false; }
  }
  tur_hamt_iter_free(iter_buf);
  return true;
  
}

static void log_hello() {
        int64_t __t0[1];
        __t0[0] = (int64_t)"hello";
        tur_effect_perform("Log", __t0, 1);
}

static int64_t ask_and_log() {
        int64_t __t1;
        int64_t __t2;
        {
            int64_t __t3 = tur_effect_perform("Ask", NULL, 0);
            int64_t n_211 = __t3;
            (void)n_211;
            int64_t __t4[1];
            __t4[0] = (int64_t)"asked";
            tur_effect_perform("Log", __t4, 1);
            int64_t __t5;
            __t5 = n_211;
            __t2 = __t5;
        }
        __t1 = __t2;
        return __t1;
}

static int64_t add(int64_t x, int64_t y) {
        return ((x) + (y));
}

static int64_t __effect_handler_7(int64_t *__effect_args, int __n_effect_args, int64_t __k, void *__env);
static int64_t __effect_handler_7(int64_t *__effect_args, int __n_effect_args, int64_t __k, void *__env) {
    const char * msg_214 = (const char *)__effect_args[0];
    int64_t k_215 = __k;
    puts(msg_214);
    int64_t __t8;
    int64_t __t9 = tur_effect_cont_resume((int64_t)(intptr_t)k_215, (int64_t)INT64_C(0));
    __t8 = __t9;
    return (int64_t)__t8;
}

static void __handle_body_6(void);
static void __handle_body_6(void) {
    log_hello();
    int64_t __t10;
    __t10 = INT64_C(0);
    tur_current_fiber->result = (int64_t)__t10;
}

static int64_t __dispatch_6(void *__ctx_void, int64_t __k_int, int64_t __resume_val);
static int64_t __dispatch_6(void *__ctx_void, int64_t __k_int, int64_t __resume_val) {
    TurEffectCaptureCtx *__dcap = (TurEffectCaptureCtx *)__ctx_void;
    FiberBlock *__fiber = (FiberBlock *)(intptr_t)__k_int;
    int64_t __r = tur_fiber_block_resume(__fiber, __resume_val);
    if (__fiber->done) { return __fiber->result; }
    if (!__dcap->has_pending_effect) return __r;
    if (strcmp(__dcap->eff_name, "Log") == 0) {
        return __effect_handler_7(__dcap->eff_args, __dcap->eff_n_args, __k_int, NULL);
    } else {
        /* Phase 19D: bubble up unhandled effect to outer fiber */
        FiberBlock *__outer_f = tur_current_fiber;
        if (__outer_f && __outer_f->eff_ctx) {
            TurEffectCaptureCtx *__outer_cap = (TurEffectCaptureCtx *)__outer_f->eff_ctx;
            __outer_cap->eff_name = __dcap->eff_name;
            int __bun = __dcap->eff_n_args < 8 ? __dcap->eff_n_args : 8;
            for (int __bi = 0; __bi < __bun; __bi++) __outer_cap->eff_args[__bi] = __dcap->eff_args[__bi];
            __outer_cap->eff_n_args = __dcap->eff_n_args;
            __outer_cap->has_pending_effect = true;
            tur_fiber_block_yield(0);
            __outer_cap->has_pending_effect = false;
            return __dispatch_6(__ctx_void, __k_int, __outer_f->arg);
        }
        fprintf(stderr, "dispatch: unhandled effect: %s\n", __dcap->eff_name);
        abort();
    }
    return 0;
}

static int64_t __effect_handler_13(int64_t *__effect_args, int __n_effect_args, int64_t __k, void *__env);
static int64_t __effect_handler_13(int64_t *__effect_args, int __n_effect_args, int64_t __k, void *__env) {
    const char * msg_217 = (const char *)__effect_args[0];
    int64_t k_218 = __k;
    puts(msg_217);
    int64_t __t14;
    int64_t __t15 = tur_effect_cont_resume((int64_t)(intptr_t)k_218, (int64_t)INT64_C(0));
    __t14 = __t15;
    return (int64_t)__t14;
}

static int64_t __effect_handler_17(int64_t *__effect_args, int __n_effect_args, int64_t __k, void *__env);
static int64_t __effect_handler_17(int64_t *__effect_args, int __n_effect_args, int64_t __k, void *__env) {
    int64_t k_216 = __k;
    int64_t __t18 = tur_effect_cont_resume((int64_t)(intptr_t)k_216, (int64_t)INT64_C(42));
    return (int64_t)__t18;
}

static void __handle_body_16(void);
static void __handle_body_16(void) {
    tur_current_fiber->result = (int64_t)ask_and_log();
}

static int64_t __dispatch_16(void *__ctx_void, int64_t __k_int, int64_t __resume_val);
static int64_t __dispatch_16(void *__ctx_void, int64_t __k_int, int64_t __resume_val) {
    TurEffectCaptureCtx *__dcap = (TurEffectCaptureCtx *)__ctx_void;
    FiberBlock *__fiber = (FiberBlock *)(intptr_t)__k_int;
    int64_t __r = tur_fiber_block_resume(__fiber, __resume_val);
    if (__fiber->done) { return __fiber->result; }
    if (!__dcap->has_pending_effect) return __r;
    if (strcmp(__dcap->eff_name, "Ask") == 0) {
        return __effect_handler_17(__dcap->eff_args, __dcap->eff_n_args, __k_int, NULL);
    } else {
        /* Phase 19D: bubble up unhandled effect to outer fiber */
        FiberBlock *__outer_f = tur_current_fiber;
        if (__outer_f && __outer_f->eff_ctx) {
            TurEffectCaptureCtx *__outer_cap = (TurEffectCaptureCtx *)__outer_f->eff_ctx;
            __outer_cap->eff_name = __dcap->eff_name;
            int __bun = __dcap->eff_n_args < 8 ? __dcap->eff_n_args : 8;
            for (int __bi = 0; __bi < __bun; __bi++) __outer_cap->eff_args[__bi] = __dcap->eff_args[__bi];
            __outer_cap->eff_n_args = __dcap->eff_n_args;
            __outer_cap->has_pending_effect = true;
            tur_fiber_block_yield(0);
            __outer_cap->has_pending_effect = false;
            return __dispatch_16(__ctx_void, __k_int, __outer_f->arg);
        }
        fprintf(stderr, "dispatch: unhandled effect: %s\n", __dcap->eff_name);
        abort();
    }
    return 0;
}

static void __handle_body_12(void);
static void __handle_body_12(void) {
    TurEffectCaptureCtx __cap_16;
    __cap_16.has_pending_effect = false;
    __cap_16.eff_name = NULL;
    __cap_16.eff_n_args = 0;
    __cap_16.dispatch = __dispatch_16;
    __cap_16.body_env = NULL;
    FiberBlock *__fiber_16 = tur_fiber_block_new(__handle_body_16, 0);
    __fiber_16->eff_ctx = &__cap_16;
    EffectHandlerFrame *__parent_chain_16 = (tur_current_fiber ? (EffectHandlerFrame *)tur_current_fiber->effect_handler_chain : global_effect_handler_chain);
    EffectHandlerFrame __eff_frame_16;
    __eff_frame_16.parent = __parent_chain_16;
    __eff_frame_16.n_cases = 1;
    __eff_frame_16.cases[0].effect_name = "Ask";
    __eff_frame_16.cases[0].handler_fn = NULL;
    __eff_frame_16.cases[0].env = NULL;
    __fiber_16->effect_handler_chain = &__eff_frame_16;
    int64_t __t19 = (int64_t)__dispatch_16(&__cap_16, (int64_t)(intptr_t)__fiber_16, 0);
    if (__fiber_16->done) { free(__fiber_16->stack); free(__fiber_16); }
    tur_current_fiber->result = (int64_t)__t19;
}

static int64_t __dispatch_12(void *__ctx_void, int64_t __k_int, int64_t __resume_val);
static int64_t __dispatch_12(void *__ctx_void, int64_t __k_int, int64_t __resume_val) {
    TurEffectCaptureCtx *__dcap = (TurEffectCaptureCtx *)__ctx_void;
    FiberBlock *__fiber = (FiberBlock *)(intptr_t)__k_int;
    int64_t __r = tur_fiber_block_resume(__fiber, __resume_val);
    if (__fiber->done) { return __fiber->result; }
    if (!__dcap->has_pending_effect) return __r;
    if (strcmp(__dcap->eff_name, "Log") == 0) {
        return __effect_handler_13(__dcap->eff_args, __dcap->eff_n_args, __k_int, NULL);
    } else {
        /* Phase 19D: bubble up unhandled effect to outer fiber */
        FiberBlock *__outer_f = tur_current_fiber;
        if (__outer_f && __outer_f->eff_ctx) {
            TurEffectCaptureCtx *__outer_cap = (TurEffectCaptureCtx *)__outer_f->eff_ctx;
            __outer_cap->eff_name = __dcap->eff_name;
            int __bun = __dcap->eff_n_args < 8 ? __dcap->eff_n_args : 8;
            for (int __bi = 0; __bi < __bun; __bi++) __outer_cap->eff_args[__bi] = __dcap->eff_args[__bi];
            __outer_cap->eff_n_args = __dcap->eff_n_args;
            __outer_cap->has_pending_effect = true;
            tur_fiber_block_yield(0);
            __outer_cap->has_pending_effect = false;
            return __dispatch_12(__ctx_void, __k_int, __outer_f->arg);
        }
        fprintf(stderr, "dispatch: unhandled effect: %s\n", __dcap->eff_name);
        abort();
    }
    return 0;
}

int main() {
        TurEffectCaptureCtx __cap_6;
        __cap_6.has_pending_effect = false;
        __cap_6.eff_name = NULL;
        __cap_6.eff_n_args = 0;
        __cap_6.dispatch = __dispatch_6;
        __cap_6.body_env = NULL;
        FiberBlock *__fiber_6 = tur_fiber_block_new(__handle_body_6, 0);
        __fiber_6->eff_ctx = &__cap_6;
        EffectHandlerFrame *__parent_chain_6 = (tur_current_fiber ? (EffectHandlerFrame *)tur_current_fiber->effect_handler_chain : global_effect_handler_chain);
        EffectHandlerFrame __eff_frame_6;
        __eff_frame_6.parent = __parent_chain_6;
        __eff_frame_6.n_cases = 1;
        __eff_frame_6.cases[0].effect_name = "Log";
        __eff_frame_6.cases[0].handler_fn = NULL;
        __eff_frame_6.cases[0].env = NULL;
        __fiber_6->effect_handler_chain = &__eff_frame_6;
        int64_t __t11 = (int64_t)__dispatch_6(&__cap_6, (int64_t)(intptr_t)__fiber_6, 0);
        if (__fiber_6->done) { free(__fiber_6->stack); free(__fiber_6); }
        {
            TurEffectCaptureCtx __cap_12;
            __cap_12.has_pending_effect = false;
            __cap_12.eff_name = NULL;
            __cap_12.eff_n_args = 0;
            __cap_12.dispatch = __dispatch_12;
            __cap_12.body_env = NULL;
            FiberBlock *__fiber_12 = tur_fiber_block_new(__handle_body_12, 0);
            __fiber_12->eff_ctx = &__cap_12;
            EffectHandlerFrame *__parent_chain_12 = (tur_current_fiber ? (EffectHandlerFrame *)tur_current_fiber->effect_handler_chain : global_effect_handler_chain);
            EffectHandlerFrame __eff_frame_12;
            __eff_frame_12.parent = __parent_chain_12;
            __eff_frame_12.n_cases = 1;
            __eff_frame_12.cases[0].effect_name = "Log";
            __eff_frame_12.cases[0].handler_fn = NULL;
            __eff_frame_12.cases[0].env = NULL;
            __fiber_12->effect_handler_chain = &__eff_frame_12;
            int64_t __t20 = (int64_t)__dispatch_12(&__cap_12, (int64_t)(intptr_t)__fiber_12, 0);
            if (__fiber_12->done) { free(__fiber_12->stack); free(__fiber_12); }
            int64_t result_219 = __t20;
            (void)result_219;
            printf("%lld\n", (long long)(result_219));
        }
        printf("%lld\n", (long long)(add(INT64_C(3), INT64_C(4))));
        int64_t __t21;
        __t21 = INT64_C(0);
        return (int)__t21;
}


