/* generated by tur (phase 2) */
#pragma GCC diagnostic ignored "-Wunused-function"
#pragma GCC diagnostic ignored "-Wunused-variable"
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <setjmp.h>
#include <pthread.h>
#define _XOPEN_SOURCE 700
#include <ucontext.h>
#undef _XOPEN_SOURCE
extern void *malloc(size_t);
extern void *calloc(size_t, size_t);
extern void free(void *);
extern void abort(void);
extern void *memset(void *, int, size_t);
extern void *memmove(void *, const void *, size_t);
extern int strcmp(const char *, const char *);

#define TUR_TEST_REGISTRY_MAX 1024
typedef int64_t (*tur_test_callback_t)(void);
static const char *tur_test_registry_names[TUR_TEST_REGISTRY_MAX];
static tur_test_callback_t tur_test_registry_fns[TUR_TEST_REGISTRY_MAX];
static int64_t tur_test_registry_count = 0;

int64_t tur_test_register(const char *name, void *test_fn) {
    if (!test_fn) return 0;
    if (tur_test_registry_count >= TUR_TEST_REGISTRY_MAX) return 0;
    tur_test_registry_names[tur_test_registry_count] = name ? name : "<unnamed>";
    tur_test_registry_fns[tur_test_registry_count] = (tur_test_callback_t)test_fn;
    tur_test_registry_count++;
    return 1;
}

int64_t tur_test_run_all(void) {
    int64_t passed = 0;
    int64_t failed = 0;
    for (int64_t i = 0; i < tur_test_registry_count; i++) {
        tur_test_callback_t fn = tur_test_registry_fns[i];
        int64_t rc = fn ? fn() : 0;
        if (rc == 1) {
            putchar('.');
            putchar('\n');
            passed++;
        } else {
            putchar('F');
            putchar('\n');
            printf("%s\n", tur_test_registry_names[i]);
            failed++;
        }
    }
    printf("summary: %lld passed, %lld failed\n",
           (long long)passed, (long long)failed);
    return failed == 0 ? 0 : 1;
}

/* tur_frame - phase 4 v1 lowering (from runtime.h) */
typedef void (*defer_fn_t)(void *env);
#define TUR_FRAME_MAX_DEFERS 32

typedef struct tur_frame {
    defer_fn_t defers[TUR_FRAME_MAX_DEFERS];
    void *envs[TUR_FRAME_MAX_DEFERS];
    int n;
    struct tur_frame *parent;
    bool may_capture;
} tur_frame;

static inline void tur_frame_init(tur_frame *f, tur_frame *parent) {
    f->n = 0; f->parent = parent; f->may_capture = false;
}
static inline int tur_frame_push_defer(tur_frame *f, defer_fn_t thunk, void *env) {
    if (f->n >= TUR_FRAME_MAX_DEFERS) return -1;
    f->defers[f->n] = thunk;
    f->envs[f->n] = env;
    f->n++;
    return 0;
}
static void tur_frame_fire_lifo(tur_frame *f) {
    for (int i = f->n - 1; i >= 0; i--) f->defers[i](f->envs[i]);
    f->n = 0;
}
static void tur_frame_fire_chain(tur_frame *f) {
    tur_frame *frames[64];
    int n_frames = 0;
    for (tur_frame *cur = f; cur != NULL && n_frames < 64; cur = cur->parent) {
        frames[n_frames++] = cur;
    }
    for (int i = n_frames - 1; i >= 0; i--) {
        tur_frame_fire_lifo(frames[i]);
    }
}

/* Exception handling - Phase 17 */
typedef struct tur_exception tur_exception;

struct tur_exception {
    int payload_type;      /* TypeKind enum value */
    void *payload;         /* The exception payload */
    int line;              /* Line where thrown */
    const char *file;      /* File where thrown */
    tur_exception *cause;  /* Chained exception */
};

typedef struct ExceptionHandler ExceptionHandler;
struct ExceptionHandler {
    jmp_buf jmp_buf;
    int active;
    tur_exception *caught;
    ExceptionHandler *parent;
};

static ExceptionHandler *global_handler_chain = NULL;

ExceptionHandler *exn_push_handler(void) {
    ExceptionHandler *h = (ExceptionHandler *)malloc(sizeof(ExceptionHandler));
    if (!h) { fprintf(stderr, "exn: out of memory\n"); abort(); }
    h->active = 1;
    h->caught = NULL;
    h->parent = global_handler_chain;
    global_handler_chain = h;
    return h;
}

ExceptionHandler *exn_pop_handler(void) {
    ExceptionHandler *old = global_handler_chain;
    if (old) global_handler_chain = old->parent;
    return old;
}

void tur_exception_free(tur_exception *exn) {
    if (!exn) return;
    if (exn->cause) { tur_exception_free(exn->cause); }
    /* Only free heap-allocated payloads (int=3, bool=2). */
    /* cstr/ptr payloads point to literals or external memory, not owned. */
    if (exn->payload_type == 3 || exn->payload_type == 2) {
        free(exn->payload);
    }
    free(exn);
}

bool tur_exception_matches(tur_exception *exn, int expected_type) {
    if (!exn) return false;
    if (exn->payload_type == expected_type) return true;
    if (expected_type == 1) return true;  /* TY_NIL = 1 = catch-all */
    return false;
}

void tur_throw(int payload_type, void *payload, int line, const char *file) {
    tur_exception *exn = (tur_exception *)malloc(sizeof(tur_exception));
    if (!exn) { abort(); }
    exn->payload_type = payload_type;
    exn->payload = payload;
    exn->line = line;
    exn->file = file;
    exn->cause = NULL;
    ExceptionHandler *h = global_handler_chain;
    if (h) {
        if (h->caught) tur_exception_free(h->caught);
        h->caught = exn;
        h->active = 0;
        longjmp(h->jmp_buf, 1);
    } else {
        fprintf(stderr, "Uncaught exception thrown at %s:%d\n", file ? file : "<unknown>", line);
        tur_exception_free(exn);
        abort();
    }
}

/* Phase R2: tur_panic */
static int tur_panic_in_progress = 0;
static tur_frame *global_panic_frame = NULL;
static void tur_panic_set_frame(tur_frame *f) {
    global_panic_frame = f;
}
static void tur_panic(const char *msg) {
    if (tur_panic_in_progress) {
        fprintf(stderr, "double panic: aborting\n");
        abort();
    }
    tur_panic_in_progress = 1;
    fprintf(stderr, "panic: %s\n", msg ? msg : "(no message)");
    if (global_panic_frame) {
        tur_frame_fire_chain(global_panic_frame);
    }
    abort();
}

/* Phase 19: Algebraic effect handler chain */
typedef struct { bool consumed; void *origin_fiber; } TurContK;

typedef struct EffectHandlerCase EffectHandlerCase;
struct EffectHandlerCase {
    const char *effect_name;
    int64_t (*handler_fn)(int64_t *args, int n_args, int64_t k, void *env);
    void *env;
};

typedef struct EffectHandlerFrame EffectHandlerFrame;
struct EffectHandlerFrame {
    struct EffectHandlerFrame *parent;
    int n_cases;
    EffectHandlerCase cases[8];
};

/* Phase T21: FiberBlock */
#ifdef __clang__
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
#endif
typedef struct FiberBlock FiberBlock;
struct FiberBlock {
    ucontext_t ctx;
    ucontext_t caller_ctx;
    char *stack;
    size_t stack_size;
    int done;
    int parked; /* Phase T21: scheduler park/unpark */
    int64_t result;
    int64_t arg;
    void *handler_chain;
    void (*entry_fn)(void);
    void *fiber_local; /* Phase T21: fiber-local storage */
};

static __thread FiberBlock *tur_current_fiber = NULL;

static void tur_fiber_shim(uint32_t hi, uint32_t lo) {
    FiberBlock *f = (FiberBlock *)(((uintptr_t)hi << 32) | (uintptr_t)(uint32_t)lo);
    f->entry_fn();
    f->done = 1;
    swapcontext(&f->ctx, &f->caller_ctx);
    abort();
}

static FiberBlock *tur_fiber_block_new(void (*fn)(void), size_t stack_size) {
    if (!stack_size) stack_size = 1024 * 1024;
    FiberBlock *f = (FiberBlock *)calloc(1, sizeof(FiberBlock));
    if (!f) { fprintf(stderr, "fiber: oom\n"); abort(); }
    f->stack = (char *)malloc(stack_size);
    if (!f->stack) { free(f); abort(); }
    f->stack_size = stack_size; f->entry_fn = fn; f->done = 0;
    getcontext(&f->ctx);
    f->ctx.uc_stack.ss_sp = f->stack;
    f->ctx.uc_stack.ss_size = stack_size;
    f->ctx.uc_link = NULL;
    uintptr_t _fp = (uintptr_t)f;
    uint32_t _hi = (uint32_t)(_fp >> 32);
    uint32_t _lo = (uint32_t)(_fp & 0xFFFFFFFFU);
    makecontext(&f->ctx, (void(*)(void))tur_fiber_shim, 2, _hi, _lo);
    return f;
}

static int64_t tur_fiber_block_resume(FiberBlock *f, int64_t arg) {
    if (!f || f->done) return f ? f->result : 0;
    FiberBlock *_prev = tur_current_fiber;
    tur_current_fiber = f;
    f->arg = arg;
    swapcontext(&f->caller_ctx, &f->ctx);
    tur_current_fiber = _prev;
    return f->result;
}

static void tur_fiber_block_yield(int64_t value) {
    FiberBlock *f = tur_current_fiber;
    if (!f) { fprintf(stderr, "fiber-yield: not in fiber\n"); abort(); }
    f->result = value;
    swapcontext(&f->ctx, &f->caller_ctx);
}

typedef struct FiberLocalEntry FiberLocalEntry;
struct FiberLocalEntry {
    int64_t key;
    int64_t value;
    FiberLocalEntry *next;
};

static void tur_fiber_local_free(FiberBlock *f) {
    FiberLocalEntry *e = (FiberLocalEntry *)f->fiber_local;
    while (e) { FiberLocalEntry *n = e->next; free(e); e = n; }
}

static int64_t tur_fiber_local_get(FiberBlock *f, int64_t key) {
    FiberLocalEntry *e = (FiberLocalEntry *)f->fiber_local;
    while (e) { if (e->key == key) return e->value; e = e->next; }
    return 0;
}

static void tur_fiber_local_set(FiberBlock *f, int64_t key, int64_t value) {
    FiberLocalEntry *e = (FiberLocalEntry *)f->fiber_local;
    while (e) { if (e->key == key) { e->value = value; return; } e = e->next; }
    FiberLocalEntry *n = (FiberLocalEntry *)malloc(sizeof(FiberLocalEntry));
    if (!n) { fprintf(stderr, "fiber-local: oom\n"); abort(); }
    n->key = key; n->value = value;
    n->next = (FiberLocalEntry *)f->fiber_local;
    f->fiber_local = (void *)n;
}

static void tur_fiber_block_free(FiberBlock *f) {
    if (!f) return;
    tur_fiber_local_free(f);
    free(f->stack); free(f);
}

typedef struct TurScheduler TurScheduler;
struct TurScheduler {
    FiberBlock **run_queue;
    int64_t run_queue_cap;
    int64_t run_queue_len;
    int64_t run_queue_head;
    int64_t run_queue_tail;
    FiberBlock *current_fiber;
    bool running;
};

static TurScheduler *tur_scheduler = NULL;

static TurScheduler *tur_scheduler_new(void) {
    TurScheduler *s = (TurScheduler *)calloc(1, sizeof(TurScheduler));
    if (!s) { fprintf(stderr, "scheduler: oom\n"); abort(); }
    s->run_queue_cap = 64;
    s->run_queue = (FiberBlock **)malloc(sizeof(FiberBlock *) * (size_t)s->run_queue_cap);
    if (!s->run_queue) { free(s); fprintf(stderr, "scheduler: queue oom\n"); abort(); }
    s->run_queue_len = 0;
    s->run_queue_head = 0;
    s->run_queue_tail = 0;
    s->current_fiber = NULL;
    s->running = false;
    return s;
}

static TurScheduler *tur_scheduler_current(void) {
    return tur_scheduler;
}

static void tur_scheduler_enqueue(TurScheduler *s, FiberBlock *f) {
    if (s->run_queue_len >= s->run_queue_cap) {
        int64_t new_cap = s->run_queue_cap * 2;
        FiberBlock **new_q = (FiberBlock **)malloc(sizeof(FiberBlock *) * (size_t)new_cap);
        if (!new_q) { fprintf(stderr, "scheduler: grow oom\n"); abort(); }
        for (int64_t i = 0; i < s->run_queue_len; i++)
            new_q[i] = s->run_queue[(s->run_queue_head + i) % s->run_queue_cap];
        free(s->run_queue);
        s->run_queue = new_q;
        s->run_queue_cap = new_cap;
        s->run_queue_head = 0;
        s->run_queue_tail = s->run_queue_len;
    }
    s->run_queue[s->run_queue_tail] = f;
    s->run_queue_tail = (s->run_queue_tail + 1) % s->run_queue_cap;
    s->run_queue_len++;
}

static FiberBlock *tur_scheduler_dequeue(TurScheduler *s) {
    if (s->run_queue_len == 0) return NULL;
    FiberBlock *f = s->run_queue[s->run_queue_head];
    s->run_queue_head = (s->run_queue_head + 1) % s->run_queue_cap;
    s->run_queue_len--;
    return f;
}

static void tur_scheduler_spawn(TurScheduler *s, FiberBlock *f) {
    tur_scheduler_enqueue(s, f);
}

static void tur_scheduler_run(TurScheduler *s) {
    s->running = true;
    while (s->running) {
        FiberBlock *f = tur_scheduler_dequeue(s);
        if (!f) { break; }
        s->current_fiber = f;
        tur_fiber_block_resume(f, 0);
        s->current_fiber = NULL;
        if (!f->done && !f->parked) tur_scheduler_enqueue(s, f);
    }
    s->running = false;
}

static void tur_scheduler_run_to_completion(TurScheduler *s) {
    s->running = true;
    while (s->run_queue_len > 0 && s->running) {
        FiberBlock *f = tur_scheduler_dequeue(s);
        if (f) {
            s->current_fiber = f;
            tur_fiber_block_resume(f, 0);
            s->current_fiber = NULL;
            if (!f->done && !f->parked) tur_scheduler_enqueue(s, f);
        }
    }
    s->running = false;
}

static void tur_scheduler_yield(void) {
    tur_fiber_block_yield(0);
}

static void tur_scheduler_park(void) {
    if (tur_current_fiber) tur_current_fiber->parked = 1;
    tur_fiber_block_yield(0);
}

static void tur_scheduler_unpark(FiberBlock *f) {
    if (!f) return;
    f->parked = 0;
    if (tur_scheduler) tur_scheduler_enqueue(tur_scheduler, f);
}

#ifdef __clang__
#pragma clang diagnostic pop
#endif

/* Phase T21-F: async/await runtime */
typedef struct TurAsyncTask TurAsyncTask;
struct TurAsyncTask {
    pthread_mutex_t lock;
    pthread_cond_t  ready;
    int64_t         value;
    int             done;
};

typedef struct { TurAsyncTask *cell; int64_t (*fn)(void *env); void *env; } TurAsyncArg;

static void *tur_async_trampoline(void *raw) {
    TurAsyncArg *a = (TurAsyncArg *)raw;
    int64_t result = a->fn(a->env);
    pthread_mutex_lock(&a->cell->lock);
    a->cell->value = result;
    a->cell->done  = 1;
    pthread_cond_broadcast(&a->cell->ready);
    pthread_mutex_unlock(&a->cell->lock);
    free(a);
    return NULL;
}

static TurAsyncTask *tur_async_call(int64_t (*fn)(void *env), void *env) {
    TurAsyncTask *cell = (TurAsyncTask *)malloc(sizeof(TurAsyncTask));
    if (!cell) { fprintf(stderr, "async: oom\n"); abort(); }
    pthread_mutex_init(&cell->lock, NULL);
    pthread_cond_init(&cell->ready, NULL);
    cell->value = 0; cell->done = 0;
    TurAsyncArg *arg = (TurAsyncArg *)malloc(sizeof(TurAsyncArg));
    if (!arg) { free(cell); fprintf(stderr, "async: oom\n"); abort(); }
    arg->cell = cell; arg->fn = fn; arg->env = env;
    pthread_t __tid;
    pthread_create(&__tid, NULL, tur_async_trampoline, arg);
    pthread_detach(__tid);
    return cell;
}

static int64_t tur_await_future(TurAsyncTask *cell) {
    pthread_mutex_lock(&cell->lock);
    while (!cell->done)
        pthread_cond_wait(&cell->ready, &cell->lock);
    int64_t v = cell->value;
    pthread_mutex_unlock(&cell->lock);
    return v;
}

static void tur_async_free(TurAsyncTask *cell) {
    if (!cell) return;
    pthread_mutex_destroy(&cell->lock);
    pthread_cond_destroy(&cell->ready);
    free(cell);
}

static __thread EffectHandlerFrame *global_effect_handler_chain = NULL;

static int64_t tur_effect_perform(const char *name, int64_t *args, int n_args) {
    EffectHandlerFrame *frame =
        (tur_current_fiber && tur_current_fiber->handler_chain)
        ? (EffectHandlerFrame *)tur_current_fiber->handler_chain
        : global_effect_handler_chain;
    while (frame) {
        for (int __i = 0; __i < frame->n_cases; __i++) {
            if (strcmp(frame->cases[__i].effect_name, name) == 0) {
                TurContK __fresh_k = {false, tur_current_fiber};
                return frame->cases[__i].handler_fn(args, n_args, (int64_t)(intptr_t)&__fresh_k, frame->cases[__i].env);
            }
        }
        frame = frame->parent;
    }
    fprintf(stderr, "Unhandled effect: %s\n", name);
    abort();
    return 0;
}

/* rc<T> + weak<T> reference counting - Phase 9 */
/* Phase 10: GC color enum for Bacon-Rajan */
typedef enum { GC_WHITE, GC_GREY, GC_BLACK, GC_PURPLE } GcColor;

typedef void (*RcDropFn)(void *value);

typedef struct RcControlBlock RcControlBlock;

struct RcControlBlock {
    uint64_t strong_count;
    uint64_t weak_count;
    void *value;
    RcDropFn drop_fn;
    uint8_t value_type_kind;
    uint8_t color;           /* GC color */
    bool may_contain_cycles;  /* Hint for GC */
    uint8_t reserved[6];
};

#define RC_FREE_QUEUE_CAPACITY 65536
static RcControlBlock *rc_free_queue[RC_FREE_QUEUE_CAPACITY];
static uint32_t rc_free_queue_count = 0;
static uint32_t rc_free_queue_drain(void);  /* Forward decl */
static void rc_free_queue_push(RcControlBlock *cb);  /* Forward decl */
bool rc_strong_decrement(RcControlBlock *cb);  /* Forward decl */
bool rc_weak_decrement(RcControlBlock *cb);    /* Forward decl */
static void rc_free_queue_push(RcControlBlock *cb) {
    if (!cb) return;
    if (rc_free_queue_count >= RC_FREE_QUEUE_CAPACITY) {
        fprintf(stderr, "rc_free_queue: full, aborting\n");
        abort();
    }
    rc_free_queue[rc_free_queue_count++] = cb;
}

#define GC_GLOBAL_REGISTRY_CAPACITY 4096
static RcControlBlock *gc_all_blocks[GC_GLOBAL_REGISTRY_CAPACITY];
static uint32_t gc_all_blocks_count = 0;

#define GC_SUSPECT_THRESHOLD 128
#define GC_MAX_SUSPECTS 4096

typedef enum { GC_DISABLED, GC_MANUAL, GC_THRESHOLD } GcMode;

static RcControlBlock *gc_suspect_roots[GC_MAX_SUSPECTS];
static uint32_t gc_suspect_count = 0;
static RcControlBlock *gc_grey_queue[GC_MAX_SUSPECTS];
static uint32_t gc_grey_count = 0;
static GcMode gc_mode = GC_DISABLED;
static bool gc_enabled = false;

static void gc_collect(void);  /* Forward decl */

static void gc_set_color(RcControlBlock *cb, GcColor color) {
    if (cb) cb->color = color;
}

static GcColor gc_get_color(RcControlBlock *cb) {
    if (cb) return cb->color;
    return GC_WHITE;
}

static void gc_register_block(RcControlBlock *cb) {
    if (!cb || gc_all_blocks_count >= GC_GLOBAL_REGISTRY_CAPACITY) return;
    gc_all_blocks[gc_all_blocks_count++] = cb;
    cb->color = GC_WHITE;
    cb->may_contain_cycles = true;
}

static void gc_unregister_block(RcControlBlock *cb) {
    if (!cb) return;
    for (uint32_t i = 0; i < gc_all_blocks_count; i++) {
        if (gc_all_blocks[i] == cb) {
            gc_all_blocks[i] = gc_all_blocks[gc_all_blocks_count - 1];
            gc_all_blocks_count--;
            break;
        }
    }
}

static void gc_add_suspect(RcControlBlock *cb) {
    if (!cb || !gc_enabled || gc_mode == GC_DISABLED) return;
    for (uint32_t i = 0; i < gc_suspect_count; i++) {
        if (gc_suspect_roots[i] == cb) return;
    }
    if (gc_suspect_count >= GC_MAX_SUSPECTS) return;
    gc_suspect_roots[gc_suspect_count++] = cb;
    cb->color = GC_PURPLE;
    /* Threshold mode: auto-collect when buffer is full */
    if (gc_mode == GC_THRESHOLD && gc_suspect_count >= GC_SUSPECT_THRESHOLD) {
        gc_collect();
    }
}

static void gc_remove_suspect(RcControlBlock *cb) {
    if (!cb) return;
    for (uint32_t i = 0; i < gc_suspect_count; i++) {
        if (gc_suspect_roots[i] == cb) {
            gc_suspect_roots[i] = gc_suspect_roots[gc_suspect_count - 1];
            gc_suspect_count--;
            return;
        }
    }
}

static void gc_on_strong_decrement(RcControlBlock *cb) {
    if (!cb) return;
    /* Zombie: strong reached 0 but weak refs still exist */
    if (cb->weak_count > 0) {
        gc_add_suspect(cb);
    }
}


/* Phase 9: Deferred free queue drain */
static uint32_t rc_free_queue_drain(void) {
    if (rc_free_queue_count == 0) return 0;
    uint32_t freed = 0;
    while (rc_free_queue_count > 0) {
        RcControlBlock *cb = rc_free_queue[0];
        memmove(rc_free_queue, rc_free_queue + 1,
                (rc_free_queue_count - 1) * sizeof(RcControlBlock *));
        rc_free_queue_count--;
        gc_unregister_block(cb);
        if (cb->value) cb->drop_fn(cb->value);
        free(cb);
        freed++;
    }
    return freed;
}

static void default_rc_drop_fn(void *value) {
    free(value);
}

static void drop_ref_payload(void *value) {
    if (!value) return;
    void *inner = *((void **)value);
    if (inner) free(inner);
    free(value);
}

static void drop_rc_payload(void *value) {
    if (!value) return;
    RcControlBlock *inner = *((RcControlBlock **)value);
    if (inner) { rc_strong_decrement(inner); rc_free_queue_drain(); }
    free(value);
}

static void drop_weak_payload(void *value) {
    if (!value) return;
    RcControlBlock *inner = *((RcControlBlock **)value);
    if (inner) rc_weak_decrement(inner);
    free(value);
}

static RcDropFn default_drop_fn_for_type(int value_type_kind) {
    switch (value_type_kind) {
        case 8: return drop_ref_payload;   /* TY_REF */
        case 9: return drop_rc_payload;    /* TY_RC */
        case 10: return drop_weak_payload; /* TY_WEAK */
        default: return default_rc_drop_fn;
    }
}

RcControlBlock *rc_cb_alloc(size_t value_size, int value_type_kind, RcDropFn drop_fn) {
    size_t total_size = sizeof(RcControlBlock) + value_size;
    RcControlBlock *cb = (RcControlBlock *)malloc(total_size);
    if (!cb) { fprintf(stderr, "rc: out of memory\n"); abort(); }
    cb->strong_count = 1;
    cb->weak_count = 0;
    cb->value = (void *)(cb + 1);
    cb->drop_fn = drop_fn ? drop_fn : default_drop_fn_for_type(value_type_kind);
    cb->value_type_kind = value_type_kind;
    memset(cb->reserved, 0, sizeof(cb->reserved));
    /* Register with GC; primitives (type_kind<=7) cannot form cycles */
    gc_register_block(cb);
    if (value_type_kind <= 7) cb->may_contain_cycles = false;
    return cb;
}

uint64_t rc_strong_increment(RcControlBlock *cb) {
    if (!cb) return 0;
    return ++cb->strong_count;
}

bool rc_strong_decrement(RcControlBlock *cb) {
    if (!cb) return false;
    cb->strong_count--;
    if (cb->strong_count == 0) {
        if (cb->weak_count > 0) {
            gc_on_strong_decrement(cb);
            return false;
        } else {
            rc_free_queue_push(cb);
            return true;
        }
    }
    return false;
}

uint64_t rc_weak_increment(RcControlBlock *cb) {
    if (!cb) return 0;
    return ++cb->weak_count;
}

bool rc_weak_decrement(RcControlBlock *cb) {
    if (!cb) return false;
    cb->weak_count--;
    if (cb->weak_count == 0 && cb->strong_count == 0) {
        gc_unregister_block(cb);
        /* Free zombie value if GC did not already collect it */
        if (cb->value && cb->drop_fn) {
            cb->drop_fn(cb->value);
        }
        free(cb);
        return true;
    }
    return false;
}

uint64_t rc_strong_count(RcControlBlock *cb) {
    if (!cb) return 0;
    return cb->strong_count;
}

uint64_t rc_weak_count(RcControlBlock *cb) {
    if (!cb) return 0;
    return cb->weak_count;
}

bool rc_is_alive(RcControlBlock *cb) {
    if (!cb) return false;
    return cb->strong_count > 0;
}

RcControlBlock *rc_upgrade(RcControlBlock *cb) {
    if (!cb) return NULL;
    if (cb->strong_count > 0) {
        rc_strong_increment(cb);
        return cb;
    }
    return NULL;
}

void *rc_get_value(RcControlBlock *cb) {
    if (!cb) return NULL;
    return cb->value;
}

RcControlBlock *tur_rc_from_ref(void *ref_value, int value_type_kind) {
    if (!ref_value) return NULL;
    RcControlBlock *cb = (RcControlBlock *)malloc(sizeof(RcControlBlock));
    if (!cb) { fprintf(stderr, "rc/from-ref: out of memory\n"); abort(); }
    cb->strong_count = 1;
    cb->weak_count = 0;
    cb->value = ref_value;
    cb->drop_fn = default_drop_fn_for_type(value_type_kind);
    cb->value_type_kind = (uint8_t)value_type_kind;
    cb->color = GC_WHITE;
    cb->may_contain_cycles = true;
    memset(cb->reserved, 0, sizeof(cb->reserved));
    gc_register_block(cb);
    return cb;
}

void *tur_ref_from_rc(RcControlBlock *cb) {
    if (!cb) return NULL;
    if (cb->strong_count != 1 || cb->weak_count != 0) {
        fprintf(stderr, "ref/from-rc requires unique rc (strong_count==1 and weak_count==0), got strong=%llu weak=%llu\n",
                (unsigned long long)cb->strong_count, (unsigned long long)cb->weak_count);
        abort();
    }
    void *value = cb->value;
    cb->value = NULL;
    gc_unregister_block(cb);
    free(cb);
    return value;
}

/* gc (Bacon-Rajan cycle collector - trial deletion) - Phase 10 */
static void gc_mark_phase(void) {
    for (uint32_t i = 0; i < gc_all_blocks_count; i++) {
        gc_all_blocks[i]->color = GC_WHITE;
    }
    for (uint32_t i = 0; i < gc_all_blocks_count; i++) {
        RcControlBlock *cb = gc_all_blocks[i];
        if (cb->strong_count > 0) {
            cb->color = GC_BLACK;
        }
    }
}

static void gc_trial_deletion_phase(void) {
    uint32_t i = 0;
    while (i < gc_suspect_count) {
        RcControlBlock *cb = gc_suspect_roots[i];
        /* If revived or reachable from strong roots, keep */
        if (cb->strong_count > 0 || cb->color == GC_BLACK) {
            cb->color = GC_WHITE;
            i++;
            continue;
        }
        /* WHITE and strong_count == 0: zombie — free value, keep cb for weak refs */
        if (cb->value && cb->drop_fn) {
            cb->drop_fn(cb->value);
            cb->value = NULL;
        }
        /* Unregister from global registry (cb stays alive for weak refs) */
        gc_unregister_block(cb);
        /* Remove from suspect buffer without advancing i */
        gc_suspect_roots[i] = gc_suspect_roots[gc_suspect_count - 1];
        gc_suspect_count--;
    }
}

static void gc_collect(void) {
    if (!gc_enabled || gc_mode == GC_DISABLED) return;
    gc_grey_count = 0;
    gc_mark_phase();
    gc_trial_deletion_phase();
}

static void gc_force(void) {
    gc_collect();
}

static void gc_enable(void) {
    gc_enabled = true;
    /* Default to manual mode when enabled */
    if (gc_mode == GC_DISABLED) gc_mode = GC_MANUAL;
}

static void gc_disable(void) {
    gc_enabled = false;
    gc_mode = GC_DISABLED;
}

static void gc_set_mode(GcMode mode) {
    gc_mode = mode;
}

static bool gc_is_alive(RcControlBlock *cb) {
    if (!cb) return false;
    if (cb->strong_count > 0) return true;
    return (cb->color == GC_BLACK || cb->color == GC_GREY);
}

int main() {
        {
            int64_t x_1 = INT64_C(10);
            (void)x_1;
            {
                void * rm_2 = &x_1;
                (void)rm_2;
                *((int64_t *)rm_2) = INT64_C(99);
            }
            printf("%lld\n", (long long)(x_1));
        }
        int64_t __t0;
        __t0 = INT64_C(0);
        return (int)__t0;
}


