/* generated by tur (phase 2) */
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>

static int64_t __fn_2(void *);
struct __env_4 {int64_t x; };
static int64_t __fn_2(void * __env_p_5) {
        struct __env_4 *__env___env_4 = (struct __env_4 *)__env_p_5;
        return ((__env___env_4->x) + (INT64_C(1)));
}

int main() {
        {
            int64_t x_1 = INT64_C(10);
            (void)x_1;
            {
                struct __env_4 __t0 = {.x = x_1};
                void *__t1 = &__t0;
                void * f_7 = __t1;
                (void)f_7;
                printf("%lld\n", (long long)(__fn_2(f_7)));
            }
        }
        return (int)0;
}


