#!/usr/bin/env bash
# tests/check-r7rs-unicode-sync.sh -- r7rs-lang-plan R10: the Unicode tables
# behind (scheme char) exist twice, generated by tools/gen-r7rs-unicode.py:
# the file-scope C block of stdlib/r7rs/unicode.tur (the compiled back end)
# and src/turi/r7rs_unicode.inc (the interpreter's natives).  They must be
# the same text, or the two back ends answer differently.  This checks the
# two copies against each other, not against the generator, so it does not
# depend on which Unicode version the local Python carries.
set -uo pipefail
cd "$(dirname "$0")/.."
if ! command -v python3 >/dev/null 2>&1; then
    echo "SKIP check-r7rs-unicode-sync: python3 not found"
    exit 0
fi
python3 - <<'PY'
import sys
tur = open("stdlib/r7rs/unicode.tur", encoding="ascii").read()
inc = open("src/turi/r7rs_unicode.inc", encoding="ascii").read()
start = tur.index("```c\n") + 5
end = tur.index("```\n", start)
if tur[start:end] != inc:
    print("FAIL check-r7rs-unicode-sync: stdlib/r7rs/unicode.tur's C block and "
          "src/turi/r7rs_unicode.inc differ -- regenerate both with "
          "python3 tools/gen-r7rs-unicode.py")
    sys.exit(1)
print("PASS check-r7rs-unicode-sync (%d bytes of C, identical)" % len(inc))
PY
