/* generated by tur (phase 2) */
#pragma GCC diagnostic ignored "-Wunused-function"
#pragma GCC diagnostic ignored "-Wunused-variable"
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <setjmp.h>
#include <pthread.h>
#define _XOPEN_SOURCE 700
#include <ucontext.h>
#undef _XOPEN_SOURCE
extern void *malloc(size_t);
extern void *calloc(size_t, size_t);
extern void free(void *);
extern void abort(void);
extern void *memset(void *, int, size_t);
extern void *memmove(void *, const void *, size_t);
extern int strcmp(const char *, const char *);

#define TUR_TEST_REGISTRY_MAX 1024
typedef int64_t (*tur_test_callback_t)(void);
static const char *tur_test_registry_names[TUR_TEST_REGISTRY_MAX];
static tur_test_callback_t tur_test_registry_fns[TUR_TEST_REGISTRY_MAX];
static int64_t tur_test_registry_count = 0;

int64_t tur_test_register(const char *name, void *test_fn) {
    if (!test_fn) return 0;
    if (tur_test_registry_count >= TUR_TEST_REGISTRY_MAX) return 0;
    tur_test_registry_names[tur_test_registry_count] = name ? name : "<unnamed>";
    tur_test_registry_fns[tur_test_registry_count] = (tur_test_callback_t)test_fn;
    tur_test_registry_count++;
    return 1;
}

int64_t tur_test_run_all(void) {
    int64_t passed = 0;
    int64_t failed = 0;
    for (int64_t i = 0; i < tur_test_registry_count; i++) {
        tur_test_callback_t fn = tur_test_registry_fns[i];
        int64_t rc = fn ? fn() : 0;
        if (rc == 1) {
            putchar('.');
            putchar('\n');
            passed++;
        } else {
            putchar('F');
            putchar('\n');
            printf("%s\n", tur_test_registry_names[i]);
            failed++;
        }
    }
    printf("summary: %lld passed, %lld failed\n",
           (long long)passed, (long long)failed);
    return failed == 0 ? 0 : 1;
}

/* tur_frame - phase 4 v1 lowering (from runtime.h) */
typedef void (*defer_fn_t)(void *env);
#define TUR_FRAME_MAX_DEFERS 32

typedef struct tur_frame {
    defer_fn_t defers[TUR_FRAME_MAX_DEFERS];
    void *envs[TUR_FRAME_MAX_DEFERS];
    int n;
    struct tur_frame *parent;
    bool may_capture;
} tur_frame;

static inline void tur_frame_init(tur_frame *f, tur_frame *parent) {
    f->n = 0; f->parent = parent; f->may_capture = false;
}
static inline int tur_frame_push_defer(tur_frame *f, defer_fn_t thunk, void *env) {
    if (f->n >= TUR_FRAME_MAX_DEFERS) return -1;
    f->defers[f->n] = thunk;
    f->envs[f->n] = env;
    f->n++;
    return 0;
}
static void tur_frame_fire_lifo(tur_frame *f) {
    for (int i = f->n - 1; i >= 0; i--) f->defers[i](f->envs[i]);
    f->n = 0;
}
static void tur_frame_fire_chain(tur_frame *f) {
    tur_frame *frames[64];
    int n_frames = 0;
    for (tur_frame *cur = f; cur != NULL && n_frames < 64; cur = cur->parent) {
        frames[n_frames++] = cur;
    }
    for (int i = n_frames - 1; i >= 0; i--) {
        tur_frame_fire_lifo(frames[i]);
    }
}

/* Exception handling - Phase 17 */
typedef struct tur_exception tur_exception;

struct tur_exception {
    int payload_type;      /* TypeKind enum value */
    void *payload;         /* The exception payload */
    int line;              /* Line where thrown */
    const char *file;      /* File where thrown */
    tur_exception *cause;  /* Chained exception */
};

typedef struct ExceptionHandler ExceptionHandler;
struct ExceptionHandler {
    jmp_buf jmp_buf;
    int active;
    tur_exception *caught;
    ExceptionHandler *parent;
};

static ExceptionHandler *global_handler_chain = NULL;

ExceptionHandler *exn_push_handler(void) {
    ExceptionHandler *h = (ExceptionHandler *)malloc(sizeof(ExceptionHandler));
    if (!h) { fprintf(stderr, "exn: out of memory\n"); abort(); }
    h->active = 1;
    h->caught = NULL;
    h->parent = global_handler_chain;
    global_handler_chain = h;
    return h;
}

ExceptionHandler *exn_pop_handler(void) {
    ExceptionHandler *old = global_handler_chain;
    if (old) global_handler_chain = old->parent;
    return old;
}

void tur_exception_free(tur_exception *exn) {
    if (!exn) return;
    if (exn->cause) { tur_exception_free(exn->cause); }
    /* Only free heap-allocated payloads (int=3, bool=2). */
    /* cstr/ptr payloads point to literals or external memory, not owned. */
    if (exn->payload_type == 3 || exn->payload_type == 2) {
        free(exn->payload);
    }
    free(exn);
}

bool tur_exception_matches(tur_exception *exn, int expected_type) {
    if (!exn) return false;
    if (exn->payload_type == expected_type) return true;
    if (expected_type == 1) return true;  /* TY_NIL = 1 = catch-all */
    return false;
}

void tur_throw(int payload_type, void *payload, int line, const char *file) {
    tur_exception *exn = (tur_exception *)malloc(sizeof(tur_exception));
    if (!exn) { abort(); }
    exn->payload_type = payload_type;
    exn->payload = payload;
    exn->line = line;
    exn->file = file;
    exn->cause = NULL;
    ExceptionHandler *h = global_handler_chain;
    if (h) {
        if (h->caught) tur_exception_free(h->caught);
        h->caught = exn;
        h->active = 0;
        longjmp(h->jmp_buf, 1);
    } else {
        fprintf(stderr, "Uncaught exception thrown at %s:%d\n", file ? file : "<unknown>", line);
        tur_exception_free(exn);
        abort();
    }
}

/* Phase R2: tur_panic */
static int tur_panic_in_progress = 0;
static tur_frame *global_panic_frame = NULL;
static void tur_panic_set_frame(tur_frame *f) {
    global_panic_frame = f;
}
static void tur_panic(const char *msg) {
    if (tur_panic_in_progress) {
        fprintf(stderr, "double panic: aborting\n");
        abort();
    }
    tur_panic_in_progress = 1;
    fprintf(stderr, "panic at %s:%d: %s\n", __FILE__, __LINE__, msg ? msg : "(no message)");
    if (global_panic_frame) {
        tur_frame_fire_chain(global_panic_frame);
    }
    abort();
}

/* Phase R5: tur_panic_abort - no unwinding, immediate abort */
static void tur_panic_abort(const char *msg) {
    fprintf(stderr, "panic (no unwind): %s\n", msg ? msg : "(no message)");
    abort();
}

/* Phase R2: tur_panic_with */
typedef struct tur_panic_payload tur_panic_payload;
struct tur_panic_payload {
    int type_tag;
    void *value;
    const char *file;
    int line;
};

static tur_panic_payload *global_panic_payload = NULL;
static jmp_buf global_panic_jmpbuf;
static int global_panic_jmpbuf_valid = 0;

static tur_panic_payload *panic_payload_new(int type_tag, void *payload, const char *file, int line) {
    tur_panic_payload *p = (tur_panic_payload *)malloc(sizeof(tur_panic_payload));
    if (!p) { fprintf(stderr, "panic: oom\n"); abort(); }
    p->type_tag = type_tag; p->value = payload; p->file = file; p->line = line;
    return p;
}

static void panic_payload_free(tur_panic_payload *p) {
    if (p) { free(p->value); free(p); }
}

static void tur_panic_with(int type_tag, void *payload, const char *file, int line) {
    if (tur_panic_in_progress) {
        fprintf(stderr, "double panic: aborting\n");
        free(payload);
        abort();
    }
    tur_panic_in_progress = 1;
    if (global_panic_jmpbuf_valid) {
        global_panic_payload = panic_payload_new(type_tag, payload, file, line);
        longjmp(global_panic_jmpbuf, 1);
    }
    fprintf(stderr, "panic at %s:%d\n", file ? file : "(unknown)", line);
    free(payload);
    abort();
}

static int tur_panic_payload_type(tur_panic_payload *p) {
    return p ? p->type_tag : 0;
}

static void *tur_panic_payload_value(tur_panic_payload *p) {
    return p ? p->value : NULL;
}

static const char *tur_panic_payload_file(tur_panic_payload *p) {
    return p ? p->file : NULL;
}

static int tur_panic_payload_line(tur_panic_payload *p) {
    return p ? p->line : 0;
}

static void *tur_panic_payload_downcast(tur_panic_payload *p, int target_type) {
    if (!p || p->type_tag != target_type) return NULL;
    return p->value;
}

/* Phase R2: catch-unwind/catch-panic-of */
typedef enum { TUR_RESULT_OK, TUR_RESULT_ERR } tur_result_tag;
typedef struct tur_result tur_result;
struct tur_result {
    tur_result_tag tag;
    union { int64_t ok_val; void *ok_ptr; tur_panic_payload *err; } u;
};

typedef void (*tur_thunk_fn)(void *env, tur_result *out);

static bool tur_catch_unwind(tur_thunk_fn thunk, void *env, tur_result *out) {
    if (global_panic_jmpbuf_valid) {
        thunk(env, out);
        return false;
    }
    global_panic_jmpbuf_valid = 1;
    if (setjmp(global_panic_jmpbuf) == 0) {
        thunk(env, out);
        global_panic_jmpbuf_valid = 0;
        if (global_panic_payload) {
            panic_payload_free(global_panic_payload);
            global_panic_payload = NULL;
        }
        return false;
    } else {
        global_panic_jmpbuf_valid = 0;
        out->tag = TUR_RESULT_ERR;
        out->u.err = global_panic_payload;
        global_panic_payload = NULL;
        return true;
    }
}

static bool tur_catch_panic_of(int expected_type, tur_thunk_fn thunk, void *env, tur_result *out) {
    if (global_panic_jmpbuf_valid) {
        thunk(env, out);
        return false;
    }
    global_panic_jmpbuf_valid = 1;
    if (setjmp(global_panic_jmpbuf) == 0) {
        thunk(env, out);
        global_panic_jmpbuf_valid = 0;
        if (global_panic_payload) {
            panic_payload_free(global_panic_payload);
            global_panic_payload = NULL;
        }
        return false;
    } else {
        global_panic_jmpbuf_valid = 0;
        if (global_panic_payload && global_panic_payload->type_tag == expected_type) {
            out->tag = TUR_RESULT_ERR;
            out->u.err = global_panic_payload;
            global_panic_payload = NULL;
            return true;
        } else {
        if (global_panic_payload) {
            /* Type mismatch - re-panic */
            tur_panic_with(global_panic_payload->type_tag, global_panic_payload->value,
                           global_panic_payload->file, global_panic_payload->line);
        }
        return false;
        }
    }
}

/* Phase 19: Algebraic effect handler chain */
typedef struct { bool consumed; void *origin_fiber; } TurContK;

typedef struct EffectHandlerCase EffectHandlerCase;
struct EffectHandlerCase {
    const char *effect_name;
    int64_t (*handler_fn)(int64_t *args, int n_args, int64_t k, void *env);
    void *env;
};

typedef struct EffectHandlerFrame EffectHandlerFrame;
struct EffectHandlerFrame {
    struct EffectHandlerFrame *parent;
    int n_cases;
    EffectHandlerCase cases[8];
};

/* Phase T21: FiberBlock */
#ifdef __clang__
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
#endif
typedef struct FiberBlock FiberBlock;
struct FiberBlock {
    ucontext_t ctx;
    ucontext_t caller_ctx;
    char *stack;
    size_t stack_size;
    int done;
    int parked; /* Phase T21: scheduler park/unpark */
    int64_t result;
    int64_t arg;
    void *effect_handler_chain; /* Phase P19-8: per-fiber effect handler chain */
    void (*entry_fn)(void);
    void *fiber_local; /* Phase T21: fiber-local storage */
    void *task_group; /* Parent TaskGroup for cancellation */
    bool cancelled; /* Set when parent TaskGroup is cancelled */
};

static __thread FiberBlock *tur_current_fiber = NULL;
static __thread bool tur_fiber_cancelled_flag = false;

static void tur_task_group_notify_done(void *task_group);

static void tur_fiber_shim(uint32_t hi, uint32_t lo) {
    FiberBlock *f = (FiberBlock *)(((uintptr_t)hi << 32) | (uintptr_t)(uint32_t)lo);
    f->entry_fn();
    f->done = 1;
    tur_task_group_notify_done(f->task_group);
    swapcontext(&f->ctx, &f->caller_ctx);
    abort();
}

static FiberBlock *tur_fiber_block_new(void (*fn)(void), size_t stack_size) {
    if (!stack_size) stack_size = 1024 * 1024;
    FiberBlock *f = (FiberBlock *)calloc(1, sizeof(FiberBlock));
    if (!f) { fprintf(stderr, "fiber: oom\n"); abort(); }
    f->stack = (char *)malloc(stack_size);
    if (!f->stack) { free(f); abort(); }
    f->stack_size = stack_size; f->entry_fn = fn; f->done = 0;
    getcontext(&f->ctx);
    f->ctx.uc_stack.ss_sp = f->stack;
    f->ctx.uc_stack.ss_size = stack_size;
    f->ctx.uc_link = NULL;
    uintptr_t _fp = (uintptr_t)f;
    uint32_t _hi = (uint32_t)(_fp >> 32);
    uint32_t _lo = (uint32_t)(_fp & 0xFFFFFFFFU);
    makecontext(&f->ctx, (void(*)(void))tur_fiber_shim, 2, _hi, _lo);
    return f;
}

static int64_t tur_fiber_block_resume(FiberBlock *f, int64_t arg) {
    if (!f || f->done) return f ? f->result : 0;
    if (f->cancelled) { f->done = 1; return 0; }
    if (f->task_group) {
        typedef struct TaskGroupBlock { bool cancelled; } TaskGroupBlock;
        if (((TaskGroupBlock *)f->task_group)->cancelled) { f->cancelled = 1; f->done = 1; return 0; }
    }
    FiberBlock *_prev = tur_current_fiber;
    tur_current_fiber = f;
    f->arg = arg;
    swapcontext(&f->caller_ctx, &f->ctx);
    tur_current_fiber = _prev;
    return f->result;
}

static void tur_fiber_block_yield(int64_t value) {
    FiberBlock *f = tur_current_fiber;
    if (!f) { fprintf(stderr, "fiber-yield: not in fiber\n"); abort(); }
    f->result = value;
    swapcontext(&f->ctx, &f->caller_ctx);
}

typedef struct FiberLocalEntry FiberLocalEntry;
struct FiberLocalEntry {
    int64_t key;
    int64_t value;
    FiberLocalEntry *next;
};

static void tur_fiber_local_free(FiberBlock *f) {
    FiberLocalEntry *e = (FiberLocalEntry *)f->fiber_local;
    while (e) { FiberLocalEntry *n = e->next; free(e); e = n; }
}

static int64_t tur_fiber_local_get(FiberBlock *f, int64_t key) {
    FiberLocalEntry *e = (FiberLocalEntry *)f->fiber_local;
    while (e) { if (e->key == key) return e->value; e = e->next; }
    return 0;
}

static void tur_fiber_local_set(FiberBlock *f, int64_t key, int64_t value) {
    FiberLocalEntry *e = (FiberLocalEntry *)f->fiber_local;
    while (e) { if (e->key == key) { e->value = value; return; } e = e->next; }
    FiberLocalEntry *n = (FiberLocalEntry *)malloc(sizeof(FiberLocalEntry));
    if (!n) { fprintf(stderr, "fiber-local: oom\n"); abort(); }
    n->key = key; n->value = value;
    n->next = (FiberLocalEntry *)f->fiber_local;
    f->fiber_local = (void *)n;
}

static void tur_fiber_block_free(FiberBlock *f) {
    if (!f) return;
    tur_fiber_local_free(f);
    free(f->stack); free(f);
}

static bool tur_fiber_cancelled(void) {
    return tur_fiber_cancelled_flag;
}

static void tur_fiber_set_cancelled(bool c) {
    tur_fiber_cancelled_flag = c;
}

static void tur_task_group_notify_done(void *task_group) {
    if (!task_group) return;
    typedef struct TaskGroupBlock {
        pthread_mutex_t lock;
        pthread_cond_t done_cond;
        int64_t task_count;
        int64_t completed_count;
        bool cancelled;
        bool done;
        pthread_t owner_thread;
    } TaskGroupBlock;
    TaskGroupBlock *g = (TaskGroupBlock *)task_group;
    pthread_mutex_lock(&g->lock);
    g->completed_count++;
    if (g->completed_count >= g->task_count) {
        g->done = true;
        pthread_cond_broadcast(&g->done_cond);
    }
    pthread_mutex_unlock(&g->lock);
}

typedef struct TurScheduler TurScheduler;
struct TurScheduler {
    FiberBlock **run_queue;
    int64_t run_queue_cap;
    int64_t run_queue_len;
    int64_t run_queue_head;
    int64_t run_queue_tail;
    FiberBlock *current_fiber;
    bool running;
};

static TurScheduler *tur_scheduler = NULL;

static TurScheduler *tur_scheduler_new(void) {
    TurScheduler *s = (TurScheduler *)calloc(1, sizeof(TurScheduler));
    if (!s) { fprintf(stderr, "scheduler: oom\n"); abort(); }
    s->run_queue_cap = 64;
    s->run_queue = (FiberBlock **)malloc(sizeof(FiberBlock *) * (size_t)s->run_queue_cap);
    if (!s->run_queue) { free(s); fprintf(stderr, "scheduler: queue oom\n"); abort(); }
    s->run_queue_len = 0;
    s->run_queue_head = 0;
    s->run_queue_tail = 0;
    s->current_fiber = NULL;
    s->running = false;
    return s;
}

static TurScheduler *tur_scheduler_current(void) {
    return tur_scheduler;
}

static void tur_scheduler_enqueue(TurScheduler *s, FiberBlock *f) {
    if (s->run_queue_len >= s->run_queue_cap) {
        int64_t new_cap = s->run_queue_cap * 2;
        FiberBlock **new_q = (FiberBlock **)malloc(sizeof(FiberBlock *) * (size_t)new_cap);
        if (!new_q) { fprintf(stderr, "scheduler: grow oom\n"); abort(); }
        for (int64_t i = 0; i < s->run_queue_len; i++)
            new_q[i] = s->run_queue[(s->run_queue_head + i) % s->run_queue_cap];
        free(s->run_queue);
        s->run_queue = new_q;
        s->run_queue_cap = new_cap;
        s->run_queue_head = 0;
        s->run_queue_tail = s->run_queue_len;
    }
    s->run_queue[s->run_queue_tail] = f;
    s->run_queue_tail = (s->run_queue_tail + 1) % s->run_queue_cap;
    s->run_queue_len++;
}

static FiberBlock *tur_scheduler_dequeue(TurScheduler *s) {
    if (s->run_queue_len == 0) return NULL;
    FiberBlock *f = s->run_queue[s->run_queue_head];
    s->run_queue_head = (s->run_queue_head + 1) % s->run_queue_cap;
    s->run_queue_len--;
    return f;
}

static void tur_scheduler_spawn(TurScheduler *s, FiberBlock *f) {
    tur_scheduler_enqueue(s, f);
}

static void tur_scheduler_run(TurScheduler *s) {
    s->running = true;
    while (s->running) {
        FiberBlock *f = tur_scheduler_dequeue(s);
        if (!f) { break; }
        s->current_fiber = f;
        tur_fiber_block_resume(f, 0);
        s->current_fiber = NULL;
        if (!f->done && !f->parked) tur_scheduler_enqueue(s, f);
    }
    s->running = false;
}

static void tur_scheduler_run_to_completion(TurScheduler *s) {
    s->running = true;
    while (s->run_queue_len > 0 && s->running) {
        FiberBlock *f = tur_scheduler_dequeue(s);
        if (f) {
            s->current_fiber = f;
            tur_fiber_block_resume(f, 0);
            s->current_fiber = NULL;
            if (!f->done && !f->parked) tur_scheduler_enqueue(s, f);
        }
    }
    s->running = false;
}

static void tur_scheduler_yield(void) {
    tur_fiber_block_yield(0);
}

static void tur_scheduler_park(void) {
    if (tur_current_fiber) tur_current_fiber->parked = 1;
    tur_fiber_block_yield(0);
}

static void tur_scheduler_unpark(FiberBlock *f) {
    if (!f) return;
    f->parked = 0;
    if (tur_scheduler) tur_scheduler_enqueue(tur_scheduler, f);
}

typedef struct TurTimeout TurTimeout;
struct TurTimeout {
    int64_t ms;
    void (*callback)(void *arg);
    void *arg;
    pthread_t thread;
    TurTimeout *next;
};

static TurTimeout *tur_timeout_list = NULL;
static pthread_mutex_t tur_timeout_lock = PTHREAD_MUTEX_INITIALIZER;

static void *tur_timeout_thread(void *raw) {
    TurTimeout *t = (TurTimeout *)raw;
    if (t->ms > 0) {
        struct timespec ts;
        ts.tv_sec = t->ms / 1000;
        ts.tv_nsec = (t->ms % 1000) * 1000000L;
        nanosleep(&ts, NULL);
    }
    t->callback(t->arg);
    pthread_mutex_lock(&tur_timeout_lock);
    TurTimeout *prev = NULL;
    TurTimeout *curr = tur_timeout_list;
    while (curr && curr != t) { prev = curr; curr = curr->next; }
    if (prev) prev->next = t->next;
    else tur_timeout_list = t->next;
    pthread_mutex_unlock(&tur_timeout_lock);
    free(t);
    return NULL;
}

static void tur_scheduler_timeout(int64_t ms, void (*callback)(void *arg), void *arg) {
    TurTimeout *t = (TurTimeout *)malloc(sizeof(TurTimeout));
    if (!t) { fprintf(stderr, "timeout: oom\n"); abort(); }
    t->ms = ms;
    t->callback = callback;
    t->arg = arg;
    t->next = NULL;
    pthread_mutex_lock(&tur_timeout_lock);
    t->next = tur_timeout_list;
    tur_timeout_list = t;
    pthread_mutex_unlock(&tur_timeout_lock);
    pthread_attr_t attr;
    pthread_attr_init(&attr);
    pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_DETACHED);
    pthread_t tid;
    pthread_create(&tid, &attr, tur_timeout_thread, t);
    pthread_attr_destroy(&attr);
}

#ifdef __clang__
#pragma clang diagnostic pop
#endif

static void tur_scheduler_run_one(TurScheduler *s) {
    FiberBlock *f = tur_scheduler_dequeue(s);
    if (!f) { return; }
    s->current_fiber = f;
    tur_fiber_block_resume(f, 0);
    s->current_fiber = NULL;
    if (!f->done && !f->parked) tur_scheduler_enqueue(s, f);
}

/* Phase T21-F: async/await runtime - fiber-based Futures */
typedef enum { FUTURE_PENDING, FUTURE_FULFILLED, FUTURE_REJECTED } TurFutureStatus;

typedef struct TurFuture TurFuture;
struct TurFuture {
    TurFutureStatus status;
    int64_t value;
    const char *error;  /* NULL if no error */
    FiberBlock *fiber;  /* The fiber running the async task */
    struct { void (*fn)(TurFuture *, int64_t); void *env; } on_complete;
};

/* Create a new pending future */
static TurFuture *tur_future_new(void) {
    TurFuture *f = (TurFuture *)calloc(1, sizeof(TurFuture));
    if (!f) { fprintf(stderr, "future: oom\n"); abort(); }
    f->status = FUTURE_PENDING;
    f->fiber = NULL;
    f->on_complete.fn = NULL;
    return f;
}

/* Fulfill a future with a value */
static void tur_future_fulfill(TurFuture *f, int64_t value) {
    if (!f || f->status != FUTURE_PENDING) return;
    f->status = FUTURE_FULFILLED;
    f->value = value;
    if (f->on_complete.fn) f->on_complete.fn(f, value);
}

/* Reject a future with an error message */
static void tur_future_reject(TurFuture *f, const char *error) {
    if (!f || f->status != FUTURE_PENDING) return;
    f->status = FUTURE_REJECTED;
    f->error = error;
}

/* Check if future is done (fulfilled or rejected) */
static int tur_future_done(TurFuture *f) {
    return f && (f->status == FUTURE_FULFILLED || f->status == FUTURE_REJECTED);
}

/* Get future value (only valid if fulfilled) */
static int64_t tur_future_get(TurFuture *f) {
    if (!f || f->status != FUTURE_FULFILLED) return 0;
    return f->value;
}

static TurFuture *tur_async_fiber(int64_t (*fn)(void)) {
    TurFuture *future = tur_future_new();
    if (!tur_scheduler) {
        /* AW-005: Initialize scheduler on first use */
        tur_scheduler = tur_scheduler_new();
    }
    /* AW-005: Simplified v1 - call function directly and fulfill */
    int64_t result = fn();
    tur_future_fulfill(future, result);
    return future;
}

/* AW-004: await lowering with shift + scheduler callback */
static int64_t tur_await_future(TurFuture *f) {
    if (!f) { fprintf(stderr, "await: null future\n"); abort(); }
    if (tur_future_done(f)) {
        if (f->status == FUTURE_REJECTED) {
            fprintf(stderr, "await: future rejected: %s\n", f->error ? f->error : "unknown");
            abort();
        }
        return f->value;
    }
    /* Future not ready */
    if (!tur_current_fiber) {
        /* Not in a fiber - run the scheduler until future is done */
        if (!tur_scheduler) {
            fprintf(stderr, "await: no scheduler and not in fiber\n");
            abort();
        }
        while (!tur_future_done(f)) {
            tur_scheduler_run_one(tur_scheduler);
        }
    } else {
        /* In a fiber - yield and let scheduler resume us */
        /* Register a callback to re-enqueue this fiber when future completes */
        f->on_complete.fn = (void (*)(TurFuture *, int64_t))tur_fiber_block_resume;
        f->on_complete.env = (void *)tur_current_fiber;
        tur_fiber_block_yield(0);
        /* When we resume, the future should be done */
        if (tur_future_done(f) && f->status == FUTURE_REJECTED) {
            fprintf(stderr, "await: future rejected: %s\n", f->error ? f->error : "unknown");
            abort();
        }
        return f->value;
    }
    if (f->status == FUTURE_REJECTED) {
        fprintf(stderr, "await: future rejected: %s\n", f->error ? f->error : "unknown");
        abort();
    }
    return f->value;
}

static void tur_future_free(TurFuture *f) {
    if (!f) return;
    free(f);
}

/* Backward compatibility: TurAsyncTask = TurFuture */
typedef TurFuture TurAsyncTask;

static __thread EffectHandlerFrame *global_effect_handler_chain = NULL;

static int64_t tur_effect_perform(const char *name, int64_t *args, int n_args) {
    EffectHandlerFrame *frame =
        (tur_current_fiber && tur_current_fiber->effect_handler_chain)
        ? (EffectHandlerFrame *)tur_current_fiber->effect_handler_chain
        : global_effect_handler_chain;
    while (frame) {
        for (int __i = 0; __i < frame->n_cases; __i++) {
            if (strcmp(frame->cases[__i].effect_name, name) == 0) {
                TurContK __fresh_k = {false, tur_current_fiber};
                return frame->cases[__i].handler_fn(args, n_args, (int64_t)(intptr_t)&__fresh_k, frame->cases[__i].env);
            }
        }
        frame = frame->parent;
    }
    fprintf(stderr, "Unhandled effect: %s\n", name);
    abort();
    return 0;
}

/* rc<T> + weak<T> reference counting - Phase 9 */
/* Phase 10: GC color enum for Bacon-Rajan */
typedef enum { GC_WHITE, GC_GREY, GC_BLACK, GC_PURPLE } GcColor;

typedef void (*RcDropFn)(void *value);

typedef struct RcControlBlock RcControlBlock;

struct RcControlBlock {
    uint64_t strong_count;
    uint64_t weak_count;
    void *value;
    RcDropFn drop_fn;
    uint8_t value_type_kind;
    uint8_t color;           /* GC color */
    bool may_contain_cycles;  /* Hint for GC */
    uint8_t reserved[6];
};

#define RC_FREE_QUEUE_CAPACITY 65536
static RcControlBlock *rc_free_queue[RC_FREE_QUEUE_CAPACITY];
static uint32_t rc_free_queue_count = 0;
static uint32_t rc_free_queue_drain(void);  /* Forward decl */
static void rc_free_queue_push(RcControlBlock *cb);  /* Forward decl */
bool rc_strong_decrement(RcControlBlock *cb);  /* Forward decl */
bool rc_weak_decrement(RcControlBlock *cb);    /* Forward decl */
static void rc_free_queue_push(RcControlBlock *cb) {
    if (!cb) return;
    if (rc_free_queue_count >= RC_FREE_QUEUE_CAPACITY) {
        fprintf(stderr, "rc_free_queue: full, aborting\n");
        abort();
    }
    rc_free_queue[rc_free_queue_count++] = cb;
}

#define GC_GLOBAL_REGISTRY_CAPACITY 4096
static RcControlBlock *gc_all_blocks[GC_GLOBAL_REGISTRY_CAPACITY];
static uint32_t gc_all_blocks_count = 0;

#define GC_SUSPECT_THRESHOLD 128
#define GC_MAX_SUSPECTS 4096

typedef enum { GC_DISABLED, GC_MANUAL, GC_THRESHOLD } GcMode;

static RcControlBlock *gc_suspect_roots[GC_MAX_SUSPECTS];
static uint32_t gc_suspect_count = 0;
static RcControlBlock *gc_grey_queue[GC_MAX_SUSPECTS];
static uint32_t gc_grey_count = 0;
static GcMode gc_mode = GC_DISABLED;
static bool gc_enabled = false;

static void gc_collect(void);  /* Forward decl */

static void gc_set_color(RcControlBlock *cb, GcColor color) {
    if (cb) cb->color = color;
}

static GcColor gc_get_color(RcControlBlock *cb) {
    if (cb) return cb->color;
    return GC_WHITE;
}

static void gc_register_block(RcControlBlock *cb) {
    if (!cb || gc_all_blocks_count >= GC_GLOBAL_REGISTRY_CAPACITY) return;
    gc_all_blocks[gc_all_blocks_count++] = cb;
    cb->color = GC_WHITE;
    cb->may_contain_cycles = true;
}

static void gc_unregister_block(RcControlBlock *cb) {
    if (!cb) return;
    for (uint32_t i = 0; i < gc_all_blocks_count; i++) {
        if (gc_all_blocks[i] == cb) {
            gc_all_blocks[i] = gc_all_blocks[gc_all_blocks_count - 1];
            gc_all_blocks_count--;
            break;
        }
    }
}

static void gc_add_suspect(RcControlBlock *cb) {
    if (!cb || !gc_enabled || gc_mode == GC_DISABLED) return;
    for (uint32_t i = 0; i < gc_suspect_count; i++) {
        if (gc_suspect_roots[i] == cb) return;
    }
    if (gc_suspect_count >= GC_MAX_SUSPECTS) return;
    gc_suspect_roots[gc_suspect_count++] = cb;
    cb->color = GC_PURPLE;
    /* Threshold mode: auto-collect when buffer is full */
    if (gc_mode == GC_THRESHOLD && gc_suspect_count >= GC_SUSPECT_THRESHOLD) {
        gc_collect();
    }
}

static void gc_remove_suspect(RcControlBlock *cb) {
    if (!cb) return;
    for (uint32_t i = 0; i < gc_suspect_count; i++) {
        if (gc_suspect_roots[i] == cb) {
            gc_suspect_roots[i] = gc_suspect_roots[gc_suspect_count - 1];
            gc_suspect_count--;
            return;
        }
    }
}

static void gc_on_strong_decrement(RcControlBlock *cb) {
    if (!cb) return;
    /* Zombie: strong reached 0 but weak refs still exist */
    if (cb->weak_count > 0) {
        gc_add_suspect(cb);
    }
}


/* Phase 9: Deferred free queue drain */
static uint32_t rc_free_queue_drain(void) {
    if (rc_free_queue_count == 0) return 0;
    uint32_t freed = 0;
    while (rc_free_queue_count > 0) {
        RcControlBlock *cb = rc_free_queue[0];
        memmove(rc_free_queue, rc_free_queue + 1,
                (rc_free_queue_count - 1) * sizeof(RcControlBlock *));
        rc_free_queue_count--;
        gc_unregister_block(cb);
        if (cb->value) cb->drop_fn(cb->value);
        free(cb);
        freed++;
    }
    return freed;
}

static void default_rc_drop_fn(void *value) {
    free(value);
}

static void drop_ref_payload(void *value) {
    if (!value) return;
    void *inner = *((void **)value);
    if (inner) free(inner);
    free(value);
}

static void drop_rc_payload(void *value) {
    if (!value) return;
    RcControlBlock *inner = *((RcControlBlock **)value);
    if (inner) { rc_strong_decrement(inner); rc_free_queue_drain(); }
    free(value);
}

static void drop_weak_payload(void *value) {
    if (!value) return;
    RcControlBlock *inner = *((RcControlBlock **)value);
    if (inner) rc_weak_decrement(inner);
    free(value);
}

static RcDropFn default_drop_fn_for_type(int value_type_kind) {
    switch (value_type_kind) {
        case 8: return drop_ref_payload;   /* TY_REF */
        case 9: return drop_rc_payload;    /* TY_RC */
        case 10: return drop_weak_payload; /* TY_WEAK */
        default: return default_rc_drop_fn;
    }
}

RcControlBlock *rc_cb_alloc(size_t value_size, int value_type_kind, RcDropFn drop_fn) {
    size_t total_size = sizeof(RcControlBlock) + value_size;
    RcControlBlock *cb = (RcControlBlock *)malloc(total_size);
    if (!cb) { fprintf(stderr, "rc: out of memory\n"); abort(); }
    cb->strong_count = 1;
    cb->weak_count = 0;
    cb->value = (void *)(cb + 1);
    cb->drop_fn = drop_fn ? drop_fn : default_drop_fn_for_type(value_type_kind);
    cb->value_type_kind = value_type_kind;
    memset(cb->reserved, 0, sizeof(cb->reserved));
    /* Register with GC; primitives (type_kind<=7) cannot form cycles */
    gc_register_block(cb);
    if (value_type_kind <= 7) cb->may_contain_cycles = false;
    return cb;
}

uint64_t rc_strong_increment(RcControlBlock *cb) {
    if (!cb) return 0;
    return ++cb->strong_count;
}

bool rc_strong_decrement(RcControlBlock *cb) {
    if (!cb) return false;
    cb->strong_count--;
    if (cb->strong_count == 0) {
        if (cb->weak_count > 0) {
            gc_on_strong_decrement(cb);
            return false;
        } else {
            rc_free_queue_push(cb);
            return true;
        }
    }
    return false;
}

uint64_t rc_weak_increment(RcControlBlock *cb) {
    if (!cb) return 0;
    return ++cb->weak_count;
}

bool rc_weak_decrement(RcControlBlock *cb) {
    if (!cb) return false;
    cb->weak_count--;
    if (cb->weak_count == 0 && cb->strong_count == 0) {
        gc_unregister_block(cb);
        /* Free zombie value if GC did not already collect it */
        if (cb->value && cb->drop_fn) {
            cb->drop_fn(cb->value);
        }
        free(cb);
        return true;
    }
    return false;
}

uint64_t rc_strong_count(RcControlBlock *cb) {
    if (!cb) return 0;
    return cb->strong_count;
}

uint64_t rc_weak_count(RcControlBlock *cb) {
    if (!cb) return 0;
    return cb->weak_count;
}

bool rc_is_alive(RcControlBlock *cb) {
    if (!cb) return false;
    return cb->strong_count > 0;
}

RcControlBlock *rc_upgrade(RcControlBlock *cb) {
    if (!cb) return NULL;
    if (cb->strong_count > 0) {
        rc_strong_increment(cb);
        return cb;
    }
    return NULL;
}

void *rc_get_value(RcControlBlock *cb) {
    if (!cb) return NULL;
    return cb->value;
}

RcControlBlock *tur_rc_from_ref(void *ref_value, int value_type_kind) {
    if (!ref_value) return NULL;
    RcControlBlock *cb = (RcControlBlock *)malloc(sizeof(RcControlBlock));
    if (!cb) { fprintf(stderr, "rc/from-ref: out of memory\n"); abort(); }
    cb->strong_count = 1;
    cb->weak_count = 0;
    cb->value = ref_value;
    cb->drop_fn = default_drop_fn_for_type(value_type_kind);
    cb->value_type_kind = (uint8_t)value_type_kind;
    cb->color = GC_WHITE;
    cb->may_contain_cycles = true;
    memset(cb->reserved, 0, sizeof(cb->reserved));
    gc_register_block(cb);
    return cb;
}

void *tur_ref_from_rc(RcControlBlock *cb) {
    if (!cb) return NULL;
    if (cb->strong_count != 1 || cb->weak_count != 0) {
        fprintf(stderr, "ref/from-rc requires unique rc (strong_count==1 and weak_count==0), got strong=%llu weak=%llu\n",
                (unsigned long long)cb->strong_count, (unsigned long long)cb->weak_count);
        abort();
    }
    void *value = cb->value;
    cb->value = NULL;
    gc_unregister_block(cb);
    free(cb);
    return value;
}

/* gc (Bacon-Rajan cycle collector - trial deletion) - Phase 10 */
static void gc_mark_phase(void) {
    for (uint32_t i = 0; i < gc_all_blocks_count; i++) {
        gc_all_blocks[i]->color = GC_WHITE;
    }
    for (uint32_t i = 0; i < gc_all_blocks_count; i++) {
        RcControlBlock *cb = gc_all_blocks[i];
        if (cb->strong_count > 0) {
            cb->color = GC_BLACK;
        }
    }
}

static void gc_trial_deletion_phase(void) {
    uint32_t i = 0;
    while (i < gc_suspect_count) {
        RcControlBlock *cb = gc_suspect_roots[i];
        /* If revived or reachable from strong roots, keep */
        if (cb->strong_count > 0 || cb->color == GC_BLACK) {
            cb->color = GC_WHITE;
            i++;
            continue;
        }
        /* WHITE and strong_count == 0: zombie — free value, keep cb for weak refs */
        if (cb->value && cb->drop_fn) {
            cb->drop_fn(cb->value);
            cb->value = NULL;
        }
        /* Unregister from global registry (cb stays alive for weak refs) */
        gc_unregister_block(cb);
        /* Remove from suspect buffer without advancing i */
        gc_suspect_roots[i] = gc_suspect_roots[gc_suspect_count - 1];
        gc_suspect_count--;
    }
}

static void gc_collect(void) {
    if (!gc_enabled || gc_mode == GC_DISABLED) return;
    gc_grey_count = 0;
    gc_mark_phase();
    gc_trial_deletion_phase();
}

static void gc_force(void) {
    gc_collect();
}

static void gc_enable(void) {
    gc_enabled = true;
    /* Default to manual mode when enabled */
    if (gc_mode == GC_DISABLED) gc_mode = GC_MANUAL;
}

static void gc_disable(void) {
    gc_enabled = false;
    gc_mode = GC_DISABLED;
}

static void gc_set_mode(GcMode mode) {
    gc_mode = mode;
}

static bool gc_is_alive(RcControlBlock *cb) {
    if (!cb) return false;
    if (cb->strong_count > 0) return true;
    return (cb->color == GC_BLACK || cb->color == GC_GREY);
}

static void * array_get(void *, int64_t);
static int64_t array_set(void *, int64_t, int64_t);
static void * array_slice(void *, int64_t, int64_t);
static void * with_c_string(const char *, int64_t);
static const char * from_c_string(const char *);
static void * box(int64_t);
static int64_t unbox(int64_t);
static int64_t compute();

static int64_t __effect_handler_4(int64_t *__effect_args, int __n_effect_args, int64_t __k, void *__env);
static int64_t __effect_handler_4(int64_t *__effect_args, int __n_effect_args, int64_t __k, void *__env) {
    int64_t x_21 = (int64_t)__effect_args[0];
    int64_t k_22 = __k;
    if (((TurContK *)(intptr_t)k_22)->origin_fiber != (void *)tur_current_fiber) { fprintf(stderr, "continuation error: resume on wrong fiber\n"); abort(); }
    ((TurContK *)(intptr_t)k_22)->consumed = true;
    return (int64_t)((x_21) + (INT64_C(10)));
}

static int64_t __effect_handler_5(int64_t *__effect_args, int __n_effect_args, int64_t __k, void *__env);
static int64_t __effect_handler_5(int64_t *__effect_args, int __n_effect_args, int64_t __k, void *__env) {
    int64_t x_23 = (int64_t)__effect_args[0];
    int64_t k_24 = __k;
    if (((TurContK *)(intptr_t)k_24)->origin_fiber != (void *)tur_current_fiber) { fprintf(stderr, "continuation error: resume on wrong fiber\n"); abort(); }
    ((TurContK *)(intptr_t)k_24)->consumed = true;
    return (int64_t)((x_23) * (INT64_C(2)));
}

static void * array_get(void * arr, int64_t idx) {
        struct __array_get_result { bool is_some; int64_t value; } *opt = malloc(sizeof(*opt));
  int64_t *array = (int64_t *)arr;
  if (idx >= 0 && (size_t)idx < 1024) {  /* v1: use a reasonable upper bound */
    opt->is_some = true;
    opt->value = array[idx];
  } else {
    opt->is_some = false;
    opt->value = 0;
  }
  return opt;
  
}

static int64_t array_set(void * arr, int64_t idx, int64_t value) {
        int64_t *array = (int64_t *)arr;
  if (idx >= 0 && (size_t)idx < 1024) {  /* v1: use a reasonable upper bound */
    array[idx] = value;
    return 1;
  }
  return 0;
  
}

static void * array_slice(void * arr, int64_t start, int64_t len) {
        /* For v1, we return a new struct containing ptr and len */
  struct { void *ptr; size_t len; } *slice = malloc(sizeof(*slice));
  slice->ptr = (char *)arr + start * sizeof(int64_t);
  slice->len = len;
  return slice;
  
}

static void * with_c_string(const char * s, int64_t f) {
        /* For v1, we just call f with s directly since cstr is already a C string */
  int64_t (*fn)(const char *) = (int64_t (*)(const char *))f;
  return (void *)(intptr_t)fn(s);
  
}

static const char * from_c_string(const char * s) {
        return s;
}

static void * box(int64_t v) {
        int64_t *boxed = malloc(sizeof(int64_t));
  *boxed = v;
  return boxed;
  
}

static int64_t unbox(int64_t p) {
        int64_t *boxed = (int64_t *)p;
  return *boxed;
  
}

static int64_t compute() {
        int64_t __t0[1];
        __t0[0] = (int64_t)INT64_C(3);
        int64_t __t1 = tur_effect_perform("Add", __t0, 1);
        int64_t __t2[1];
        __t2[0] = (int64_t)INT64_C(4);
        int64_t __t3 = tur_effect_perform("Mul", __t2, 1);
        return ((__t1) * (__t3));
}


int main(void) {
    EffectHandlerFrame __eff_frame_6;
    EffectHandlerFrame **__eff_chain_6 = (tur_current_fiber ? (EffectHandlerFrame **)&tur_current_fiber->effect_handler_chain : &global_effect_handler_chain);
    __eff_frame_6.parent = *__eff_chain_6;
    __eff_frame_6.n_cases = 2;
    __eff_frame_6.cases[0].effect_name = "Add";
    __eff_frame_6.cases[0].handler_fn = __effect_handler_4;
    __eff_frame_6.cases[0].env = NULL;
    __eff_frame_6.cases[1].effect_name = "Mul";
    __eff_frame_6.cases[1].handler_fn = __effect_handler_5;
    __eff_frame_6.cases[1].env = NULL;
    *__eff_chain_6 = &__eff_frame_6;
    int64_t __t7 = compute();
    *__eff_chain_6 = (*__eff_chain_6)->parent;
    printf("%lld\n", (long long)(__t7));
    return 0;
}
