/* generated by tur (phase 2) */
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
extern void *malloc(size_t);
extern void free(void *);

/* tur_frame - phase 4 v1 lowering (from runtime.h) */
typedef void (*defer_fn_t)(void *env);
#define TUR_FRAME_MAX_DEFERS 32

typedef struct tur_frame {
    defer_fn_t defers[TUR_FRAME_MAX_DEFERS];
    void *envs[TUR_FRAME_MAX_DEFERS];
    int n;
    struct tur_frame *parent;
    bool may_capture;
} tur_frame;

static inline void tur_frame_init(tur_frame *f, tur_frame *parent) {
    f->n = 0; f->parent = parent; f->may_capture = false;
}
static inline int tur_frame_push_defer(tur_frame *f, defer_fn_t thunk, void *env) {
    if (f->n >= TUR_FRAME_MAX_DEFERS) return -1;
    f->defers[f->n] = thunk;
    f->envs[f->n] = env;
    f->n++;
    return 0;
}
static void tur_frame_fire_lifo(tur_frame *f) {
    for (int i = f->n - 1; i >= 0; i--) f->defers[i](f->envs[i]);
    f->n = 0;
}

struct __defer_env_10 {void * outer; };

struct __defer_env_7 {void * inner; };

static void __defer_11(void *__env) {
    struct __defer_env_10 *__e = (struct __defer_env_10 *)__env;
    free(__e->outer);
}

static void __defer_8(void *__env) {
    struct __defer_env_7 *__e = (struct __defer_env_7 *)__env;
    free(__e->inner);
}

int main() {
        int64_t __t0;
        {
            void * __t1 = malloc(sizeof(int64_t));
            *((int64_t *)__t1) = INT64_C(10);
            void * outer_1 = __t1;
            (void)outer_1;
            tur_frame __frame_2;
            tur_frame_init(&__frame_2, NULL);
            {
                void * __t3 = malloc(sizeof(int64_t));
                *((int64_t *)__t3) = INT64_C(20);
                void * inner_2 = __t3;
                (void)inner_2;
                tur_frame __frame_4;
                tur_frame_init(&__frame_4, &__frame_2);
                int64_t __t5 = *((int64_t *)inner_2);
                printf("%lld\n", (long long)(__t5));
                int64_t __t6 = *((int64_t *)outer_1);
                printf("%lld\n", (long long)(__t6));
                struct __defer_env_7 __t9 = {.inner = inner_2};
                tur_frame_push_defer(&__frame_4, __defer_8, &__t9);
                tur_frame_fire_lifo(&__frame_4);
            }
            struct __defer_env_10 __t12 = {.outer = outer_1};
            tur_frame_push_defer(&__frame_2, __defer_11, &__t12);
            int64_t __t13;
            __t13 = INT64_C(0);
            tur_frame_fire_lifo(&__frame_2);
            __t0 = __t13;
        }
        return (int)__t0;
}


