# CMake generated Testfile for 
# Source directory: /Users/rjungemann/Projects/turmeric
# Build directory: /Users/rjungemann/Projects/turmeric/build_nosub
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[tur_tests]=] "bash" "tests/run.sh")
set_tests_properties([=[tur_tests]=] PROPERTIES  DEPENDS "tur" WORKING_DIRECTORY "/Users/rjungemann/Projects/turmeric" _BACKTRACE_TRIPLES "/Users/rjungemann/Projects/turmeric/CMakeLists.txt;19;add_test;/Users/rjungemann/Projects/turmeric/CMakeLists.txt;0;")
add_test([=[tur_cli_tests]=] "bash" "tests/run-cli.sh")
set_tests_properties([=[tur_cli_tests]=] PROPERTIES  DEPENDS "tur" WORKING_DIRECTORY "/Users/rjungemann/Projects/turmeric" _BACKTRACE_TRIPLES "/Users/rjungemann/Projects/turmeric/CMakeLists.txt;24;add_test;/Users/rjungemann/Projects/turmeric/CMakeLists.txt;0;")
add_test([=[tur_span_tests]=] "bash" "tests/check-span-unknown.sh")
set_tests_properties([=[tur_span_tests]=] PROPERTIES  DEPENDS "tur" WORKING_DIRECTORY "/Users/rjungemann/Projects/turmeric" _BACKTRACE_TRIPLES "/Users/rjungemann/Projects/turmeric/CMakeLists.txt;29;add_test;/Users/rjungemann/Projects/turmeric/CMakeLists.txt;0;")
add_test([=[tur_flags_tests]=] "bash" "tests/run-flags.sh")
set_tests_properties([=[tur_flags_tests]=] PROPERTIES  DEPENDS "tur" WORKING_DIRECTORY "/Users/rjungemann/Projects/turmeric" _BACKTRACE_TRIPLES "/Users/rjungemann/Projects/turmeric/CMakeLists.txt;34;add_test;/Users/rjungemann/Projects/turmeric/CMakeLists.txt;0;")
add_test([=[tur_repl_tests]=] "bash" "tests/turi/eval-test.sh")
set_tests_properties([=[tur_repl_tests]=] PROPERTIES  DEPENDS "tur" WORKING_DIRECTORY "/Users/rjungemann/Projects/turmeric" _BACKTRACE_TRIPLES "/Users/rjungemann/Projects/turmeric/CMakeLists.txt;41;add_test;/Users/rjungemann/Projects/turmeric/CMakeLists.txt;0;")
add_test([=[tur_repl_smoke]=] "bash" "tests/turi/repl-smoke.sh")
set_tests_properties([=[tur_repl_smoke]=] PROPERTIES  DEPENDS "tur" WORKING_DIRECTORY "/Users/rjungemann/Projects/turmeric" _BACKTRACE_TRIPLES "/Users/rjungemann/Projects/turmeric/CMakeLists.txt;47;add_test;/Users/rjungemann/Projects/turmeric/CMakeLists.txt;0;")
add_test([=[tur_eval_import]=] "bash" "tests/turi/eval-import.sh")
set_tests_properties([=[tur_eval_import]=] PROPERTIES  DEPENDS "tur" ENVIRONMENT "TUR_CC_FLAGS=-O2 -std=c99 -Wall -I/Users/rjungemann/Projects/turmeric/src -L/Users/rjungemann/Projects/turmeric/build_nosub/src" WORKING_DIRECTORY "/Users/rjungemann/Projects/turmeric" _BACKTRACE_TRIPLES "/Users/rjungemann/Projects/turmeric/CMakeLists.txt;53;add_test;/Users/rjungemann/Projects/turmeric/CMakeLists.txt;0;")
add_test([=[tur_eval_basic]=] "/Users/rjungemann/Projects/turmeric/build_nosub/tur_eval_basic")
set_tests_properties([=[tur_eval_basic]=] PROPERTIES  DEPENDS "tur" WORKING_DIRECTORY "/Users/rjungemann/Projects/turmeric" _BACKTRACE_TRIPLES "/Users/rjungemann/Projects/turmeric/CMakeLists.txt;69;add_test;/Users/rjungemann/Projects/turmeric/CMakeLists.txt;0;")
add_test([=[tur_eval_effects]=] "bash" "tests/turi/eval-effects.sh")
set_tests_properties([=[tur_eval_effects]=] PROPERTIES  DEPENDS "tur" WORKING_DIRECTORY "/Users/rjungemann/Projects/turmeric" _BACKTRACE_TRIPLES "/Users/rjungemann/Projects/turmeric/CMakeLists.txt;75;add_test;/Users/rjungemann/Projects/turmeric/CMakeLists.txt;0;")
add_test([=[tur_eval_s4]=] "bash" "tests/turi/eval-s4.sh")
set_tests_properties([=[tur_eval_s4]=] PROPERTIES  DEPENDS "tur" WORKING_DIRECTORY "/Users/rjungemann/Projects/turmeric" _BACKTRACE_TRIPLES "/Users/rjungemann/Projects/turmeric/CMakeLists.txt;81;add_test;/Users/rjungemann/Projects/turmeric/CMakeLists.txt;0;")
add_test([=[tur_eval_async_basic]=] "bash" "tests/turi/eval-async-basic.sh")
set_tests_properties([=[tur_eval_async_basic]=] PROPERTIES  DEPENDS "tur" WORKING_DIRECTORY "/Users/rjungemann/Projects/turmeric" _BACKTRACE_TRIPLES "/Users/rjungemann/Projects/turmeric/CMakeLists.txt;88;add_test;/Users/rjungemann/Projects/turmeric/CMakeLists.txt;0;")
add_test([=[tur_eval_async_composition]=] "bash" "tests/turi/eval-async-composition.sh")
set_tests_properties([=[tur_eval_async_composition]=] PROPERTIES  DEPENDS "tur" WORKING_DIRECTORY "/Users/rjungemann/Projects/turmeric" _BACKTRACE_TRIPLES "/Users/rjungemann/Projects/turmeric/CMakeLists.txt;93;add_test;/Users/rjungemann/Projects/turmeric/CMakeLists.txt;0;")
add_test([=[tur_eval_async_effects]=] "bash" "tests/turi/eval-async-effects.sh")
set_tests_properties([=[tur_eval_async_effects]=] PROPERTIES  DEPENDS "tur" WORKING_DIRECTORY "/Users/rjungemann/Projects/turmeric" _BACKTRACE_TRIPLES "/Users/rjungemann/Projects/turmeric/CMakeLists.txt;98;add_test;/Users/rjungemann/Projects/turmeric/CMakeLists.txt;0;")
add_test([=[tur_eval_async_timeout]=] "bash" "tests/turi/eval-async-timeout.sh")
set_tests_properties([=[tur_eval_async_timeout]=] PROPERTIES  DEPENDS "tur" WORKING_DIRECTORY "/Users/rjungemann/Projects/turmeric" _BACKTRACE_TRIPLES "/Users/rjungemann/Projects/turmeric/CMakeLists.txt;103;add_test;/Users/rjungemann/Projects/turmeric/CMakeLists.txt;0;")
add_test([=[tur_eval_async_cancel]=] "bash" "tests/turi/eval-async-cancel.sh")
set_tests_properties([=[tur_eval_async_cancel]=] PROPERTIES  DEPENDS "tur" WORKING_DIRECTORY "/Users/rjungemann/Projects/turmeric" _BACKTRACE_TRIPLES "/Users/rjungemann/Projects/turmeric/CMakeLists.txt;108;add_test;/Users/rjungemann/Projects/turmeric/CMakeLists.txt;0;")
add_test([=[tur_eval_async_error]=] "bash" "tests/turi/eval-async-error.sh")
set_tests_properties([=[tur_eval_async_error]=] PROPERTIES  DEPENDS "tur" WORKING_DIRECTORY "/Users/rjungemann/Projects/turmeric" _BACKTRACE_TRIPLES "/Users/rjungemann/Projects/turmeric/CMakeLists.txt;113;add_test;/Users/rjungemann/Projects/turmeric/CMakeLists.txt;0;")
add_test([=[tur_eval_async_io]=] "bash" "tests/turi/eval-async-io.sh")
set_tests_properties([=[tur_eval_async_io]=] PROPERTIES  DEPENDS "tur" WORKING_DIRECTORY "/Users/rjungemann/Projects/turmeric" _BACKTRACE_TRIPLES "/Users/rjungemann/Projects/turmeric/CMakeLists.txt;118;add_test;/Users/rjungemann/Projects/turmeric/CMakeLists.txt;0;")
subdirs("src")
