/* emit_dk_runtime.c -- DK delimited-control runtime prelude emitters
 * (cps-backend-unification U7, step 1: "relocate the runtime").
 *
 * Relocated verbatim out of emit_cps.c so the load-bearing DK runtime is no
 * longer entangled with the direct-style lowering functions that U7 deletes.
 * Both the direct emitter (emit_cps.c) and the native CT-IR backend
 * (emit_cps_ir.c) generate calls into the C emitted here. The emitted text is
 * byte-identical to the pre-relocation emitters -- this is a pure code move.
 *
 * See emit_dk_runtime.h for the model and
 * docs/archive/cps-backend-unification-u7-readiness-plan.md for the cut
 * sequence this is the first step of.
 */

#include "emit_dk_runtime.h"
#include "globals.h"  /* compiler config globals */

/* ---- (call/cc f) / (escape f): undelimited escape-continuation runtime ---- */

void emit_cps_callcc_prelude(Buf *out) {
    buf_puts(out,
"/* call-cc-completion: undelimited escape-continuation runtime.\n"
" * (call/cc f)/(escape f) set up a landing here; the continuation handle f\n"
" * receives is &tur_escape_cont. Invoking it (tur_escape_resume) is a one-shot\n"
" * upward escape: it longjmps back to the call/cc site delivering the value.\n"
" * Capture is O(1) and unbounded -- no TUR_CONT_MAX_CAPTURED_FRAMES ceiling. */\n"
"typedef struct tur_escape_cont {\n"
"    jmp_buf buf;\n"
"    int64_t result;  /* value delivered by tur_escape_resume */\n"
"    bool    valid;   /* false once the call/cc prompt has returned */\n"
"} tur_escape_cont;\n"
"static int64_t tur_escape_resume(int64_t k, int64_t v) {\n"
"    tur_escape_cont *cc = (tur_escape_cont *)(intptr_t)k;\n"
"    if (!cc || !cc->valid) {\n"
"        fprintf(stderr, \"tur: continuation invoked after its call/cc prompt returned\\n\");\n"
"        abort();\n"
"    }\n"
"    cc->result = v;\n"
"    longjmp(cc->buf, 1);\n"
"    return 0; /* unreachable */\n"
"}\n"
"\n");
}

/* Bridge: a cloneable continuation whose captured context is a DK chain.
 * Reuses the emitted tur_cloneable_cont struct -- the DK chain rides in `env`,
 * resume dispatches to dk_invoke (multi-shot), clone copies the chain, drop
 * frees it. Emitted after both the cloneable runtime and the DK machine. */
void emit_cps_cloneable_bridge_prelude(Buf *out) {
    buf_puts(out,
"/* cps-transform-plan (CPS9): cloneable continuation <-> DK bridge.\n"
" * The reified delimited context (a DK chain) rides in the cloneable cont's\n"
" * env; resume = dk_invoke (multi-shot, copies internally), clone = chain\n"
" * copy, drop = dk_free. Reuses the existing tur_cloneable_cont machinery. */\n"
"static int64_t __dk_cont_fn(void *env, int64_t value) {\n"
"    return (int64_t)dk_invoke((DK *)env, (intptr_t)value);\n"
"}\n"
"static void *__dk_env_clone(const void *env) {\n"
"    return (void *)dk_copy_range((const DK *)env, NULL);\n"
"}\n"
"static void __dk_env_drop(void *env) { dk_free((DK *)env); }\n"
"\n");
}

/* Serial marshaling runtime: the fixed tagged context frames + the resume /
 * serialize / deserialize builtins. Emitted after the DK machine prelude,
 * gated on preamble_uses_serial (emit_module.c). */
void emit_cps_serial_runtime_prelude(Buf *out) {
    buf_puts(out,
"/* cps-transform-plan (CPS10 / CPS5.4): serializable continuations.\n"
" * The captured continuation is a DK chain of tagged context frames; it is\n"
" * marshaled by writing each frame's stable tag + env (no code addresses), and\n"
" * rebuilt by mapping the tag back to a frame fn. Buffer layout matches stdlib\n"
" * `bytes` (int64 length prefix, then payload). */\n"
"enum { SK_TAG_ADD = 1, SK_TAG_MUL = 2, SK_TAG_SUBR = 3, SK_TAG_SUBL = 4,\n"
"       SK_TAG_DIVR = 5, SK_TAG_DIVL = 6 };\n"
"static intptr_t __sk_add (intptr_t env, intptr_t v) { return env + v; }\n"
"static intptr_t __sk_mul (intptr_t env, intptr_t v) { return env * v; }\n"
"static intptr_t __sk_subr(intptr_t env, intptr_t v) { return env - v; } /* other - hole */\n"
"static intptr_t __sk_subl(intptr_t env, intptr_t v) { return v - env; } /* hole - other */\n"
"static intptr_t __sk_divr(intptr_t env, intptr_t v) {  /* other / hole */\n"
"    return (v) ? (env / v) : (fprintf(stderr, \"division by zero\\n\"), abort(), 0);\n"
"}\n"
"static intptr_t __sk_divl(intptr_t env, intptr_t v) {  /* hole / other */\n"
"    return (env) ? (v / env) : (fprintf(stderr, \"division by zero\\n\"), abort(), 0);\n"
"}\n"
"static DKFrame __sk_frame_for_tag(int tag) {\n"
"    switch (tag) {\n"
"        case SK_TAG_ADD:  return __sk_add;\n"
"        case SK_TAG_MUL:  return __sk_mul;\n"
"        case SK_TAG_SUBR: return __sk_subr;\n"
"        case SK_TAG_SUBL: return __sk_subl;\n"
"        case SK_TAG_DIVR: return __sk_divr;\n"
"        case SK_TAG_DIVL: return __sk_divl;\n"
"        default: return NULL;\n"
"    }\n"
"}\n"
"static int __sk_tag_for_frame(DKFrame f) {\n"
"    if (f == __sk_add)  return SK_TAG_ADD;\n"
"    if (f == __sk_mul)  return SK_TAG_MUL;\n"
"    if (f == __sk_subr) return SK_TAG_SUBR;\n"
"    if (f == __sk_subl) return SK_TAG_SUBL;\n"
"    if (f == __sk_divr) return SK_TAG_DIVR;\n"
"    if (f == __sk_divl) return SK_TAG_DIVL;\n"
"    return 0;  /* not an arithmetic frame -- a call frame (see the registry) */\n"
"}\n"
"/* Call-frame registry: each per-site call frame self-registers (via a C\n"
" * constructor) a stable name <-> DKFrame mapping, so a call frame marshals as\n"
" * its name rather than a code address -- the same name-keyed scheme the\n"
" * interpreter's serial.c uses, here with the emitted C function name. */\n"
"/* env_kind: 0 = int (inline int64), 1 = cstr (length-prefixed bytes),\n"
" * 2 = serializable (marshaled via the env type's Serializable instance). For a\n"
" * serializable env, ser/deser point at __inst_Serializable_{serialize,\n"
" * deserialize}_<T>: ser(env) -> a `bytes` {int64 len; data} buffer; deser(bytes)\n"
" * -> the env value. */\n"
"typedef struct SkReg {\n"
"    const char *name; DKFrame fn; int env_kind;\n"
"    void *(*ser)(int64_t); int64_t (*deser)(void *);\n"
"    struct SkReg *next;\n"
"} SkReg;\n"
"static SkReg *__sk_registry = NULL;\n"
"static void __sk_register(SkReg *r) { r->next = __sk_registry; __sk_registry = r; }\n"
"static DKFrame __sk_call_for_name(const char *name) {\n"
"    for (SkReg *r = __sk_registry; r; r = r->next)\n"
"        if (strcmp(r->name, name) == 0) return r->fn;\n"
"    return NULL;\n"
"}\n"
"static SkReg *__sk_reg_by_name(const char *name) {\n"
"    for (SkReg *r = __sk_registry; r; r = r->next)\n"
"        if (strcmp(r->name, name) == 0) return r;\n"
"    return NULL;\n"
"}\n"
"static SkReg *__sk_reg_for_frame(DKFrame f) {\n"
"    for (SkReg *r = __sk_registry; r; r = r->next)\n"
"        if (r->fn == f) return r;\n"
"    return NULL;\n"
"}\n"
"#define SK_TAG_CALL 100\n"
"#define SK_ENV_INT  0\n"
"#define SK_ENV_CSTR 1\n"
"#define SK_ENV_SER  2\n");
    buf_puts(out,
"/* Resume a (possibly deserialized) serial continuation on a value. */\n"
"static int64_t tur_serial_cont_resume(int64_t k, int64_t v) {\n"
"    return (int64_t)dk_invoke((DK *)(intptr_t)k, (intptr_t)v);\n"
"}\n"
"/* Marshal to a length-prefixed buffer ([int64 payload_len][int64 n][records]).\n"
" * Each record is self-describing. An arithmetic frame is [tag(1..6)][int64 env].\n"
" * A call frame is [SK_TAG_CALL][name_len][name][env_kind][env]: an int env is an\n"
" * inline int64; a cstr env is [int64 len][bytes] -- so a non-int (cstr) env is\n"
" * marshaled by value, not as a code/heap address. All scalars are memcpy'd. */\n"
"static int64_t tur_serial_cont_serialize(int64_t k) {\n"
"    DK *p = (DK *)(intptr_t)k;\n"
"    int64_t n = 0, sz = 8;  /* 8 bytes for the frame count */\n"
"    for (DK *q = p; q && q->kind == DKK_FRAME; q = q->next) {\n"
"        n++;\n"
"        if (__sk_tag_for_frame(q->fn)) { sz += 16; continue; }\n"
"        SkReg *r = __sk_reg_for_frame(q->fn);\n"
"        const char *nm = r ? r->name : \"\";\n"
"        int64_t L = (int64_t)strlen(nm);\n"
"        sz += 8 + 8 + L + 8;  /* tag + name_len + name + env_kind */\n"
"        if (r && r->env_kind == SK_ENV_CSTR) {\n"
"            const char *s = (const char *)(intptr_t)q->env;\n"
"            sz += 8 + (int64_t)(s ? strlen(s) : 0);  /* str_len + bytes */\n"
"        } else if (r && r->env_kind == SK_ENV_SER && r->ser) {\n"
"            void *b = r->ser((int64_t)q->env);       /* instance bytes {len;data} */\n"
"            int64_t bl = b ? ((int64_t *)b)[0] : 0;\n"
"            sz += 8 + bl; free(b);                    /* len + data */\n"
"        } else { sz += 8; }                            /* inline int64 */\n"
"    }\n"
"    uint8_t *buf = (uint8_t *)malloc((size_t)(8 + sz));\n"
"    if (!buf) abort();\n"
"    memcpy(buf, &sz, 8);\n"
"    uint8_t *c = buf + 8;\n"
"    memcpy(c, &n, 8); c += 8;\n"
"    for (DK *q = p; q && q->kind == DKK_FRAME; q = q->next) {\n"
"        int t = __sk_tag_for_frame(q->fn);\n"
"        if (t) {\n"
"            int64_t tag = t, env = (int64_t)q->env;\n"
"            memcpy(c, &tag, 8); c += 8; memcpy(c, &env, 8); c += 8;\n"
"            continue;\n"
"        }\n"
"        SkReg *r = __sk_reg_for_frame(q->fn);\n"
"        const char *nm = r ? r->name : \"\";\n"
"        int64_t tag = SK_TAG_CALL, L = (int64_t)strlen(nm);\n"
"        int64_t ek = r ? r->env_kind : SK_ENV_INT;\n"
"        memcpy(c, &tag, 8); c += 8;\n"
"        memcpy(c, &L, 8); c += 8;\n"
"        if (L) { memcpy(c, nm, (size_t)L); c += L; }\n"
"        memcpy(c, &ek, 8); c += 8;\n"
"        if (ek == SK_ENV_CSTR) {\n"
"            const char *s = (const char *)(intptr_t)q->env;\n"
"            int64_t sl = (int64_t)(s ? strlen(s) : 0);\n"
"            memcpy(c, &sl, 8); c += 8;\n"
"            if (sl) { memcpy(c, s, (size_t)sl); c += sl; }\n"
"        } else if (ek == SK_ENV_SER && r && r->ser) {\n"
"            void *b = r->ser((int64_t)q->env);\n"
"            int64_t bl = b ? ((int64_t *)b)[0] : 0;\n"
"            memcpy(c, &bl, 8); c += 8;\n"
"            if (bl) { memcpy(c, (int64_t *)b + 1, (size_t)bl); c += bl; }\n"
"            free(b);\n"
"        } else {\n"
"            int64_t env = (int64_t)q->env;\n"
"            memcpy(c, &env, 8); c += 8;\n"
"        }\n"
"    }\n"
"    return (int64_t)(intptr_t)buf;\n"
"}\n");
    buf_puts(out,
"/* Rebuild a runnable chain [frames..., prompt, done] from a marshaled buffer.\n"
" * Records are parsed forward, then prepended in reverse so the first-written\n"
" * frame stays at the front of the chain. A cstr env is rematerialized as a\n"
" * fresh heap string. */\n"
"static int64_t tur_serial_cont_deserialize(int64_t bytes) {\n"
"    uint8_t *c = (uint8_t *)(intptr_t)bytes + 8;  /* skip the length prefix */\n"
"    int64_t n; memcpy(&n, c, 8); c += 8;\n"
"    DKFrame *fns = (DKFrame *)malloc(sizeof(DKFrame) * (size_t)(n > 0 ? n : 1));\n"
"    intptr_t *envs = (intptr_t *)malloc(sizeof(intptr_t) * (size_t)(n > 0 ? n : 1));\n"
"    if (!fns || !envs) abort();\n"
"    for (int64_t i = 0; i < n; i++) {\n"
"        int64_t tag; memcpy(&tag, c, 8); c += 8;\n"
"        if (tag == SK_TAG_CALL) {\n"
"            int64_t L; memcpy(&L, c, 8); c += 8;\n"
"            char *nm = (char *)malloc((size_t)L + 1);\n"
"            if (!nm) abort();\n"
"            if (L) memcpy(nm, c, (size_t)L);\n"
"            nm[L] = 0; c += L;\n"
"            fns[i] = __sk_call_for_name(nm);\n"
"            SkReg *reg = __sk_reg_by_name(nm); free(nm);\n"
"            int64_t ek; memcpy(&ek, c, 8); c += 8;\n"
"            if (ek == SK_ENV_CSTR) {\n"
"                int64_t sl; memcpy(&sl, c, 8); c += 8;\n"
"                char *s = (char *)malloc((size_t)sl + 1);\n"
"                if (!s) abort();\n"
"                if (sl) memcpy(s, c, (size_t)sl);\n"
"                s[sl] = 0; c += sl;\n"
"                envs[i] = (intptr_t)s;\n"
"            } else if (ek == SK_ENV_SER) {\n"
"                int64_t bl; memcpy(&bl, c, 8); c += 8;\n"
"                int64_t *bb = (int64_t *)malloc(sizeof(int64_t) + (size_t)bl);\n"
"                if (!bb) abort();\n"
"                bb[0] = bl;\n"
"                if (bl) memcpy(bb + 1, c, (size_t)bl);\n"
"                c += bl;\n"
"                envs[i] = (reg && reg->deser) ? (intptr_t)reg->deser(bb) : 0;\n"
"                free(bb);\n"
"            } else {\n"
"                int64_t env; memcpy(&env, c, 8); c += 8;\n"
"                envs[i] = (intptr_t)env;\n"
"            }\n"
"        } else {\n"
"            fns[i] = __sk_frame_for_tag((int)tag);\n"
"            int64_t env; memcpy(&env, c, 8); c += 8;\n"
"            envs[i] = (intptr_t)env;\n"
"        }\n"
"    }\n"
"    DK *chain = dk_prompt(1, dk_done());\n"
"    for (int64_t i = n - 1; i >= 0; i--) chain = dk_frame(fns[i], envs[i], chain);\n"
"    free(fns); free(envs);\n"
"    return (int64_t)(intptr_t)chain;\n"
"}\n"
"\n");
}

/* ---- runtime prelude: a faithful C port of src/runtime/cps_prompt.c ----- */

void emit_cps_runtime_prelude(Buf *out) { emit_cps_runtime_prelude_ex(out, false); }

void emit_cps_runtime_prelude_ex(Buf *out, bool tramp) {
    buf_puts(out,
"/* CPS substrate (cps-transform-plan): multi-prompt delimited-control machine.\n"
" * Heap-reified continuation chains (DK); a reset is a prompt, a shift slices\n"
" * the chain up to the nearest prompt. Faithful port of src/runtime/cps_prompt.c.\n"
" * Capture is O(depth-of-slice) and unbounded -- no 16-frame ceiling. */\n"
"#define DK_ROOT_TAG 0\n"
"typedef struct DK DK;\n"
"typedef intptr_t (*DKFrame)(intptr_t env, intptr_t value);\n"
"typedef intptr_t (*DKBody)(intptr_t env, DK *subk);\n"
"typedef intptr_t (*DKHandler)(intptr_t env, intptr_t arg, DK *subk);\n"
/* A RESUME frame (multi-suspension continuation lowering, Track A): unlike a
 * plain DKK_FRAME value-transform, it receives its run-time downstream chain
 * `rest` (this node's k->next as spliced by dk_perform -- the reinstalled
 * handler tail) and CONSUMES it (dk_run_impl returns rfn's result rather than
 * continuing the loop).  That is what lets a nested control op inside a lifted
 * continuation thread the correct enclosing handler and deliver exactly once. */
"typedef intptr_t (*DKResumeFrame)(intptr_t env, intptr_t value, DK *rest);\n"
/* E3a (cps-backend-owning-env-teardown): owning-env clone/drop glue.  A frame
 * whose captured env holds an owning value carries this pair so a multi-shot
 * resume gets its own refcounted copy instead of a shared shallow alias; both
 * default NULL, in which case dk_copy_node keeps the shallow env-pointer copy
 * and dk_free never touches the env -- byte-identical to the pre-E3a path. */
"typedef intptr_t (*DKEnvClone)(intptr_t env);\n"
"typedef void (*DKEnvDrop)(intptr_t env);\n"
"typedef enum { DKK_DONE, DKK_FRAME, DKK_PROMPT, DKK_SHIFT, DKK_SHIFT0, DKK_HANDLER, DKK_RESUME_FRAME } DKKind;\n"
"struct DK {\n"
"    DKKind kind; DKFrame fn; intptr_t env; int tag;\n"
"    DKBody body; intptr_t body_env;\n"
"    DKHandler handler; intptr_t handler_env; bool shallow;\n"
"    DKResumeFrame rfn; DKEnvClone env_clone; DKEnvDrop env_drop; DK *next;\n"
/* Spine unification (cps-multishot-nontail-resume-inner-handle-drops-clause-
 * rest): a handle-continuation frame's `next` is the ACTUAL enclosing chain --
 * one spine serves dk_perform's search, dk_copy_range's boundary, and the
 * H->next delivery alike -- but that chain has its own reap owner, so this
 * node's free must not walk into it.  borrow_next marks exactly that: dk_free
 * frees this node and stops.  Copies never inherit it (dk_copy_node leaves it
 * false): a dk_copy_range copy OWNS every node it copied, including the ones
 * past the borrow point. */
"    bool borrow_next;  /* ->next is borrowed (another chain owns it): dk_free stops here */\n"
/* Re-opening delivery protocol (cps-case-reopen-marker-kont-truncates-capture):
 * a handler whose case RE-OPENS an outer effect runs with the REAL enclosing
 * chain as its continuation and delivers its own value through it
 * (dk_run(__kont, v) on every exit).  dk_perform's inline branch must then
 * return the case's result verbatim instead of delivering H->next a second
 * time -- the measured failure of the naive real-chain conversion was exactly
 * that double delivery.  The flag is a property of the case FN's protocol, so
 * dk_copy_node carries it (a marker copy's case still delivers for itself). */
"    bool case_delivers;  /* case fn delivers through the chain itself: dk_perform returns its result as-is */\n");
    if (tramp) buf_puts(out,
"    bool tail_resume;  /* E7: this handler tail-resumes -> dk_perform yields to driver */\n"
"    int hgroup;        /* re-opening: same-handle sibling group id (0 = ungrouped);\n"
"                        * distinguishes this handle's cases from an enclosing\n"
"                        * handle's handlers once a re-install flattens the chain */\n"
"    bool consumed;     /* (cont? k): a handler-case continuation is unconsumed until\n"
"                        * the program `resume`s it; set at the user resume site so\n"
"                        * `cont?` can read `!k->consumed` (matches the fiber path). */\n");
    buf_puts(out,
"};\n"
"static DK *dk_new(DKKind kind, DK *next) {\n"
"    DK *k = (DK *)calloc(1, sizeof(DK)); k->kind = kind; k->next = next; return k;\n"
"}\n"
"static DK *dk_done(void) { return dk_new(DKK_DONE, NULL); }\n"
"static DK *dk_frame(DKFrame fn, intptr_t env, DK *next) {\n"
"    DK *k = dk_new(DKK_FRAME, next); k->fn = fn; k->env = env; return k;\n"
"}\n"
"/* E3a: a plain frame whose env is owning -- carries the clone/drop pair fired\n"
" * by dk_copy_node / dk_free.  NULL for both is exactly dk_frame. */\n"
"__attribute__((unused))\n"
"static DK *dk_frame_owning(DKFrame fn, intptr_t env,\n"
"                           DKEnvClone env_clone, DKEnvDrop env_drop, DK *next) {\n"
"    DK *k = dk_new(DKK_FRAME, next); k->fn = fn; k->env = env;\n"
"    k->env_clone = env_clone; k->env_drop = env_drop; return k;\n"
"}\n"
"static DK *dk_frame_resume(DKResumeFrame fn, intptr_t env, DK *next) {\n"
"    DK *k = dk_new(DKK_RESUME_FRAME, next); k->rfn = fn; k->env = env; return k;\n"
"}\n"
"/* A handle-continuation resume-frame whose `next` is the ACTUAL enclosing\n"
" * chain, borrowed.  The one spine then serves every consumer: dk_perform's\n"
" * handler search walks straight into the real enclosing handlers, its capture\n"
" * boundary (dk_copy_range(k, H)) stops at the real H, and its delivery\n"
" * (dk_run_impl(H->next, r)) runs the real rest of the program -- exactly once,\n"
" * however many times the handler case resumed its sub-continuation.  The frame\n"
" * fn is a DKResumeFrame, so a COPY of this node threads the COPY's own next\n"
" * (its reified, marker-terminated tail) rather than a baked env pointer to the\n"
" * original chain -- which is what confined a resumed continuation to its\n"
" * delimiter.  borrow_next keeps dk_free out of the enclosing chain (it has its\n"
" * own reap owner). */\n"
"__attribute__((unused))\n"
"static DK *dk_frame_resume_borrow(DKResumeFrame fn, intptr_t env, DK *next) {\n"
"    DK *k = dk_frame_resume(fn, env, next); k->borrow_next = true; return k;\n"
"}\n"
"static DK *dk_prompt(int tag, DK *next) {\n"
"    DK *k = dk_new(DKK_PROMPT, next); k->tag = tag; return k;\n"
"}\n"
"static DK *dk_shift_impl(DKKind kind, int tag, DKBody body, intptr_t env, DK *next) {\n"
"    DK *k = dk_new(kind, next); k->tag = tag; k->body = body; k->body_env = env; return k;\n"
"}\n"
"static DK *dk_shift(int tag, DKBody body, intptr_t env, DK *next) {\n"
"    return dk_shift_impl(DKK_SHIFT, tag, body, env, next);\n"
"}\n"
"static DK *dk_shift0(int tag, DKBody body, intptr_t env, DK *next) {\n"
"    return dk_shift_impl(DKK_SHIFT0, tag, body, env, next);\n"
"}\n"
"static DK *dk_handler_impl(int tag, DKHandler fn, intptr_t env, bool shallow, DK *next) {\n"
"    DK *k = dk_new(DKK_HANDLER, next); k->tag = tag; k->handler = fn; k->handler_env = env; k->shallow = shallow; return k;\n"
"}\n"
"static DK *dk_handler(int tag, DKHandler fn, intptr_t env, DK *next) {\n"
"    return dk_handler_impl(tag, fn, env, false, next);\n"
"}\n"
"static DK *dk_handler_shallow(int tag, DKHandler fn, intptr_t env, DK *next) {\n"
"    return dk_handler_impl(tag, fn, env, true, next);\n"
"}\n"
"/* Mark a handler whose case delivers its own value through the real chain\n"
" * (a RE-OPENING case -- see the case_delivers field).  Composes with any of\n"
" * the dk_handler ctors: dk_case_delivers(dk_handler(...)). */\n"
"__attribute__((unused))\n"
"static DK *dk_case_delivers(DK *k) { k->case_delivers = true; return k; }\n");
    if (tramp) buf_puts(out,
"/* E7: a deep handler whose case tail-resumes -- dk_perform yields to the entry\n"
" * driver instead of resuming inline, keeping deep effectful recursion flat. */\n"
"static DK *dk_handler_tail(int tag, DKHandler fn, intptr_t env, DK *next) {\n"
"    DK *k = dk_handler_impl(tag, fn, env, false, next); k->tail_resume = true; return k;\n"
"}\n"
"/* Re-opening: stamp the maximal run of consecutive DKK_HANDLER nodes starting at\n"
" * `head` (exactly ONE handle's sibling cases -- the run ends at this handle's\n"
" * continuation frame) with a fresh, shared group id.  dk_case_enclosing_real and\n"
" * dk_perform's re-install then skip only same-group handlers, so an enclosing\n"
" * handle's handlers that become ADJACENT after a chain-flattening re-install are\n"
" * no longer mistaken for this handle's siblings (they carry a different id). */\n"
"static int g_dk_hgroup_ctr = 0;\n"
"static DK *dk_hgroup(DK *head) {\n"
"    int g = ++g_dk_hgroup_ctr;\n"
"    for (DK *p = head; p && p->kind == DKK_HANDLER; p = p->next) p->hgroup = g;\n"
"    return head;\n"
"}\n");
    buf_puts(out,
"/* B3: install a DK handler group from a runtime first-class handler table -- the\n"
" * DK-side analogue of running a with-handler body under a dynamic handler value.\n"
" * Each entry contributes a dk_handler(dk_tag, dk_fn, env, ...) node, chained\n"
" * h1-outer (entry 0 outermost, matching tur_handler_table_concat order and the\n"
" * static handle chain) over `base` (the with-handler continuation frame), then\n"
" * stamped as one hgroup.  The DK case fns + tags were emitted at the handler\n"
" * literal's creation site (colored context). */\n"
"__attribute__((unused))\n"
"static DK *dk_hgroup_from_table(const tur_handler_table_t *t, DK *base) {\n"
"    DK *head = base;\n"
"    if (t) for (int i = t->n_entries - 1; i >= 0; i--) {\n"
"        tur_handler_entry_t *e = &t->entries[i];\n"
"        if (!e->dk_fn) continue;  /* case not DK-emittable -> leave unhandled, don't crash */\n"
"        /* The emitted DK case fns always end in a tail `return dk_tail_resume`,\n"
"         * so install as a tail handler (dk_perform yields the resumed chain to\n"
"         * the entry driver), matching the static handle path. */\n"
"        head = dk_handler_tail(e->dk_tag, (DKHandler)e->dk_fn, (intptr_t)e->env, head);\n"
"    }\n"
"    return dk_hgroup(head);\n"
"}\n");
    buf_puts(out,
"static DK *dk_copy_node(const DK *n);\n");
    buf_puts(out,
"static DK *dk_copy_node(const DK *n) {\n"
"    DK *c = dk_new(n->kind, NULL); c->fn = n->fn; c->tag = n->tag;\n"
/* E3a: an owning frame gets an OWNED copy of its env (rc incref / aggregate
 * deep-copy) instead of a shared shallow alias; NULL env_clone keeps the shallow
 * copy.  The clone/drop glue rides along so the copy frees its env symmetrically. */
"    c->env = n->env_clone ? n->env_clone(n->env) : n->env;\n"
"    c->env_clone = n->env_clone; c->env_drop = n->env_drop;\n"
"    c->body = n->body; c->body_env = n->body_env;\n"
"    c->handler = n->handler; c->handler_env = n->handler_env; c->shallow = n->shallow;\n");
    if (tramp) buf_puts(out,
"    c->tail_resume = n->tail_resume;\n"
"    c->hgroup = n->hgroup;\n");
    buf_puts(out,
/* borrow_next is deliberately NOT copied: dk_copy_range crosses a borrow link
 * like any other ->next, and the copy OWNS everything it copied -- its dk_free
 * must walk the whole copied chain, not stop where the ORIGINAL's ownership
 * boundary happened to sit.  case_delivers IS copied: it describes the case
 * fn's delivery protocol, which a re-installed marker copy shares. */
"    c->case_delivers = n->case_delivers;\n"
"    c->rfn = n->rfn; return c;\n"
"}\n"
"static DK *dk_copy_enclosing_handlers(const DK *from) {\n"
"    DK *head = NULL, *tail = NULL;\n"
"    for (const DK *p = from; p && p->kind != DKK_DONE; p = p->next) {\n"
"        if (p->kind != DKK_HANDLER) continue;\n"
"        DK *c = dk_copy_node(p);\n"
"        if (!head) head = tail = c; else { tail->next = c; tail = c; }\n"
"    }\n"
"    DK *done = dk_done();\n"
"    if (!head) return done;\n"
"    tail->next = done; return head;\n"
"}\n"
"/* Effect re-opening: the REAL enclosing chain in effect at the dynamic point a\n"
" * handler case body runs -- i.e. everything past this handle's sibling group,\n"
" * BORROWED.  A re-opening case takes this as its `__kont`: a `perform` in the\n"
" * case dispatches into the real enclosing handlers, its capture crosses into\n"
" * the real intermediate frames (so a multishot outer resume re-runs them per\n"
" * resume), and the case delivers its own value through the same chain\n"
" * (dk_run(__kont, v) on every exit -- the case_delivers protocol; dk_perform\n"
" * then returns the case's result without a second H->next delivery).  This\n"
" * replaced a done-terminated marker COPY, which truncated the capture at the\n"
" * marker and left the pending delivery as a C-stack frame that a tail-resume\n"
" * longjmp silently discarded (cps-case-reopen-marker-kont-truncates-capture).\n"
" * For a deep handler we skip the whole dk_handler sibling group starting at H\n"
" * (its case shares the handle's continuation context, so a sibling effect\n"
" * propagates OUTWARD, matching dk_perform's own `ge` walk); a shallow handler\n"
" * skips only H itself.  The returned chain is borrowed -- the case must only\n"
" * read, thread, or copy it, never free it. */\n"
"__attribute__((unused))\n"
"static DK *dk_case_enclosing_real(const DK *H) {\n"
"    if (!H) return NULL;\n"
"    const DK *ge = H;\n"
"    if (H->shallow) ge = H->next;\n");
    /* Deep skip: a flattening re-install can make an enclosing handle's handlers
     * ADJACENT to H, so "consecutive DKK_HANDLER" over-skips them.  Under the
     * re-opening-capable path (tramp), skip only H's own sibling GROUP (same
     * hgroup); the default path keeps the historical consecutive-HANDLER walk
     * (no re-install ever makes distinct handles adjacent there). */
    if (tramp) buf_puts(out,
"    else while (ge && ge->kind == DKK_HANDLER && ge->hgroup == H->hgroup) ge = ge->next;\n");
    else buf_puts(out,
"    else while (ge && ge->kind == DKK_HANDLER) ge = ge->next;\n");
    buf_puts(out,
"    return (DK *)ge;\n"
"}\n"
"static DK *dk_copy_range(const DK *from, const DK *stop) {\n"
"    DK *head = NULL, *tail = NULL;\n"
"    for (const DK *p = from; p && p != stop; p = p->next) {\n"
"        DK *c = dk_copy_node(p);\n"
"        if (!head) head = tail = c; else { tail->next = c; tail = c; }\n"
"    }\n"
"    return head;\n"
"}\n"
"static DK *dk_append(DK *a, DK *b) {\n"
"    if (!a) return b;\n"
"    DK *p = a;\n"
"    while (p->next) p = p->next;\n"
"    p->next = b;\n"
"    return a;\n"
"}\n"
/* E3a: drop each frame's owning env (if any) before freeing the node.
 * A borrow_next node ends the walk: its ->next belongs to another chain (with
 * its own reap entry), so following it would double-free -- and by reap time
 * the borrowed tail may already be gone, so it must not even be read. */
"static void dk_free(DK *k) { while (k) { DK *n = k->borrow_next ? NULL : k->next; if (k->env_drop) k->env_drop(k->env); free(k); k = n; } }\n");
    buf_puts(out,
"/* Free a single spliced node without following ->next -- used to reclaim the\n"
" * one-off shift/perform node whose ->next points into an enclosing continuation\n"
" * (dk_free would walk into that continuation and risk a double free).  See\n"
" * docs/archive/cps-delimited-dk-node-leak.md. */\n"
"__attribute__((unused)) static void dk_free_node(DK *k) { if (k && k->env_drop) k->env_drop(k->env); free(k); }\n");
    if (tramp) buf_puts(out,
"/* E2a: direct-entry -> CPS-entry registry (probes/e2a-registry-probe.c). */\n"
"typedef intptr_t (*__tur_cps_fn)();\n"
"static struct { intptr_t direct; __tur_cps_fn cps; } __tur_cps_reg[256];\n"
"static int __tur_cps_reg_n = 0;\n"
"__attribute__((unused)) static void __tur_cps_register(intptr_t direct, __tur_cps_fn cps) {\n"
"    if (__tur_cps_reg_n < 256) { __tur_cps_reg[__tur_cps_reg_n].direct = direct;\n"
"        __tur_cps_reg[__tur_cps_reg_n].cps = cps; __tur_cps_reg_n++; }\n"
"}\n"
"__attribute__((unused)) static __tur_cps_fn __tur_cps_lookup(intptr_t direct) {\n"
"    for (int i = 0; i < __tur_cps_reg_n; i++)\n"
"        if (__tur_cps_reg[i].direct == direct) return __tur_cps_reg[i].cps;\n"
"    return (__tur_cps_fn)0;\n"
"}\n"
"/* A registry MISS used to be called straight through -- i.e. a call to NULL,\n"
"   which lands as a bare SIGSEGV with nothing pointing at the cause.  Only a\n"
"   value whose CPS entry was registered at startup can thread the handler\n"
"   chain, so a miss is a compiler bug, not a user error; say so and stop. */\n"
"__attribute__((unused)) static __tur_cps_fn __tur_cps_lookup_checked(intptr_t direct,\n"
"                                                                     const char *who) {\n"
"    __tur_cps_fn f = __tur_cps_lookup(direct);\n"
"    if (!f) {\n"
"        fprintf(stderr, \"tur: internal error: no CPS entry registered for \"\n"
"                        \"effectful fn-value '%s' -- it cannot thread the \"\n"
"                        \"effect handler chain\\n\", who ? who : \"?\");\n"
"        abort();\n"
"    }\n"
"    return f;\n"
"}\n");
    buf_puts(out,
"/* Structural-chain reaping (docs/archive/cps-delimited-dk-node-leak.md).\n"
" * reset/handle install a prompt/handler chain as the current continuation and\n"
" * thread it through the delimited body in TAIL position, so the install site\n"
" * never regains control to free it.  Each chain is self-contained (its tail is\n"
" * dk_done; its frame envs carry the enclosing k as an intptr, not via ->next),\n"
" * so once the outermost dk_run has fully settled every registered chain is dead\n"
" * and dk_free-able without aliasing another.  We register each at construction\n"
" * and reap at the outermost direct->cps entry boundary.  The same registry\n"
" * reclaims per-continuation env structs (plain malloc, freed one-by-one). */\n"
"static void **__dk_reap_v = NULL;\n"
"static unsigned char *__dk_reap_kind = NULL;  /* 1 = DK chain (dk_free), 0 = plain (free) */\n"
"static size_t __dk_reap_n = 0, __dk_reap_cap = 0;\n"
"static int __dk_entry_depth = 0;\n"
"static void __dk_reap_push(void *p, unsigned char kind) {\n"
"    if (__dk_reap_n == __dk_reap_cap) {\n"
"        __dk_reap_cap = __dk_reap_cap ? __dk_reap_cap * 2 : 16;\n"
"        __dk_reap_v = (void **)realloc(__dk_reap_v, __dk_reap_cap * sizeof(void *));\n"
"        __dk_reap_kind = (unsigned char *)realloc(__dk_reap_kind, __dk_reap_cap);\n"
"    }\n"
"    __dk_reap_v[__dk_reap_n] = p; __dk_reap_kind[__dk_reap_n] = kind; __dk_reap_n++;\n"
"}\n"
"__attribute__((unused)) static DK *__dk_reap_keep(DK *k) { __dk_reap_push(k, 1); return k; }\n"
"__attribute__((unused)) static intptr_t __dk_reap_ptr(intptr_t p) { __dk_reap_push((void *)p, 0); return p; }\n"
"/* Register a single spliced node (->next points into an enclosing k) for a\n"
" * single-node free at reap -- dk_free would walk into the enclosing chain. */\n"
"__attribute__((unused)) static DK *__dk_reap_node(DK *k) { __dk_reap_push(k, 0); return k; }\n");
    /* closure-drop-glue: a boundary-reaped closure env is headered (env[-1] holds
     * its drop-glue), so a bare free of the past-header pointer would be an
     * interior free (corruption).  Reap kind 2 = "headered closure", released
     * through TUR_CLOSURE_DROP (recovers the header, walks owning captures, frees
     * the base). */
    buf_puts(out,
"__attribute__((unused)) static intptr_t __dk_reap_closure(intptr_t p) { __dk_reap_push((void *)p, 2); return p; }\n"
"static void __dk_reap_run(void) {\n"
"    for (size_t i = 0; i < __dk_reap_n; i++) {\n"
"        if (__dk_reap_kind[i] == 1) dk_free((DK *)__dk_reap_v[i]);\n"
"        else if (__dk_reap_kind[i] == 2) TUR_CLOSURE_DROP(__dk_reap_v[i]);\n"
"        else free(__dk_reap_v[i]);\n"
"    }\n"
"    free(__dk_reap_v); free(__dk_reap_kind);\n"
"    __dk_reap_v = NULL; __dk_reap_kind = NULL; __dk_reap_n = __dk_reap_cap = 0;\n"
"}\n");
    buf_puts(out,
"static intptr_t dk_run_impl(DK *k, intptr_t v, bool root) {\n"
"    while (k) {\n"
"        switch (k->kind) {\n"
"            case DKK_DONE: return v;\n"
"            case DKK_PROMPT: case DKK_HANDLER: k = k->next; break;\n"
"            case DKK_FRAME: v = k->fn(k->env, v); k = k->next; break;\n"
"            case DKK_RESUME_FRAME: return k->rfn(k->env, v, k->next);\n"
"            case DKK_SHIFT:\n"
"            case DKK_SHIFT0: {\n"
"                DK *P = k->next;\n"
"                while (P && !(P->kind == DKK_PROMPT && P->tag == k->tag)\n"
"                         && P->kind != DKK_DONE) P = P->next;\n"
"                bool to_root = (!P || P->kind == DKK_DONE);\n"
"                bool reinstall = (k->kind == DKK_SHIFT);\n"
"                DK *sub = dk_copy_range(k->next, P);\n"
"                DK *tail = reinstall\n"
"                    ? dk_prompt(to_root ? DK_ROOT_TAG : k->tag, dk_done()) : dk_done();\n"
"                sub = dk_append(sub, tail);\n"
"                intptr_t bodyval = k->body(k->body_env, sub);\n"
"                dk_free(sub);\n"
"                if (to_root) return bodyval;\n"
"                k = P->next; v = bodyval; break;\n"
"            }\n"
"        }\n"
"    }\n"
"    (void)root; return v;\n"
"}\n"
"static intptr_t dk_run(DK *k, intptr_t v)      { return dk_run_impl(k, v, false); }\n"
"static intptr_t dk_run_root(DK *k, intptr_t v) { return dk_run_impl(k, v, true); }\n");
    if (tramp) buf_puts(out,
"/* Forward decl of the entry driver (defined with the E7 runtime below): dk_invoke\n"
" * consults it to know whether running the invoked chain might tail-resume out. */\n"
"static jmp_buf *g_dk_driver;\n"
"static size_t   g_dk_meta_n;   /* tentative defn; the E7 block below defines it */\n"
"static intptr_t __dk_drive_bounded(DK *first, intptr_t firstv, size_t floor);\n"
"static intptr_t dk_invoke(DK *sub, intptr_t w) {\n"
"    DK *c = dk_copy_range(sub, NULL);\n"
"    /* A tail-resume inside the invoked chain longjmps to whichever landing\n"
"     * g_dk_driver names.  That landing must be THIS ONE, not the program entry:\n"
"     * dk_invoke is how a NON-tail `resume` runs, so its caller is a handler case\n"
"     * with more clause left to run (`(+ (resume k 1) (resume k 10))`).  Letting\n"
"     * the yield escape to the entry driver unwinds the case, delivering the\n"
"     * first resume's value as the whole handle's value and discarding the rest\n"
"     * -- a silent wrong answer, `2` where the answer is `22`.  See\n"
"     * docs/archive/cps-multishot-nontail-resume-inner-handle-drops-clause-rest.md.\n"
"     *\n"
"     * So install a landing scoped to this invoke and run the trampoline bounded\n"
"     * by the meta-stack watermark: deliveries queued during THIS run drain here,\n"
"     * anything an outer level queued stays for that level.  The E7 fast path is\n"
"     * untouched -- a tail resume reached without an intervening dk_invoke still\n"
"     * yields all the way to the entry driver, so deep effectful recursion stays\n"
"     * flat.\n"
"     *\n"
"     * `c` is reaped rather than freed on every path in the bounded loop: a\n"
"     * pending delivery may still reference it (the reason __dk_drive_after\n"
"     * stopped eagerly freeing a yielded chain -- see\n"
"     * docs/archive/effect-rec-nested-handler-nonterminates.md), and reaping only\n"
"     * ever defers a free to the outermost boundary, never double-frees.\n"
"     * With no driver a longjmp is impossible -- free eagerly as before. */\n"
"    if (g_dk_driver) return __dk_drive_bounded(c, w, g_dk_meta_n);\n"
"    intptr_t r = dk_run_impl(c, w, false);\n"
"    dk_free(c); return r;\n"
"}\n");
    else buf_puts(out,
"static intptr_t dk_invoke(DK *sub, intptr_t w) {\n"
"    DK *c = dk_copy_range(sub, NULL); intptr_t r = dk_run_impl(c, w, false);\n"
"    dk_free(c); return r;\n"
"}\n");
    if (tramp) buf_puts(out,
"/* ---- E7: trampolined tail-resume (cps-tramp-resume) -------------------- *\n"
" * A tail-resume handler does not resume inline (which nests ~160 B of C stack\n"
" * per resumed perform -> O(N)); instead dk_perform yields the resumed chain to\n"
" * the entry driver, which re-enters it from the top. Pending handle-continuation\n"
" * deliveries (what dk_run_impl(H->next,r) would run) ride a heap meta-stack in\n"
" * nesting (LIFO) order; a delivery of only HANDLER/DONE nodes is a no-op and is\n"
" * elided, so the meta-stack stays O(nesting), not O(N). Validated end-to-end at\n"
" * N=1e6 by docs/artifacts/probes/e7-fidelity-probe.c. */\n"
"static jmp_buf *g_dk_driver = NULL;      /* current entry-driver landing (NULL => inline) */\n"
"static DK      *g_dk_resume_chain = NULL;\n"
"static intptr_t g_dk_resume_val = 0;\n"
"static DK     **g_dk_meta = NULL;\n"
"static size_t   g_dk_meta_cap = 0;\n"
"static void __dk_meta_push(DK *d) {\n"
"    if (g_dk_meta_n == g_dk_meta_cap) {\n"
"        g_dk_meta_cap = g_dk_meta_cap ? g_dk_meta_cap * 2 : 16;\n"
"        g_dk_meta = (DK **)realloc(g_dk_meta, g_dk_meta_cap * sizeof(DK *));\n"
"    }\n"
"    g_dk_meta[g_dk_meta_n++] = d;\n"
"}\n"
"static bool __dk_delivery_noop(const DK *d) {   /* only HANDLER/DONE -> identity */\n"
"    for (const DK *p = d; p; p = p->next)\n"
"        if (p->kind != DKK_HANDLER && p->kind != DKK_DONE) return false;\n"
"    return true;\n"
"}\n"
"/* tail-resume: yield the resumed chain to the driver (never returns).  With no\n"
" * active driver (dk_perform did NOT take its tail-resume yield branch, so no\n"
" * delivery was queued), fall back to the inline dk_invoke resume -- byte-identical\n"
" * to the non-trampolined path, keeping the two sides consistent. */\n"
"static intptr_t dk_tail_resume(DK *sub, intptr_t v) {\n"
"    if (!g_dk_driver) return dk_invoke(sub, v);\n"
"    g_dk_resume_chain = sub; g_dk_resume_val = v;\n"
"    longjmp(*g_dk_driver, 1);\n"
"    return 0; /* unreachable */\n"
"}\n"
"");
    if (tramp) buf_puts(out,
"/* Run `first` to completion, absorbing any tail-resume yields it makes, and\n"
" * return its value.  Same trampoline as __dk_drive_after but SCOPED: it drains\n"
" * the meta-stack only down to `floor` (the depth at entry), and restores the\n"
" * previous landing on the way out, so a nested run cannot consume an outer\n"
" * level's pending deliveries or steal its yields.  dk_invoke uses it to keep a\n"
" * non-tail resume's tail-resume from unwinding the handler case that called it.\n"
" *\n"
" * Locals are re-read from the resume globals at the top of each iteration (and\n"
" * setjmp is re-armed there) rather than carried across the longjmp, which is\n"
" * what makes them well-defined on the yield path -- the same structure\n"
" * __dk_drive_after uses. */\n"
"static intptr_t __dk_drive_bounded(DK *first, intptr_t firstv, size_t floor) {\n"
"    jmp_buf jb; jmp_buf *saved = g_dk_driver;\n"
"    g_dk_driver = &jb;\n"
"    g_dk_resume_chain = first; g_dk_resume_val = firstv;\n"
"    intptr_t r;\n"
"    for (;;) {\n"
"        DK *ch = g_dk_resume_chain; intptr_t rv = g_dk_resume_val;\n"
"        if (setjmp(jb) == 0) {\n"
"            r = dk_run_impl(ch, rv, false);\n"
"            __dk_reap_keep(ch);\n"
"            if (g_dk_meta_n <= floor) break;\n"
"            g_dk_resume_chain = g_dk_meta[--g_dk_meta_n];\n"
"            g_dk_resume_val = r;\n"
"        } else {\n"
"            __dk_reap_keep(ch);   /* a pending delivery may still reference it */\n"
"        }\n"
"    }\n"
"    g_dk_driver = saved;\n"
"    return r;\n"
"}\n"
"/* Run the meta-stack trampoline to completion after a tail-resume longjmp landed\n"
" * in the entry wrapper. Owns its own jmp_buf so further yields land here. */\n"
"static intptr_t __dk_drive_after(void) {\n"
"    jmp_buf jb; g_dk_driver = &jb;\n"
"    intptr_t r;\n"
"    for (;;) {\n"
"        DK *ch = g_dk_resume_chain; intptr_t rv = g_dk_resume_val;\n"
"        if (setjmp(jb) == 0) {\n"
"            r = dk_run_impl(ch, rv, false);\n"
"            dk_free(ch);\n"
"            if (g_dk_meta_n == 0) return r;\n"
"            g_dk_resume_chain = g_dk_meta[--g_dk_meta_n];\n"
"            g_dk_resume_val = r;\n"
"        } else {\n"
"            /* Yielded mid-run: `ch` tail-resumed again from deep inside its own\n"
"             * execution.  With nested handlers the pending meta-stack delivery\n"
"             * queued by that interior perform re-enters the machine and reifies\n"
"             * continuations that still point into `ch`, so eagerly freeing it\n"
"             * here is a use-after-free (an inner `perform` under an outer\n"
"             * handler resumed across it -> dk_run_impl walks freed nodes and\n"
"             * spins forever).  Hand `ch` a boundary owner instead -- the same\n"
"             * treatment dk_invoke gives a chain that may tail-resume out -- so it\n"
"             * is freed exactly once at the outermost entry (__dk_reap_run) after\n"
"             * every delivery that references it has drained.  A single-handler\n"
"             * deep loop is unaffected in correctness; it only defers these frees\n"
"             * to the entry boundary.  See\n"
"             * docs/archive/effect-rec-nested-handler-nonterminates.md. */\n"
"            __dk_reap_keep(ch);   /* was dk_free(ch): premature under nesting */\n"
"        }\n"
"    }\n"
"}\n");
    buf_puts(out,
"/* Effect re-opening: the handler node whose case is currently running, set just\n"
" * before dk_perform calls the case.  A re-opening case reads it (into a local, at\n"
" * entry, before any interior perform can overwrite it) to recover its real\n"
" * enclosing chain via dk_case_enclosing_real. */\n"
"static const DK *g_dk_case_reopen_hnode = NULL;\n"
"static intptr_t dk_perform(int tag, intptr_t arg, DK *k) {\n"
"    DK *H = k;\n"
"    while (H && !(H->kind == DKK_HANDLER && H->tag == tag) && H->kind != DKK_DONE) H = H->next;\n"
"    if (!H || H->kind == DKK_DONE) { fprintf(stderr, \"tur: unhandled effect (tag %d)\\n\", tag); abort(); }\n"
"    DK *sub = dk_copy_range(k, H);\n"
"    DK *tail;\n"
"    if (H->shallow) {\n"
"        tail = dk_copy_enclosing_handlers(H->next);\n"
"    } else {\n"
"        /* Deep: re-install H AND its consecutive SIBLING handlers -- the rest of\n"
"         * this handle's dk_handler group (a multi-effect handle emits one\n"
"         * dk_handler node per case, chained: HANDLER(A)->HANDLER(B)->cont-frame).\n"
"         * dk_copy_range(k,H) already copied the siblings BEFORE H; the siblings\n"
"         * AFTER H live in H->next and would otherwise be lost, so a re-perform of\n"
"         * a sibling effect (e.g. perform B in the continuation resumed by the A\n"
"         * case) escaped -> `unhandled effect`.  Re-install the maximal run of\n"
"         * DKK_HANDLER nodes starting at H (it ends at the first non-handler node,\n"
"         * the handle's continuation frame), so the full group is present in the\n"
"         * resumed sub-continuation.  A single-case handle copies just H (identical\n"
"         * to the old dk_handler(tag,...) re-install). */\n"
"        const DK *ge = H;\n");
    /* Same sibling-group boundary fix as dk_case_enclosing_real: under the re-opening
     * path skip only H's own hgroup, so a prior re-install that flattened an
     * enclosing handle adjacent to H does not fold it into H's re-installed group. */
    if (tramp) buf_puts(out,
"        while (ge && ge->kind == DKK_HANDLER && ge->hgroup == H->hgroup) ge = ge->next;\n");
    else buf_puts(out,
"        while (ge && ge->kind == DKK_HANDLER) ge = ge->next;\n");
    buf_puts(out,
"        /* Terminate the re-installed group with the ENCLOSING handler markers, not\n"
"         * dk_done(): a deep handler leaves the outer handlers in place, so an\n"
"         * effect the group does NOT handle, performed in the resumed continuation,\n"
"         * propagates outward (e.g. inner handles Write, its body also performs Log\n"
"         * which must reach the enclosing Log handler).  dk_done() cut that off ->\n"
"         * `unhandled effect`.  dk_copy_enclosing_handlers(ge) copies the outer\n"
"         * HANDLER markers past this handle's continuation frame; with no enclosing\n"
"         * handler it is [done], i.e. unchanged from before. */\n"
"        tail = dk_append(dk_copy_range(H, ge), dk_copy_enclosing_handlers(ge));\n"
"    }\n"
"    sub = dk_append(sub, tail);\n");
    if (tramp) buf_puts(out,
"    /* E7: a tail-resume handler under an active driver yields the resumed chain\n"
"     * rather than resuming inline; queue its H->next delivery (unless a no-op) so\n"
"     * it runs after the resumed chain settles, in nesting order. */\n"
"    if (H->tail_resume && g_dk_driver) {\n"
"        DK *__deliv = dk_copy_range(H->next, NULL);\n"
"        if (__dk_delivery_noop(__deliv)) dk_free(__deliv); else __dk_meta_push(__deliv);\n"
"        g_dk_case_reopen_hnode = H;  /* re-opening: case reads its enclosing markers */\n"
"        return H->handler(H->handler_env, arg, sub);  /* ends in dk_tail_resume -> longjmp */\n"
"    }\n");
    buf_puts(out,
"    g_dk_case_reopen_hnode = H;  /* re-opening: case reads its enclosing markers */\n");
    if (tramp) buf_puts(out,
"    /* A non-tail deep case that RE-OPENS an outer effect ends its body in that\n"
"     * interior perform; if the outer effect is tail-resumed, dk_tail_resume\n"
"     * longjmps to the entry driver and this dk_perform frame is unwound -- so the\n"
"     * `dk_free(sub)` below never runs and `sub` leaks once per re-opened perform\n"
"     * (O(N), docs/archive/cps-reopen-perform-onode-leak.md).  Give `sub` an owner\n"
"     * that survives the longjmp: register it for a boundary dk_free at the\n"
"     * outermost entry (__dk_reap_run), mirroring how every other per-perform node\n"
"     * on this path is owned.  This is safe against double-free -- only a TAIL case\n"
"     * hands its `sub` to the driver (the E7 branch above, which the driver frees),\n"
"     * and a case body only ever reaps COPIES of `subk`, never `subk`/`sub` itself\n"
"     * -- so reaping is `sub`'s sole disposal on both the return and longjmp paths.\n"
"     * We reap BEFORE the handler call so a longjmp cannot skip the registration. */\n"
"    __dk_reap_keep(sub);\n"
"    intptr_t r = H->handler(H->handler_env, arg, sub);\n"
/* case_delivers: a re-opening case already delivered its value through the
 * real chain (its __kont = dk_case_enclosing_real covers H->next); `r` is the
 * value that bubbled back from that delivery, so deliver it AGAIN and the rest
 * of the program runs twice (the measured spurious `1000` in
 * cps-case-reopen-marker-kont-truncates-capture).  Return it verbatim. */
"    return H->case_delivers ? r : dk_run_impl(H->next, r, false);\n"
"}\n");
    else buf_puts(out,
"    intptr_t r = H->handler(H->handler_env, arg, sub);\n"
"    dk_free(sub);\n"
"    return H->case_delivers ? r : dk_run_impl(H->next, r, false);\n"
"}\n"
"/* Abortive shift body: deliver the precomputed receiver result f(v),\n"
" * ignoring the captured sub-continuation (Turmeric shift never resumes it). */\n"
"static intptr_t __dk_abort_body(intptr_t env, DK *subk) { (void)subk; return env; }\n"
"\n");
}
