/* generated by tur (phase 2) */
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <setjmp.h>
extern void *malloc(size_t);
extern void free(void *);
extern void abort(void);
extern void *memset(void *, int, size_t);

/* tur_frame - phase 4 v1 lowering (from runtime.h) */
typedef void (*defer_fn_t)(void *env);
#define TUR_FRAME_MAX_DEFERS 32

typedef struct tur_frame {
    defer_fn_t defers[TUR_FRAME_MAX_DEFERS];
    void *envs[TUR_FRAME_MAX_DEFERS];
    int n;
    struct tur_frame *parent;
    bool may_capture;
} tur_frame;

static inline void tur_frame_init(tur_frame *f, tur_frame *parent) {
    f->n = 0; f->parent = parent; f->may_capture = false;
}
static inline int tur_frame_push_defer(tur_frame *f, defer_fn_t thunk, void *env) {
    if (f->n >= TUR_FRAME_MAX_DEFERS) return -1;
    f->defers[f->n] = thunk;
    f->envs[f->n] = env;
    f->n++;
    return 0;
}
static void tur_frame_fire_lifo(tur_frame *f) {
    for (int i = f->n - 1; i >= 0; i--) f->defers[i](f->envs[i]);
    f->n = 0;
}
static void tur_frame_fire_chain(tur_frame *f) {
    tur_frame *frames[64];
    int n_frames = 0;
    for (tur_frame *cur = f; cur != NULL && n_frames < 64; cur = cur->parent) {
        frames[n_frames++] = cur;
    }
    for (int i = n_frames - 1; i >= 0; i--) {
        tur_frame_fire_lifo(frames[i]);
    }
}

/* Exception handling - Phase 17 */
typedef struct tur_exception tur_exception;

struct tur_exception {
    int payload_type;      /* TypeKind enum value */
    void *payload;         /* The exception payload */
    int line;              /* Line where thrown */
    const char *file;      /* File where thrown */
    tur_exception *cause;  /* Chained exception */
};

typedef struct ExceptionHandler ExceptionHandler;
struct ExceptionHandler {
    jmp_buf jmp_buf;
    int active;
    tur_exception *caught;
    ExceptionHandler *parent;
};

static ExceptionHandler *global_handler_chain = NULL;

ExceptionHandler *exn_push_handler(void) {
    ExceptionHandler *h = (ExceptionHandler *)malloc(sizeof(ExceptionHandler));
    if (!h) { fprintf(stderr, "exn: out of memory\n"); abort(); }
    h->active = 1;
    h->caught = NULL;
    h->parent = global_handler_chain;
    global_handler_chain = h;
    return h;
}

ExceptionHandler *exn_pop_handler(void) {
    ExceptionHandler *old = global_handler_chain;
    if (old) global_handler_chain = old->parent;
    return old;
}

void tur_exception_free(tur_exception *exn) {
    if (!exn) return;
    if (exn->cause) { tur_exception_free(exn->cause); }
    free(exn->payload);
    free(exn);
}

bool tur_exception_matches(tur_exception *exn, int expected_type) {
    if (!exn) return false;
    if (exn->payload_type == expected_type) return true;
    if (expected_type == 0) return true;  /* TY_UNKNOWN = 0 = catch-all */
    return false;
}

void tur_throw(int payload_type, void *payload, int line, const char *file) {
    tur_exception *exn = (tur_exception *)malloc(sizeof(tur_exception));
    if (!exn) { abort(); }
    exn->payload_type = payload_type;
    exn->payload = payload;
    exn->line = line;
    exn->file = file;
    exn->cause = NULL;
    ExceptionHandler *h = global_handler_chain;
    if (h) {
        if (h->caught) tur_exception_free(h->caught);
        h->caught = exn;
        h->active = 0;
        longjmp(h->jmp_buf, 1);
    } else {
        tur_exception_free(exn);
        abort();
    }
}

/* rc<T> + weak<T> reference counting - Phase 9 */
/* Phase 10: GC color enum for Bacon-Rajan */
typedef enum { GC_WHITE, GC_GREY, GC_BLACK, GC_PURPLE } GcColor;

typedef void (*RcDropFn)(void *value);

typedef struct RcControlBlock RcControlBlock;

struct RcControlBlock {
    uint64_t strong_count;
    uint64_t weak_count;
    void *value;
    RcDropFn drop_fn;
    uint8_t value_type_kind;
    uint8_t color;           /* GC color */
    bool may_contain_cycles;  /* Hint for GC */
    uint8_t reserved[6];
};

#define GC_GLOBAL_REGISTRY_CAPACITY 4096
static RcControlBlock *gc_all_blocks[GC_GLOBAL_REGISTRY_CAPACITY];
static uint32_t gc_all_blocks_count = 0;

static void gc_register_block(RcControlBlock *cb) {
    if (!cb || gc_all_blocks_count >= GC_GLOBAL_REGISTRY_CAPACITY) return;
    gc_all_blocks[gc_all_blocks_count++] = cb;
    cb->color = GC_WHITE;
    cb->may_contain_cycles = true;
}

static void gc_unregister_block(RcControlBlock *cb) {
    if (!cb) return;
    for (uint32_t i = 0; i < gc_all_blocks_count; i++) {
        if (gc_all_blocks[i] == cb) {
            gc_all_blocks[i] = gc_all_blocks[gc_all_blocks_count - 1];
            gc_all_blocks_count--;
            break;
        }
    }
}

static void gc_on_strong_decrement(RcControlBlock *cb) {
    if (!cb) return;
    if (cb->weak_count > 0) {
        cb->color = GC_PURPLE;
    }
}

static void default_rc_drop_fn(void *value) {
    free(value);
}

RcControlBlock *rc_cb_alloc(size_t value_size, int value_type_kind, RcDropFn drop_fn) {
    size_t total_size = sizeof(RcControlBlock) + value_size;
    RcControlBlock *cb = (RcControlBlock *)malloc(total_size);
    if (!cb) { fprintf(stderr, "rc: out of memory\n"); abort(); }
    cb->strong_count = 1;
    cb->weak_count = 0;
    cb->value = (void *)(cb + 1);
    cb->drop_fn = drop_fn ? drop_fn : default_rc_drop_fn;
    cb->value_type_kind = value_type_kind;
    memset(cb->reserved, 0, sizeof(cb->reserved));
    /* Register with GC */
    gc_register_block(cb);
    return cb;
}

uint64_t rc_strong_increment(RcControlBlock *cb) {
    if (!cb) return 0;
    return ++cb->strong_count;
}

bool rc_strong_decrement(RcControlBlock *cb) {
    if (!cb) return false;
    cb->strong_count--;
    if (cb->strong_count == 0) {
        if (cb->weak_count > 0) {
            gc_on_strong_decrement(cb);
            return false;
        } else {
            gc_unregister_block(cb);
            if (cb->value) cb->drop_fn(cb->value);
            free(cb);
            return true;
        }
    }
    return false;
}

uint64_t rc_weak_increment(RcControlBlock *cb) {
    if (!cb) return 0;
    return ++cb->weak_count;
}

bool rc_weak_decrement(RcControlBlock *cb) {
    if (!cb) return false;
    cb->weak_count--;
    if (cb->weak_count == 0 && cb->strong_count == 0) {
        gc_unregister_block(cb);
        free(cb);
        return true;
    }
    return false;
}

uint64_t rc_strong_count(RcControlBlock *cb) {
    if (!cb) return 0;
    return cb->strong_count;
}

uint64_t rc_weak_count(RcControlBlock *cb) {
    if (!cb) return 0;
    return cb->weak_count;
}

bool rc_is_alive(RcControlBlock *cb) {
    if (!cb) return false;
    return cb->strong_count > 0;
}

RcControlBlock *rc_upgrade(RcControlBlock *cb) {
    if (!cb) return NULL;
    if (cb->strong_count > 0) {
        rc_strong_increment(cb);
        return cb;
    }
    return NULL;
}

void *rc_get_value(RcControlBlock *cb) {
    if (!cb) return NULL;
    return cb->value;
}

/* gc (Bacon-Rajan cycle collector) - Phase 10 */
#define GC_SUSPECT_THRESHOLD 128
#define GC_MAX_SUSPECTS 4096

typedef enum { GC_DISABLED, GC_MANUAL, GC_THRESHOLD } GcMode;

static RcControlBlock *gc_suspect_roots[GC_MAX_SUSPECTS];
static uint32_t gc_suspect_count = 0;
static RcControlBlock *gc_grey_queue[GC_MAX_SUSPECTS];
static uint32_t gc_grey_count = 0;
static GcMode gc_mode = GC_DISABLED;
static bool gc_enabled = false;

static void gc_set_color(RcControlBlock *cb, GcColor color) {
    if (cb) cb->color = color;
}

static GcColor gc_get_color(RcControlBlock *cb) {
    if (cb) return cb->color;
    return GC_WHITE;
}

static void gc_mark_phase(void) {
    for (uint32_t i = 0; i < gc_all_blocks_count; i++) {
        gc_all_blocks[i]->color = GC_WHITE;
    }
    for (uint32_t i = 0; i < gc_all_blocks_count; i++) {
        RcControlBlock *cb = gc_all_blocks[i];
        if (cb->strong_count > 0) {
            cb->color = GC_BLACK;
        }
    }
}

static void gc_collect(void) {
    if (!gc_enabled || gc_mode == GC_DISABLED) return;
    gc_grey_count = 0;
    gc_mark_phase();
}

static void gc_force(void) {
    gc_collect();
}

static void gc_enable(void) {
    gc_enabled = true;
}

static void gc_disable(void) {
    gc_enabled = false;
}

static void gc_set_mode(GcMode mode) {
    gc_mode = mode;
}

static bool gc_is_alive(RcControlBlock *cb) {
    if (!cb) return false;
    if (cb->strong_count > 0) return true;
    return (cb->color == GC_BLACK || cb->color == GC_GREY);
}

static int64_t __fn_7(int64_t);
static int64_t __fn_11(int64_t);
static int64_t __fn_15(int64_t);
static int64_t __fn_19(void *, int64_t);
static int64_t __fn_26(int64_t);
static int64_t __fn_34(void *, int64_t);
static int64_t test_nested_reset();
static int64_t test_shift_return_different();
static int64_t test_multiple_shifts();
static int64_t test_shift_ignores_k();
static int64_t test_reset_no_shift();
static int64_t test_deeply_nested_shift();
static int64_t __fn_7(int64_t v) {
        return ((v) * (INT64_C(2)));
}

static int64_t __fn_11(int64_t v) {
        return ((v) + (INT64_C(100)));
}

static int64_t __fn_15(int64_t v) {
        return ((v) * (INT64_C(2)));
}

struct __env_21 {int64_t x; };
static int64_t __fn_19(void * __env_p_22, int64_t v) {
        struct __env_21 *__env___env_21 = (struct __env_21 *)__env_p_22;
        return ((__env___env_21->x) + (v));
}

static int64_t __fn_26(int64_t v) {
        return INT64_C(42);
}

struct __env_36 {int64_t a; int64_t b; int64_t c; };
static int64_t __fn_34(void * __env_p_37, int64_t v) {
        struct __env_36 *__env___env_36 = (struct __env_36 *)__env_p_37;
        return ((__env___env_36->a) + (((__env___env_36->b) + (((__env___env_36->c) + (v))))));
}

static int64_t test_nested_reset() {
        int64_t __t0 = __fn_7(INT64_C(5));
        return ((INT64_C(1)) + (((INT64_C(10)) + (__t0))));
}

static int64_t test_shift_return_different() {
        int64_t __t1 = __fn_11(INT64_C(7));
        return __t1;
}

static int64_t test_multiple_shifts() {
        int64_t __t2;
        {
            int64_t __t3 = __fn_15(INT64_C(3));
            int64_t x_17 = __t3;
            (void)x_17;
            struct __env_21 __t5 = {.x = x_17};
            void *__t6 = &__t5;
            int64_t __t4 = __fn_19(__t6, INT64_C(4));
            __t2 = __t4;
        }
        return __t2;
}

static int64_t test_shift_ignores_k() {
        int64_t __t7 = __fn_26(INT64_C(10));
        return __t7;
}

static int64_t test_reset_no_shift() {
        return INT64_C(123);
}

static int64_t test_deeply_nested_shift() {
        int64_t __t8;
        {
            int64_t a_30 = INT64_C(1);
            (void)a_30;
            int64_t b_31 = INT64_C(2);
            (void)b_31;
            int64_t c_32 = INT64_C(3);
            (void)c_32;
            struct __env_36 __t10 = {.a = a_30, .b = b_31, .c = c_32};
            void *__t11 = &__t10;
            int64_t __t9 = __fn_34(__t11, INT64_C(10));
            __t8 = __t9;
        }
        return __t8;
}


int main(void) {
    return 0;
}
