/* generated by tur (phase 2) */
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
extern void *malloc(size_t);
extern void free(void *);

/* tur_frame - phase 4 v1 lowering (from runtime.h) */
typedef void (*defer_fn_t)(void *env);
#define TUR_FRAME_MAX_DEFERS 32

typedef struct tur_frame {
    defer_fn_t defers[TUR_FRAME_MAX_DEFERS];
    void *envs[TUR_FRAME_MAX_DEFERS];
    int n;
    struct tur_frame *parent;
    bool may_capture;
} tur_frame;

static inline void tur_frame_init(tur_frame *f, tur_frame *parent) {
    f->n = 0; f->parent = parent; f->may_capture = false;
}
static inline int tur_frame_push_defer(tur_frame *f, defer_fn_t thunk, void *env) {
    if (f->n >= TUR_FRAME_MAX_DEFERS) return -1;
    f->defers[f->n] = thunk;
    f->envs[f->n] = env;
    f->n++;
    return 0;
}
static void tur_frame_fire_lifo(tur_frame *f) {
    for (int i = f->n - 1; i >= 0; i--) f->defers[i](f->envs[i]);
    f->n = 0;
}

int main(void) {
    printf("%lld\n", (long long)(((((INT64_C(1)) + (INT64_C(2))) + (INT64_C(3))) + (INT64_C(4)))));
    printf("%lld\n", (long long)(((((INT64_C(100)) - (INT64_C(1))) - (INT64_C(2))) - (INT64_C(3)))));
    printf("%lld\n", (long long)((((INT64_C(2)) * (INT64_C(3))) * (INT64_C(4)))));
    printf("%lld\n", (long long)(((INT64_C(100)) / (INT64_C(7)))));
    printf("%lld\n", (long long)(((INT64_C(100)) % (INT64_C(7)))));
    puts((((INT64_C(1)) == (INT64_C(1)))) ? "true" : "false");
    puts((((INT64_C(1)) == (INT64_C(2)))) ? "true" : "false");
    puts((((INT64_C(1)) != (INT64_C(2)))) ? "true" : "false");
    puts((((INT64_C(1)) < (INT64_C(2)))) ? "true" : "false");
    puts((((INT64_C(5)) >= (INT64_C(5)))) ? "true" : "false");
    bool __t0 = ((INT64_C(1)) == (INT64_C(1)));
    if (__t0) {
        __t0 = ((INT64_C(0)) < (INT64_C(5)));
    }
    if (__t0) {
        __t0 = ((INT64_C(3)) != (INT64_C(4)));
    }
    puts((__t0) ? "true" : "false");
    bool __t1 = ((INT64_C(1)) == (INT64_C(2)));
    if (!__t1) {
        __t1 = ((INT64_C(5)) < (INT64_C(0)));
    }
    if (!__t1) {
        __t1 = ((INT64_C(7)) == (INT64_C(7)));
    }
    puts((__t1) ? "true" : "false");
    puts(((!(((INT64_C(1)) == (INT64_C(2)))))) ? "true" : "false");
    return 0;
}
