#!/usr/bin/env python3
"""
tools/doctest.py -- Generate doctest test files from stdlib ;;; Example blocks.

For each stdlib module that has at least one testable example, emits three files
into the output directory:

  <stem>.tur      -- standalone Turmeric program that prints one line per case
  <stem>.expected -- expected output lines, one per case
  <stem>.names    -- function names, one per case (for error messages)

Usage:
    python3 tools/doctest.py stdlib/ --out tests/doctest-generated/
    python3 tools/doctest.py stdlib/list.tur --out tests/doctest-generated/
"""

import argparse
import sys
from pathlib import Path

# Reuse the parser and doctest extractor from gendocs.py
sys.path.insert(0, str(Path(__file__).parent))
from gendocs import collect_tur_files, parse_tur_file, extract_doctest_cases


def _generate_test_source(source_path, cases):
    """
    Return the .tur source string for a generated doctest program.

    All testable calls are wrapped in a single (unsafe ...) block, which
    discharges the #{Unsafe} effect annotation required by most stdlib
    functions without needing per-call wrappers.
    """
    load_path = str(source_path).replace('\\', '/')

    header = [
        '; AUTO-GENERATED by tools/doctest.py -- do not edit.',
        f'(load "{load_path}")',
        '',
    ]

    if not cases:
        return '\n'.join(header + ['; no testable examples']) + '\n'

    body = []
    for i, case in enumerate(cases):
        if i > 0:
            body.append('')
        for setup in case.setup_lines:
            body.append(f'  {setup}')
        body.append(f'  ; {case.defn_name}: {case.expr}  ; => {case.expected}')
        body.append(f'  (println {case.expr})')

    # Closing ) goes on the same line as the last statement
    unsafe_lines = ['(unsafe'] + body[:-1] + [body[-1] + ')']
    return '\n'.join(header + unsafe_lines) + '\n'


def main():
    parser = argparse.ArgumentParser(
        description='Generate doctest files from Turmeric stdlib ;;; Example blocks.'
    )
    parser.add_argument(
        'source',
        help='Path to a .tur file or a directory containing .tur files',
    )
    parser.add_argument(
        '--out', '-o',
        default='tests/doctest-generated',
        help='Output directory for generated test files (default: tests/doctest-generated)',
    )
    args = parser.parse_args()

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    # Remove stale generated files so modules with 0 testable cases don't linger
    for old in out_dir.glob('*.tur'):
        old.unlink()
    for old in out_dir.glob('*.expected'):
        old.unlink()
    for old in out_dir.glob('*.names'):
        old.unlink()

    source_path = Path(args.source)
    source_root = source_path.resolve() if source_path.is_dir() else source_path.parent.resolve()

    tur_files = collect_tur_files(args.source)
    if not tur_files:
        print(f'No .tur files found in {args.source}', file=sys.stderr)
        sys.exit(1)

    total_cases = 0
    total_files = 0
    annotated = []

    for f in tur_files:
        try:
            module = parse_tur_file(f)
        except Exception as e:
            print(f'  Warning: failed to parse {f}: {e}', file=sys.stderr)
            continue

        cases = []
        for defn in module['definitions']:
            doc = defn.get('docstring')
            if doc:
                cases.extend(extract_doctest_cases(module['name'], defn['name'], doc))
                # Cases carrying an explicit `; doctest: <reason>` opt-out.
                # Reported rather than dropped quietly, so a module that stops
                # being covered says so instead of just getting smaller.
                for defn_name, reason in getattr(
                        extract_doctest_cases, 'last_skipped', []):
                    annotated.append((module['name'], defn_name, reason))

        if not cases:
            continue

        # Derive a collision-free stem from the path relative to the source root.
        # e.g. stdlib/tidal/pattern.tur -> tidal-pattern
        try:
            rel = Path(f).resolve().relative_to(source_root)
            stem = '-'.join(rel.with_suffix('').parts)
        except ValueError:
            stem = Path(f).stem

        source = _generate_test_source(f, cases)
        expected_text = '\n'.join(c.expected for c in cases) + '\n'
        names_text = '\n'.join(c.defn_name for c in cases) + '\n'

        (out_dir / f'{stem}.tur').write_text(source, encoding='utf-8')
        (out_dir / f'{stem}.expected').write_text(expected_text, encoding='utf-8')
        (out_dir / f'{stem}.names').write_text(names_text, encoding='utf-8')

        total_cases += len(cases)
        total_files += 1
        print(f'  Generated {out_dir}/{stem}.tur ({len(cases)} cases)')

    print(f'\nDone. {total_files} files, {total_cases} testable cases -> {out_dir}/')
    if annotated:
        print(f'\n{len(annotated)} example(s) opted out via `; doctest:`:')
        for mod, defn_name, reason in annotated:
            print(f'  {mod}:{defn_name} -- {reason}')


if __name__ == '__main__':
    main()
