#!/usr/bin/env python3
"""gen-r7rs-inc.py -- r7rs-lang-plan T0/T1: the shared C of `#lang r7rs`'s
numbers, copied for the compiled back end.

Two C files are the ONE implementation of their job for every back end:

  src/compiler/r7rs_bignum.inc     exact integers outside int64 (T1)
  src/compiler/r7rs_numsyntax.inc  the R7RS number syntax (T0; needs bignum)

The source reader (src/compiler/reader.c) and the interpreter's natives
(src/turi/interpreter_natives.c) #include them.  The compiled back end cannot,
because a program's C is built away from this tree, so this script copies
each into the file-scope C block of a stdlib file, followed by the inline-C
wrappers the prelude calls:

  stdlib/r7rs/bignum.tur      the bignum core and its wrappers
  stdlib/r7rs/numsyntax.tur   the number parser and its wrappers

The prelude loads bignum.tur first, so the parser's block sees the core.
tests/check-r7rs-inc-sync.sh checks each block is byte for byte its .inc.
Edit an .inc (or a wrapper below), then run:

  python3 tools/gen-r7rs-inc.py
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

BIGNUM_HEAD = """\
;;; r7rs/bignum -- exact integers outside int64 for `#lang r7rs` (T1).
;;;
;;; GENERATED by tools/gen-r7rs-inc.py -- do not edit; regenerate.  The C
;;; below is src/compiler/r7rs_bignum.inc, which the interpreter #includes
;;; (registering natives over these wrappers), so both back ends compute a
;;; bignum with the same code.  A bignum crosses as its decimal spelling.
;;;
;;; Since: r7rs-lang-plan T1
;; The prelude loads this file; nothing else should.
"""

BIGNUM_TAIL = """\
;;; r7rs-int-ovf?__ -- internal: the int64 op (0 +, 1 -, 2 *) on a and b
;;; overflows, so the answer is a bignum.
(defn r7rs-int-ovf?__ [op : int a : int b : int] : bool
  ```c
  int64_t r;
  return op == 0 ? __builtin_add_overflow(a, b, &r) : op == 1 ? __builtin_sub_overflow(a, b, &r) : __builtin_mul_overflow(a, b, &r);
  ```)
;;; r7rs-big-op__ -- internal: one exact-integer operation on decimal
;;; spellings (the R7BN_* codes: 0 + 1 - 2 * 3 quotient 4 remainder 5 modulo
;;; 6 gcd 7 expt 8 isqrt 9 negate).
(defn r7rs-big-op__ [op : int a : cstr b : cstr] : cstr
  ```c
  return r7rs_big_op((int)op, a, b);
  ```)
;;; r7rs-big-cmp__ -- internal: -1, 0 or 1.
(defn r7rs-big-cmp__ [a : cstr b : cstr] : int
  ```c
  return r7rs_big_cmp(a, b);
  ```)
;;; r7rs-big-cmp-float__ -- internal: an exact integer against a double,
;;; exactly: -1, 0, 1, or 2 for a NaN.
(defn r7rs-big-cmp-float__ [a : cstr f : float] : int
  ```c
  return r7rs_big_cmp_float(a, f);
  ```)
;;; r7rs-big->float__ -- internal: the nearest double.
(defn r7rs-big->float__ [a : cstr] : float
  ```c
  return r7rs_big_to_float(a);
  ```)
;;; r7rs-float->big__ -- internal: a finite integral double, exactly.
(defn r7rs-float->big__ [f : float] : cstr
  ```c
  return r7rs_big_of_float(f);
  ```)
;;; r7rs-big-radix__ -- internal: the spelling in radix 2, 8, 10 or 16.
(defn r7rs-big-radix__ [a : cstr radix : int] : cstr
  ```c
  return r7rs_big_radix(a, (int)radix);
  ```)
;;; r7rs-exact-of-float__ -- internal: T2 -- the exact value of a finite
;;; double, spelled "n" or "n/d".
(defn r7rs-exact-of-float__ [f : float] : cstr
  ```c
  return r7rs_big_exact_of_float(f);
  ```)
;;; r7rs-ratio->float__ -- internal: T2 -- the double nearest n/d.
(defn r7rs-ratio->float__ [n : cstr d : cstr] : float
  ```c
  return r7rs_ratio_to_float(n, d);
  ```)
;;; r7rs-ratio-part__ -- internal: T2 -- the numerator (0) or denominator
;;; (1) of an "n/d" spelling.
(defn r7rs-ratio-part__ [s : cstr which : int] : cstr
  ```c
  return r7rs_ratio_part(s, (int)which);
  ```)
;;; r7rs-big-fits?__ -- internal: the spelling is an int64.
(defn r7rs-big-fits?__ [a : cstr] : bool
  ```c
  int64_t v; return r7rs_big_fits(a, &v) != 0;
  ```)
;;; r7rs-big-int__ -- internal: the int64 a fitting spelling is.
(defn r7rs-big-int__ [a : cstr] : int
  ```c
  int64_t v = 0; (void)r7rs_big_fits(a, &v); return v;
  ```)
"""

NUMSYNTAX_HEAD = """\
;;; r7rs/numsyntax -- the R7RS number syntax behind `string->number` and `read`.
;;;
;;; GENERATED by tools/gen-r7rs-inc.py -- do not edit; regenerate.  The C
;;; below is src/compiler/r7rs_numsyntax.inc, which the source reader and the
;;; interpreter #include (the interpreter registers natives over the
;;; wrappers), so all three read a number the same way.  It calls the bignum
;;; core of stdlib/r7rs/bignum.tur, which the prelude loads first.
;;;
;;; Since: r7rs-lang-plan T0
;; The prelude loads this file; nothing else should.
"""

NUMSYNTAX_TAIL = """\
;;; r7rs-numsyn-kind__ -- internal: what s reads as in radix (a prefix
;;; overrides it): 0 not a number, 1 an exact integer, 2 an inexact real,
;;; 3 refused (r7rs-numsyn-why__ says why), 4 an exact integer outside int64,
;;; 5 an exact non-integer and 6 a non-real complex number (T6)
;;; (r7rs-numsyn-big__ spells them).
(defn r7rs-numsyn-kind__ [s : cstr radix : int] : int
  ```c
  r7rs_ns_result res; r7rs_ns_parse(s, strlen(s), (int)radix, &res); free(res.big); return res.kind;
  ```)
;;; r7rs-numsyn-int__ -- internal: the exact integer s reads as (kind 1).
(defn r7rs-numsyn-int__ [s : cstr radix : int] : int
  ```c
  r7rs_ns_result res; r7rs_ns_parse(s, strlen(s), (int)radix, &res); free(res.big); return res.i;
  ```)
;;; r7rs-numsyn-float__ -- internal: the inexact real s reads as (kind 2).
(defn r7rs-numsyn-float__ [s : cstr radix : int] : float
  ```c
  r7rs_ns_result res; r7rs_ns_parse(s, strlen(s), (int)radix, &res); free(res.big); return res.f;
  ```)
;;; r7rs-numsyn-why__ -- internal: why s is refused (kind 3), else "".
(defn r7rs-numsyn-why__ [s : cstr radix : int] : cstr
  ```c
  r7rs_ns_result res; r7rs_ns_parse(s, strlen(s), (int)radix, &res); free(res.big); return (char *)(res.why ? res.why : "");
  ```)
;;; r7rs-numsyn-big__ -- internal: the spelling of the bignum (kind 4), the
;;; "n/d" of the ratio (kind 5) or the "<re> <im>" of the complex number
;;; (kind 6) s reads as, else "".
(defn r7rs-numsyn-big__ [s : cstr radix : int] : cstr
  ```c
  r7rs_ns_result res; r7rs_ns_parse(s, strlen(s), (int)radix, &res);
  if (res.kind == R7NS_BIG || res.kind == R7NS_RATIO || res.kind == R7NS_COMPLEX) return res.big;
  char *e = (char *)malloc(1); if (e) *e = 0; return e;
  ```)
;;; r7rs-numsyn-part__ -- internal (T6): part `which` (0 real, 1 imaginary)
;;; of a "<re> <im>" complex spelling.
(defn r7rs-numsyn-part__ [s : cstr which : int] : cstr
  ```c
  return r7rs_ns_complex_part(s, (int)which);
  ```)
"""

PAIRS = [
    ("src/compiler/r7rs_bignum.inc", "stdlib/r7rs/bignum.tur", BIGNUM_HEAD, BIGNUM_TAIL),
    ("src/compiler/r7rs_numsyntax.inc", "stdlib/r7rs/numsyntax.tur", NUMSYNTAX_HEAD, NUMSYNTAX_TAIL),
]


def main():
    for inc, out, head, tail in PAIRS:
        with open(os.path.join(ROOT, inc), encoding="ascii") as f:
            c = f.read()
        with open(os.path.join(ROOT, out), "w", encoding="ascii", newline="\n") as f:
            f.write(head + "```c\n" + c + "```\n\n" + tail)
        print("wrote " + out)


if __name__ == "__main__":
    main()
