#!/usr/bin/env python3
"""gen-r7rs-numsyntax.py -- r7rs-lang-plan T0: the R7RS number parser for the
compiled back end.

src/compiler/r7rs_numsyntax.inc is the ONE parser for `#lang r7rs` number
syntax.  The source reader (src/compiler/reader.c) and the interpreter's
natives (src/turi/interpreter_natives.c) #include it; the compiled back end
cannot, because a program's C is built away from this tree, so this script
copies the text into the file-scope C block of

  stdlib/r7rs/numsyntax.tur    the block plus the four inline-C wrappers
                               `string->number` and `read` call

tests/check-r7rs-numsyntax-sync.sh checks the copy is byte for byte the
.inc.  Edit the .inc, then run:

  python3 tools/gen-r7rs-numsyntax.py
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INC = os.path.join(ROOT, "src", "compiler", "r7rs_numsyntax.inc")
OUT = os.path.join(ROOT, "stdlib", "r7rs", "numsyntax.tur")

HEAD = """\
;;; r7rs/numsyntax -- the R7RS number syntax behind `string->number` and `read`.
;;;
;;; GENERATED by tools/gen-r7rs-numsyntax.py -- do not edit; regenerate.  The C
;;; below is src/compiler/r7rs_numsyntax.inc, which the source reader and the
;;; interpreter #include (the interpreter registers natives over the four
;;; wrappers), so all three read a number the same way.
;;;
;;; Since: r7rs-lang-plan T0
;; The prelude loads this file; nothing else should.
"""

TAIL = """\
;;; r7rs-numsyn-kind__ -- internal: what s reads as in radix (a prefix
;;; overrides it): 0 not a number, 1 an exact integer, 2 an inexact real,
;;; 3 refused (r7rs-numsyn-why__ says why).
(defn r7rs-numsyn-kind__ [s : cstr radix : int] : int
  ```c
  r7rs_ns_result res; r7rs_ns_parse(s, strlen(s), (int)radix, &res); return res.kind;
  ```)
;;; r7rs-numsyn-int__ -- internal: the exact integer s reads as (kind 1).
(defn r7rs-numsyn-int__ [s : cstr radix : int] : int
  ```c
  r7rs_ns_result res; r7rs_ns_parse(s, strlen(s), (int)radix, &res); return res.i;
  ```)
;;; r7rs-numsyn-float__ -- internal: the inexact real s reads as (kind 2).
(defn r7rs-numsyn-float__ [s : cstr radix : int] : float
  ```c
  r7rs_ns_result res; r7rs_ns_parse(s, strlen(s), (int)radix, &res); return res.f;
  ```)
;;; r7rs-numsyn-why__ -- internal: why s is refused (kind 3), else "".
(defn r7rs-numsyn-why__ [s : cstr radix : int] : cstr
  ```c
  r7rs_ns_result res; r7rs_ns_parse(s, strlen(s), (int)radix, &res); return (char *)(res.why ? res.why : "");
  ```)
"""


def main():
    with open(INC, encoding="ascii") as f:
        c = f.read()
    with open(OUT, "w", encoding="ascii", newline="\n") as f:
        f.write(HEAD + "```c\n" + c + "```\n\n" + TAIL)
    print("wrote " + os.path.relpath(OUT, ROOT))


if __name__ == "__main__":
    main()
