#!/usr/bin/env python3
"""
tools/genspices.py -- Generate the Spices directory page.

Data source priority:
  1. ../turmeric-spices/README.md  (local sibling repo, relative to CWD)
  2. https://raw.githubusercontent.com/rjungemann/turmeric-spices/main/README.md

Usage:
    python3 tools/genspices.py [--out docs/html/spices/]
"""

import argparse
import re
import sys
import urllib.request
from pathlib import Path

import markdown as md_lib

# Share constants and helpers from genguides.py (same tools/ directory).
sys.path.insert(0, str(Path(__file__).parent))
from genguides import (SIDEBAR_TOGGLE_JS, SYNTAX_TOGGLE_JS,
                       TURMERIC_HIGHLIGHT_JS, GUIDE_CSS,
                       inject_syntax_toggles, toc_tokens_to_sidebar)

GITHUB_BASE = 'https://github.com/rjungemann/turmeric-spices'
GITHUB_RAW_README = 'https://raw.githubusercontent.com/rjungemann/turmeric-spices/main/README.md'
LOCAL_README = Path('../turmeric-spices/README.md')
STYLE_REL = '../api/style.css'

PAGE_HEADER = '''\
  <header class="site-header">
    <button class="hamburger" aria-label="Toggle navigation">
      <span></span><span></span><span></span>
    </button>
    <a class="nav-logo" href="/">
      <img src="/logo-icon.svg" width="28" height="28" alt="">
      <img src="/logo.svg" width="101" height="28" alt="Turmeric">
    </a>
    <nav>
      <a href="/docs/html/guides/">Guides</a>
      <a href="/docs/html/api/">API Docs</a>
      <a href="/docs/html/spices/" class="active">Spices</a>
      <a href="/try">Try It</a>
    </nav>
  </header>'''


def load_readme() -> tuple[str, str]:
    """Return (text, source_label). Tries local sibling repo first, then GitHub."""
    if LOCAL_README.exists():
        return LOCAL_README.read_text(encoding='utf-8'), str(LOCAL_README)
    print(f'  {LOCAL_README} not found locally; fetching from GitHub...')
    try:
        with urllib.request.urlopen(GITHUB_RAW_README, timeout=15) as resp:
            return resp.read().decode('utf-8'), GITHUB_RAW_README
    except Exception as exc:
        sys.exit(f'error: could not load spices README: {exc}')


def rewrite_links(text: str) -> str:
    """Point relative spice subdir links at the canonical GitHub tree URL."""
    return re.sub(
        r'\[([^\]]+)\]\((spices/[^)]+)\)',
        lambda m: f'[{m.group(1)}]({GITHUB_BASE}/tree/main/{m.group(2)})',
        text,
    )


def render_page(text: str, source: str, out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)

    text = rewrite_links(text)

    conv = md_lib.Markdown(
        extensions=['fenced_code', 'tables', 'toc'],
        extension_configs={'toc': {'permalink': False}},
    )
    body_html = conv.convert(text)
    body_html = inject_syntax_toggles(body_html)
    toc_tokens = getattr(conv, 'toc_tokens', [])

    sidebar_items = toc_tokens_to_sidebar(toc_tokens)
    sidebar_html = (
        '<div style="margin-bottom:1.25rem">'
        '<a href="/" style="font-size:0.8rem;color:var(--text-sec)">← Home</a>'
        '</div>\n      '
        f'<h3>On this page</h3>\n      <ul>{sidebar_items}</ul>'
    )

    html = f'''<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Spices | Turmeric</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@300;400;500&display=swap" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/@fontsource/iosevka@5/400.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/@fontsource/iosevka@5/500.css" rel="stylesheet">
  <link rel="stylesheet" href="{STYLE_REL}">
  <style>
{GUIDE_CSS}
  </style>
</head>
<body>
{PAGE_HEADER}
{SIDEBAR_TOGGLE_JS}
  <div class="page-layout">
    <div class="sidebar">
      {sidebar_html}
    </div>
    <div class="content guide-content">
      {body_html}
    </div>
  </div>
  <footer class="site-footer">
    Auto-generated by <code>tools/genspices.py</code> &mdash; source: <code>{source}</code>
  </footer>
{TURMERIC_HIGHLIGHT_JS}
{SYNTAX_TOGGLE_JS}
</body>
</html>
'''
    out_path = out_dir / 'index.html'
    out_path.write_text(html, encoding='utf-8')
    print(f'  index.html  (source: {source})')


def main() -> None:
    p = argparse.ArgumentParser(description='Generate the Spices directory page.')
    p.add_argument('--out', default='docs/html/spices/', help='Output directory')
    args = p.parse_args()

    text, source = load_readme()
    out_dir = Path(args.out)
    print('Generating spices page:')
    render_page(text, source, out_dir)
    print(f'Done: {out_dir / "index.html"}')


if __name__ == '__main__':
    main()
