#!/usr/bin/env python3
"""
tools/snapshot-diff-summary.py — Classify a git diff over expected.c snapshots.

Usage:
    git diff [ref] -- 'tests/fixtures/**/expected.c' | python3 tools/snapshot-diff-summary.py
    python3 tools/snapshot-diff-summary.py [--from REF] [--to REF] [--list-body]

Output:
    1380 preamble-only, 42 mangling-only, 20 body -- review the 20.
    <list of body files when --list-body is given>

Classification (per file):
    preamble-only -- every diff hunk touches only the boilerplate header region
                     (includes, typedefs, static tur_ helpers, phase comments).
    mangling-only -- every diff hunk changes only identifier spellings that match
                     a known mangling rewrite (e.g. _hy infix for kebab '-').
    body          -- anything else; flagged for human review.
"""

import re
import subprocess
import sys
from argparse import ArgumentParser
from dataclasses import dataclass, field
from typing import Optional


# ---------------------------------------------------------------------------
# Preamble detection
# ---------------------------------------------------------------------------
# Lines in the generated preamble match these patterns.  A diff hunk is
# "preamble" if every changed line (+ or -) matches at least one of these.

_PREAMBLE_LINE_PATTERNS: list[re.Pattern] = [pat for pat in (re.compile(p) for p in [
    r'^\s*$',                                   # blank
    r'^[+-]\s*$',                               # blank diff line
    r'^[+-]?\s*/\*.*\*/',                       # single-line block comment
    r'^[+-]?\s*/\*',                            # start of block comment
    r'^[+-]?\s*\*',                             # continuation/end of block comment
    r'^[+-]?\s*#\s*(define|undef|pragma|include|ifndef|ifdef|endif|if|else)', # preprocessor
    r'^[+-]?\s*typedef\s',                      # typedef
    r'^[+-]?\s*typedef\s|^[+-]?\s*} \w+;',     # typedef close
    r'^[+-]?\s*static\s+(?:inline\s+)?(?:int|bool|void|int64_t|uint\w+|float|double|size_t|tur_)\w*[\s*]', # static tur helper
    r'^[+-]?\s*int64_t\s+g_tur_',              # global tur vars
    r'^[+-]?\s*static\s+int64_t\s+g_tur_',
    r'^[+-]?\s*extern\s',                       # extern declarations
    r'^[+-]/\* generated by tur',               # header comment
])]


def _is_preamble_line(line: str) -> bool:
    """Return True if a diff content line looks like preamble boilerplate."""
    stripped = line[1:] if line and line[0] in ('+', '-') else line
    # Lines starting with @@ or \ are hunk headers / "no newline" markers
    if line.startswith('@@') or line.startswith('\\'):
        return True
    for pat in _PREAMBLE_LINE_PATTERNS:
        if pat.match(line):
            return True
    # Braces/semicolons closing preamble structs
    if re.match(r'^[+-]\s*[{}];?\s*$', line):
        return True
    # Lines that are continuations of struct/helper bodies (whitespace + C)
    if re.match(r'^[+-]\s{4,}', line) and re.search(r'tur_[a-z_]+|__tur_|int64_t|uint\d+_t', line):
        return True
    return False


# ---------------------------------------------------------------------------
# Mangling detection
# ---------------------------------------------------------------------------
# A diff hunk is "mangling-only" if every changed pair differs only by
# identifier renames matching a known mangling transform.
#
# Current manglings:
#   kebab '-'  -> '_hy'   (e.g. list-concat -> list_hyconcat)
#   '/'        -> '_sl'   (e.g. list/concat -> list_slconcat)
#   '>'        -> '_gt'
#   '<'        -> '_lt'
#   '?'        -> '_qu'
#   '!'        -> '_ex'
#   '='        -> '_eq'   (where it appears as part of an operator name)
#   '*'        -> '_st'

_MANGLE_PAIRS = [
    ('-', r'_hy'),
    ('/', r'_sl'),
    ('>', r'_gt'),
    ('<', r'_lt'),
    ('?', r'_qu'),
    ('!', r'_ex'),
    ('=', r'_eq'),
    ('*', r'_st'),
]

# Build a regex that matches any mangled identifier token
_MANGLED_TOKEN = re.compile(r'\b\w+(?:_hy|_sl|_gt|_lt|_qu|_ex|_eq|_st)\w*\b')


def _mangle_identifier(name: str) -> str:
    """Apply the current mangling scheme to a Turmeric identifier."""
    for char, repl in _MANGLE_PAIRS:
        name = name.replace(char, repl)
    return name


def _lines_differ_only_by_mangling(removed: list[str], added: list[str]) -> bool:
    """
    Return True if every (removed, added) pair of lines differs only by
    identifier mangling rewrites.  We pair up lines positionally; if the
    counts differ it's a structural change, not just a rename.
    """
    if len(removed) != len(added):
        return False
    for r_line, a_line in zip(removed, added):
        # Strip the leading +/- before comparing
        r = r_line[1:] if r_line and r_line[0] == '-' else r_line
        a = a_line[1:] if a_line and a_line[0] == '+' else a_line
        # Tokenise both lines; compare token-by-token
        r_tokens = re.findall(r'\w+|[^\w\s]', r)
        a_tokens = re.findall(r'\w+|[^\w\s]', a)
        if len(r_tokens) != len(a_tokens):
            return False
        for rt, at in zip(r_tokens, a_tokens):
            if rt == at:
                continue
            # Check if mangling rt -> at explains the difference
            if _mangle_identifier(rt) == at:
                continue
            # Check the inverse direction (for snapshot that already uses new mangling)
            if rt == _mangle_identifier(at):
                continue
            # Check whether both tokens contain mangling escapes (rename in progress)
            if _MANGLED_TOKEN.match(rt) and _MANGLED_TOKEN.match(at):
                continue
            return False
    return True


# ---------------------------------------------------------------------------
# Diff parser
# ---------------------------------------------------------------------------

@dataclass
class FileDiff:
    path: str
    hunks: list[tuple[list[str], list[str]]] = field(default_factory=list)  # (removed, added) per hunk


def _parse_diff(text: str) -> list[FileDiff]:
    """Parse a unified git diff into a list of FileDiff objects."""
    files: list[FileDiff] = []
    current: Optional[FileDiff] = None
    removed: list[str] = []
    added: list[str] = []

    def _flush_hunk() -> None:
        if current is not None and (removed or added):
            current.hunks.append((removed[:], added[:]))
        removed.clear()
        added.clear()

    for line in text.splitlines():
        if line.startswith('diff --git'):
            _flush_hunk()
            current = None
        elif line.startswith('+++ b/'):
            path = line[6:]
            if 'tests/fixtures/' in path and path.endswith('expected.c'):
                _flush_hunk()
                current = FileDiff(path=path)
                files.append(current)
                removed.clear()
                added.clear()
            else:
                current = None
        elif line.startswith('@@'):
            _flush_hunk()
        elif current is not None:
            if line.startswith('-') and not line.startswith('---'):
                removed.append(line)
            elif line.startswith('+') and not line.startswith('+++'):
                added.append(line)

    _flush_hunk()
    return files


# ---------------------------------------------------------------------------
# Classification
# ---------------------------------------------------------------------------

def _classify(fd: FileDiff) -> str:
    """Return 'preamble-only', 'mangling-only', or 'body'."""
    if not fd.hunks:
        return 'preamble-only'

    all_preamble = True
    all_mangling = True

    for removed, added in fd.hunks:
        all_changed = removed + added
        # Check preamble: every changed line looks like boilerplate
        if not all(_is_preamble_line(ln) for ln in all_changed):
            all_preamble = False
        # Check mangling: changes are only identifier renames
        if not _lines_differ_only_by_mangling(removed, added):
            all_mangling = False

    if all_mangling:
        return 'mangling-only'
    if all_preamble:
        return 'preamble-only'
    return 'body'


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def _get_diff(from_ref: Optional[str], to_ref: Optional[str]) -> str:
    cmd = ['git', 'diff']
    if from_ref:
        cmd.append(from_ref)
    if to_ref:
        cmd.append(to_ref)
    cmd += ['--', 'tests/fixtures/**/expected.c', 'tests/fixtures/*/expected.c']
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f'git diff failed: {result.stderr}', file=sys.stderr)
        sys.exit(1)
    return result.stdout


def main() -> None:
    parser = ArgumentParser(description=__doc__)
    parser.add_argument('--from', dest='from_ref', metavar='REF',
                        help='Base ref for git diff (default: working tree vs index)')
    parser.add_argument('--to', dest='to_ref', metavar='REF',
                        help='Target ref for git diff')
    parser.add_argument('--list-body', action='store_true',
                        help='Print the paths of body-classified files')
    parser.add_argument('--list-all', action='store_true',
                        help='Print path and classification for every changed file')
    args = parser.parse_args()

    # Read diff from stdin if piped, otherwise invoke git diff
    if not sys.stdin.isatty():
        diff_text = sys.stdin.read()
    else:
        diff_text = _get_diff(args.from_ref, args.to_ref)

    if not diff_text.strip():
        print('No snapshot changes found.')
        return

    files = _parse_diff(diff_text)
    if not files:
        print('No expected.c files changed in diff.')
        return

    buckets: dict[str, list[str]] = {'preamble-only': [], 'mangling-only': [], 'body': []}
    for fd in files:
        cat = _classify(fd)
        buckets[cat].append(fd.path)

    n_pre = len(buckets['preamble-only'])
    n_mangle = len(buckets['mangling-only'])
    n_body = len(buckets['body'])
    total = n_pre + n_mangle + n_body

    summary_parts = []
    if n_pre:
        summary_parts.append(f'{n_pre} preamble-only')
    if n_mangle:
        summary_parts.append(f'{n_mangle} mangling-only')
    if n_body:
        summary_parts.append(f'{n_body} body')

    if n_body:
        print(f"{', '.join(summary_parts)} -- review the {n_body}.")
    else:
        print(f"{', '.join(summary_parts)} -- no body changes, safe to land.")

    if args.list_body and buckets['body']:
        print()
        print('Body-changed files (require human review):')
        for path in sorted(buckets['body']):
            print(f'  {path}')

    if args.list_all:
        print()
        print('All changed snapshots:')
        for cat in ('preamble-only', 'mangling-only', 'body'):
            for path in sorted(buckets[cat]):
                print(f'  [{cat:15}]  {path}')


if __name__ == '__main__':
    main()
