/* generated by tur (phase 2) */
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
extern void *malloc(size_t);
extern void free(void *);

/* tur_frame - phase 4 v1 lowering (from runtime.h) */
typedef void (*defer_fn_t)(void *env);
#define TUR_FRAME_MAX_DEFERS 32

typedef struct tur_frame {
    defer_fn_t defers[TUR_FRAME_MAX_DEFERS];
    void *envs[TUR_FRAME_MAX_DEFERS];
    int n;
    struct tur_frame *parent;
    bool may_capture;
} tur_frame;

static inline void tur_frame_init(tur_frame *f, tur_frame *parent) {
    f->n = 0; f->parent = parent; f->may_capture = false;
}
static inline int tur_frame_push_defer(tur_frame *f, defer_fn_t thunk, void *env) {
    if (f->n >= TUR_FRAME_MAX_DEFERS) return -1;
    f->defers[f->n] = thunk;
    f->envs[f->n] = env;
    f->n++;
    return 0;
}
static void tur_frame_fire_lifo(tur_frame *f) {
    for (int i = f->n - 1; i >= 0; i--) f->defers[i](f->envs[i]);
    f->n = 0;
}

struct __defer_env_1 {int64_t x; };

static void __defer_2(void *__env) {
    struct __defer_env_1 *__e = (struct __defer_env_1 *)__env;
    printf("%lld\n", (long long)(__e->x));
}

int main() {
        {
            int64_t x_1 = INT64_C(10);
            (void)x_1;
            tur_frame __frame_0;
            tur_frame_init(&__frame_0, NULL);
            struct __defer_env_1 __t3 = {.x = x_1};
            tur_frame_push_defer(&__frame_0, __defer_2, &__t3);
            x_1 = INT64_C(20);
            tur_frame_fire_lifo(&__frame_0);
        }
        int64_t __t4;
        __t4 = INT64_C(0);
        return (int)__t4;
}


