/* jit_win_prelude.h -- c2mir-on-MinGW compat prelude.
 *
 * AUTO-CONVERTED once from the bring-up worksheet; from here on edit
 * these literals directly, the same way JIT_PRELUDE is maintained.
 * See the JIT_PRELUDE_WIN usage note in jit_engine.c. */
#ifndef TUR_JIT_WIN_PRELUDE_H
#define TUR_JIT_WIN_PRELUDE_H
static const char JIT_PRELUDE_WIN[] =
  "/* mircwin: c2mir-on-MinGW compat prelude (prototype for JIT_PRELUDE).\n"
  " *\n"
  " * c2mir cannot digest the UCRT/MinGW system headers (vadefs.h hard-#errors\n"
  " * without GCC/MSVC va intrinsics; winnt.h pulls the GCC-internal\n"
  " * x86intrin.h).  Rather than teach it the SDK, neutralize it: predefine every\n"
  " * include guard the emitted TU can reach, so `#include <stdio.h>` opens the\n"
  " * file and expands to NOTHING, then declare the small surface the emitted\n"
  " * code actually uses.  Types embedded by value in shared structs are spelled\n"
  " * with the host's measured layout (gcc 16 / UCRT64, sizes.c probe):\n"
  " * jmp_buf 256B align 16; pthread mutex/cond = intptr_t; once = long;\n"
  " * key = unsigned; pthread_t = uintptr_t; fd_set 520B; SOCKET 8B.\n"
  " * Symbols resolve at MIR-link time against the host via dlsym(RTLD_DEFAULT).\n"
  " */\n"
  "\n"
  "/* ---- include-guard stuffing ------------------------------------------ */\n"
  "#define _INC_STDIO\n"
  "#define _INC_STDLIB\n"
  "#define _INC_STRING\n"
  "#define _INC_SETJMP\n"
  "#define WIN_PTHREADS_H\n"
  "#define WIN_PTHREADS_SCHED_H\n"
  "#define _WINSOCK2API_\n"
  "#define _WINDOWS_\n"
  "#define _IO_H_\n"
  "#define _INC_FCNTL\n"
  "#define _MATH_H_\n"
  "#define _TIME_H_\n"
  "#define _INC_ERRNO\n"
  "#define _UNISTD_H\n"
  "#define _WS2TCPIP_H_\n"
  "#define _INC_PROCESS\n"
  "#define _INC_SIGNAL\n"
  "#define _INC_CORECRT\n"
  "#define _INC_CRTDEFS\n"
  "\n"
  "/* ---- c2mir builtin headers (resolved internally, never UCRT) ---------- */\n"
  "#include <stdarg.h>\n"
  "#include <stddef.h>\n"
  "#include <stdint.h>\n"
  "#include <stdbool.h>\n"
  "#include <limits.h>\n"
  "/* c2mir's builtin stddef.h guards its NULL behind\n"
  " * `#if !defined(__APPLE__) && !defined(_WIN32)` -- on those targets it\n"
  " * expects the real SDK headers to supply it.  Ours are guard-stuffed. */\n"
  "#ifndef NULL\n"
  "#define NULL ((void *) 0)\n"
  "#endif\n"
  "\n"
  "/* The emitted Windows ucontext shim carries a file-scope GNU __asm__ block\n"
  " * (the COMDAT context-switch + trampoline).  c2mir has no GNU asm; under the\n"
  " * JIT the host process already carries these primitives, resolved at MIR-link\n"
  " * time, so the block is swallowed whole.  The extern decls beside it stay. */\n"
  "#define __asm__(...)\n"
  "\n"
  "/* ---- stdio ----------------------------------------------------------- */\n"
  "typedef struct _iobuf FILE;\n"
  "FILE *__acrt_iob_func(unsigned);\n"
  "#define stdin  (__acrt_iob_func(0))\n"
  "#define stdout (__acrt_iob_func(1))\n"
  "#define stderr (__acrt_iob_func(2))\n"
  "#define EOF (-1)\n"
  "int printf(const char *, ...);\n"
  "int fprintf(FILE *, const char *, ...);\n"
  "int snprintf(char *, unsigned long long, const char *, ...);\n"
  "int vsnprintf(char *, unsigned long long, const char *, va_list);\n"
  "int vfprintf(FILE *, const char *, va_list);\n"
  "int sscanf(const char *, const char *, ...);\n"
  "int fputs(const char *, FILE *);\n"
  "int fputc(int, FILE *);\n"
  "int putchar(int);\n"
  "int puts(const char *);\n"
  "int fflush(FILE *);\n"
  "FILE *fopen(const char *, const char *);\n"
  "int fclose(FILE *);\n"
  "unsigned long long fread(void *, unsigned long long, unsigned long long, FILE *);\n"
  "unsigned long long fwrite(const void *, unsigned long long, unsigned long long, FILE *);\n"
  "char *fgets(char *, int, FILE *);\n"
  "int fgetc(int);\n"
  "int fseek(FILE *, long, int);\n"
  "long ftell(FILE *);\n"
  "int feof(FILE *);\n"
  "int ferror(FILE *);\n"
  "int remove(const char *);\n"
  "int rename(const char *, const char *);\n"
  "#define SEEK_SET 0\n"
  "#define SEEK_CUR 1\n"
  "#define SEEK_END 2\n"
  "\n"
  "/* ---- stdlib ---------------------------------------------------------- */\n"
  "void *malloc(unsigned long long);\n"
  "void *calloc(unsigned long long, unsigned long long);\n"
  "void *realloc(void *, unsigned long long);\n"
  "void free(void *);\n"
  "void abort(void);\n"
  "void exit(int);\n"
  "int atexit(void (*)(void));\n"
  "int atoi(const char *);\n"
  "long long atoll(const char *);\n"
  "double atof(const char *);\n"
  "long strtol(const char *, char **, int);\n"
  "long long strtoll(const char *, char **, int);\n"
  "unsigned long long strtoull(const char *, char **, int);\n"
  "double strtod(const char *, char **);\n"
  "char *getenv(const char *);\n"
  "int rand(void);\n"
  "void srand(unsigned);\n"
  "void qsort(void *, unsigned long long, unsigned long long,\n"
  "           int (*)(const void *, const void *));\n"
  "\n"
  "/* ---- string ---------------------------------------------------------- */\n"
  "void *memcpy(void *, const void *, unsigned long long);\n"
  "void *memmove(void *, const void *, unsigned long long);\n"
  "void *memset(void *, int, unsigned long long);\n"
  "int memcmp(const void *, const void *, unsigned long long);\n"
  "unsigned long long strlen(const char *);\n"
  "int strcmp(const char *, const char *);\n"
  "int strncmp(const char *, const char *, unsigned long long);\n"
  "char *strcpy(char *, const char *);\n"
  "char *strncpy(char *, const char *, unsigned long long);\n"
  "char *strcat(char *, const char *);\n"
  "char *strncat(char *, const char *, unsigned long long);\n"
  "char *strchr(const char *, int);\n"
  "char *strrchr(const char *, int);\n"
  "char *strstr(const char *, const char *);\n"
  "char *strdup(const char *);\n"
  "char *strerror(int);\n"
  "\n"
  "/* ---- errno ----------------------------------------------------------- */\n"
  "int *_errno(void);\n"
  "#define errno (*_errno())\n"
  "#define EINTR 4\n"
  "#define EAGAIN 11\n"
  "#define EWOULDBLOCK 140\n"
  "#define EINPROGRESS 112\n"
  "#define ECONNRESET 108\n"
  "\n"
  "/* ---- math ------------------------------------------------------------ */\n"
  "double pow(double, double);\n"
  "double sqrt(double);\n"
  "double floor(double);\n"
  "double ceil(double);\n"
  "double fabs(double);\n"
  "double fmod(double, double);\n"
  "double sin(double);\n"
  "double cos(double);\n"
  "double tan(double);\n"
  "double asin(double);\n"
  "double acos(double);\n"
  "double atan(double);\n"
  "double atan2(double, double);\n"
  "double exp(double);\n"
  "double log(double);\n"
  "double log2(double);\n"
  "double log10(double);\n"
  "double round(double);\n"
  "double trunc(double);\n"
  "float fabsf(float);\n"
  "#define NAN (0.0 / 0.0)\n"
  "#define INFINITY (1.0 / 0.0)\n"
  "#define HUGE_VAL (1.0 / 0.0)\n"
  "\n"
  "/* ---- setjmp: layout only; calling is deferred work -------------------- */\n"
  "typedef struct { _Alignas(16) char __opaque[256]; } __tur_mirc_jmpbuf;\n"
  "typedef __tur_mirc_jmpbuf jmp_buf[1];\n"
  "int setjmp(jmp_buf);\n"
  "void longjmp(jmp_buf, int);\n"
  "\n"
  "/* ---- pthreads (winpthreads: all scalars) ------------------------------ */\n"
  "typedef unsigned long long pthread_t;\n"
  "typedef long long pthread_mutex_t;\n"
  "typedef long long pthread_cond_t;\n"
  "typedef long pthread_once_t;\n"
  "typedef unsigned pthread_key_t;\n"
  "typedef struct pthread_attr_t pthread_attr_t;\n"
  "typedef struct pthread_mutexattr_t pthread_mutexattr_t;\n"
  "typedef struct pthread_condattr_t pthread_condattr_t;\n"
  "#define PTHREAD_MUTEX_INITIALIZER -1\n"
  "#define PTHREAD_COND_INITIALIZER -1\n"
  "#define PTHREAD_ONCE_INIT 0\n"
  "int pthread_create(pthread_t *, const pthread_attr_t *,\n"
  "                   void *(*)(void *), void *);\n"
  "int pthread_join(pthread_t, void **);\n"
  "int pthread_detach(pthread_t);\n"
  "pthread_t pthread_self(void);\n"
  "int pthread_equal(pthread_t, pthread_t);\n"
  "int pthread_mutex_init(pthread_mutex_t *, const pthread_mutexattr_t *);\n"
  "int pthread_mutex_lock(pthread_mutex_t *);\n"
  "int pthread_mutex_trylock(pthread_mutex_t *);\n"
  "int pthread_mutex_unlock(pthread_mutex_t *);\n"
  "int pthread_mutex_destroy(pthread_mutex_t *);\n"
  "int pthread_cond_init(pthread_cond_t *, const pthread_condattr_t *);\n"
  "int pthread_cond_wait(pthread_cond_t *, pthread_mutex_t *);\n"
  "int pthread_cond_signal(pthread_cond_t *);\n"
  "int pthread_cond_broadcast(pthread_cond_t *);\n"
  "int pthread_cond_destroy(pthread_cond_t *);\n"
  "int pthread_once(pthread_once_t *, void (*)(void));\n"
  "int pthread_key_create(pthread_key_t *, void (*)(void *));\n"
  "void *pthread_getspecific(pthread_key_t);\n"
  "int pthread_setspecific(pthread_key_t, const void *);\n"
  "\n"
  "/* ---- winsock minimum (types only; socket programs stay on cc) -------- */\n"
  "typedef unsigned long long SOCKET;\n"
  "typedef unsigned int u_int;\n"
  "typedef unsigned long u_long;\n"
  "typedef unsigned short u_short;\n"
  "typedef int socklen_t;\n"
  "struct sockaddr { u_short sa_family; char sa_data[14]; };\n"
  "struct timeval { long tv_sec; long tv_usec; };\n"
  "typedef struct fd_set { u_int fd_count; SOCKET fd_array[64]; } fd_set;\n"
  "#define FD_SETSIZE 64\n"
  "#define INVALID_SOCKET ((SOCKET)~0)\n"
  "/* Winsock's FD_* are header macros (FD_ISSET normally bounces through the\n"
  " * imported __WSAFDIsSet); with winsock2.h guard-stuffed they must be spelled\n"
  " * here, over the same struct layout. */\n"
  "static int __tur_mirc_fd_isset(SOCKET f, fd_set *s) {\n"
  "  for (u_int __i = 0; __i < s->fd_count; __i++)\n"
  "    if (s->fd_array[__i] == f) return 1;\n"
  "  return 0;\n"
  "}\n"
  "#define FD_ZERO(s)     ((s)->fd_count = 0)\n"
  "#define FD_SET(fd, s)  ((s)->fd_array[(s)->fd_count++] = (SOCKET)(fd))\n"
  "#define FD_ISSET(fd, s) __tur_mirc_fd_isset((SOCKET)(fd), (s))\n"
  "#define FD_CLR(fd, s)  do { \\\n"
  "    for (u_int __i = 0; __i < (s)->fd_count; __i++) \\\n"
  "      if ((s)->fd_array[__i] == (SOCKET)(fd)) { \\\n"
  "        (s)->fd_array[__i] = (s)->fd_array[--(s)->fd_count]; break; } \\\n"
  "  } while (0)\n"
  "int select(int, fd_set *, fd_set *, fd_set *, struct timeval *);\n"
  "\n"
  "/* ---- io.h / fcntl.h minimum (binary-stdout prologue in main) ---------- */\n"
  "int _setmode(int, int);\n"
  "int _fileno(FILE *);\n"
  "#define _O_BINARY 0x8000\n"
  "#define _O_TEXT   0x4000\n"
  "\n"
  "/* ---- time ------------------------------------------------------------- */\n"
  "typedef long long time_t;\n"
  "typedef long clock_t;\n"
  "struct tm { int tm_sec, tm_min, tm_hour, tm_mday, tm_mon, tm_year,\n"
  "                tm_wday, tm_yday, tm_isdst; };\n"
  "time_t time(time_t *);\n"
  "clock_t clock(void);\n"
  "#define CLOCKS_PER_SEC 1000\n"
  "struct timespec { time_t tv_sec; long tv_nsec; };\n"
  "/* winpthreads pthread_time.h values */\n"
  "#define CLOCK_REALTIME 0\n"
  "#define CLOCK_MONOTONIC 1\n"
  "int clock_gettime(int, struct timespec *);\n"
  "int nanosleep(const struct timespec *, struct timespec *);\n"
  "void Sleep(unsigned long);\n"
  "\n"
  ;
#endif /* TUR_JIT_WIN_PRELUDE_H */
