/* kind_check.c — Kind inference and validation pass (Phase HKT H1).
 *
 * This pass runs after elaboration (PASS_KIND_CHECK slot).  In Phase H1 it
 * performs two jobs:
 *
 *   1. Kind annotation propagation: walk all EX_TYPECLASS_DEF nodes; for
 *      each typeclass with kind-annotated parameters (type_param_kinds !=
 *      NULL), ensure the kind array is consistent (sets KIND_STAR for any
 *      un-annotated slot).
 *
 *   2. Kind validation at instance sites: walk all EX_TYPECLASS_INST_DEF
 *      nodes; for each instance, confirm that the type_args satisfy the
 *      corresponding kind constraints declared on the typeclass.  This is a
 *      belt-and-suspenders check — elab_definstance already performs the
 *      same validation, so this pass reports the same error only if it finds
 *      a mismatch that slipped through (e.g. generated by a macro).
 *
 * Future phases (H2+) will add:
 *   - KIND_ARROW inference for one-parameter type constructors.
 *   - Validation that type arguments are applied at the correct kind.
 */

#include "kind_check.h"
#include "diag.h"
#include "expr.h"
#include "typeclass.h"
#include "types.h"

/* ---------------------------------------------------------------------------
 * Internal helpers
 * ------------------------------------------------------------------------- */

/* Returns the effective kind of a Type value in H1.
 * Primitive scalar types are KIND_STAR.
 * Struct types (user-defined, can wrap an inner type) are KIND_ARROW.
 * All other types default to KIND_STAR in H1. */
static Kind type_effective_kind(Type t) {
    switch (t.kind) {
        case TY_STRUCT: return KIND_ARROW;
        case TY_INT:
        case TY_BOOL:
        case TY_CSTR:
        case TY_NIL:
        case TY_FLOAT:
        case TY_PTR_VOID:
            return KIND_STAR;
        default:
            return KIND_STAR;
    }
}

/* Walk a single Expr node (non-recursive helper used by the tree walk). */
static int kind_check_expr(Expr *expr) {
    if (!expr) return 0;
    int errors = 0;

    switch (expr->kind) {
        case EX_TYPECLASS_DEF: {
            /* Propagate: fill NULL kind slots with KIND_STAR. */
            TypeClass *tc = expr->as.typeclass_def_.typeclass;
            if (tc && tc->n_type_params > 0 && tc->type_param_kinds == NULL) {
                /* type_param_kinds was never allocated — all params are KIND_STAR
                 * by definition; nothing to validate. */
            }
            break;
        }
        case EX_INSTANCE_DEF: {
            /* Belt-and-suspenders: validate kind constraints on type_args. */
            TypeClassInstance *inst = expr->as.instance_def_.instance;
            if (inst && inst->typeclass && inst->typeclass->type_param_kinds) {
                TypeClass *tc = inst->typeclass;
                for (uint8_t i = 0; i < inst->n_type_args; i++) {
                    if (i >= tc->n_type_params) break;
                    Kind expected = tc->type_param_kinds[i];
                    if (expected == KIND_ARROW) {
                        Kind actual = type_effective_kind(inst->type_args[i]);
                        if (actual != KIND_ARROW) {
                            diag_emit_with_code(DIAG_ERROR, expr->span,
                                TUR_E0012_KIND_MISMATCH,
                                "kind mismatch (TUR-E0012): instance of '%s' provides a "
                                "kind-'*' type for parameter %d which expects kind '* -> *'",
                                tc->name->name, (int)(i + 1));
                            errors++;
                        }
                    }
                }
            }
            break;
        }
        default:
            break;
    }

    /* Recurse into child expressions. */
    switch (expr->kind) {
        case EX_DO: {
            for (uint32_t i = 0; i < expr->as.do_.n; i++) {
                errors += kind_check_expr(expr->as.do_.items[i]);
            }
            break;
        }
        case EX_FN_DEF:
            if (expr->as.fn_def_.fn && expr->as.fn_def_.fn->body)
                errors += kind_check_expr(expr->as.fn_def_.fn->body);
            break;
        case EX_FN:
            if (expr->as.fn_.fn && expr->as.fn_.fn->body)
                errors += kind_check_expr(expr->as.fn_.fn->body);
            break;
        case EX_LET:
            for (uint32_t i = 0; i < expr->as.let_.n; i++) {
                errors += kind_check_expr(expr->as.let_.bindings[i].init);
            }
            errors += kind_check_expr(expr->as.let_.body);
            break;
        case EX_CALL: {
            for (uint32_t i = 0; i < expr->as.call_.n_args; i++) {
                errors += kind_check_expr(expr->as.call_.args[i]);
            }
            break;
        }
        case EX_IF:
            errors += kind_check_expr(expr->as.if_.cond);
            errors += kind_check_expr(expr->as.if_.then_);
            if (expr->as.if_.else_or_null)
                errors += kind_check_expr(expr->as.if_.else_or_null);
            break;
        default:
            break;
    }

    return errors;
}

/* ---------------------------------------------------------------------------
 * Public entry point
 * ------------------------------------------------------------------------- */

int kind_check_pass(Arena *a, Expr *program) {
    (void)a;
    if (!program) return 0;
    int errors = 0;

    /* The top-level program node is EX_DO. */
    if (program->kind == EX_DO) {
        for (uint32_t i = 0; i < program->as.do_.n; i++) {
            errors += kind_check_expr(program->as.do_.items[i]);
        }
    } else {
        errors += kind_check_expr(program);
    }

    return errors > 0 ? 1 : 0;
}
