# embed_region_runtime.cmake -- turn the region runtime sources into C byte
# arrays the compiler links, so an emitted program can carry the SAME
# src/runtime/{arena,region}.{h,c} the archive is built from.
#
# RM3 regions are on by default, which means every emitted spine constructor
# calls tur_region_alloc_or_malloc and every static init registers
# tur_region_shutdown.  Those bodies used to live only in libturt_runtime.a,
# which is fine for the one link line `tur build <file>` controls and wrong
# for every other consumer of the emitted C: a project build, a --shared
# library, the REPL's spice cache, and a bare `cc` of `tur emit-c` output all
# linked with `undefined reference to tur_region_shutdown`.  The rc<T>/GC
# runtime solved the identical problem with the DEDUP-4b archive posture --
# declarations when the archive is on the link line, bodies replicated into
# the owner TU otherwise -- and the emitter (src/compiler/emit_module.c,
# emit_region_runtime_bodies) now gives regions the same treatment.  Rather
# than hand-write a replica that drifts from the maintained implementation,
# the real sources are embedded here at build time and pasted verbatim.
#
# Usage (from src/CMakeLists.txt, as a custom command):
#   cmake -DSRC_DIR=<src/runtime> -DOUT=<gen>/region_rt_embed.c \
#         -P cmake/embed_region_runtime.cmake
#
# The output is only rewritten when its content changes, so an untouched
# runtime does not rebuild emit_module.c's consumers.

if(NOT SRC_DIR OR NOT OUT)
  message(FATAL_ERROR "embed_region_runtime.cmake: SRC_DIR and OUT are required")
endif()

set(_out "/* AUTO-GENERATED by cmake/embed_region_runtime.cmake from src/runtime/\n")
string(APPEND _out " * {region.h,arena.h,arena.c,region.c} -- do not edit.  Each array is the\n")
string(APPEND _out " * file's exact bytes plus a NUL terminator; the _len is the byte count\n")
string(APPEND _out " * without it.  See the script header for why these exist. */\n")
string(APPEND _out "#include <stddef.h>\n#include \"runtime/region_rt_embed.h\"\n\n")

# Order matters for the emitter (headers ahead of bodies), not here; the
# arrays are independent.
foreach(_pair
        "region.h=tur_rt_embed_region_h"
        "arena.h=tur_rt_embed_arena_h"
        "arena.c=tur_rt_embed_arena_c"
        "region.c=tur_rt_embed_region_c")
  string(REPLACE "=" ";" _kv "${_pair}")
  list(GET _kv 0 _file)
  list(GET _kv 1 _sym)
  set(_path "${SRC_DIR}/${_file}")
  if(NOT EXISTS "${_path}")
    message(FATAL_ERROR "embed_region_runtime.cmake: missing ${_path}")
  endif()
  # HEX read sidesteps every quoting/escaping question a text read would
  # raise (semicolons, brackets, backslashes, quotes).
  file(READ "${_path}" _hex HEX)
  string(LENGTH "${_hex}" _hexlen)
  math(EXPR _nbytes "${_hexlen} / 2")
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")
  # One line per 16 bytes so the generated TU stays diffable.
  string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){16})" "\\1\n" _bytes "${_bytes}")
  string(APPEND _out "/* ${_file}: ${_nbytes} bytes */\n")
  string(APPEND _out "const unsigned char ${_sym}[] = {\n${_bytes}\n0x00 };\n")
  string(APPEND _out "const size_t ${_sym}_len = ${_nbytes};\n\n")
endforeach()

get_filename_component(_dir "${OUT}" DIRECTORY)
file(MAKE_DIRECTORY "${_dir}")
file(WRITE "${OUT}.tmp" "${_out}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${OUT}.tmp" "${OUT}"
                RESULT_VARIABLE _rc)
file(REMOVE "${OUT}.tmp")
if(NOT _rc EQUAL 0)
  message(FATAL_ERROR "embed_region_runtime.cmake: could not write ${OUT}")
endif()
