#!/usr/bin/env bash
# Launch Lite XL with the Turmeric plugin pointed at the in-tree compiler.
# Invoked by the `lite-xl` Justfile recipe (kept as its own script because
# `tur run`'s just-subset implementation truncates shebang recipes that
# contain heredocs -- see commit history for the symptom).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
CFG="$HOME/.config/lite-xl"

mkdir -p "$CFG/plugins" "$CFG/colors"
ln -sf "$ROOT/tools/lite-xl/turmeric.lua" "$CFG/plugins/turmeric.lua"

# Write init.lua via printf so we never depend on heredoc support up the
# call stack.
printf '%s\n' \
  "-- Auto-generated by 'tur run lite-xl' -- points the Turmeric plugin at" \
  "-- the in-tree compiler so it survives macOS Finder's sanitized GUI PATH." \
  "local config = require \"core.config\"" \
  "config.plugins.turmeric = config.plugins.turmeric or {}" \
  "config.plugins.turmeric.tur = \"$ROOT/build/tur\"" \
  > "$CFG/init.lua"

# Absolutize positional args. `open -a` launches the .app with CWD=/,
# so a relative `examples/foo.tur` resolves against root inside the app.
# Anything that already looks absolute is passed through unchanged.
abs_args=()
for arg in "$@"; do
    case "$arg" in
        /*|-*) abs_args+=("$arg") ;;
        *)
            if [ -e "$arg" ]; then
                abs_args+=("$(cd "$(dirname "$arg")" && pwd)/$(basename "$arg")")
            else
                abs_args+=("$arg")
            fi
            ;;
    esac
done

# macOS: launch via LaunchServices (`open -a`) so the .app gets a proper
# NSApplication bootstrap and stays alive after we return. Direct-execing
# the bundle's Mach-O works in some shells but quits silently in others
# (no controlling terminal, GUI activation race).
if [ "$(uname -s)" = "Darwin" ] && [ -d "/Applications/Lite XL.app" ] && [ -z "${TUR_LITE_XL:-}" ]; then
    echo "lite-xl: open -a 'Lite XL' with tur=$ROOT/build/tur"
    # `open --args` forwards everything after it to the app's argv. If
    # there are no extra args the trailing `--args` is harmless.
    exec open -a "Lite XL" --args "${abs_args[@]}"
fi

LITE_BIN="${TUR_LITE_XL:-}"
if [ -z "$LITE_BIN" ]; then
    if command -v lite-xl >/dev/null 2>&1; then
        LITE_BIN="lite-xl"
    elif [ -x "/Applications/Lite XL.app/Contents/MacOS/lite-xl" ]; then
        LITE_BIN="/Applications/Lite XL.app/Contents/MacOS/lite-xl"
    else
        echo "error: no Lite XL binary found." >&2
        echo "  install it from https://lite-xl.com (native .dmg / .exe / AppImage)" >&2
        echo "  or set TUR_LITE_XL=/path/to/lite-xl and retry." >&2
        exit 127
    fi
fi
echo "lite-xl: launching $LITE_BIN with tur=$ROOT/build/tur"
exec "$LITE_BIN" "${abs_args[@]}"
