#!/usr/bin/env bash
# Launch Lite XL with the Turmeric plugin pointed at the in-tree compiler.
# Invoked by the `lite-xl` Justfile recipe (kept as its own script because
# `tur run`'s just-subset implementation truncates shebang recipes that
# contain heredocs -- see commit history for the symptom).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
CFG="$HOME/.config/lite-xl"

mkdir -p "$CFG/plugins" "$CFG/colors"
ln -sf "$ROOT/tools/lite-xl/turmeric.lua" "$CFG/plugins/turmeric.lua"
ln -sf "$ROOT/tools/lite-xl/colors/turmeric-dark.lua"  "$CFG/colors/turmeric-dark.lua"
ln -sf "$ROOT/tools/lite-xl/colors/turmeric-light.lua" "$CFG/colors/turmeric-light.lua"

# Probe for an installed Iosevka in the standard font directories. First
# hit wins. Empty if nothing matches -- init.lua falls back to the
# Lite XL-bundled JetBrains Mono in that case.
IOSEVKA=""
for candidate in \
    "$ROOT/tools/lite-xl/fonts/Iosevka-Regular.ttf" \
    "$HOME/Library/Fonts/IosevkaNerdFontMono-Regular.ttf" \
    "$HOME/Library/Fonts/IosevkaNerdFont-Regular.ttf" \
    "$HOME/Library/Fonts/Iosevka-Regular.ttf" \
    "/Library/Fonts/IosevkaNerdFontMono-Regular.ttf" \
    "/Library/Fonts/Iosevka-Regular.ttf" \
    "$HOME/.local/share/fonts/IosevkaNerdFontMono-Regular.ttf" \
    "$HOME/.local/share/fonts/Iosevka-Regular.ttf" \
    "/usr/share/fonts/iosevka/Iosevka-Regular.ttf" \
    "/usr/local/share/fonts/Iosevka-Regular.ttf"; do
    if [ -f "$candidate" ]; then
        IOSEVKA="$candidate"
        break
    fi
done

# Write init.lua via printf so we never depend on heredoc support up the
# call stack.
printf '%s\n' \
  "-- Auto-generated by 'tur run lite-xl' -- points the Turmeric plugin at" \
  "-- the in-tree compiler so it survives macOS Finder's sanitized GUI PATH." \
  "local core = require \"core\"" \
  "local style = require \"core.style\"" \
  "local config = require \"core.config\"" \
  "config.plugins.turmeric = config.plugins.turmeric or {}" \
  "config.plugins.turmeric.tur = \"$ROOT/build/tur\"" \
  "-- Default the Try Turmeric dark theme on first launch." \
  "core.reload_module(\"colors.turmeric-dark\")" \
  "-- Code font: Iosevka 12pt when found by tur run lite-xl, otherwise" \
  "-- inherit the Lite XL default (JetBrains Mono)." \
  "local iosevka_path = \"$IOSEVKA\"" \
  "if iosevka_path ~= \"\" then" \
  "  local ok, font = pcall(renderer.font.load, iosevka_path, 12 * SCALE)" \
  "  if ok then style.code_font = font else core.warn(\"turmeric: failed to load Iosevka: \" .. tostring(font)) end" \
  "end" \
  > "$CFG/init.lua"

# Absolutize positional args. `open -a` launches the .app with CWD=/,
# so a relative `examples/foo.tur` resolves against root inside the app.
# Anything that already looks absolute is passed through unchanged.
abs_args=()
for arg in "$@"; do
    case "$arg" in
        /*|-*) abs_args+=("$arg") ;;
        *)
            if [ -e "$arg" ]; then
                abs_args+=("$(cd "$(dirname "$arg")" && pwd)/$(basename "$arg")")
            else
                abs_args+=("$arg")
            fi
            ;;
    esac
done

# macOS: launch via LaunchServices (`open -a`) so the .app gets a proper
# NSApplication bootstrap and stays alive after we return. Direct-execing
# the bundle's Mach-O works in some shells but quits silently in others
# (no controlling terminal, GUI activation race).
if [ "$(uname -s)" = "Darwin" ] && [ -z "${TUR_LITE_XL:-}" ]; then
    # Prefer the rebranded sibling bundle (Turmeric.app) if it has been
    # built; the dock then shows the Turmeric icon instead of generic
    # Lite XL. The sibling bundle is just symlinks back into the user's
    # stock /Applications/Lite XL.app with a custom Info.plist + icon,
    # so it stays in lock-step with upstream Lite XL automatically.
    # Auto-build the branded sibling on first run (cheap; only runs once
    # unless build-app-icon.sh is re-invoked). Skip via TUR_SKIP_BRAND=1.
    if [ -z "${TUR_SKIP_BRAND:-}" ] \
        && [ ! -d "$ROOT/tools/lite-xl/Turmeric.app" ] \
        && [ -d "/Applications/Lite XL.app" ] \
        && command -v magick >/dev/null 2>&1 \
        && command -v iconutil >/dev/null 2>&1; then
        echo "lite-xl: building branded Turmeric.app (one-time)"
        bash "$ROOT/tools/lite-xl/build-app-icon.sh" >&2 || true
    fi
    LAUNCH_APP=""
    if [ -d "$ROOT/tools/lite-xl/Turmeric.app" ]; then
        LAUNCH_APP="$ROOT/tools/lite-xl/Turmeric.app"
    elif [ -d "/Applications/Lite XL.app" ]; then
        LAUNCH_APP="/Applications/Lite XL.app"
    fi
    if [ -n "$LAUNCH_APP" ]; then
        echo "lite-xl: open -a '$LAUNCH_APP' with tur=$ROOT/build/tur"
        # `open --args` forwards everything after it to the app's argv.
        # If there are no extra args the trailing `--args` is harmless.
        exec open -a "$LAUNCH_APP" --args ${abs_args[@]+"${abs_args[@]}"}
    fi
fi

LITE_BIN="${TUR_LITE_XL:-}"
if [ -z "$LITE_BIN" ]; then
    if command -v lite-xl >/dev/null 2>&1; then
        LITE_BIN="lite-xl"
    elif [ -x "/Applications/Lite XL.app/Contents/MacOS/lite-xl" ]; then
        LITE_BIN="/Applications/Lite XL.app/Contents/MacOS/lite-xl"
    else
        echo "error: no Lite XL binary found." >&2
        echo "  install it from https://lite-xl.com (native .dmg / .exe / AppImage)" >&2
        echo "  or set TUR_LITE_XL=/path/to/lite-xl and retry." >&2
        exit 127
    fi
fi
echo "lite-xl: launching $LITE_BIN with tur=$ROOT/build/tur"
exec "$LITE_BIN" ${abs_args[@]+"${abs_args[@]}"}
